### ISSUE TITLE
[GUI] Template details: API not found

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1000]
Error message in the detailed view of the template:

![Screenshot_5](https://user-images.githubusercontent.com/37310063/54831401-0939c900-4c99-11e9-8529-978e65645ba3.png)

**Affected Version:** 58.2-20190321

**Comment by cfrancisco** [comment]
It sounds like a lack of configuration, maybe in the docker compose. I'll check.

**Comment by cfrancisco** [comment]
@betefaber  Could you check it again in the new baseline?

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/55655608-0bd50c00-57cb-11e9-8a35-c97ad522a4b6.png)
