### ISSUE TITLE
[GUI] Template/Device screen with cards over spaced 

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#1009]
Version: 
 - branch: development
 - commit 86e19293912490387fcbe6aa59d9969d06f6d5de)

![image](https://user-images.githubusercontent.com/21104864/55098535-b9923d80-509c-11e9-9dc9-e81d5e213d3c.png)

**Comment by raulnegreiros** [comment]
just one more information, is you click on space below the card it opens the template (it does not happen with the device).

**Comment by betefaber** [comment]
Test OK.

- Devices:

![image](https://user-images.githubusercontent.com/37310063/61744704-56749700-ad6e-11e9-87d1-6f163b772364.png)

- Templates:

![image](https://user-images.githubusercontent.com/37310063/61744746-6b512a80-ad6e-11e9-88d2-f5f627cfc1db.png)

Tested in version: **63.1-20190705**
