### ISSUE TITLE
[GUI] device attribute's value is cut at the beginning

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#1014]
In this situation, the static attribute `client_endpoint` has the value `unsecure-client-endpoint-0` but the GUI cuts the beginnning (first letter). The following image illustrates the situation.

![image](https://user-images.githubusercontent.com/21104864/55186593-b1f29780-5175-11e9-92fa-266ae2f2b87f.png)

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/61906310-77b9bc80-af01-11e9-933f-a58e22fb4563.png)

![image](https://user-images.githubusercontent.com/37310063/61906542-edbe2380-af01-11e9-8d51-e71fca78dc34.png)

Tested in version: **63.1-20190705**
