### ISSUE TITLE
[GUI] GUI does not update the attribute values after some time

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#1015]
This screenshot was taken 08:00 AM, as we can see the GUI stopped the updates 04:55PM (previous day).

version:
- branch: development
- commit: 86e19293912490387fcbe6aa59d9969d06f6d5de

![image](https://user-images.githubusercontent.com/21104864/55228855-fb84c600-51f9-11e9-9bbb-5b26d6f1e085.png)

**Comment by rascaraficci** [comment]
Could you attach to the issue the data broker's logs?

**Comment by raulnegreiros** [comment]
> Could you attach to the issue the data broker's logs?

I believe it isn't a data broker issue, because after refreshing the page it worked again

**Comment by cfrancisco** [comment]
It is likely that this behavior was changed because the UI was factored in.
