### ISSUE TITLE
[Device-Manager] Template: Problem in editing attributes of actuator type

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1018]
The actuator attribute is being displayed as a configuration attribute.

The attribute display is incorrect, making it impossible to edit.

**Steps to reproduce the problem:**

1. Create a template with a dynamic attribute and an actuator attribute

- request

![Screenshot_47](https://user-images.githubusercontent.com/37310063/55254063-b54d5800-5235-11e9-8183-f8c601c0d0eb.png)

- response

![Screenshot_45](https://user-images.githubusercontent.com/37310063/55254084-c26a4700-5235-11e9-917e-2b79a198c7aa.png)

2. Open the template edit screen

- template details

![Screenshot_48](https://user-images.githubusercontent.com/37310063/55254101-cac28200-5235-11e9-8e53-b7604932382f.png)

3. View the actuator attribute

![Screenshot_49](https://user-images.githubusercontent.com/37310063/55254115-d3b35380-5235-11e9-83e8-896e26be27c4.png)

- ### actuator attribute details

![Screenshot_50](https://user-images.githubusercontent.com/37310063/55254127-d746da80-5235-11e9-8038-12bcb63b9bae.png)

4. Device of this template

![Screenshot_51](https://user-images.githubusercontent.com/37310063/55254787-93ed6b80-5237-11e9-8594-2a35bf343145.png)

**Affected Version:** 58.2-20190321

**Comment by cfrancisco** [comment]
Hm, sounds like the backend is sending the actuators attributes in config_attr list. Adding @andersonluisribeiro in the conversation.

**Comment by mprevide** [comment]
Add actuator on data_attr instead of config

**Comment by betefaber** [comment]
Test OK.

- Create a template with an actuator attribute

![Screenshot_49](https://user-images.githubusercontent.com/37310063/58814159-a602d600-85fb-11e9-97ab-6b4098887741.png)

- Actuator attribute details

![Screenshot_50](https://user-images.githubusercontent.com/37310063/58814161-a69b6c80-85fb-11e9-9a53-50805a308e76.png)

- Update template

![Screenshot_51](https://user-images.githubusercontent.com/37310063/58814168-aac78a00-85fb-11e9-8b0f-bbe9cce767c2.png)

Tested on Version: **62.2-20190524**
