### ISSUE TITLE
[GUI] Attribute metadata visualization

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#1023]
Is not possible to visualize the attributes metadata from the device details screen. (it was possible once in the past)

**Comment by mprevide** [comment]
i couldn't find this feature in the past, i think it is a new feature.

**Comment by mprevide** [comment]
This was initiated in `https://github.com/giampaolli/gui.git metadata`

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/59690366-b5ffe580-91b7-11e9-8e20-99e5d429330e.png)

Tested on Version: **62.3-20190603**
