### ISSUE TITLE
[GUI] There is no indication that the actuator attribute was selected

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1026]
**Steps to reproduce the problem:** 

1. Open device details screen
2. Select any dynamic attribute

![Screenshot_70](https://user-images.githubusercontent.com/37310063/55566040-4c505f00-56d1-11e9-978e-5f63f69dda6e.png)

3. Select the actuator attribute

![image](https://user-images.githubusercontent.com/37310063/55566000-3d69ac80-56d1-11e9-84e2-287012b8e728.png)

**Actual result:** There is no indication that the actuator attribute was selected.

**Expected behavior:** Maintain the same behavior pattern as the other attributes.

**Affected Version:** 58.2-20190321

**Comment by mprevide** [comment]
The PR was reverted

**Comment by mprevide** [comment]
Utilizar a tag na gui  mprevide/gui:updatefirmware

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/59061841-cee4ce80-887a-11e9-8eb5-1d7002bbdbb6.png)

Tested on Version: **62.3-20190603**
