### ISSUE TITLE
[GUI] Edit metadata: change of data is not discarded

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1029]
When the change of a metadata is discarded, the data is retained.
In order for the data to be discarded, it is necessary to discard the update of attribute and template.

**Steps to reproduce the problem:** 
1. Add a metadata to the attribute

![Screenshot_95](https://user-images.githubusercontent.com/37310063/55647762-e210ea80-57b4-11e9-9e13-f5f687e8a98a.png)

2. Change the data

![Screenshot_96](https://user-images.githubusercontent.com/37310063/55647790-f7861480-57b4-11e9-9b4c-d5c42db5c69d.png)

3. Click DISCARD. The data is retained.

![Screenshot_97](https://user-images.githubusercontent.com/37310063/55647803-fead2280-57b4-11e9-84d0-4e731916d190.png)

![Screenshot_98](https://user-images.githubusercontent.com/37310063/55647816-04a30380-57b5-11e9-8339-f07be6628277.png)

**Note**: If the attribute and template are saved, the changes made to the metadata will be updated even if they have been discarded.

**Affected Version:** 58.2-20190321

**Comment by cfrancisco** [comment]
This was really hard to solve it, maybe we should think to reimplement these sidebars interactions.

**Comment by betefaber** [comment]
Test OK.

- attribute a

![atributo_a](https://user-images.githubusercontent.com/37310063/59219501-07491d00-8b99-11e9-8f96-1bfbb91ae873.png)

- metadata b

![metadata_b](https://user-images.githubusercontent.com/37310063/59219516-1039ee80-8b99-11e9-9f4c-16c159aa12d2.png)

- change metadata and discard changes

![descarta_alteracao_meta](https://user-images.githubusercontent.com/37310063/59219731-8c343680-8b99-11e9-9ad7-3a4a7517a81d.png)

- changes are discarded 

![Screenshot_52](https://user-images.githubusercontent.com/37310063/59219744-95bd9e80-8b99-11e9-8d59-515736366978.png)


Tested on Version: **62.3-20190603**
