### ISSUE TITLE
Acessar Interface Web - Dúvida

### ISSUE THREAD

**Issue by LucasDibz** [dojot/dojot#1031]
Olá, 
Executei a instalação via docker do dojot porem estou com dificuldades para acessar a interface web.
Já liberei as portas TCP no firewall e no roteador, porém continuo sempre com a mesma mensagem de 'A conexão com localhost foi recusada.'

Alguma sugestão?

Obrigado,
Lucas.

**Comment by mprevide** [comment]
Olá,

Você está tentando acessar a interface web via porta 8000? http://localhost:8000? 

Att.
Mariane

**Comment by LucasDibz** [comment]
Olá!

Sim, estou tentando acessar via http://localhost:8000

"Não é possível acessar esse site A conexão com localhost foi recusada.
Tente:

Verificar a conexão
Verificar o proxy e o firewall
ERR_CONNECTION_REFUSED"

Segue em anexo o estado do docker-compose up -d
![Docker ps](https://user-images.githubusercontent.com/49247275/55818607-5e653f80-5acd-11e9-951c-0f337e912177.png)

**Comment by LucasDibz** [comment]
Olá!

Sim, estou tentando acessar pela porta 8000.

Sou leigo neste quesito, criei um servidor local (localhost) atraves do XAMPP, ou seja, Apache.
Liberei para que ele possa escutar (Listen 8000) ; fiz a liberação da porta no firewall.

Acredito que realizei a instalação do dojot corretamente...

Baixei o Docker-Toolbox p/ windows (vem incluso o docker-compose)

Abri um novo diretorio no computador e executei os comandos no GitBashHere para clonar a plataforma dojot.
Apos subir o docker-compose -up -d ; tentei acessar a interace web via a porta 8000.

Executei algum passo errado ?
Muito obrigado.

Segue o fim da instação via docker ps
![Docker ps](https://user-images.githubusercontent.com/49247275/55826433-6b3e5f00-5ade-11e9-8245-0df6c7a592eb.png)

**Comment by LucasDibz** [comment]
Olá!

Resolvido.

A Maquina Host não pode ser OS Windows 10.

Refiz a instalação em Linux Ubuntu e consegui acessar a interface web.
