### ISSUE TITLE
data-broker - implement remainder of subscription management (GET/PUT/DELETE)

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#105]

**Comment by mmagr** [comment]
This is, in broad terms, just a few adaptations and improvements on what's been already contributed by @giovannicuriel .

A few points to be updated/improved:
- Subscription configuration data must be kept on a database;
- Query language (i.e. contents of field "subject.condition.expression.q") needs to be more resilient to user's idioms (variable syntax, argument positioning, spaces, etc.);
- Topics with subscription results must be automatically generated by the subscription manager, not set by the callers;

**Comment by mmagr** [comment]
This was actually part of dojot/data-broker#2
