### ISSUE TITLE
[GUI] device with repeated attributes: the text has not been translated

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1052]
The text has not been translated into Portuguese.

**Steps to reproduce the problem**:

1. Click "Novo dispositivo"
2. Fill in device name
3. Select templates with repeated attributes
4. Click "Voltar"
5. Click "Salvar"

![atributosarepetidos](https://user-images.githubusercontent.com/37310063/55978912-56410780-5c67-11e9-868c-44eb0503b107.png)

**Affected Version**: 58.2-20190321

**Comment by bizetti** [comment]
Ticket analisys meeting (May 29th): It's low. Back to new issues.

**Comment by cfrancisco** [comment]
In version 0.6 it still occurs.

**Comment by cfrancisco** [comment]
It will no longer be prioritized.
