### ISSUE TITLE
[GUI] Actuator shouldnt have static value

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1055]
It should be the same behavior as dynamic.

**Comment by mprevide** [comment]
#966

**Comment by joab-cpqd** [comment]
![Captura de tela de 2019-06-28 16-30-50.png](https://images.zenhubusercontent.com/5cd42b2e6d03ff555513fe23/7c663488-37fd-4b66-80f9-7b5e5e634a0a)
