### ISSUE TITLE
[Flowbroker] The tooltip text in the template node has not been translated

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1056]
**Steps to reproduce the problem**:

1. Click "Novo Fluxo"
2. Edit template node

![template_tooltip](https://user-images.githubusercontent.com/37310063/55985127-8394b200-5c75-11e9-882d-b87be1ed899b.png)

**Affected Version**: 58.2-20190321

**Comment by bizetti** [comment]
Ticket analisys meeting (May 29th): It's low. Back to new issues.

**Comment by mprevide** [comment]
I believe this is something from the ace library used to generate this text field, maybe it's not something trivial to mess with and I don't think it's worth fixing it considering the effort and the result.

**Comment by bizetti** [comment]
Won't be fixed.
