### ISSUE TITLE
dojot is violating the firmware-update state machine

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#1061]
There is a state machine defined for the firmware update and according to that the 'send' and 'apply' operations must meet some rules:

1. The 'send operation' can be executed if and only if the state is IDLE.
2. The 'apply operation' can be executed if and only if the state is DOWNLOADED. 

dojot is not imposing any rules to execute these operations; so you can execute them in any order or moment. Furthermore, the GUI returns success messages ('Image successfully transferred' or 'Image applied'), causing misunderstandings of what is happening.

**Comment by cfrancisco** [comment]
About the operations, we could add these rules in GUI, but should be applied in the backend as well.
About the messages, we could change the response to "command sent to the device: request to transfer image or apply image" or something like this?

**Comment by rascaraficci** [comment]
For me, the firmware-update operations are special actuations; and the rules should be imposed by the back-end.

Regarding to the messages, we don't have any guarantees that they were sent to the devices. We only know that the back-end accepted the requests. My suggestions are:

- Request to transfer firmware image was accepted.
- Request to apply the firmware image was accepted.

**Comment by cfrancisco** [comment]
Regarding the GUI, the messages were updated. 

For now, I'll remain this ticket opened and I'm adding @giovannicuriel to clarify the backend points (for further improvements).

**Comment by mprevide** [comment]
Utilizar a tag na gui  mprevide/gui:updatefirmware
