### ISSUE TITLE
[GUI] Format date displayed according to the language

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1067]
format date displayed according to the language, for example:
PT: day / month / year
EN: month / day / year

**Comment by betefaber** [comment]
Test OK.

- **Portuguese**: day / month / year

![pt-br](https://user-images.githubusercontent.com/37310063/61901465-366fdf80-aef6-11e9-8623-b2737c4cb14a.png)

- **English**: month / day / year

![Screenshot at 2019-07-25 15-23-14](https://user-images.githubusercontent.com/37310063/61898791-78962280-aef0-11e9-802f-9903eb0956b2.png)

tested in version: **63.1-20190705**
