### ISSUE TITLE
Cannot enable firmware-update during the template creation

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#1068]
In the GUI, the firmware update can only be enabled after the template has been created. 
It should be possible to enable it during the template creation too.

**Comment by cfrancisco** [comment]
In fact, it is a limitation in the image manager, which requires a template ID to perform its operations. 
We could allow the access to "firmware enabling sidebar" and remove the save button from there. Anyway, at this point, the user couldn't manage its images.

**Comment by bizetti** [comment]
Won't be fixed.
