### ISSUE TITLE
Failed to subscribe to MQTT broker

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#1071]
Subscribe to MQTT broker using the command 'mosquitto_sub -h localhost -p 1883 -t /admin/7569d5/config' failed, and the following messages were logged by the IoT-Agent:

iotagent-mqtt_1               | {"pid":7,"hostname":"13e416518f10","name":"MoscaServer","level":30,"time":1555092810016,"msg":"subscribe not authorized","topic":"/admin/7569d5/config","client":"mosqsub|23341-draven","v":1}
iotagent-mqtt_1               | (node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'release' of null
iotagent-mqtt_1               |     at SingleCaller.release (/opt/iot-agent/node_modules/fastparallel/parallel.js:157:17)
iotagent-mqtt_1               |     at Client.handleAuthorizeSubscribe (/opt/iot-agent/node_modules/mosca/lib/client.js:436:5)
iotagent-mqtt_1               |     at /opt/iot-agent/node_modules/mosca/lib/client.js:472:12
iotagent-mqtt_1               |     at iota.getDevice.then.catch (/opt/iot-agent/index.js:305:7)
iotagent-mqtt_1               |     at <anonymous>
iotagent-mqtt_1               |     at process._tickCallback (internal/process/next_tick.js:189:7)
iotagent-mqtt_1               | (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)

The weird is that I can publish using the command 'mosquitto_pub -h localhost -p 1883 -t /admin/7569d5/attrs -m '{"update_result": 3}'

**Comment by giovannicuriel** [comment]
Did you use any tag or just the `latest` one?

**Comment by bizetti** [comment]
Ticket analysis (Jan, 3rd 2020): Retest.

**Comment by betefaber** [comment]
Test OK.

**mosquitto_sub -h localhost -p 1883 -t /admin/9cfed5/config**
```
iotagent-mqtt_1               | <20:33:18 10/01/2020> -- DEBUG: Authenticating MQTT client
iotagent-mqtt_1               | {"pid":7,"hostname":"5898f24a75d3","name":"MoscaServer","level":30,"time":1578688398593,"msg":"client connected","client":"mosqsub|20540-efaber-Op","v":1}
iotagent-mqtt_1               | <20:33:18 10/01/2020> -- INFO: client up
iotagent-mqtt_1               | <20:33:18 10/01/2020> -- DEBUG: Authorizing client mosqsub|20540-efaber-Op to subscribe to /admin/9cfed5/config
iotagent-mqtt_1               | <20:33:18 10/01/2020> -- |iotagent -- INFO: Getting device from http://device-manager:5000/device/9cfed5
iotagent-mqtt_1               | <20:33:18 10/01/2020> -- INFO: Parameters are: url: http://device-manager:5000/device/9cfed5, headers: { authorization: 'Bearer and0IHNjaGVtYQ==.eyJzZXJ2aWNlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImlvdGFnZW50LW1xdHQifQ==.ZHVtbXkgc2lnbmF0dXJl' }, method: get, TAG
iotagent-mqtt_1               | <20:33:18 10/01/2020> -- DEBUG: Got device {"attrs":{"8":[{"created":"2020-01-10T19:53:27.608575+00:00","id":31,"is_static_overridden":false,"label":"mensagem","static_value":"","template_id":"8","type":"actuator","value_type":"string"},{"created":"2020-01-10T19:53:27.606848+00:00","id":29,"label":"bool","template_id":"8","type":"dynamic","value_type":"boolean"},{"created":"2020-01-10T19:53:27.603088+00:00","id":25,"label":"float","template_id":"8","type":"dynamic","value_type":"float"},{"created":"2020-01-10T19:53:27.605930+00:00","id":28,"label":"gps","metadata":[{"created":"2020-01-10T19:53:27.610842+00:00","id":33,"is_static_overridden":false,"label":"unidade","static_value":"decimal","type":"meta","updated":null,"value_type":"string"},{"created":"2020-01-10T19:53:27.611983+00:00","id":34,"is_static_overridden":false,"label":"descricao","static_value":"localização do dispositivo","type":"meta","updated":null,"value_type":"string"}],"template_id":"8","type":"dynamic","value_type":"geo:point"},{"created":"2020-01-10T19:53:27.604091+00:00","id":26,"label":"int","template_id":"8","type":"dynamic","value_type":"integer"},{"created":"2020-01-10T19:53:27.605068+00:00","id":27,"label":"str","template_id":"8","type":"dynamic","value_type":"string"},{"created":"2020-01-10T19:53:27.609442+00:00","id":32,"is_static_overridden":false,"label":"protocol","static_value":"mqtt","template_id":"8","type":"static","value_type":"string"},{"created":"2020-01-10T19:53:27.607650+00:00","id":30,"is_static_overridden":false,"label":"serial","static_value":"indefinido","template_id":"8","type":"static","value_type":"string"}]},"created":"2020-01-10T19:53:30.306483+00:00","id":"9cfed5","label":"device","templates":[8]}
iotagent-mqtt_1               | <20:33:18 10/01/2020> -- DEBUG: Authorized client mosqsub|20540-efaber-Op to subscribe to topic /admin/9cfed5/config
iotagent-mqtt_1               | {"pid":7,"hostname":"5898f24a75d3","name":"MoscaServer","level":30,"time":1578688398624,"msg":"subscribed to topic","topic":"/admin/9cfed5/config","qos":0,"client":"mosqsub|20540-efaber-Op","v":1}
```
----
**mosquitto_pub -h localhost -p 1883 -t /admin/9cfed5/attrs -m '{"mensagem":"teste"}'**
```
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- DEBUG: Authenticating MQTT client
iotagent-mqtt_1               | {"pid":7,"hostname":"5898f24a75d3","name":"MoscaServer","level":30,"time":1578688626654,"msg":"client connected","client":"mosqpub|22611-efaber-Op","v":1}
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- INFO: client up
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- DEBUG: Authorizing MQTT client mosqpub|22611-efaber-Op to publish to /admin/9cfed5/attrs
iotagent-mqtt_1               | {"pid":7,"hostname":"5898f24a75d3","name":"MoscaServer","level":30,"time":1578688626655,"msg":"closed","client":"mosqpub|22611-efaber-Op","v":1}
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- INFO: client down
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- |iotagent -- INFO: Getting device from http://device-manager:5000/device/9cfed5
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- INFO: Parameters are: url: http://device-manager:5000/device/9cfed5, headers: { authorization: 'Bearer and0IHNjaGVtYQ==.eyJzZXJ2aWNlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImlvdGFnZW50LW1xdHQifQ==.ZHVtbXkgc2lnbmF0dXJl' }, method: get, TAG
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- DEBUG: Got device {"attrs":{"8":[{"created":"2020-01-10T19:53:27.608575+00:00","id":31,"is_static_overridden":false,"label":"mensagem","static_value":"","template_id":"8","type":"actuator","value_type":"string"},{"created":"2020-01-10T19:53:27.606848+00:00","id":29,"label":"bool","template_id":"8","type":"dynamic","value_type":"boolean"},{"created":"2020-01-10T19:53:27.603088+00:00","id":25,"label":"float","template_id":"8","type":"dynamic","value_type":"float"},{"created":"2020-01-10T19:53:27.605930+00:00","id":28,"label":"gps","metadata":[{"created":"2020-01-10T19:53:27.610842+00:00","id":33,"is_static_overridden":false,"label":"unidade","static_value":"decimal","type":"meta","updated":null,"value_type":"string"},{"created":"2020-01-10T19:53:27.611983+00:00","id":34,"is_static_overridden":false,"label":"descricao","static_value":"localização do dispositivo","type":"meta","updated":null,"value_type":"string"}],"template_id":"8","type":"dynamic","value_type":"geo:point"},{"created":"2020-01-10T19:53:27.604091+00:00","id":26,"label":"int","template_id":"8","type":"dynamic","value_type":"integer"},{"created":"2020-01-10T19:53:27.605068+00:00","id":27,"label":"str","template_id":"8","type":"dynamic","value_type":"string"},{"created":"2020-01-10T19:53:27.609442+00:00","id":32,"is_static_overridden":false,"label":"protocol","static_value":"mqtt","template_id":"8","type":"static","value_type":"string"},{"created":"2020-01-10T19:53:27.607650+00:00","id":30,"is_static_overridden":false,"label":"serial","static_value":"indefinido","template_id":"8","type":"static","value_type":"string"}]},"created":"2020-01-10T19:53:30.306483+00:00","id":"9cfed5","label":"device","templates":[8]}
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- DEBUG: Expected topic is /admin/9cfed5/attrs
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- DEBUG: Device published on topic /admin/9cfed5/attrs
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- DEBUG: Authorized client mosqpub|22611-efaber-Op to publish to topic /admin/9cfed5/attrs
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- DEBUG: Published data: {"mensagem":"teste"}, client: mosqpub|22611-efaber-Op, topic: /admin/9cfed5/attrs
iotagent-mqtt_1               | <20:37:06 10/01/2020> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'device-data': 
iotagent-mqtt_1               |    { admin: 'f92b5e5c-29f5-4b4a-ad4c-a2c513252a4d',
iotagent-mqtt_1               |      teste: '0b6f762f-124d-4ca2-8f4a-f033c61ff9a3' } }
```
----
**actuation via Postman**

![Screenshot at 2020-01-10 17-41-08](https://user-images.githubusercontent.com/37310063/72185121-d94ae600-33d0-11ea-904f-bfa44824eb65.png)

```
iotagent-mqtt_1               | <20:40:48 10/01/2020> -- |messenger -- DEBUG: Emitting new event message for subject dojot.device-manager.device@admin
iotagent-mqtt_1               | <20:40:48 10/01/2020> -- |messenger -- DEBUG: Emitting new event device.configure for subject iotagent.device@admin
iotagent-mqtt_1               | <20:40:48 10/01/2020> -- |undefined -- DEBUG: Got configure event from Device Manager
iotagent-mqtt_1               | <20:40:48 10/01/2020> -- |undefined -- DEBUG: Publishing
iotagent-mqtt_1               | <20:40:48 10/01/2020> -- DEBUG: ignoring internal message
iotagent-mqtt_1               | <20:40:48 10/01/2020> -- DEBUG: Message out!!
```
![Screenshot at 2020-01-10 17-41-52](https://user-images.githubusercontent.com/37310063/72185142-e667d500-33d0-11ea-9225-cacfb8000e6b.png)

Tested in version: **v0.4.1_rc2**

**Comment by ramonfontes** [comment]
Hello,

Was this problem solved? I just installed Dojot from https://github.com/dojot/docker-compose and mosquitto_sub isn't working. I can successfully run mosquitto_pub and see the results in the dashboard though.

**Comment by mprevide** [comment]
Hello!
Are you using development version (default branch)? 
How are using mosquitto_sub?

**Comment by mprevide** [comment]
I recomend you use the last version v0.4.1 (https://github.com/dojot/docker-compose/releases/tag/v0.4.1). 
You can see how to use this version at https://dojotdocs.readthedocs.io/en/latest/installation-guide.html#installation.
The development version has not been tested.

**Comment by mprevide** [comment]
An example of how to sub with mosquitto_sub

```
mosquitto_sub -t /admin/4a030a/config -i admin:4a030a  -p 1883 -h localhost

```
where *4a030a* is **device** id and *admin* is **tenant**

**Comment by mprevide** [comment]
See also this issue (https://github.com/dojot/docker-compose/issues/129), you need this setting for pub and sub in insecure mode.

**Comment by ramonfontes** [comment]
Yes, I was using the default one (development branch). However, the behavior is still the same with v0.4.1

This is the publisher:
`mosquitto_pub -t "/admin/3406cd/attrs" -m '{"sta1":1}'`

* mosquitto_pub works fine and I can see values being sent to Dojot through the dashboard

This is the subscriber:
`mosquitto_sub -t /admin/3406cd/attrs -i admin:3406cd  -p 1883 -h 192.168.10.117`

I also tried:
`mosquitto_sub -t /admin/3406cd/attrs`
`mosquitto_sub -t /admin/3406cd/attrs -i admin:3406cd  -p 1883 -h 127.0.0.1`

It works fine if I use Mosquitto MQTT Server instead of Dojot.

I've changed docker-compose.yml as below:
`ALLOW_UNSECURED_MODE: 'true'`
`MOSCA_TLS_DNS_LIST: '192.168.10.117'`

I had to change "localhost" to my host IP address. Otherwise, mosquitto_pub wouldn't work.

**Comment by mprevide** [comment]
Hi,
How are actuate in device to sub? Are you using a flow or the endpoint of actuate from device? 

To sending actuate to device, you can use this endpoint https://dojot.github.io/device-manager/apiary_latest.html#devices-device-info-put-1

:)

**Comment by ramonfontes** [comment]
I'm not doing anything special. I'm just trying to receive the message that is being sent by mosquitto_pub. Since I'm able to make it work with Mosquitto MQTT Server I was expecting to do the same with Dojot.

**Comment by mprevide** [comment]
You need create a flow to received a message from mosquitto_pub to mosquitto_sub, see more about flows https://dojotdocs.readthedocs.io/en/latest/flow.html 
Or you can just use the end point https://dojot.github.io/device-manager/apiary_latest.html#devices-device-info-put-1

**Comment by ramonfontes** [comment]
I created an attribute of type _actuator_ and the result is still the same. Then, I created two flows as _input_ (_event device_ and _event device template_) and connect them to a _multi actuate_ as output flow - according to https://dojotdocs.readthedocs.io/en/latest/flow.html#multi-actuate I need to use the _multi actuate_ node. The result is still the same. I was wondering if I need to put any other flow between _input_ and _output_. 

I selected all the events on both _event device_ and _event device template_ and  set `payload.data.attrs.sta1` as source in the multi actuate node. I tried `payload.data.actuate.sta1` too.

**Comment by mprevide** [comment]
Yes, you need put others nodes between input and output.
But are you try to use  the endpoint just to check if your mosquitto_sub is working?

**Comment by ramonfontes** [comment]
Great! It worked after adding a new flow between input and output. Thanks!

**Comment by mprevide** [comment]
Did you pass the JWT token when you use the endpoint?  See how here https://dojotdocs.readthedocs.io/en/latest/using-api-interface.html#getting-access-token

I think you don't need this information anymore, but to keep it registered.

**Comment by ramonfontes** [comment]
Ookay! It works as well! I really appreciate your support @mprevide
