### ISSUE TITLE
A device can publish data to an attribute of type actuator

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#1072]
The steps to reproduce the problem:

1. Create a device with an attribute of type actuator

2. Publish data to this attribute as you typically do for dynamic attributes

3. Look at the attribute at the device details page.
You will see the data published by the device. It doesn't make sense once it is expected only to see data sent from dojot to device.

**Comment by giovannicuriel** [comment]
I think we can work on this... Devices publishing in actuator attributes might be a feature, not a bug :smile:

**Comment by rascaraficci** [comment]
The idea is to keep the device data opaque to the IoT Agent, so this issue will be closed because it is not a bug.
