### ISSUE TITLE
[GUI] User without permission

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1075]
Error messages are displayed on the home screen when the user does not have permission.

- without permission

![UsuarioSemPermissão](https://user-images.githubusercontent.com/37310063/56132193-c00b2b00-5f5f-11e9-8d06-5855471d1332.png)

- user without permission to access devices

![UsuarioSemPermissaoDevice](https://user-images.githubusercontent.com/37310063/56132200-c4374880-5f5f-11e9-82a9-e88e0ef1bc82.png)

**Comment by cfrancisco** [comment]
Initially, we should fix this error. But also, in my opinion, we need to redirect the user to an allowed page.

**Comment by betefaber** [comment]
Test OK. 

The error messages are not displayed.

![Screenshot at 2019-07-16 14-38-55](https://user-images.githubusercontent.com/37310063/61316936-56a5ed00-a7d8-11e9-91fe-9315a778cb84.png)

But if the user does not have permissions, no page should be accessed. However, the device list is being displayed. Another issue will open.

Tested in version **63.1-20190705**
