### ISSUE TITLE
Wrong return when removing all templates through API

### ISSUE THREAD

**Issue by andersonluisribeiro** [dojot/dojot#1078]
When you remove all templates through API, it returns NULL, and when some template is linked to some device and you try to remove it, an "Internal Error" message is returned as response.

**Comment by betefaber** [comment]
Test OK.

![Screenshot at 2019-07-05 17-18-59](https://user-images.githubusercontent.com/37310063/60743698-1b3e2f80-9f49-11e9-8260-fdb87ba543fe.png)


Tested in version: **62.3-20190603**
