### ISSUE TITLE
Error verbose device creation

### ISSUE THREAD

**Issue by andersonluisribeiro** [dojot/dojot#1080]
When you create a device verbosely through API, as as in the example below, an HTTP 500 error is returned as a response:

> http://localhost:8000/device?verbose=True

**Comment by giovannicuriel** [comment]
Did you try with `true` (lowercase)? Just checking whether this feature is working (and this issue is simply a missing input validation) or it is completely broker :weary:

**Comment by andersonluisribeiro** [comment]
Yes @giovannicuriel, I did. I used true (lowercase) and the same error was returned.

**Comment by betefaber** [comment]
Test OK.

- verbose=true

![verbose](https://user-images.githubusercontent.com/37310063/60344120-31b61b00-998c-11e9-9fae-e9a7d2e4af2c.png)

- verbose=True

![verbose_True](https://user-images.githubusercontent.com/37310063/60344139-3a0e5600-998c-11e9-8046-2ca114baf6d4.png)

- verbose=false

![verbose_false](https://user-images.githubusercontent.com/37310063/60344155-41356400-998c-11e9-9e22-0311509db052.png)

Tested in version: **62.3-20190603**
