### ISSUE TITLE
[GUI] Updating manage firmware already updates template

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1088]
**Steps to reproduce the problem**:

1. Edit template
2. Click "Manage Firmware"

![Screenshot_193](https://user-images.githubusercontent.com/37310063/56298364-66923000-6108-11e9-8c15-5805914ce051.png)

3. Click "SAVE"

![TemplateUpdated](https://user-images.githubusercontent.com/37310063/56298282-3f3b6300-6108-11e9-819d-86e9d0f3c04e.png)

**Affected Version**: 58.2-20190321

**Comment by cfrancisco** [comment]
As @mprevide showed, some config and attributes could be saved even if the user discards the operation.  Updating the issue status.

**Comment by cfrancisco** [comment]
I just checked that Save button inside "manage firmware sidebar" doesn't save attributes and configurations made in other sidebars.

**Comment by mprevide** [comment]
I think this a bug because the user doesn't expected that behavior.
