### ISSUE TITLE
[GUI] Non-intuitive error when missing a static_value during a template creation

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#1097]
The error `This text is not valid`is a non-intuitive error, it does not help the user to find out that the static_value is missing.

![image](https://user-images.githubusercontent.com/21104864/56961774-16b16100-6b2b-11e9-9682-849adc110da6.png)

**Comment by betefaber** [comment]
The reported problem still happens. The message should indicate that the field is empty.

![image](https://user-images.githubusercontent.com/37310063/76760192-f5218e00-676b-11ea-8d62-3b7637f4ae90.png)

Tested in version **v0.4.2**.

**Note**: This limitation not exist in BE. (#607)

**Comment by bizetti** [comment]
Ticket analisys meeting (March, 20th): Change the return GUI message.

**Comment by cfrancisco** [comment]
![image.png](https://images.zenhubusercontent.com/5cdb17917c26f8023263517e/354c67c4-d4ba-46eb-a4c0-6bede83ee448)

Upon reviewing the alerts, there is one specific message per type. The message for the String type sounds unfamiliar to me.
