### ISSUE TITLE
[FlowBroker] Not working properly after connection with RabbitMQ unexpected close

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#1098]
Flowbroker gets messages from Kafka but cannot en-queue them on RabbitMQ. These messages are discarded and not processed.

> <00:00:23 27/04/2019> -- |producer -- DEBUG: Error while creating producer: Error: broker transport failure
> <05:40:23 28/04/2019> -- |producer -- DEBUG: Error while creating producer: Error: broker transport failure
> <09:10:23 28/04/2019> -- |producer -- DEBUG: Error while creating producer: Error: broker transport failure
> <21:11:12 28/04/2019> -- |undefined -- ERROR: uncaughtException: write EPIPE
> Error: write EPIPE
>     at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
> <21:11:21 28/04/2019> -- |undefined -- ERROR: uncaughtException: write EPIPE
> Error: write EPIPE
>     at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
> <21:11:21 28/04/2019> -- |undefined -- ERROR: uncaughtException: write EPIPE
> Error: write EPIPE
>     at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
> <21:11:25 28/04/2019> -- |undefined -- ERROR: uncaughtException: Unexpected close
> Error: Unexpected close
>     at succeed (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:272:13)
>     at onOpenOk (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:254:5)
>     at /opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:166:32
>     at /opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:160:12
>     at Socket.recv (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:499:12)
>     at Object.onceWrapper (events.js:313:30)
>     at emitNone (events.js:106:13)
>     at Socket.emit (events.js:208:7)
>     at emitReadable_ (_stream_readable.js:513:10)
>     at emitReadable (_stream_readable.js:507:7)
>     at addChunk (_stream_readable.js:274:7)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>     at TCP.onread (net.js:601:20)
> <21:11:25 28/04/2019> -- |undefined -- ERROR: uncaughtException: Unexpected close
> Error: Unexpected close
>     at succeed (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:272:13)
>     at onOpenOk (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:254:5)
>     at /opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:166:32
>     at /opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:160:12
>     at Socket.recv (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:499:12)
>     at Object.onceWrapper (events.js:313:30)
>     at emitNone (events.js:106:13)
>     at Socket.emit (events.js:208:7)
>     at emitReadable_ (_stream_readable.js:513:10)
>     at emitReadable (_stream_readable.js:507:7)
>     at addChunk (_stream_readable.js:274:7)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>     at TCP.onread (net.js:601:20)
> <21:11:34 28/04/2019> -- |undefined -- ERROR: uncaughtException: Heartbeat timeout
> Error: Heartbeat timeout
>     at Heart.<anonymous> (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:427:19)
>     at emitNone (events.js:106:13)
>     at Heart.emit (events.js:208:7)
>     at Heart.runHeartbeat (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/heartbeat.js:88:17)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)
> <21:11:37 28/04/2019> -- |undefined -- ERROR: uncaughtException: Heartbeat timeout
> Error: Heartbeat timeout
>     at Heart.<anonymous> (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:427:19)
>     at emitNone (events.js:106:13)
>     at Heart.emit (events.js:208:7)
>     at Heart.runHeartbeat (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/heartbeat.js:88:17)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)
>     at listOnTimeoutNT (timers.js:369:26)
>     at _combinedTickCallback (internal/process/next_tick.js:136:11)
>     at process._tickCallback (internal/process/next_tick.js:181:9)
> <21:11:37 28/04/2019> -- |undefined -- ERROR: uncaughtException: Heartbeat timeout
> Error: Heartbeat timeout
>     at Heart.<anonymous> (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:427:19)
>     at emitNone (events.js:106:13)
>     at Heart.emit (events.js:208:7)
>     at Heart.runHeartbeat (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/heartbeat.js:88:17)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)
>     at listOnTimeoutNT (timers.js:369:26)
>     at _combinedTickCallback (internal/process/next_tick.js:136:11)
>     at process._tickCallback (internal/process/next_tick.js:181:9)
> <21:11:37 28/04/2019> -- |producer -- DEBUG: Error while creating producer: Error: timed out
> <21:13:33 28/04/2019> -- |undefined -- ERROR: uncaughtException: Heartbeat timeout
> Error: Heartbeat timeout
>     at Heart.<anonymous> (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:427:19)
>     at emitNone (events.js:106:13)
>     at Heart.emit (events.js:208:7)
>     at Heart.runHeartbeat (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/heartbeat.js:88:17)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)
> <21:13:37 28/04/2019> -- |undefined -- ERROR: uncaughtException: Heartbeat timeout
> Error: Heartbeat timeout
>     at Heart.<anonymous> (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:427:19)
>     at emitNone (events.js:106:13)
>     at Heart.emit (events.js:208:7)
>     at Heart.runHeartbeat (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/heartbeat.js:88:17)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)

**Comment by bizetti** [comment]
Ticket analyis (Dec, 27th): Move to test (Rafael is responsible for testing)

**Comment by rascaraficci** [comment]
Done.
