### ISSUE TITLE
[GUI] Authentication error message is displayed from time to time

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1100]
![Screenshot at 2019-05-01 11-16-42](https://user-images.githubusercontent.com/37310063/57023019-52b9f400-6c07-11e9-8a36-1048cc91ad34.png)

![Screenshot at 2019-05-01 11-44-55](https://user-images.githubusercontent.com/37310063/57023028-59e10200-6c07-11e9-91b2-c2826a98f7f7.png)

![Screenshot at 2019-05-01 11-45-54](https://user-images.githubusercontent.com/37310063/57023031-5d748900-6c07-11e9-9615-bcfcb678d9b4.png)

![Screenshot at 2019-05-01 11-56-11](https://user-images.githubusercontent.com/37310063/57023345-20f55d00-6c08-11e9-9ef6-cbdb9a2cfd7b.png)

**Affected Version:** 61.1-20190423

**Comment by betefaber** [comment]
**Note**: apparently the token is  lost when the device publishes geolocation data.

![Screenshot at 2019-05-08 11-43-24](https://user-images.githubusercontent.com/37310063/57384534-324de480-7187-11e9-9afe-a05f4b69f112.png)

**Comment by betefaber** [comment]
**Note**: the error happens even if there is no geolocation data published

![Screenshot at 2019-05-10 18-28-58](https://user-images.githubusercontent.com/37310063/57557918-2a8e6b80-7352-11e9-82e6-f4432be7653e.png)

**Comment by bizetti** [comment]
Ticket analysis meeting (May, 22nd): It will be retested.

**Comment by betefaber** [comment]
The message is no longer displayed.

![10](https://user-images.githubusercontent.com/37310063/83184783-5963b500-a100-11ea-9acb-85bb9fb93e80.png)

![Screenshot_31](https://user-images.githubusercontent.com/37310063/83184760-51a41080-a100-11ea-9b98-fcd31582daa1.png)

![Screenshot_38](https://user-images.githubusercontent.com/37310063/83184738-4a7d0280-a100-11ea-96b5-6f08039d31ca.png)

Tested in version **v0.5.0-alpha.1**
