### ISSUE TITLE
[GUI] Add version information about dojot

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1102]

**Comment by bizetti** [comment]
Ticket analysis meeting (Mach, 13th): One possibility is to get the version from an environment variable.

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/83141006-57c8cb80-a0c5-11ea-8b8d-fe21d89eadc5.png)

**Comment by betefaber** [comment]
Tested in v0.4.3-rc.1

- docker-compose
![image](https://user-images.githubusercontent.com/37310063/89945780-4721ef00-dbf8-11ea-95bb-76ab43a12649.png)

- k8s
![image](https://user-images.githubusercontent.com/37310063/89945726-2d80a780-dbf8-11ea-988e-06f2c1a5659b.png)
