### ISSUE TITLE
[GUI] Firmware in details of device

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1103]

**Comment by mprevide** [comment]
Utilizar a tag na gui  mprevide/gui:updatefirmware

**Comment by betefaber** [comment]
Test OK.

- In devices details is shown full FW Update status text.

![Screenshot_188](https://user-images.githubusercontent.com/37310063/59712489-b3b38080-91e3-11e9-8509-b294ff2bbc77.png)

- There is indication that the actuator attribute was selected.

![Screenshot_189](https://user-images.githubusercontent.com/37310063/59712503-b9a96180-91e3-11e9-913b-909ebe760989.png)

Tested on Version: **62.3-20190603**
