### ISSUE TITLE
[GUI] Cache problem in device creation

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1104]
**Steps to reproduce the problem:**

1. Create a template with static attribute
2. Create a device of this template and edit the static attribute
3. Click on device to edit it
4. Click on "New device", without discarding the edition
5. Create a new device from the same template and edit the static attribute with the same value as the previous device

![Screenshot at 2019-05-03 10-19-23](https://user-images.githubusercontent.com/37310063/57140796-05688e80-6d8f-11e9-9567-178aca811f22.png)

![Screenshot at 2019-05-03 10-19-32](https://user-images.githubusercontent.com/37310063/57140800-08fc1580-6d8f-11e9-90b7-10f5f3ed100a.png)

**Affected Version:** 61.1-20190423

**Comment by mprevide** [comment]
Utilizar a tag na gui  mprevide/gui:updatefirmware

**Comment by joab-cpqd** [comment]
![Captura de tela de 2019-06-28 14-55-29.png](https://images.zenhubusercontent.com/5cd42b2e6d03ff555513fe23/d92d590a-eb98-441f-b05f-8c3df9c437aa)
