### ISSUE TITLE
[IotAgent Leshan] Update Firmware -  reset machine and improve simulator

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1109]
- Implement state machine reset
- Leshan Simulator - Implement state machine reset
- IoTAgent + Simulator set test

**Comment by betefaber** [comment]
Test OK.

State machine reset has been implemented.

![Screenshot_186](https://user-images.githubusercontent.com/37310063/59710334-253d0000-91df-11e9-9393-eee553e8212a.png)

![Screenshot_187](https://user-images.githubusercontent.com/37310063/59710344-29691d80-91df-11e9-956d-d0396c33ab5d.png)

Tested on Version: **62.3-20190603**
