### ISSUE TITLE
Prepare Raspberry-Pi + Sense Hat for dojot's training

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#1114]
As I tutor of dojot's training I want that all attendees to be able to configure a dojot's device that is associated with the same instance of a Raspberry-Pi + Sense Hat. So that, the Raspberry-Pi + Sense Hat publishes data and all attendees receive them.

Acceptance Criteria:
1. Create multiples dojot's devices in different tenants associated with the Raspberry-Pi+SenseHat
2. Publish data from Raspberry-Pi+SenseHat
3. Check if all dojot's devices receive the data

**Comment by rascaraficci** [comment]
Code is available at:

https://github.com/rascaraficci/dojot-sense-hat/tree/dojot-training_version

Branch: dojot-training_version

**Comment by giovannicuriel** [comment]
Looks good!
