### ISSUE TITLE
dojot tutorials - notification

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#1118]
As a user, I would like to know how to generate and retrieve notifications. Also, I would like to know which notifications are currently being generated by dojot (using current set of modules).

## Acceptance criteria

Scenario:
- An inexperienced user with access to a fully functional dojot instance.

The user should be able to generate notifications via Flowbroker and get them via socket.io and History (using GUI and a ad-hoc client). Also, the user should know which notifications are being currently generated in dojot.

**Comment by mprevide** [comment]
This is already done 
https://dojotdocs.readthedocs.io/en/development/flow.html#notification

**Comment by mprevide** [comment]
There is a new example https://dojotdocs.readthedocs.io/en/development/flow.html#using-cumulative-sum-switch-and-notification-node
I think maybe it can be closed
