### ISSUE TITLE
[IotAgent Leshan] Update Firmware - change actuator for just writer

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1121]
The history is persist the URI insted of version when actuate

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/59710746-fbd0a400-91df-11e9-8509-4f0a66fa0988.png)

![image](https://user-images.githubusercontent.com/37310063/59711003-916c3380-91e0-11e9-8cf7-f9cab865c39c.png)


Tested on Version: **62.3-20190603**
