### ISSUE TITLE
[GUI] Unable to edit template created by the API using the GUI

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#1122]
It is not possible to edit a template created by the API using the GUI.

How to reproduce:
1) create a template 
Example:
```
curl -X POST http://127.0.0.1:8000/template \
-H "Authorization: Bearer ${JWT}" \
-H 'Content-Type:application/json' \
-d '{ "label": "created_by_api",
      "attrs": [
                { "label": "dummy_attr",
                  "type": "dynamic",
                  "value_type": "string"
                }]	
}'
```
2) open the GUI and select the created template
3) add a new attribute to the template
4) save your change

GUI version:  37e0e9d [development]

**Comment by mprevide** [comment]
Doesnt happen anymore.

**Comment by joab-cpqd** [comment]
![Captura de tela de 2019-07-01 13-10-12.png](https://images.zenhubusercontent.com/5cd42b2e6d03ff555513fe23/d63bfadd-73ee-4706-be9c-eda04ff925f2)

![Captura de tela de 2019-07-01 13-14-33.png](https://images.zenhubusercontent.com/5cd42b2e6d03ff555513fe23/a6da4695-85cc-4f49-b65d-8c33b338b736)
