### ISSUE TITLE
[AUTH/KONG] Call failed on dojot page when restarting containers

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1135]
If the dojot page is open, restarting the containers (docker-compose down) and reloading the page causes the "call failed" error.

![Screenshot at 2019-05-14 17-57-58](https://user-images.githubusercontent.com/37310063/57732748-26c15880-7674-11e9-8de2-871d33e82d61.png)
![Screenshot at 2019-05-14 17-58-15](https://user-images.githubusercontent.com/37310063/57732749-2759ef00-7674-11e9-8973-dfe9a44bcd44.png)
![Screenshot at 2019-05-14 17-58-34](https://user-images.githubusercontent.com/37310063/57732750-2759ef00-7674-11e9-953f-b706088eaa3e.png)
![Screenshot at 2019-05-14 17-58-43](https://user-images.githubusercontent.com/37310063/57732751-2759ef00-7674-11e9-8f51-5f159f64fd81.png)
![Screenshot at 2019-05-14 17-59-04](https://user-images.githubusercontent.com/37310063/57732753-2759ef00-7674-11e9-8d28-3a7e333e972c.png)

- You must delete the token.

![Screenshot at 2019-05-14 17-59-33](https://user-images.githubusercontent.com/37310063/57732772-30e35700-7674-11e9-91e3-6ec22156dc09.png)

**Note**: the page was open as incognito in Chrome

**Affected Version**: 61.1-20190423

**Comment by mprevide** [comment]
The problem is in AUTH
When the token was valid, but the token doest exist should rerturn 401 instead of 403.

**Comment by bizetti** [comment]
Ticket analysis (February, 28th 2020): Have to be analysed.

**Comment by betefaber** [comment]
Tested in **v0.6.0-rc.2**.

![Captura de tela de 2021-03-26 15-18-28.png](https://images.zenhubusercontent.com/5cd0940469cf6b4ee443403a/c27a04e5-e66e-4b68-b2c0-2cf83a8f4694)
