### ISSUE TITLE
[GUI] Remove buttons, configuracoes and etc for configurations in devices and templates

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1138]

**Comment by betefaber** [comment]
Test OK.

![Screenshot_22](https://user-images.githubusercontent.com/37310063/59110803-3a2fae80-8916-11e9-8f8c-39610f07aebe.png)

![Screenshot_23](https://user-images.githubusercontent.com/37310063/59110804-3ac84500-8916-11e9-9128-b73accf160fb.png)

![Screenshot_24](https://user-images.githubusercontent.com/37310063/59110805-3ac84500-8916-11e9-8275-97ccfeb9427d.png)

Tested on Version: **62.3-20190603**
