### ISSUE TITLE
Sidebar is floating in Profile and Groups pages

### ISSUE THREAD

**Issue by cfrancisco** [dojot/dojot#1140]
![image.png](https://images.zenhubusercontent.com/5cdb17917c26f8023263517e/9e7d63b0-28c1-4306-a8f2-ea2908adaab8)

**Comment by betefaber** [comment]
Test OK.

![Screenshot_7.png](https://images.zenhubusercontent.com/5cd0940469cf6b4ee443403a/e464a15e-ac6e-403a-8321-069baec34b3d)

Tested on Version: **62.3-20190603**
