### ISSUE TITLE
[Flowbroker] Cron node - Validations

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1141]
@raulnegreiros:

This regex seems don't follow the field specification:
"The cron time string is five values separated by spaces. From the most left value to the righest one, we have minute (0-59), hour (0-23), day of month (1-31), month (1-12 or names), and day of week (0-7 or names, 0 or 7 are sunday). You may use multiple values separated by comma e.g 0,10,20,30,40,50, * * * * ."
The multiple values are not supported
https://github.com/dojot/flowbroker/pull/151#discussion_r284205052

And

https://github.com/dojot/flowbroker/pull/151#discussion_r284205422

**Comment by bizetti** [comment]
Ticket analysis meeting (March, 6th): Medium.

**Comment by bizetti** [comment]
Ticket analysis meeting (May, 22nd): Out of roadmap column.

**Comment by betefaber** [comment]
The cron time expression is validated. If the expression is invalid, there is an indication that the cron node is not configured correctly.

![image](https://user-images.githubusercontent.com/37310063/98585031-68e94b80-22a5-11eb-9632-ffe7f6a8914f.png)
