### ISSUE TITLE
[GUI] Device details

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1145]
Just if you have  view permisson you can view details of device.
Actually, If you have modifer and/or view, this option should be able

**Comment by cfrancisco** [comment]
Now there're 2 wrapper functions over Ability class: CanView and canModify, i.e:

    const canView = ability.canView('device');
    const canEdit = ability.canModify('device');

Inside canView is been checking viewer and modifier permission.

**Comment by betefaber** [comment]
When the Device Modifier option is selected, the permission associated with this profile is "all_device", that is, the user can create, **read**, update and delete the devices.

**Note**: As in creating a device you need the list of templates, this permission is also added.

 - profile 

![Screenshot_5](https://user-images.githubusercontent.com/37310063/58591747-5a3bdf80-823d-11e9-8b66-2088cc26ee0b.png)

- permissions associated with the profile

![Screenshot_6](https://user-images.githubusercontent.com/37310063/58592561-1e097e80-823f-11e9-9c77-5be23b87526e.png)

- permissions associated with the user of this profile

![Screenshot_7](https://user-images.githubusercontent.com/37310063/58591920-b999ef80-823d-11e9-82b6-07caabea9b6e.png)


Through the API, a user with this permission (all_device) can read the device data.


![Screenshot_8](https://user-images.githubusercontent.com/37310063/58592174-3fb63600-823e-11e9-9432-af630b7af227.png)

![Screenshot_9](https://user-images.githubusercontent.com/37310063/58592173-3f1d9f80-823e-11e9-9f68-82381477e8ba.png)

So, it makes no sense for me to add the **ro_device** permission to view the device data. This permission only makes sense for a user who can only view devices.

**Comment by betefaber** [comment]
Test OK.

- **grupoA**: all_devices permission

![Screenshot at 2019-07-10 16-37-33](https://user-images.githubusercontent.com/37310063/61001195-8a46ca00-a335-11e9-9bfc-aa8da7b74918.png)

![Screenshot at 2019-07-10 16-30-50](https://user-images.githubusercontent.com/37310063/61001218-93379b80-a335-11e9-9186-f2b35db5e0eb.png)

![Screenshot at 2019-07-10 16-31-34](https://user-images.githubusercontent.com/37310063/61001884-d6ded500-a336-11e9-886e-43963eca4556.png)

view template:
![Screenshot at 2019-07-10 16-32-50](https://user-images.githubusercontent.com/37310063/61001331-d134bf80-a335-11e9-9dfa-3689474baa29.png)

view device details:
![Screenshot at 2019-07-10 16-32-58](https://user-images.githubusercontent.com/37310063/61001377-e4e02600-a335-11e9-8460-dd6c7ccaef8a.png)

edit device:
![Screenshot at 2019-07-10 16-33-05](https://user-images.githubusercontent.com/37310063/61001409-f7f2f600-a335-11e9-9550-7d331279d4fc.png)

- **grupoB**: ro_device permission

![Screenshot at 2019-07-10 16-37-48](https://user-images.githubusercontent.com/37310063/61001447-03deb800-a336-11e9-82f9-331cdc79f16f.png)

![Screenshot at 2019-07-10 16-30-09](https://user-images.githubusercontent.com/37310063/61001463-0a6d2f80-a336-11e9-9787-d9a9d4779ec4.png)

![Screenshot at 2019-07-10 16-28-20](https://user-images.githubusercontent.com/37310063/61001832-c595c880-a336-11e9-912d-6bf36c971283.png)

view device details: 
![Screenshot at 2019-07-10 16-31-59](https://user-images.githubusercontent.com/37310063/61001546-35f01a00-a336-11e9-843d-f668beda2aa3.png)

Tested in version: **63.1-20190705**
