### ISSUE TITLE
 Save flows: Emit a message before leave flow page

### ISSUE THREAD

**Issue by cfrancisco** [dojot/dojot#1146]

**Comment by betefaber** [comment]
Test NOK.

The alert message is only displayed after page reload.

----
**test 1**
----

1. Log in the dojot
2. click "Data Flows"
3. Click "Create a data flow"
4. Fill in the name of the flow
5. Add a node. **The alert message is displayed**.

![image](https://user-images.githubusercontent.com/37310063/61663300-aa1bad80-aca6-11e9-9964-606fad98e9ed.png)

6. Save the flow
----
**test 2**
----
1. Edit flow
2. Add new nodes and turn them on. **No messages are displayed.**
3. Click "Return to Flow list". The change is lost.

![image](https://user-images.githubusercontent.com/37310063/61712655-2c4eb500-ad2d-11e9-8cf5-4096b88b02bb.png)

----
**test 3**
----
1. Edit flow
2. Add new nodes and turn them on. **No messages are displayed.**
3. Click on another menu. The change is lost.

![image](https://user-images.githubusercontent.com/37310063/61714269-d3811b80-ad30-11e9-8715-1e20749b19ed.png)

----
**test 4**
----
1. Edit flow
2. Add new nodes and turn them on. **No messages are displayed.**
3. Click F5 or "Reload this page". Alert message is displayed.

![image](https://user-images.githubusercontent.com/37310063/61714696-e8aa7a00-ad31-11e9-84da-1d0beaca5f51.png)

----
**test 5**
----
1. Reload the page
2. Create new flow
3. Add new nodes. **The message is displayed.**

![image](https://user-images.githubusercontent.com/37310063/61714485-586c3500-ad31-11e9-8cf1-ca2afd004275.png)

4. Save the flow
5. Edit flow
6. Connect the nodes. **No messages are displayed.**

![image](https://user-images.githubusercontent.com/37310063/61714534-776ac700-ad31-11e9-93a7-649eb8cc41a9.png)

7. Click "Return to Flow list". The change is lost.

Tested in version: **63.1-20190705**

**Comment by thiagodpf** [comment]
Corrections applied in v0.4.1_rc2

In addition to the warning message, a dialog box is also displayed asking if the user really wants to exit when flow is not saved.

**Comment by betefaber** [comment]
1. When flow changes, alert message is displayed.

![aviso](https://user-images.githubusercontent.com/37310063/69568516-817c2b00-0f9a-11ea-9928-b4e401036157.png)

2. If the flow is changed but **not saved**, the user needs to confirm that he wants the changes to be lost.

- user chooses another menu item: **OK**

![menu](https://user-images.githubusercontent.com/37310063/69568580-a5d80780-0f9a-11ea-9cc8-0f66cfebd219.png)

- user clicks Return to Flow list: **OK**

![return](https://user-images.githubusercontent.com/37310063/69568596-abcde880-0f9a-11ea-9392-8ef5e486f6c5.png)

- user reloads page: **OK**

![F5](https://user-images.githubusercontent.com/37310063/69568602-b12b3300-0f9a-11ea-8bd6-a20eae9dd3c1.png)

- user closes window: **OK**

![close](https://user-images.githubusercontent.com/37310063/69568614-b5efe700-0f9a-11ea-8f61-2f9d88ff0f24.png)

3. If the modified flow is **saved**, the alert message is removed and no confirmation is requested.

- user chooses another menu item: **OK**
- user clicks Return to Flow list: **OK**
- user reloads page: **OK**
- user closes window: **OK**

4. If the flow does not change, the alert message will not be displayed and confirmation will not be requested when you leave the page.

5. If the flow is created and then changed, changes will be lost when you leave the page. (Test 5 reported on ticket: **NOK**)

**Note**: No validation if only flow name is changed

**Comment by betefaber** [comment]
When the flow changes, the alert message _Don't forget to save your updates_ is displayed.
