### ISSUE TITLE
[GUI] Device details: protocol label is different from what was registered

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1147]
In the device details screen, the protocol attribute label is different from the one that was registered.

![Screenshot_2](https://user-images.githubusercontent.com/37310063/58500273-35217100-8158-11e9-8ddc-938e9c39f39b.png)

- with other attributes, this does not happen

![Screenshot_3](https://user-images.githubusercontent.com/37310063/58500644-f04a0a00-8158-11e9-875c-64a305ee2f2a.png)

- in Portuguese, the label is translated

![Screenshot_4](https://user-images.githubusercontent.com/37310063/58500271-35217100-8158-11e9-9b4c-65c8b87559ae.png)

**Comment by cfrancisco** [comment]
Ow, that's funny. :nerd_face:

**Comment by betefaber** [comment]
Test OK.

![Screenshot_2](https://user-images.githubusercontent.com/37310063/58888048-20dff580-86bd-11e9-8a45-733e809e5fb9.png)

![Screenshot_3](https://user-images.githubusercontent.com/37310063/58888049-21788c00-86bd-11e9-978a-aa5e8b997bbc.png)

Tested on Version: **62.3-20190603**
