### ISSUE TITLE
User without permission is able to read devices and templates

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1148]
User only has the permissions **all_users** (CRUD of users) and **ro_pap** (read only of the registered profiles/permissions).

- profile **a**

![Screenshot_21](https://user-images.githubusercontent.com/37310063/58658292-94b58300-82f6-11e9-8f61-729ebfd6facd.png)

![Screenshot_22](https://user-images.githubusercontent.com/37310063/58659037-58832200-82f8-11e9-8da5-2685b74a04ce.png)

- profile permissions

![Screenshot_28](https://user-images.githubusercontent.com/37310063/58658999-3c7f8080-82f8-11e9-9fd0-0cb646a881d9.png)

When logging in with this user, the lists of devices and templates are accessed and the devices are displayed.

![Screenshot_20](https://user-images.githubusercontent.com/37310063/58658642-4bb1fe80-82f7-11e9-8012-47873c519b88.png)

- via API are also accessible

![Screenshot_27](https://user-images.githubusercontent.com/37310063/58658389-cb8b9900-82f6-11e9-8c6d-f874db7bf598.png)

![Screenshot_26](https://user-images.githubusercontent.com/37310063/58658409-d0e8e380-82f6-11e9-9d18-5ad7b6c3214e.png)

The expected behavior is that devices and templates would not be accessible.

**Note**: In version **58.2-20190321**, when trying to read devices and templates without permission, the backend response was **403 Forbidden**

**Expected Behavior**: The home page should be one it is allowed to access.

**Affected Version: 62.2-20190524**

**Comment by betefaber** [comment]
If the user does not have any permission, also has access to templates and devices.

![Screenshot at 2019-07-16 14-11-30](https://user-images.githubusercontent.com/37310063/61318806-46900c80-a7dc-11e9-8a94-5637852c567f.png)

![Screenshot at 2019-07-16 14-11-45](https://user-images.githubusercontent.com/37310063/61318818-4abc2a00-a7dc-11e9-91b4-ff6ac13352dc.png)

![Screenshot at 2019-07-16 14-12-02](https://user-images.githubusercontent.com/37310063/61319277-493f3180-a7dd-11e9-8ff4-7b693f987937.png)

**Comment by bizetti** [comment]
Ticket analysis meeting (May, 22nd): It will be retested.

**Comment by betefaber** [comment]
The user does not have access to templates and devices, but the cards are displayed (#1184).

![Screenshot_28](https://user-images.githubusercontent.com/37310063/82711144-eae3aa80-9c5a-11ea-85d3-f7046c6587cc.png)


```
 curl -X GET http://10.50.11.237:30001/template -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json'                        <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty/1.11.2.4</center>
</body>
</html>
```
```
 curl -X GET http://10.50.11.237:30001/device -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json'                          <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty/1.11.2.4</center>
</body>
</html>
```

Tested in **v0.5.0-alpha.1**
