### ISSUE TITLE
Fix text in Portuguese on "multi device out" and "multi actuator" nodes

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1156]
Steps to reproduce the problem:

1. Click "Novo Fluxo"
2. Edit "multi dispositivo out"

![Screenshot_97](https://user-images.githubusercontent.com/37310063/59380128-bec36800-8d2e-11e9-98c9-5362dbb236b5.png)

3. Edit "multi atuador"

![Screenshot_98](https://user-images.githubusercontent.com/37310063/59380141-c8e56680-8d2e-11e9-9fe2-a15782e478e2.png)

Affected Version: **62.3-20190603**

**Comment by ctossato** [comment]
Tested
