### ISSUE TITLE
[Manage Firmware] Unexpected error message: 'failed to parse attr'

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1159]
**Steps to reproduce the problem:**

1. Create a template with firmware and image added
2. Edit the template
3. Click Manage Firmware
4. Erase the name of any parameter
5. Click on SAVE button

![Screenshot_180](https://user-images.githubusercontent.com/37310063/59610541-ff84fd80-90ef-11e9-83a2-1259bcdd83b0.png)

Affected Version: **62.3-20190603**

**Comment by cfrancisco** [comment]
This bug was fixed.
