### ISSUE TITLE
[GUI] Manage Firmware: No identification of template

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1162]
No template identification in firmware management.

![templateFWUpdate](https://user-images.githubusercontent.com/37310063/60216107-8dbf5900-983f-11e9-92fe-e77d97b67c2d.png)

![ManageFW](https://user-images.githubusercontent.com/37310063/60215778-cf033900-983e-11e9-9add-75e2dbabba38.png)

Affected version: **62.3-20190603**

**Comment by cfrancisco** [comment]
It will no longer be prioritized.
