### ISSUE TITLE
[GUI] No property when firmware update attributes are saved

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1163]
When the firmware update attributes of a template are saved, the number of template properties is zero.
Saving the template, the number of properties is updated.

**Steps to reproduce the problem:**

1. Edit the template with associated FW
2. Click Manage Firmware

![templateFWUpdate](https://user-images.githubusercontent.com/37310063/60287140-8a7fa800-98e7-11e9-9ea8-4e2a34b02df8.png)

3. Click Save to save the attributes

![Screenshot at 2019-06-27 12-35-00](https://user-images.githubusercontent.com/37310063/60287169-9bc8b480-98e7-11e9-93fa-634894d26172.png)

![Screenshot at 2019-06-27 12-38-33](https://user-images.githubusercontent.com/37310063/60287186-a4b98600-98e7-11e9-8178-bf1a467e099b.png)

4. Click Save to save the template

![Screenshot at 2019-06-27 12-38-46](https://user-images.githubusercontent.com/37310063/60287311-eea26c00-98e7-11e9-872f-5705643641b2.png)

Affected Version: **62.3-20190603**

**Comment by cfrancisco** [comment]
It's still happen.

![image.png](https://images.zenhubusercontent.com/5cdb17917c26f8023263517e/f5b1cc53-a869-4b59-bfc3-ce4554abca4e)

**Comment by cfrancisco** [comment]
It will no longer be applied.
