### ISSUE TITLE
[GUI] Real time tracking is discontinued when any device is hidden

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1164]
- bus-14 tracking

![tracking14](https://user-images.githubusercontent.com/37310063/60541397-ec754e80-9ce7-11e9-9847-0dcaf19558e2.png)

- bus-14 tracking when bus-17 is hidden

![tracking14-hide17](https://user-images.githubusercontent.com/37310063/60541403-f39c5c80-9ce7-11e9-9bf9-73fe96c8b95c.png)

- bus-14 tracking when bus-17 is shown

![tracking14-show17](https://user-images.githubusercontent.com/37310063/60541415-fd25c480-9ce7-11e9-83be-624ed2b14d2c.png)

Affected version: **62.3-20190603**

**Comment by betefaber** [comment]
It also happens if you click on "Hide All" and "Show All".

- show all

![image](https://user-images.githubusercontent.com/37310063/61542156-5fd0cd00-aa17-11e9-99db-eebdcf4da4a1.png)

- hide all

![image](https://user-images.githubusercontent.com/37310063/61542207-75de8d80-aa17-11e9-8253-4f157e4ef24e.png)

- show all

**Comment by bizetti** [comment]
Ticket analysis meeting (May, 22nd): Out of roadmap column in this moment.

**Comment by betefaber** [comment]
Tested in baseline v0.4.3-rc2, k8s environment:

![image](https://user-images.githubusercontent.com/37310063/92150898-8b1ea300-edf6-11ea-920c-391f170289a8.png)

**Comment by eduardogmisiuk** [comment]
The same behaviour happens in v0.5.0-rc1. Docker Compose environment, using VerneMQ as iotagent.

**Comment by FrancielePessi** [comment]
The same behaviour happens in v0.5.0-rc1. Kubernetes - K8s environment, using Mosca

**Comment by cfrancisco** [comment]
The real-time tracking mechanism was disabled (dojot 0.6).
