### ISSUE TITLE
[GUI][Image-manager] GUI break when file is invalid

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1165]
When the file is associated with the FW version is invalid, a blank screen is displayed.

**Steps to reproduce the problem:**

1. Create the FW version
2. Associate an invalid file (not .HEX)

![updateFW-InvalidFile](https://user-images.githubusercontent.com/37310063/60615159-e1ccbf00-9da4-11e9-860a-009bd734727d.png)

3. Click SAVE

![updateFW-Tela](https://user-images.githubusercontent.com/37310063/60615173-e98c6380-9da4-11e9-8a86-353e4dbd11b4.png)

Affected version: **62.3-20190603**

**Comment by mprevide** [comment]
not use as validation the fact that the file name has .hex as an extension

**Comment by bizetti** [comment]
Ticket analysis meeting (March, 6th): Verify if it is happening.

**Comment by betefaber** [comment]
Still happens in version **v0.4.2**

![Screenshot at 2020-03-09 11-56-49](https://user-images.githubusercontent.com/37310063/76226854-36122380-61fd-11ea-9fd9-a34a94cfd4ca.png)

**Note**: The file extension should not be limited to .hex (#943)

**Comment by betefaber** [comment]
The GUI break was fixed in the v0.4.3, although it still requires the .HEX extension.


![Screenshot_2](https://user-images.githubusercontent.com/37310063/91075990-3d938080-e615-11ea-863f-38838bcdaadf.png)

![Screenshot_1](https://user-images.githubusercontent.com/37310063/91076204-877c6680-e615-11ea-9dcf-a347de787d6b.png)

![Screenshot_3](https://user-images.githubusercontent.com/37310063/91075983-3c625380-e615-11ea-809b-4b2ff8eb6195.png)

**Comment by betefaber** [comment]
The GUI break was fixed in the v0.5.0-alpha.4, although it still requires the .HEX extension.

![Screenshot_43](https://user-images.githubusercontent.com/37310063/94485269-0f750380-01b4-11eb-8c6c-303b2686da17.png)
