### ISSUE TITLE
Unsecured mode configuration is case sensitive

### ISSUE THREAD

**Issue by ericbaum** [dojot/dojot#1170]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug report

* **What is the current behavior?**
In the current behavior if we set the variable ALLOW_UNSECURED_MODE as "True" it does not work, the value is treated as false. The only value that is accepted is "true".

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
To reproduce the issue, just set the variable ALLOW_UNSECURED_MODE as "True", the unsecured mode will not be enabled

* **What is the expected behavior?**
The expected behavior is that the variable tolerates variations of the True keyword like true, TRUE, True, 1, etc

* **What is the motivation / use case for changing the behavior?**
Avoid configuration mistakes made by users because of the way they are used to writing reserved terms

* **Please tell us about your environment:**
  
  - Version: 0.3.x
  - Environment: [kubernetes]
  - Operating system: [Ubuntu 18.04]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by betefaber** [comment]
Test OK.

Tested in **v0.5.0-alpha.1**
