### ISSUE TITLE
Standardize environment variable names

### ISSUE THREAD

**Issue by ericbaum** [dojot/dojot#1171]
* **I'm submitting a ...**
  - [ x ] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
There is a need to standardize and document iotagent-mqtt environment variables as it is causing issues after their names were changed, mainly the Kafka related variables

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.3.x
  - Environment: [kubernetes]
  - Operating system: [Ubuntu 16.04]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rascaraficci** [comment]
In the newer versions of the dojot platform the environment variables are standardized.
