### ISSUE TITLE
[GUI] Message has not been translated

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1176]
**Steps to reproduce the problem:**

1. Click "Novo Fluxo"
2. Edit flow

![image](https://user-images.githubusercontent.com/37310063/61055108-240a8780-a3c7-11e9-8408-21974e4ed932.png)

Affected version: **63.1-20190705**

**Comment by betefaber** [comment]
3. Click F5

![image](https://user-images.githubusercontent.com/37310063/62142314-7a7f2d80-b2c4-11e9-844c-cc262e123868.png)

**Comment by bizetti** [comment]
It will be retested.

**Comment by betefaber** [comment]
Test OK. 

- edit/update flow:

![image](https://user-images.githubusercontent.com/37310063/88228529-b2a21d80-cc45-11ea-8c28-a4d5d93ffdce.png)

- reload page:

![image](https://user-images.githubusercontent.com/37310063/88228699-ed0bba80-cc45-11ea-890f-b8edf110f365.png)

Tested in **v0.5.0-alpha.2**
