### ISSUE TITLE
[iotagent-mqtt] Logger level using environment variable

### ISSUE THREAD

**Issue by joab-cpqd** [dojot/dojot#1177]

**Comment by betefaber** [comment]
LOG_LEVEL environment variable has been added.

Log levels:

- debug
![level-debug](https://user-images.githubusercontent.com/37310063/84176811-5d74c880-aa58-11ea-9037-5c1320d2ab68.png)

- info
![level-info](https://user-images.githubusercontent.com/37310063/84176825-62d21300-aa58-11ea-947d-c9e18167b6f6.png)

- warn
![level-warn](https://user-images.githubusercontent.com/37310063/84176847-69f92100-aa58-11ea-9655-982ec419ba06.png)

- error
![image](https://user-images.githubusercontent.com/37310063/84177153-daa03d80-aa58-11ea-8c56-b1283e7f18b3.png)

Tested in **v0.5.0-alpha.1**
