### ISSUE TITLE
Context Manager Logger Port for Kubernetes

### ISSUE THREAD

**Issue by andersonluisribeiro** [dojot/dojot#1178]
As a sysadmin
I want that flowbroker and context manager use the different logger ports
So that I run both in the same Kubernetes Pod

Acceptance criteria:

Scenario: Run flow broker and context manager
Given that I need to run flow broker and context manager in the same Kubernetes Pod
When I run dojot using kubernetes
Then I see flowbroker and context manager running in the same Kubernetes Pod

**Comment by betefaber** [comment]
Environment variable has been added.
