### ISSUE TITLE
The list of templates is not ordered by label

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1181]
- in creating devices

![image](https://user-images.githubusercontent.com/37310063/61226684-40752f80-a6f9-11e9-91f1-e0342f9c7db4.png)

- in template filtering

![image](https://user-images.githubusercontent.com/37310063/61226737-5a167700-a6f9-11e9-977e-0779bfadca5a.png)

Affected version: **63.1-20190705**

**Comment by mprevide** [comment]
Probably associate #1022

**Comment by betefaber** [comment]
Test OK.

**GUI image:**    image: dojot/gui:release_63.1-20190705

![listatemplatesordenada](https://user-images.githubusercontent.com/37310063/61896781-07ed0700-aeec-11e9-8ef7-df3109243c74.png)

----
![image](https://user-images.githubusercontent.com/37310063/61897496-85654700-aeed-11e9-90c4-0998c48abcac.png)


Tested in version: **63.1-20190705**
