### ISSUE TITLE
User without permission view the list of devices

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1184]
If the user does not have permissions, no page should be accessed. However, the device list is being displayed.

![Screenshot at 2019-07-16 14-11-30](https://user-images.githubusercontent.com/37310063/61318361-45121480-a7db-11e9-991d-2fb01dff9b93.png)

Affected version: **63.1-20190705**

**Comment by betefaber** [comment]
The command **git submodule update --init --recursive** hs been executed. 

Devices are no longer viewed. But the message **Call failed** is displayed.

![1184](https://user-images.githubusercontent.com/37310063/62061590-e185df00-b1fd-11e9-8fc8-41ac6230fa53.png)

**Comment by bizetti** [comment]
Ticket analysis meeting (May, 22nd): It will be retested.

**Comment by betefaber** [comment]
The error still happens: cards are displayed

![Screenshot_23](https://user-images.githubusercontent.com/37310063/82709641-6f342e80-9c57-11ea-8789-4832bfbe51aa.png)

Tested in **v0.5.0-alpha.1**

**Comment by betefaber** [comment]
**Note**: Need to clear the browser cache.

![1184](https://user-images.githubusercontent.com/37310063/83288952-a015e580-a1ba-11ea-8fa1-a98cede5682b.png)
