### ISSUE TITLE
[GUI] Attribute metadata are not specialized  in creating or changing device (attribute has more than one metadata)

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1191]
When the attribute has more than one metadata, it is not possible to specialize this metadata when creating / changing the device.

**Steps to reproduce the problem:**

1. Create a template
2. One of the template attributes has more than one metadata

- metadata - initial value

![criacao-device](https://user-images.githubusercontent.com/37310063/61651113-931b9200-ac8b-11e9-87c8-ae57277b1a38.png)

- specializing metadata 1

![meta1](https://user-images.githubusercontent.com/37310063/61649697-5c904800-ac88-11e9-82cf-3a50d6be1d99.png)

- specializing metadata 2: value of metadata 1 = initial value

![meta2-1](https://user-images.githubusercontent.com/37310063/61649714-6619b000-ac88-11e9-9700-084f92ebe24f.png)

- specializing metadata 1: value of metadata 2 = initial value

![meta1-2](https://user-images.githubusercontent.com/37310063/61649734-6dd95480-ac88-11e9-9051-09cb71e7fa30.png)

Affected version: **63.1-20190705**

**Comment by bizetti** [comment]
Ticket analysis meeting (May, 22nd): It has to fix. Not typical use.
