### ISSUE TITLE
MQTT - CNAME (user) is the same for all instances

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1192]
All iot-agent runs are registered with the same "user" (cname) in EJBCA.
Is this a problem for scalability?

**Comment by mprevide** [comment]
initialConf.py

35  certUtils.createEJBCAUser(conf.EJBCA_API_URL, conf.CAName, "mosca", passwd)

**Comment by rascaraficci** [comment]
We've already discussed this issue with our security team, and concluded that for our use case, its not a problem.
