### ISSUE TITLE
EJBCA - CA name 

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1196]
The CA Name is a certificate-retriever parameter, but nothing other than IOTmidCA is accepted, because a CA is always generated at EJBCA-Rest startup, named IOTmidCA.

**Comment by betefaber** [comment]
Test OK.
```
openssl x509 -noout -subject -in 26d6e3.crt
subject=CN = admin:26d6e3
```
Tested in **v0.5.0-alpha.1**
