### ISSUE TITLE
[data-broker] use environment variable to set logger level

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1199]

**Comment by betefaber** [comment]
LOG_LEVEL environment variable has been added.

Log levels:

- debug

![data-broker-debug](https://user-images.githubusercontent.com/37310063/85075218-33c44b80-b194-11ea-910b-1cc067116f03.png)

- info

![data-broker-info](https://user-images.githubusercontent.com/37310063/85075244-39ba2c80-b194-11ea-970f-cdf946f36558.png)

- warn

![data-broker-warn](https://user-images.githubusercontent.com/37310063/85075258-3fb00d80-b194-11ea-836f-d69868efa384.png)

- error

![data-broker-error](https://user-images.githubusercontent.com/37310063/85075273-463e8500-b194-11ea-829d-fb4042c7cedc.png)

Tested in **v0.5.0-alpha.1**
