### ISSUE TITLE
[GUI] Invalid profile name: text has not been translated

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1207]
**Steps to reproduce the problem:**

1. Click "Novo perfil"
2. Fill in "Nome do perfil" with invalid value
3. Fill in the description
4. Click Save

![Screenshot at 2019-07-26 16-17-07](https://user-images.githubusercontent.com/37310063/61978153-d72dd000-afc6-11e9-8edf-0e393b3fa1c5.png)

Affected version: **63.1-20190705**

**Note**: GUI image: **_dojot/gui:release_63.1-20190705_**

**Comment by bizetti** [comment]
Ticket analysis meeting (May, 22nd): Low

**Comment by cfrancisco** [comment]
![image.png](https://images.zenhubusercontent.com/5cdb17917c26f8023263517e/265a4214-d79c-4ba4-8405-8f48e1c6b628) 

The bug was fixed (dojot 0.6).
