### ISSUE TITLE
Improve Data Broker log messages

### ISSUE THREAD

**Issue by andersonluisribeiro** [dojot/dojot#1208]
As a sysadmin
I want to see a good Data Broker message log
So that I debug de service efficiently

Acceptance criteria:

Scenario: Debugging Data Broker
Given that I need to debug data broker
When I run and use the service
Then I see the log messages with correct levels, without unnecessary messages and with messages that generate value

**Comment by eduardogmisiuk** [comment]
Issue related to https://github.com/dojot/dojot/issues/1202.

**Comment by bizetti** [comment]
Done.
