### ISSUE TITLE
Dojot não conecta (offline)/conversa com o App Automate.

### ISSUE THREAD

**Issue by AndreLovo** [dojot/dojot#1213]
Caros, bom dia!!
Instalei o Dojot em um SO Linux Ubuntu 16.04 LTS, através de máquina virtual.
Para fazer uma simulação usei o tutorial do site: 

https://www.embarcados.com.br/simulacao-de-dispositivos-na-plataforma-dojot/

Instalei no meu smartphone o Automate que está "rodando", e enviando as informações (o smathphone "escuta o som e envia as informações"), mas o Dojot não consegue ler estas informações ou não está as recebendo(o componente só fica em modo offline - vermelho).

Como faço para fazer o meu componente no Dojot ficar online (Linha Azul). 
 
Muito obrigado.

**Comment by cfrancisco** [comment]
Olá @AndreLevo! 

Gostaria de confirmar algumas informações, você chegou a realizar os testes de envio utilizando mosquitto_pub e funcionou corretamente?

Há um simulador de envio continuo de dados para a plataforma que pode ajudar a testar o efeito online/offline: https://github.com/rascaraficci/tracking-simulator

Caso esteja operando corretamente, há um problema de comunicação do Automate com a Dojot e podemos verificar mais a fundo isto.

**Comment by AndreLovo** [comment]
Consegui resolver o problema @cfrancisco!! 
Muito obrigado pela resposta!!
