### ISSUE TITLE
[data-broker] Topic is created/retrieved even if there is an error

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1223]
From `TopicManager` class.
In the `if` block at line 82, the code does not return after receiving an error, causing the program to continue the flow and (to try to) create/retrieve the topic.
Another problem is that if no callback is passed and an error has occurred, it will not be treated nor reported at all.

![error not being treated](https://user-images.githubusercontent.com/12804963/62729989-7c986900-b9f5-11e9-9838-5c0ee02f7b36.png)

**Comment by bizetti** [comment]
Done.
