### ISSUE TITLE
Update Image - Image files do not appear properly when transferring an image to the device.

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1227]
1° )    3 templates were created using the simulator. 
![1 Update image](https://user-images.githubusercontent.com/52173618/62866294-d6937a00-bce6-11e9-930b-2e4bf37d739f.png)

2°)     3 devices were created using the simulator.
![2 Updade Image](https://user-images.githubusercontent.com/52173618/62866521-53265880-bce7-11e9-9cba-73e72e049897.png)

3°)   A new template was created manually and 4 image files were added and then template was associated with the device.
![3 Update image](https://user-images.githubusercontent.com/52173618/62868101-37bd4c80-bceb-11e9-85e4-71a513ba9cc6.png)

- Adding template to device
![6 Updade Image](https://user-images.githubusercontent.com/52173618/62872581-2c225380-bcf4-11e9-9e05-1d8271785f53.png)

 - Added hexadecimal images 
![4 Updade Image](https://user-images.githubusercontent.com/52173618/62868236-8c60c780-bceb-11e9-9bfe-5925713744e4.png)

4°)   When it is necessary to transfer images to the device, the system has difficulty understanding which model to fetch the images from, thus bringing images from a template created by the simulator and sometimes bringing images from the manually created template.

![5 Updade Image](https://user-images.githubusercontent.com/52173618/62869062-72c07f80-bced-11e9-8d25-f874c78494c5.png)

**Comment by bizetti** [comment]
Ticket analysis (Dec, 27th): The system should deny more then one template with FW image.

**Comment by cfrancisco** [comment]
It will no longer be applied.
