### ISSUE TITLE
[Auth] Giving Permissions to users.

### ISSUE THREAD

**Issue by nativanando** [dojot/dojot#1228]
I've been a problem with user permissions management.

Let me explain it better: I'm creating new permissions to deny some resources to specific users on dojot, the flow is basically to create a new permission and to delegate it to a user, but when I try to access the resource with the user the rules are not applied.

the code bellow shows an example:

```javascript
 const addPermission = () => {
    try {
      const requestParams = {
        "path": "/device/(.*)",
        "method": "(.*)",
        "permission": "deny",
        "name": "device_deny_operations"
      }
      const url = '/auth/pap/permission';
      const response = post(url, requestParams, getToken());
      if (!response.ok && response.status === 400) {
        return 0;
      }
    } catch (e) {
      console.error("Error on submit - There's something wrong", e);
    }
 }
```
Suppose this permission above was included to a user, my question is: in this case the user wouldn't have access to the '/device/' resources, would it? Because it's not working...

Can someone help me?
Thanks a lot!

**Comment by mprevide** [comment]
Hello,

Did you install the external modules with the command below ?
```
git submodule update --init --recursive
```
(https://dojotdocs.readthedocs.io/en/development/installation-guide.html)

**Comment by nativanando** [comment]
Hello @mprevide thanks for the tips, it works!! I Just wanna know why aren't the submodules load by default?  Is there a way to config or enable them automatically? In my opinion these features are very important then it would be interesting to enable automatically! (just a suggest :smile: )

**Comment by mprevide** [comment]
Thanks for the tip.
We are thinking of doing something like this in the future, it's in our roadmap. :smile:
