### ISSUE TITLE
Device attribute visualization toggled by any keyboard key press

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1232]
**Steps to reproduce**:
- Open any device details screen in a device with at least one dynamic attribute
- Click in any dynamic attribute
- The visualization of this attribute can be toggled by pressing any key in the keyboard

**Tested in**:
- Google Chrome version 75.0.3770.142 64bits
- Firefox Quantum version 68.0.1 64bits
- Dojot latest development version

**Comment by bizetti** [comment]
Ticket analysis meeting (April, 17th): Improvement.

**Comment by cfrancisco** [comment]
It's still happen.
