### ISSUE TITLE
Device list is not displayed after remove last device from the page

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1242]
**Steps to reproduce the problem:**

1. Create some devices

![last_device](https://user-images.githubusercontent.com/37310063/63797779-1eb5bd80-c8df-11e9-8839-e4ac6cb7aabc.png)

2. Remove the last device from a page

![device_removed](https://user-images.githubusercontent.com/37310063/63797787-24130800-c8df-11e9-82d7-348101926814.png)

Affected version: **63.2-20190820**

**Comment by juliamourac** [comment]
Solved with dojot/dojot#1179

**Comment by betefaber** [comment]
Problem remains in version **v0.4.2**.

**Comment by betefaber** [comment]
Test OK.

- **last device on page 3**

![Screenshot_52](https://user-images.githubusercontent.com/37310063/83685664-66c8e580-a5bf-11ea-974c-ed75e16eb09c.png)

----
![Screenshot_53](https://user-images.githubusercontent.com/37310063/83685721-7ea06980-a5bf-11ea-873a-2d5a48015238.png)

- **last device**

![Screenshot_55](https://user-images.githubusercontent.com/37310063/83686033-efe01c80-a5bf-11ea-9cad-e9c3cb1da915.png)
----
![Screenshot_56](https://user-images.githubusercontent.com/37310063/83686028-eeaeef80-a5bf-11ea-8f51-c65b32af49b6.png)

Tested in **v0.5.0-alpha.1**

**Comment by betefaber** [comment]
**This has not been fixed in v0.4.3-rc.2**

- last device on page 3

![0 4 3-1](https://user-images.githubusercontent.com/37310063/91492581-4b9f0680-e88c-11ea-874d-05388c4d8c64.png)

- remove device

![0 4 3-2](https://user-images.githubusercontent.com/37310063/91492586-4cd03380-e88c-11ea-8136-fe6652866def.png)

- click page 2

![0 4 3-F5](https://user-images.githubusercontent.com/37310063/91492588-4d68ca00-e88c-11ea-9e1a-0f6dabd43875.png)

----

**But has been fixed in v0.5.0-alpha.4**

- last device on page 3

![0 5 0-1a](https://user-images.githubusercontent.com/37310063/91492778-9882dd00-e88c-11ea-8f46-86efdc637f1e.png)

- remove device

![0 5 0-2a](https://user-images.githubusercontent.com/37310063/91493582-ec41f600-e88d-11ea-92c9-5d2cc5b9d524.png)

**Comment by bizetti** [comment]
It has fixed in 0.5.x version.
