### ISSUE TITLE
[GUI] A firmware version is kept on screen even after its deletion

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1251]
After user clicks on confirm button a delete request is sent to server. the screen is not refreshed and the deleted firmware still is displayed.
![1](https://user-images.githubusercontent.com/53264012/64977034-fb03e880-d888-11e9-8687-5933a15eb342.png)
_____________________________________________________
![2](https://user-images.githubusercontent.com/53264012/64977039-fdfed900-d888-11e9-9fb5-3e5e96548ce8.png)
In this moment, a delete request is sent
_______________________________________________________
![3](https://user-images.githubusercontent.com/53264012/64977043-ffc89c80-d888-11e9-9bdd-2e142e019704.png)

**Comment by betefaber** [comment]
Teste OK.

- Adding images FW-1.0 e FW-2.0:
```
image-manager_1               | 172.18.0.19 - - [21/Oct/2019:15:31:17 +0000] "POST /image/ HTTP/1.1" 201 177 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
image-manager_1               | 172.18.0.19 - - [21/Oct/2019:15:31:17 +0000] "POST /image/1840f975-1842-448d-bd79-212f56938c1b/binary HTTP/1.1" 200 86 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
image-manager_1               | 172.18.0.19 - - [21/Oct/2019:15:31:38 +0000] "POST /image/ HTTP/1.1" 201 177 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
image-manager_1               | 
image-manager_1               | {'label': '3', 'fw_version': 'FW-1.0'}
image-manager_1               | {'label': '3', 'fw_version': 'FW-1.0'}
image-manager_1               | 
image-manager_1               | {'label': '3', 'fw_version': 'FW-2.0'}
image-manager_1               | {'label': '3', 'fw_version': 'FW-2.0'}
image-manager_1               |  - - [21/Oct/2019:15:31:38 +0000] "POST /image/0c870241-1fbb-4712-906f-6972d95d8e5b/binary HTTP/1.1" 200 86 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
```
![Screenshot at 2019-10-21 12-32-20](https://user-images.githubusercontent.com/37310063/67220248-d1962980-f3ff-11e9-8ee7-3a924ae713c6.png)

----
- image FW-2.0 removed
```
image-manager_1               | 172.18.0.19 - - [21/Oct/2019:15:32:42 +0000] "DELETE /image/0c870241-1fbb-4712-906f-6972d95d8e5b HTTP/1.1" 200 273 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
```
![Screenshot at 2019-10-21 12-32-46](https://user-images.githubusercontent.com/37310063/67220274-db1f9180-f3ff-11e9-8e7f-ca75c28c365f.png)

----
- image FW-1.0 removed
```
image-manager_1               | 172.18.0.19 - - [21/Oct/2019:15:33:26 +0000] "DELETE /image/1840f975-1842-448d-bd79-212f56938c1b HTTP/1.1" 200 273 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
```
![Screenshot at 2019-10-21 12-33-29](https://user-images.githubusercontent.com/37310063/67220283-e1157280-f3ff-11e9-94cb-010bb9080398.png)

Tested on version **v0.4.1**
