### ISSUE TITLE
Device - Message Actuator

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1255]
When a message acts / arrives on the device, when loading the page, the message disappears.

Message has arrived. 

![Menssagem 1](https://user-images.githubusercontent.com/52173618/65707065-24c7c700-e062-11e9-826c-0b80d90e0914.png)

When reloading the page, message is not found.

![Menssagem 2](https://user-images.githubusercontent.com/52173618/65707146-4c1e9400-e062-11e9-8da8-db4edccb81ed.png)

**Comment by bizetti** [comment]
Solved in #1246
