### ISSUE TITLE
[GUI] [Firefox] 'Set Password' screens are not OK when Password Manager is acting

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1264]
When user is using password manager of Firefox, with at least one password saved, the screens 'New password' and 'modify password' show a weird message and fill some field, even when he is not logged with a user that has a password saved. See the following pictures (No text was typed in):

![NewPwd](https://user-images.githubusercontent.com/53264012/67283045-58eba780-f4a9-11e9-9ab6-7c4abd7c19d0.png)
 
![ModifyPwd](https://user-images.githubusercontent.com/53264012/67283075-630da600-f4a9-11e9-9324-4048259661a3.png)

**Comment by bizetti** [comment]
Ticket analysis meeting (April, 3rd): Fix after.

**Comment by cfrancisco** [comment]
It will no longer be applied.
