### ISSUE TITLE
[GUI] [Português] Tela de cadastro de senha exibe tradução errada "Novo senha"

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1265]
Tela de cadastro de senha exibe tradução errada "Novo senha". Deveria ser "Nova senha"

![NewPwd](https://user-images.githubusercontent.com/53264012/67287929-65c0c900-f4b2-11e9-8bdf-a613580a0f86.png)

**Comment by FrancielePessi** [comment]
![Captura de tela de 2020-06-08 15-27-38.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/2f806da2-8968-426b-8920-f3032506b739)

Problem solved
