### ISSUE TITLE
Modular GUI: Screen prototypes for UC Dashboard

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1293]
- [x] Define interviews script
- [x] Define interviewed users
- [x] Apply interviews
- [x] Analyse results
- [x] Design sprint
- [x] Low-Fidelity Prototype
- [x] High-Fidelity Prototype

**Comment by nunesjoab** [comment]
Final wireframes used to test users about Dashboard

[https://app.zenhub.com/files/103167521/27a4830f-1c82-4ef2-95fd-d2b6d1fd9e30/download](https://app.zenhub.com/files/103167521/27a4830f-1c82-4ef2-95fd-d2b6d1fd9e30/download)
