### ISSUE TITLE
[Flow broker] Notification node should assure the structure of his document in mongodb

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1299]
I has created a flow with a http node followed by a notification node. http node output was configured as input of notification node. It produce a invalid JSON as document in mongodb:

> { "_id" : ObjectId("5db0900e2e83690006db43c8"), "msgID" : "9f713ac3-dd77-4dba-b8de-b6564580b7d3", "message" : { "statusCode" : 200, "headers" : { "access-control-allow-origin" : "*", "content-type" : "text/html; charset=utf-8", "x-cloud-trace-context" : "34195791fcc7ef64ae160ba3fe7cd06e", "date" : "Wed, 23 Oct 2019 17:38:21 GMT", "server" : "Google Frontend", "content-length" : "54", "connection" : "close" }, "responseUrl" : "http://ptsv2.com/t/03h43-1568895574/post", "payload" : "Thank you for this dump. I hope you have a lovely day!", "shouldPersist" : true }, "metaAttrsFilter" : { "statusCode" : 200, "headers" : { "access-control-allow-origin" : "*", "content-type" : "text/html; charset=utf-8", "x-cloud-trace-context" : "34195791fcc7ef64ae160ba3fe7cd06e", "date" : "Wed, 23 Oct 2019 17:38:21 GMT", "server" : "Google Frontend", "content-length" : "54", "connection" : "close" }, "responseUrl" : "http://ptsv2.com/t/03h43-1568895574/post", "payload" : "Thank you for this dump. I hope you have a lovely day!", "shouldPersist" : true }, "subject" : "user_notification", "ts" : ISODate("2019-10-23T17:38:21.631Z") }
> { "_id" : ObjectId("5db098b12e83690006db43ce"), "msgID" : "f9594c46-4267-4264-b939-14ac4abab303", "message" : "asdasd", "metaAttrsFilter" : { "statusCode" : 200, "headers" : { "access-control-allow-origin" : "*", "content-type" : "text/html; charset=utf-8", "x-cloud-trace-context" : "a9592a00b3d1695dd92cb1fd7a54f063", "date" : "Wed, 23 Oct 2019 18:15:12 GMT", "server" : "Google Frontend", "content-length" : "54", "connection" : "close" }, "responseUrl" : "http://ptsv2.com/t/03h43-1568895574/post", "payload" : "Thank you for this dump. I hope you have a lovely day!", "shouldPersist" : true }, "subject" : "user_notification", "ts" : ISODate("2019-10-23T18:15:12.247Z") }

gui notification list crashes after this document has been inserted.

**Comment by bizetti** [comment]
Ticket analysis meeting (Dec, 2nd): GUI should verify if the input is a JSON. Notification node should verify if the input is a JSON as well.

**Comment by betefaber** [comment]
Tested in v0.4.3-rc.1.
