### ISSUE TITLE
Security: EJBCA's private key persistence

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1300]

**Comment by muhamedcpqd** [comment]
For this issue, we will create a doc and a script to help the system administrator export/import the keys/certificate file (.p12 file) related with the ROOT CA. For now, this issue and the feature related will be 'on hold'.

**Comment by muhamedcpqd** [comment]
This issue is related with dojot/dojot#1305

**Comment by muhamedcpqd** [comment]
When EJBCA create the tables in postgres db, he automatically inserts his keys (private and public) and his certificates in the database, persisting all his data.
