### ISSUE TITLE
[GUI] Satellite images not loading

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1303]
Execute the following steps to reproduce:

1 - Insert at lest one device
2 - Click on Templates on left menu bar
3 - Click on Devices on left menu bar
4 - Enable the Map view
5 - Configure to Satellite view
6 - Repeat the steps 2 to 5. (For first time the satellite images are loaded)

**Comment by bizetti** [comment]
Ticket analysis meeting (April, 17th): Have to be fixed but it is low priority.

**Comment by eduardogmisiuk** [comment]
I couldn't reproduce this problem in v0.5.0-rc.1. The only problem is that it sometimes get a little clumsy to load the pages.

**Comment by cfrancisco** [comment]
This issue was resolved when we updated the Map schema.
