### ISSUE TITLE
Como migrar os devices de um dojot para o outro

### ISSUE THREAD

**Issue by angela-aads** [dojot/dojot#1310]
Eu criei disposiivos em um Dojot e preciso migrar para outro Dojot...ao invés de fazer o template novamente, que outro caminho posso faze-lo

**Comment by nunesjoab** [comment]
Qual a versão da Dojot? Nas versões mais recentes há a opção Exportar (na setinha ao lado do nome do usuário no canto superior direito), que exporta os templates e dispositivos.

**Comment by angela-aads** [comment]
Olá Joab!

Minha versão é a mais recente...faz um mês que instalei...
Ao clicar nessa setinha ñ tem essa opção de exportar!
Ângela



Em sex, 8 de nov de 2019 15:35, Joab R. Nunes <notifications@github.com>
escreveu:

**Comment by nunesjoab** [comment]
Angela,
boa tarde.

Mesmo tendo instalado a Dojot há um mês, você pode ter instalado uma versão anterior a que possui o recurso de Importar/Exportar.
Segue uma imagem de onde essa opção está localizada. Caso não encontre essa opção, temos que ver qual versão da Dojot está instalada para ver quais outras opções estão disponíveis pra você exportar os seus dados.

![Dojot_Importar-Exportar](https://user-images.githubusercontent.com/13135441/68796405-90292080-0631-11ea-801c-88705082f3c4.png)

**Comment by mprevide** [comment]
Você pode descobrir sua versão exata: 
https://github.com/dojot/dojot/issues/1311#issuecomment-557175512

**Comment by bizetti** [comment]
Fechado por inatividade.
