### ISSUE TITLE
Como criar alarmes

### ISSUE THREAD

**Issue by angela-aads** [dojot/dojot#1311]
dentro de data flow quero realizar a criação de um alarme para quando um veiculo sair na área de atividade... como faço

**Comment by mprevide** [comment]
Olá,
Qual é a sua versão da dojot? 
Você pode executar `docker ps --format '{{.Image}}'` (precisa de root) e ver as images dos containers que estão sendo executados atualmente. 
As images da dojot iniciam com **dojot/** , seguem com o nome do serviço e depois a tag  **dojot/service:tag**, olhando a **tag** você pode descobrir qual versão da dojot está rodando.

**Comment by mprevide** [comment]
Na versão v0.4.0 nos oferecemos o serviço de notificação, que poderia contemplar o que você precisa. 

Nó do flow:
https://dojotdocs.readthedocs.io/en/v0.4.0/flow.html#notification

Nó de geolocalização (permite disparar um evento caso sai de uma área definida. )
https://dojotdocs.readthedocs.io/en/v0.4.0/flow.html#geofence

Qualquer outra dúvida estamos a disposição.

**Comment by bizetti** [comment]
Os tickets que não têm evolução por mais de 90 dias serão fechados.
