### ISSUE TITLE
[FW Update] [GUI] a version that don't have a binary associated must not be listed in "images available to transfer"

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1316]
User can select a version without a binary associated to "transfer image to device"

It can cause confusion because user can transfer the image and it seems to be ok. Maybe user has forgot to upload the binary.

steps to reproduce:
1 - add a version and don't upload a binary.
![fw_version](https://user-images.githubusercontent.com/53264012/68695947-c34cb080-055a-11ea-8cfb-1ac1f2bc8eaa.PNG)

2 - Go to firmware update screen of a device.
3 - realise that the version created in step 1 is in list

**Comment by bizetti** [comment]
Ticket analysis meeting (March, 27th):  Suggestion accepted.

**Comment by bizetti** [comment]
Won't be fixed.
