### ISSUE TITLE
Paging - Backend returns wrong number of device pages when some devices are deleted

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1317]
Linket to #dojot/dojot 1179

**Comment by bizetti** [comment]
Ticket analysis meeting (March, 27th): It's necessary better caracterization.

**Comment by betefaber** [comment]
Related to #1242.

**Comment by betefaber** [comment]
- last device on the page has been removed

![Screenshot_7](https://user-images.githubusercontent.com/37310063/77771719-d356bf80-7025-11ea-922f-7d20cb067b92.png)

- wrong number of device pages and
- although there are devices on the previous pages, it displays the message "nenhum dispositivo configurado"


![Screenshot_6](https://user-images.githubusercontent.com/37310063/77771782-e8335300-7025-11ea-8a71-d4bf5923352f.png)

- request

![Screenshot_8](https://user-images.githubusercontent.com/37310063/77771797-eec1ca80-7025-11ea-8405-ca869fec371a.png)

- after F5

![Screenshot_9](https://user-images.githubusercontent.com/37310063/77771828-fc775000-7025-11ea-9a22-c6a79902294c.png)

Tested in version: **v0.4.2**

**Comment by cfrancisco** [comment]
The bug has been fixed (dojot 0.6).
