### ISSUE TITLE
 Login Messages 

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1319]
Entering an incorrect password displays two informational messages, both of which are the same with different animations.
![1 Mensagens.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/72f56476-3867-4d5f-932f-62beea8a14e5)

Keep following message
![2 correta.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/978497c3-b8cf-4e4b-bada-8b076ffdd531)

Environment tested: Kubernetes

**Comment by bizetti** [comment]
Ticket analysis meeting (March, 27th): Low.

**Comment by cfrancisco** [comment]
It still happens.

**Comment by cfrancisco** [comment]
It will no longer be applied.
