### ISSUE TITLE
User without password registered

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1320]
1° Create a new user.
2° An email will be sent containing a link to be entering a password.
3° To perform the test, this link was ignored, and only the user registration was performed. 
4° An attempt was made to log in with the new user without password registration.
5° The following message is displayed:
                       * "user not found or wrong password".
The message to be presented should be more intuitive so that the user does not get lost in the process, such as:
                   *Password not fulfilled 
or
                   *This user is inactive.

 ![user not found or wrong password.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/8536da9b-a652-41cb-9c2a-42ba189984de)

**Comment by bizetti** [comment]
It's ok the behavior. Ticket cancelled.
