### ISSUE TITLE
 Login message - Out of pattern content and design

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1321]
1° Recover a user's password (Forgot Password?)
![4Forgot Password](https://user-images.githubusercontent.com/52173618/69158155-bda81b00-0ac4-11ea-9b6a-df3f5421dda6.png)

2° Enter a username that does not exist in the database to retrieve the password.
![5Recuparar senha](https://user-images.githubusercontent.com/52173618/69158265-ed572300-0ac4-11ea-8e15-b55b23f25655.png)

3° Click the send button, a message will appear informing you that the email has been sent. However, the message box format is not standard (design) and the message content does not correspond to the expected, expected message, "User not found".
![3fora do padrão](https://user-images.githubusercontent.com/52173618/69165404-4d9f9200-0ad0-11ea-9212-608626b97ba9.png)

**Comment by bizetti** [comment]
Ticket analysis meeting (March, 27th): It has to put more data in this ticket. What is the standard?

**Comment by FrancielePessi** [comment]
In a conversation with Joab, it was seen that step 3, would be out of the content when a non-existent user was inserted. Being sent an email even when the user does not exist. Expected message, something like "User not found".

**Comment by cfrancisco** [comment]
It will no longer be applied.
