### ISSUE TITLE
Login Message - Message Description

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1322]
1° Click on -> Forgot password 
![4Forgot Password](https://user-images.githubusercontent.com/52173618/69166656-5beead80-0ad2-11ea-8915-194f2ce8d6fc.png)

2°  Login with unregistered user "Any user"
![1usuario incorreto](https://user-images.githubusercontent.com/52173618/69166804-9a846800-0ad2-11ea-889e-4c85b3b7eb8d.png)

3° The following message does not agree with the test performed. If the user does not exist, should be informed, suggestion: "Informed user not found."
![GUI](https://user-images.githubusercontent.com/52173618/69167182-4332c780-0ad3-11ea-9d67-92ffca67bf61.png)

**Comment by bizetti** [comment]
Ticket analysis meeting (March, 27th): It has to be analysed with security team.

**Comment by cfrancisco** [comment]
It will no longer be prioritized.
