### ISSUE TITLE
Tests: Test backlog for baseline v0.4.1_rc2

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1325]
dojot/gui
---------

dojot/gui#562, fixing dojot/dojot#1146: [issue#1146] Warning Message Always Visible in Top
dojot/gui#561, fixing dojot/dojot#1028 dojot/dojot#1028: 1028rc

dojot/auth
----------

dojot/auth#91, fixing dojot/dojot#1260: Adds exception handler in the kafkaPublisher init

----
Baseline specification available at dojot/baseline-builder@21cf602a6989ef6e6aef1d73120aa9b595059354
----

----
Docker compose file available at dojot-nightly/docker-compose@e7b9005aa2da576408594955bc7f86e1c006090f

**Comment by betefaber** [comment]
Issues tested:

- #1146
- #1028
- #1260

environments:

- [x] docker-compose
- [x] k8s

**Comment by betefaber** [comment]
Problem found: #1337

**Comment by mprevide** [comment]
To test: 
- [ ] #1318 
- [ ] #1337

**Comment by mprevide** [comment]
https://github.com/dojot/ansible-dojot/releases/tag/v0.4.1_rc2

**Comment by mprevide** [comment]
https://github.com/dojot/docker-compose/releases/tag/v0.4.1_RC2
