### ISSUE TITLE
Repository: Putting the "100K devices" code into github using the new defined structure and their realted tools (Ex.: Trevis)

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1330]

**Comment by mprevide** [comment]
-  [ ] v2k	
-  [ ] k2v	
-  [ ] VerneMQ	
-  [ ] Plugin VerneMQ ACL	
-  [ ] Plugin VerneMQ Disconnect	
-  [ ] Locust	
-  [ ] Prometheus	
-  [ ] Ansible	
-  [ ]  Documentação (readmes)
