### ISSUE TITLE
When the flow changes, confirmation is not requested and changes will be lost when leaving the flow page

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1332]
When the flow changes, the alert message (Don't forget to save your updates) is displayed.

But confirmation is not requested and changes will be lost when leaving flow page in the following situations:

- If the flow is created and changed

**Steps**:
1. Create new flow
2. Add new nodes. The alert message is displayed.
3. Save the flow
4. Edit flow,adding new nodes or connecting the nodes The alert message is displayed.
5. Click "Back to Flow List" or choose another menu item or reload the page or close the window: The changes will be lost.

- or if only the flow name changes

**Comment by bizetti** [comment]
Ticket analisys meeting (March, 20th): Fixed (see #1146)
