### ISSUE TITLE
[GUI] Pages with different languages

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1339]
- Menu and flow node list have different languages

![Screenshot at 2019-12-02 17-07-52](https://user-images.githubusercontent.com/37310063/69993050-c4557a00-1529-11ea-9f5b-debd5e93bbd4.png)

- Browser setting

![browser](https://user-images.githubusercontent.com/37310063/69993040-be5f9900-1529-11ea-8186-a715c7e6947f.png)

- Local setting

![local](https://user-images.githubusercontent.com/37310063/69993030-b9024e80-1529-11ea-84db-78d81ce7c7a5.png)

Affected version: **v0.4.1_rc2**

**Comment by bizetti** [comment]
Ticket analisys meeting (March, 20th): It has to fixed, but priority low.

**Comment by cfrancisco** [comment]
Once we remove the Flow schema for GUI v1 (in Dojot 0.9), this issue should be resolved. Due to this, I will close since the issue will not be fixed until this milestone.
