### ISSUE TITLE
[history] history returns 404 instead an empty list with status 200

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1340]
History returns http 404 when get the history of a device without data. It should be an empty list with status 200.

Example:
- register a device
- get the history endpoint /history/device/{{device_id}}/history
- Although the device exists, verify that you got a 404 response status with body "{"title": "device not found"; "description": "No data for given device could be found"}"

**Comment by ctossato** [comment]
affects version 0.4.1_rc2

**Comment by bizetti** [comment]
Ticket analisys meeting (March, 20th): It has to return an empty list.
