### ISSUE TITLE
Flow broker: How faster did new FTP become?

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1341]
This ticket is to register the measures before and after the new FTP schema.

**Comment by betefaber** [comment]
In FTP flow, the flowbroker can handle a message every 3s.

**_Test performed:_**

- 900 publications (1800 files), 1 publication every 3s
- 900 publications (1800 files) without interval
- transfer to 2 FTP servers

**_Test result:_**

**8K image** 

- publish every 3s: transfer in 3s

- publish without interval: it takes 10 minutes to transfer all files

FTP transfer start: 11:05 am (1st file timestamp: 1575986751912)
FTP transfer end:  11:15 am (last file timestamp: 1575986782151)


**100k image** 

- publish every 3s: transfer in 3s

- publish without interval: it takes 13 minutes to transfer all files

FTP transfer start: 11:28 am (1st file timestamp: 1575988085034)
FTP transfer end:  11:41 am (last file timestamp: 1575988140869)

- repeating the test

FTP transfer start: 14:07 am (1st file timestamp: 1575997636614)
FTP transfer end:  17:21 am (last file timestamp: 1575997680956)

**Comment by mprevide** [comment]
Unfortunately flowbroker isn't able to scale, my suggestion for improving time is to create a new custom node for this case, with less opening and closing ftp connections.

**Comment by bizetti** [comment]
Associado ao ticket #1401

**Comment by betefaber** [comment]
Tested in **v0.5.0-alpha.1**.

----
**ftp node**:
----

![image](https://user-images.githubusercontent.com/37310063/86496517-2ee6c680-bd54-11ea-8671-72a653afbe00.png)

**_Test performed_**:

- 900 publications (1800 files), 1 publication every 3s
- 900 publications (1800 files) without interval
- transfer to 2 FTP servers

**image size: 8k**

- publish without interval: 2 minutes to transfer the last file received

FTP transfer start: 1593780935919 (09:55:35.919 GMT-03:00)
FTP transfer end:  1593781051618 (09:57:31.618 GMT-03:00)    

FTP server 1: 
```
-rw-------    1 ftp      ftp          8949 Jul 03 12:55 6-1593780935919-01.jpg
-rw-------    1 ftp      ftp           134 Jul 03 12:55 6-1593780935919.txt

-rw-------    1 ftp      ftp          8949 Jul 03 12:59 6-1593781051618-01.jpg
-rw-------    1 ftp      ftp           134 Jul 03 12:59 6-1593781051618.txt
```

FTP server 2: 
```
-rw-------    1 ftp      ftp          8949 Jul 03 12:55 6-1593780935919-01.jpg
-rw-------    1 ftp      ftp           134 Jul 03 12:55 6-1593780935919.txt

-rw-------    1 ftp      ftp          8949 Jul 03 12:59 6-1593781051618-01.jpg
-rw-------    1 ftp      ftp           134 Jul 03 12:59 6-1593781051618.txt
```

**image size: 100k**

- publish every 3s: the transfer is immediate

FTP transfer start: 1593796737837 (14:18:57.837 GMT-03:00)
FTP transfer end:  1593799654304 (15:07:34.304 GMT-03:00)

FTP server 1: 
```
-rw-------    1 ftp      ftp        113916 Jul 03 17:18 6-1593796737837-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 17:18 6-1593796737837.txt

-rw-------    1 ftp      ftp        113916 Jul 03 18:07 6-1593799654304-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 18:07 6-1593799654304.txt
```

FTP server 2: 
```
-rw-------    1 ftp      ftp        113916 Jul 03 17:18 6-1593796737837-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 17:18 6-1593796737837.txt

-rw-------    1 ftp      ftp        113916 Jul 03 18:07 6-1593799654304-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 18:07 6-1593799654304.txt
```
- publish without interval: 6 minutes to transfer the last file received

FTP transfer start: 1593799882626 (15:11:22.626 GMT-03:00)
FTP transfer end:  1593800110391 (15:15:10.391 GMT-03:00)

FTP server 1: 
```
-rw-------    1 ftp      ftp        113916 Jul 03 18:11 6-1593799882626-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 18:11 6-1593799882626.txt

-rw-------    1 ftp      ftp        113916 Jul 03 18:21 6-1593800110391-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 18:21 6-1593800110391.txt
```

FTP server 2: 
```
-rw-------    1 ftp      ftp        113916 Jul 03 18:11 6-1593799882626-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 18:11 6-1593799882626.txt

-rw-------    1 ftp      ftp        113916 Jul 03 18:21 6-1593800110391-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 18:21 6-1593800110391.txt
```
----
**publish-ftp node**:
----

![image](https://user-images.githubusercontent.com/37310063/86496459-f47d2980-bd53-11ea-8f8c-faea8056ead5.png)

**_Test performed:_**

- 900 publications (1800 files) without interval
- MAX_CONCURRENT_CONNECTIONS: 10
- RETRIES: 13

**image size: 8k**

-publish without interval: **the transfer is immediate**

FTP transfer start: 1593802157261 (15:49:17.261 GMT-03:00)
FTP transfer end:  1593802274950 (15:51:14.950 GMT-03:00)

FTP server:
```
-rw-------    1 ftp      ftp          8949 Jul 03 18:48 6-1593802081310-01.jpg
-rw-------    1 ftp      ftp           134 Jul 03 18:48 6-1593802081310.txt

-rw-------    1 ftp      ftp          8949 Jul 03 18:51 6-1593802274950-01.jpg
-rw-------    1 ftp      ftp           134 Jul 03 18:51 6-1593802274950.txt
```

**image size: 100k**

- publish without interval: **the transfer is immediate**

FTP transfer start: 1593805807620 (16:50:07.620 GMT-03:00)
FTP transfer end:  1593805984898 (16:53:04.898 GMT-03:00)

FTP server:
```
-rw-------    1 ftp      ftp        113916 Jul 03 19:50 6-1593805807835-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 19:50 6-1593805807835.txt

-rw-------    1 ftp      ftp        113916 Jul 03 19:53 6-1593805984898-01.jpg
-rw-------    1 ftp      ftp           143 Jul 03 19:53 6-1593805984898.txt
```

**Comment by betefaber** [comment]
- 900 publications (1800 files)
- **MAX_CONCURRENT_CONNECTIONS: 1**
- **RETRIES: 3**

**image size: 8k**

- publish without interval: the transfer is immediate
```
FTP transfer start: 1594047450470 11:57:30.470 GMT-03:00
FTP transfer end:   1594047561654 11:59:21.654 GMT-03:00
```
FTP server:
```
-rw-------    1 ftp      ftp          8949 Jul 06 14:57 6-1594047450470-01.jpg
-rw-------    1 ftp      ftp           134 Jul 06 14:57 6-1594047450470.txt

-rw-------    1 ftp      ftp          8949 Jul 06 14:59 6-1594047561654-01.jpg
-rw-------    1 ftp      ftp           134 Jul 06 14:59 6-1594047561654.txt
```

**image size: 100k**

- publish without interval: 2 minutes to transfer the last file received
```
FTP transfer start: 1594060624334 (15:37:04.334 GMT-03:00)
FTP transfer end:   1594060913487 (15:41:53.487 GMT-03:00)
```
FTP server:
```
-rw-------    1 ftp      ftp        113916 Jul 06 18:37 6-1594060624334-01.jpg
-rw-------    1 ftp      ftp           143 Jul 06 18:37 6-1594060624334.txt

-rw-------    1 ftp      ftp        113916 Jul 06 18:43 6-1594060913487-01.jpg
-rw-------    1 ftp      ftp           143 Jul 06 18:43 6-1594060913487.txt
```
