### ISSUE TITLE
(Dojot v0.3.0) Sigfox custom callback

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/dojot#1343]
Hello.

I wanna do a callback using dojot platform. But it is not working.

Answer:
![image](https://user-images.githubusercontent.com/29581014/70940852-fc7cb280-2029-11ea-83ec-39a2f1090b05.png)

How it was filled:
![image](https://user-images.githubusercontent.com/29581014/70941171-a0fef480-202a-11ea-9bba-0123ba824e29.png)

Someone can help me?

**Comment by rascaraficci** [comment]
Could you give more details about what you're trying to do?
Are you running a SigFox IoT Agent (https://github.com/dojot/iotagent-sigfox)?

**Comment by danielnunesdeoliveira** [comment]
Yes, I could.

I am sending message to Sigfox platform(Embedded >> Sigfox Cloud ):  
![image](https://user-images.githubusercontent.com/29581014/70943140-eae9d980-202e-11ea-8858-057264f5923f.png)

I wanna forward above message to Dojot platform too:

![image](https://user-images.githubusercontent.com/29581014/70943424-a1e65500-202f-11ea-8246-6aac9a586107.png)

But I am not knowing filled this:
![image](https://user-images.githubusercontent.com/29581014/70943312-52a02480-202f-11ea-9894-45da74af02a1.png)

No, I am not running a Sigfox IoT Agent (I didn't enable it).

**Comment by danielnunesdeoliveira** [comment]
Hello.

I am following iotagent-sigfox documentation to docker image build: [https://giovanni-iotagent-sigfox.readthedocs.io/en/latest/deployment.html](url)

But it is not working to me, look at this:
![image](https://user-images.githubusercontent.com/29581014/71093627-55625d00-2188-11ea-92f6-47231a52debc.png)

What should I do?

**Comment by nunesjoab** [comment]
Hi Daniel.

Thank you for your question. We are looking into our branches and pull requests for this bug you reported and we will be back soon with a position.

**Comment by mprevide** [comment]
Hi Daniel,

Unfortunately, we don't support iotagent sigfox in dojot version => 3.0.0.
I suggest you look at https://github.com/dojot/iotagent-sigfox/pull/7, which you can use as a reference to develop your own sigfox, and  besides that you'll need to add a route in kong with an endpoint from your iotagent- sigfox.

Note: I fixed the build at https://github.com/dojot/iotagent-sigfox/pull/6, but I think work it isn't work with dojot> = v0.3.0

**Comment by rascaraficci** [comment]
Closed due to inactivity.

**Comment by dayvsonleandro** [comment]
Which versions of dojot are compatible with iotagent-sigfox? Where do I find official documentation to implement it?
