### ISSUE TITLE
After 5 minutes socket.io loses token

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1346]
After ~ 5 minutes (in Chrome browser) socket.io loses token.

Affected version: **v0.4.1_rc2**

**Comment by betefaber** [comment]
**Observations**:

- last data viewed

![ultimoDadoVisualizado](https://user-images.githubusercontent.com/37310063/71745376-b0fb3e80-2e48-11ea-9601-07fac41d0763.png)

- session renewal

![renovação-sessionID](https://user-images.githubusercontent.com/37310063/71745388-ba84a680-2e48-11ea-8334-fc3821613d7d.png)

- unknown token

![token-invalido](https://user-images.githubusercontent.com/37310063/71745400-c1131e00-2e48-11ea-99c2-ae5755c0c817.png)

**Comment by thiagodpf** [comment]
The problem was that the web socket connection was being terminated by timeout, so a new one-time token connection was not generated, so real-time data was no longer retrieved.

**Comment by betefaber** [comment]
When the token expired, the real-time data was not updated.
With token renewal, the update is resumed.

![1346](https://user-images.githubusercontent.com/37310063/73681715-b9d86d80-469d-11ea-9e7e-ddc3bb68e870.png)

Tested in version: **v0.4.2_rc.1**
