### ISSUE TITLE
Use Case CRUD User

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1347]

**Comment by thiagodpf** [comment]
The use case is documented in:
dojot > Requisitos > Casos de Uso > UC - Manter Usuário

Link:
https://docs.google.com/document/d/1iHsFNpkN_HnvRvSn5wwqfN4L-dvGbMtQjI5megeZSvQ/edit

**Comment by bizetti** [comment]
Postponde. The feature will be revewed.
