### ISSUE TITLE
Tests: Test backlog for pre-release v0.4.2-rc.1

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1357]
dojot/gui
---------

dojot/gui#567, fixing dojot/dojot#1346: fix: Fixed component that use web socket real time data

dojot/flowbroker
----------------

dojot/flowbroker#201, fixing dojot/dojot#1348: fix: bugfix remote node on kubernetes

dojot/ansible-dojot
----------------

dojot/ansible-dojot#10, fixing dojot/dojot#1337: fix: add auth/pap, ejbca /user and mqtt metrics

dojot/ejbca-rest
----------------

dojot/ejbca-rest#45, fixing dojot/dojot#685 dojot/dojot#776: fix: ejbca not restarting correctly and reason revoke

----
Baseline specification available at dojot/baseline-builder@84572f46d70482d5c887532c5f888d688d1c1ec7
----

----
Docker-compose available at dojot/docker-compose@c844d61b93d5f76b34a1ed6b5e7a90898b9bffaf
----

----
Ansible available at dojot/ansible-dojot@0c85deaab42551149e4ea2717f7c94d00cc4f5bd
----

**Comment by betefaber** [comment]
- [ ] 665
- [ ] 776
- [ ] 1337
- [ ] 1346
- [ ] 1348
