### ISSUE TITLE
Tests: Test backlog for release v0.4.2

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1381]
Documentation in english: https://dojotdocs.readthedocs.io/en/v0.4.2/
Documentation in portuguese: https://dojotdocs.readthedocs.io/pt_BR/v0.4.2/

**NOTE: In this version all external components have been change to use images in docker-hub of dojot.**

dojot/gui
---------
dojot/gui#567, fixing dojot/dojot#1346 dojot/dojot#1346: fix: Fixed component that use web socket real time data

dojot/ansible-dojot
----------------

dojot/ansible-dojot#10, fixing dojot/dojot#1337: fix: add auth/pap, ejbca /user and mqtt metrics

dojot/ejbca-rest
----------------

dojot/ejbca-rest#45, fixing dojot/dojot#685 dojot/dojot#776: fix: ejbca not restarting correctly and reason revoke

----
Baseline specification available at dojot/baseline-builder@fb4f84ab4b113ad512aa2787a93724cd77fea308
----

----
Docker-compose available at dojot/docker-compose@9256e530ecb2fb83983d526b421601110aafba6a
----

----
Ansible available at dojot/ansible-dojot@82b41a34eb997b3cb0ce1c05b3cf65afd2933bf6
----

**Comment by betefaber** [comment]
- [ ] 685
- [ ] 776
- [ ] 1337
- [ ] 1346
- [ ] 1348
