### ISSUE TITLE
Problema ao executar nó remoto na versão Caratê 0.4.2

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1397]
Encaminhada por usuário da comunidade:

Estou com problema na execução do exemplo a seguir:
https://dojotdocs.readthedocs.io/en/latest/faq/faq.html#how-can-i-add-a-new-node-type-to-its-menu  

Acabo obtendo o seguinte erro ao adicionar o nó Kelvin ou qualquer outro na versão Caratê 0.4.2:  The upstream server is timing out

root@ubuntu-s-2vcpu-4gb-ams3-01:~/docker-compose# curl -H "Authorization: Bearer ${JWT}" http://IP:8000/flows/v1/node -H "content-type: application/json" -d '{"image": "mmagr/kelvin:latest","id":"kelvin"}'

**Comment by betefaber** [comment]
A imagem utilizada não existe mais. A imagem correta é `"dojot/kelvin-example:3.0.0-alpha2"`.

**Comment by betefaber** [comment]
Usuário também reportou que não consegue adicionar um nó remoto na versão `caratê`, sendo que o mesmo nó foi adicionado na versão `aikido`.

![image](https://user-images.githubusercontent.com/37310063/76792323-91b25300-67a1-11ea-9400-5dcbcfb033ed.png)

**Comment by mprevide** [comment]
Houve mudanças na biblioteca do flowbroker entre a *aikido* e *caratê*, provavelmente você terá que adequar o código para utilizar na *caratê*.

Mas de qualquer forma iremos investigar o problema. 

Obrigada

**Comment by bizetti** [comment]
Oi Daniel,

Como foi comentado anteriormente, houve alterações na forma de o nó remoto interagir com a dojot por meio de uma nova versão de biblioteca do flowbroker.

O nó remoto que você criou precisa ser adaptado para essa versão.

Por favor, siga o exemplo do nó Kelvin atual que funciona e promova as alterações necessárias no seu código.

Para efeito de comparação do que mudou, você pode conferir os exemplos da versão 0.3.0 e da 0.4.2 nesses locais:

https://github.com/dojot/flowbroker/tree/v0.3.0/lib/sampleNode

https://github.com/dojot/flowbroker/tree/v0.4.2/lib/samples

Ats,

**Comment by danielnunesdeoliveira** [comment]
> Oi Daniel,
> 
> Como foi comentado anteriormente, houve alterações na forma de o nó remoto interagir com a dojot por meio de uma nova versão de biblioteca do flowbroker.
> 
> O nó remoto que você criou precisa ser adaptado para essa versão.
> 
> Por favor, siga o exemplo do nó Kelvin atual que funciona e promova as alterações necessárias no seu código.
> 
> Para efeito de comparação do que mudou, você pode conferir os exemplos da versão 0.3.0 e da 0.4.2 nesses locais:
> 
> https://github.com/dojot/flowbroker/tree/v0.3.0/lib/sampleNode
> 
> https://github.com/dojot/flowbroker/tree/v0.4.2/lib/samples
> 
> Ats,

Olá pessoal, estou seguindo as comparações para conseguir elaborar o meu próprio Nó.
Mas ainda estou com dificuldade na hora da construção da imagem. Vejam só:  

Imagem 1 - Erro na construção da imagem

![image](https://user-images.githubusercontent.com/29581014/179845842-ff59a8cd-08e4-47fb-a4d2-671e0336e78a.png)

Imagem 2 - Configuração do arquivo Dockerfile
![image](https://user-images.githubusercontent.com/29581014/179845473-d2e3b0b7-429d-4c20-8ae9-bfd647b402b7.png)

Estou seguindo o exemplo de ter uma pasta **"scr" com os conteúdos .html e index.json** e o arquivo package.json e o Dockerfile fora dessa pasta.

**Comment by danielnunesdeoliveira** [comment]
> Oi Daniel,
> 
> Como foi comentado anteriormente, houve alterações na forma de o nó remoto interagir com a dojot por meio de uma nova versão de biblioteca do flowbroker.
> 
> O nó remoto que você criou precisa ser adaptado para essa versão.
> 
> Por favor, siga o exemplo do nó Kelvin atual que funciona e promova as alterações necessárias no seu código.
> 
> Para efeito de comparação do que mudou, você pode conferir os exemplos da versão 0.3.0 e da 0.4.2 nesses locais:
> 
> https://github.com/dojot/flowbroker/tree/v0.3.0/lib/sampleNode
> 
> https://github.com/dojot/flowbroker/tree/v0.4.2/lib/samples
> 
> Ats,

Olá pessoal.

Estou com muita dificuldade em utilizar "FLUXOS" quando construo o NÓ TELEGRAM.

Figura 1 - NÓ TELEGRAM CONFIGURADO
![image](https://user-images.githubusercontent.com/29581014/182700722-5b4dc475-19a8-441d-98ec-60d96f272666.png)

Só quando vou construir a imagem NÓ TELEGRAM, obtenho os seguintes:

Figura 2.1 - Criando a imagem NÓ TELEGRAM
![image](https://user-images.githubusercontent.com/29581014/182701537-20128ef2-05af-4a61-bf59-9de8ee6ed18d.png)

Figura 2.2 - Cont. - Criando a imagem NÓ TELEGRAM
![image](https://user-images.githubusercontent.com/29581014/182702062-3b522f1f-adf8-4c22-a196-cf431e6e3f2c.png)

Imagino que o não funcionamento do NÓ TELEGRAM se deve a isso, mas ainda temos dúvidas. Alguém pode nos ajudar? O @rascaraficci já nos ajudou horrores e não queríamos mais tomar do seu tempo com esse assunto. Só que também estamos precisando muito de ajuda.

Seguimos as comparações citadas por @bizetti, criamos as novas pastas e afins. Mas na hora de usar o NÓ, não funciona e dá o erro citado aí.

Obrigado pessoal.
