### ISSUE TITLE
(Flowbroker/GUI Notification) I wanna using channel to see my notifications

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/dojot#1408]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
I wanna see my notifications on GUI interface

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
I should see all my notification in just one location.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.4.2
  - Environment: docker-compose
  - Operating system: Ubuntu 16.04 LTS 64

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by danielnunesdeoliveira** [comment]
Hello.

I tried to follow this:

1) 
![image](https://user-images.githubusercontent.com/29581014/76970122-2b950f80-690a-11ea-8607-5ef832a77049.png)

2) Device model node
![image](https://user-images.githubusercontent.com/29581014/76970177-3f407600-690a-11ea-82c8-bbe7f0b25743.png)

3) Interrupt node
![image](https://user-images.githubusercontent.com/29581014/76970200-4d8e9200-690a-11ea-9067-003e05ba9932.png)

4) Model node
![image](https://user-images.githubusercontent.com/29581014/76970262-5f703500-690a-11ea-9f44-b3ff67491443.png)

5) Notification node
![image](https://user-images.githubusercontent.com/29581014/76970299-6b5bf700-690a-11ea-9ae0-94e9e79d0411.png)

But It is not working to me.

**Comment by danielnunesdeoliveira** [comment]
I am not sure if there are some problem in my configuration, because It is not working yet.

In my flow I am using:
![image](https://user-images.githubusercontent.com/29581014/76995203-47121180-692e-11ea-8f2a-4201c11d6f5c.png)

Nodes:
My "evento dispositivo" was configured like:
![image](https://user-images.githubusercontent.com/29581014/76995342-80e31800-692e-11ea-8257-76ee63835284.png)

My "modelo" was configured like:
![image](https://user-images.githubusercontent.com/29581014/76995419-98ba9c00-692e-11ea-951c-9dc33781e638.png)

My "notificação" was configured like:
![image](https://user-images.githubusercontent.com/29581014/76995489-b1c34d00-692e-11ea-88bf-01e0534f9136.png)

I sent this message:
![image](https://user-images.githubusercontent.com/29581014/76995710-036bd780-692f-11ea-93f5-53c51d6f3180.png)

But I did not have a answer:
![image](https://user-images.githubusercontent.com/29581014/76995837-3dd57480-692f-11ea-8a46-6eb23e250cc9.png)

**Comment by betefaber** [comment]
Hi Daniel, try to configure this way:

![image](https://user-images.githubusercontent.com/37310063/77000510-48940780-6937-11ea-9769-43b50ff1e037.png)

**Comment by danielnunesdeoliveira** [comment]
Now, It is working very well.

My sincerely regards.
