### ISSUE TITLE
Errors while bringing up the project

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1412]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* **Do you want to request a *feature* or report a *bug*?**
Problemas na instalação/execução da dojot

  - Version: 0.3.1
  - Environment: docker-compose
  - Operating system: Não informado

Erros na imagem atachada
![SAC DOJOT](https://user-images.githubusercontent.com/31511415/77550453-e768b880-6e8f-11ea-9ff0-519937744a66.png)

**Comment by bizetti** [comment]
Olá Priscila,

Poderia informar o sistema operacional e versão que está utilizando?

Haveria algum problema de você utilizar a versão mais recente da dojot, a 0.4.2?

Ats.

**Comment by mprevide** [comment]
Olhe esta issue, é simular:  dojot/docker-compose#143

**Comment by priscilalobatoo** [comment]
Muito obrigada, funcionou @mprevide
