### ISSUE TITLE
Websocket security

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1414]
- [x] HTTPs between kong and ws, kong and external 
- [x] Add kafka
- [ ] JWT periodic expiration check. The aim of this plugin is to periodically check whether a Websocket connection must be closed because of JWT expiration, lifetime.
- [x] Add code to use https and env variables in new service ws

**Comment by mprevide** [comment]
https://docs.google.com/drawings/d/1Xi5YUh7JWW5lhrwCzTxAqUhAIxIpOM69n-5FSOhJxoc/edit
