### ISSUE TITLE
Parameter idsOnly in /device endpoint description is wrong

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1415]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Report a "bug".

* **What is the current behavior?**
The [idsOnly parameter documentation](https://dojot.github.io/device-manager/apiary_latest.html#devices-device-info-get-1) states that:
```
Return only the ids of all existing devices. Ignores any page_size and page_num configurations
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1) Create more than 20 devices in Dojot
2) Request a JWT token
3) Execute`curl -H {"Authorization": "Bearer <jwt>"} <dojot_url>:<dojot_port>/device?idsOnly=true`
4) It'll only return 20 devices.

* **What is the expected behavior?**
The [Device Manager code](https://github.com/dojot/device-manager/blob/316602c16f9cef098382c3f211ef0a87da23c3ae/DeviceManager/DeviceHandler.py#L337) returns only the devices' IDs from the requested page, so the documentation should be fixed, since this parameter is not ignoring neither `page_num` nor `page_size`.

* **What is the motivation / use case for changing the behavior?**
Clearer documentation.

* **Please tell us about your environment:**
  
  - Version: development
  - Environment: kubernetes
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by FrancielePessi** [comment]
![Captura de tela de 2020-06-18 13-55-12.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/4a8dc9fa-b9b4-43e0-a449-9e2af212dc9f)
