### ISSUE TITLE
Websocket Connections

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1422]
The goal is to create a new microservice for Websocket that can support 10k connections.

**Comment by mprevide** [comment]
- [x] HTTPs between kong and ws, kong and external 
- [ ] JWT periodic expiration check. The aim of this plugin is to periodically check whether a Websocket connection must be closed because of JWT expiration, lifetime.

**Comment by mprevide** [comment]
In version v0.5.0-alpha.2 probably will be available in `localhost:30002//kafka-ws`
