### ISSUE TITLE
[GUI] Error when generating certificates

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1441]
- Error when generating certificates by GUI

![Screenshot_19](https://user-images.githubusercontent.com/37310063/79385711-6b6a0980-7f3f-11ea-8737-cf68f0899900.png)

- Load CA certificate : **OK**

![Screenshot_18](https://user-images.githubusercontent.com/37310063/79385729-72911780-7f3f-11ea-9672-cf7cb182c4ed.png)

Affected version: `epic-100kMqttDevices`

**Comment by mprevide** [comment]
The new EJBCA does not automatically register devices, I will change that. 

But there is something else: we use a lib crypto.subtle in the browser,  but is to be undefined in insecure contexts.

Segure contexts are:
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)

Maybe we can change etc/hosts to map an ip to the local host.

**Comment by betefaber** [comment]
The ticket will be tested later on the Ubuntu OS.

**Comment by mprevide** [comment]
Test this v0.5.0-alpha.3 or later.
