### ISSUE TITLE
Erro na instalação do Dojot

### ISSUE THREAD

**Issue by Joinersa** [dojot/dojot#1445]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [X] support request

**Relatar um Bug**
Estou tentando reinstalar o Dojot, mas sem sucesso devido aos erros:

ERROR: for kong-migration  Container "8591e34b8ac6" is unhealthy.

ERROR: for auth  Container "8591e34b8ac6" is unhealthy.

ERROR: for postgres-users  Container "8591e34b8ac6" is unhealthy.

ERROR: for apigw  Container "8591e34b8ac6" is unhealthy.
ERROR: Encountered errors while bringing up the project.

* **Estou usando as configurações:**
  
  - Dojot Version: 0.3.1
  - Operating system: [Ubuntu 18.04]

**Comment by mprevide** [comment]
Acredito que seja um problema de versão do postgres. 

Tente seguir as instruções que dei nessa issue:
https://github.com/dojot/docker-compose/issues/143

E se vocẽ puder, recomendo utilizar a versão v0.4.2 (https://github.com/dojot/docker-compose/releases/tag/v0.4.2)

**Comment by Joinersa** [comment]
Era esse mesmo o problema.
Resolvido!
Obrigado!

**Comment by bizetti** [comment]
Solved.
