### ISSUE TITLE
Problema ao enviar dados ao Dojot

### ISSUE THREAD

**Issue by Joinersa** [dojot/dojot#1446]
**Solicitação de suporte**

* **Configurações:**
  - Dojot v0.4.2
  - SO: [Ubuntu 18.04]

Estou tendo problemas ao tentar inserir dados em um *device* no Dojot.

Na v0.3.1 do Dojot, eu conseguia inserir dados utilizando o script descrito na imagem abaixo. Após atualizar o Dojot para versão atual, v0.4.2, não obtive o mesmo resultado.

![Captura de tela de 2020-04-23 17-11-16](https://user-images.githubusercontent.com/28037901/80146484-4bae9300-8588-11ea-881a-ad5c56d471f5.png)

Preciso adicionar ou atualizar libs para conseguir inserir dados?

Agradeço a atenção.

**Comment by mprevide** [comment]
A versão desta dojot vem com o modo não seguro do MQTT desativado por padrão, você pode conectar-se apenas ao broker usando um certificado. Se você deseja ativar o modo não seguro, altere a variável de ambiente ALLOW_UNSECURED_MODE localizada no docker-compose.yml para 'true'.

Além disso, eu acho que a linha 9 não deveria estar aí, mas de qualquer forma o tópico de subscribe é tem *config* no final e não  *attrs*.

**Comment by Joinersa** [comment]
Entendi, muito obrigado.

Como seria pra eu usar mesmo no modo seguro, utilizando o certificado. Tem algum tutorial na documentação?

**Comment by mprevide** [comment]
Nesta versão ainda não temos um tutorial e uma interface simples para geração de certificados, mas ela terá na nossa próxima versão v0.5.x.

Temos esse código em python que ajuda na geração dos certificados 
https://github.com/dojot/certificate-retriever/releases/tag/v0.4.2

Vocẽ chegou a testar com o ALLOW_UNSECURED_MODE: 'true'? Após essa alteração é necessário rodar: `docker-compose kill iotagent-mqtt` e `docker-compose up -d iotagent-mqtt`  para matar e inicializar o broker  mqtt ou simplesmente   `docker-compose down` e  `docker-compose up -d`  para matar tudo e inicializar tudo novamente.

**Comment by Joinersa** [comment]
Testei, funcionou.

Vou verificar o código em python.

Muito obrigado!
