### ISSUE TITLE
Geração de certificados

### ISSUE THREAD

**Issue by gnleo** [dojot/dojot#1453]
Solicitação de suporte

    Configurações:
        Dojot v0.4.2
        SO: [Ubuntu 18.04]

Conforme indicado na issue #1446 
Para executar os arquivos .py, devo acessar o terminal de um container específico?

Qual procedimento a ser tomado?

**Comment by mprevide** [comment]
### Passos:

```
git clone https://github.com/dojot/certificate-retriever.git
cd certificate-retriever/
git checkout v0.4.2 https://github.com/dojot/certificate-retriever/releases/tag/v0.4.2
sudo apt install python3-pip #se necessárío
pip3 install crypt
pip3 install pyOpenSSL
mkdir certs
python3 generateLoginPwd.py http://localhost:8000 5c6512 IOTmidCA
```
Os certificados estarão em `certs`

#### Exemplo de como publicar com `mosquitto_pub` com os certificados:

```
sudo apt-get install mosquitto-clients  #se necessárío
cd certs 
mosquitto_pub -h localhost -p 32665 -t /admin/5c6512/attrs  -m '{"test_payload":1000}' --cert 5c6512.crt --key 5c6512.key --cafile IOTmidCA.crt
```

#### Notas:

- O valor `5c6512` é o ID do device, deve ser substituido pelo ID do device já criado na dojot que será gerado certificados. 
- A URL `http://localhost:8000` é o endereço da dojot, deve ser substituido se necessário.
- O host `localhost`, é parte dessa URL citada acima
- A porta `8883` é a porta segura do MQTT por default, mas poderia ser outra dependendo do deployment, no `docker-compose` oficial da dojot é `8883`.

**Comment by gnleo** [comment]
obrigado pelas instruções.
