### ISSUE TITLE
[Latency pub test prometheus]  Best practices on metric naming and exporters

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1455]
https://prometheus.io/docs/instrumenting/writing_exporters/
https://prometheus.io/docs/practices/naming/#metric-names

**Comment by mprevide** [comment]
Or remove that service, and create prometheus endpoints in each service, which seems more like a best practice.

**Comment by bizetti** [comment]
Ticket analysis meeting (June, 5th): It has to be verified the best solution in the roadmap vision.
