### ISSUE TITLE
[GUI] Incorrect date in real-time attribute detail

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1464]
Incorrect date when updating the chart in real time.

**Steps to reproduce the problem**:

1. Publish data

2. View the attribute detail

![Screenshot_36](https://user-images.githubusercontent.com/37310063/81733938-23b89e00-9469-11ea-946a-d777c396c295.png)

3. Publish data

![Screenshot_37](https://user-images.githubusercontent.com/37310063/81733974-316e2380-9469-11ea-89aa-e84835fbf60c.png)

4. Refresh the page (F5)

![refresh](https://user-images.githubusercontent.com/37310063/81733987-3cc14f00-9469-11ea-8ad3-4625819c432d.png)

5. Historic
```
curl -X GET http://10.50.11.237:30001/history/device/3ae73e/history -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json'

{
  "atua": [
     {"attr": "atua", "value": "14", "device_id": "3ae73e", "ts": "2020-05-12T18:26:27.879000Z", "metadata": {}},
     {"attr": "atua", "value": "12", "device_id": "3ae73e", "ts": "2020-05-12T18:12:08.686000Z", "metadata": {}},
     {"attr": "atua", "value": "15", "device_id": "3ae73e", "ts": "2020-05-12T18:11:41.773000Z", "metadata": {}},
     {"attr": "atua", "value": "10", "device_id": "3ae73e", "ts": "2020-05-12T18:10:47.394000Z", "metadata": {}}
   ],
  "int": [
     {"attr": "int", "value": 14, "device_id": "3ae73e", "ts": "2020-05-12T18:26:26Z", "metadata": {}},
     {"attr": "int", "value": 12, "device_id": "3ae73e", "ts": "2020-05-12T18:12:07Z", "metadata": {}},
     {"attr": "int", "value": 15, "device_id": "3ae73e", "ts": "2020-05-12T18:11:40Z", "metadata": {}},
     {"attr": "int", "value": 10, "device_id": "3ae73e", "ts": "2020-05-12T18:10:46Z", "metadata": {}}
   ]
}
```

Affected version: `epic-100kMqttDevices`

**NOTE**: using version v0.4.2 of the GUI in deployment, the problem also happens

![image](https://user-images.githubusercontent.com/37310063/81811635-54e1ae80-94fb-11ea-8ae7-35018936aba8.png)

After F5:

![image](https://user-images.githubusercontent.com/37310063/81811717-7478d700-94fb-11ea-9ef5-14eb17012f60.png)

**Comment by betefaber** [comment]
does not happen in version v0.4.2:

![image](https://user-images.githubusercontent.com/37310063/81742215-1f46b200-9476-11ea-802b-4c5264bc395d.png)

**Comment by betefaber** [comment]
**NOTE**: the timestamp is correct:

![image](https://user-images.githubusercontent.com/37310063/82228140-1e42d400-98ff-11ea-8899-7fee26e5e132.png)

**Comment by mprevide** [comment]
This problem seems to happen only when vernemq is used, no fly does not happen.
