### ISSUE TITLE
Tests: Test backlog for release v0.5.0-alpha.1

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1471]
### News features:

- vernemq-broker (See more https://github.com/dojot/dojot/blob/release/v0.5.0-alpha/connector/mqtt/vernemq/README.md)
- k2v-bridge
- v2k-brigde
- kafka2ftp (See more https://github.com/dojot/dojot/blob/release/v0.5.0-alpha/connector/kafka2ftp/README.md)
- ejbca-node (temporary, Should not be tested)
- latency-pub-test-prometheus
- metrics (prometheus and grafana)

See here about exposed ports: https://github.com/dojot/ansible-dojot/tree/release/v0.5.0-alpha#exposed-ports
### Backlog:

API Documentations (temporary, just for consultation):

https://dojot.github.io/auth/apiary_development.html
https://dojot.github.io/history/apiary_development.html
https://dojot.github.io/device-manager/apiary_development.html
https://dojot.github.io/image-manager/apiary_development.html
https://dojot.github.io/flowbroker/apiary_development.html
https://dojot.github.io/data-broker/apiary_development.html
https://dojot.github.io/data-manager/apiary_development.html
https://dojot.github.io/cron/apiary_development.html
https://dojot.github.io/dojot/pki/ejbca/apiary_ejbca_service_temporary.html

dojot/dojot (News features)
-------------
#1362, feat: [mqtt/vernemq/broker] custom vernemq with plugins, fixing  #1330, #1314, #1308, #1269, #1267
#1374, feat: [mqtt/vernemq/v2k-bridge] add v2k-bridge service, fixing #1330
#1407, feat: [tools/kafka/loopback] added loopback service  
#1413, doc: [mqtt/vernemq/broker] Add info about plugin order in VerneMQ config 
#1364, doc: [mqtt/vernemq] Readme,  fixing #1330, #1305, #1304
#1416, [mqtt/locust] generate_certs script corrections 
#1363, feat: [mqtt/latency-pub-test-prometheus] A prometheus client to measure the latency,  fixing  #1330, #1342, #1307
#1454, [mqtt/locust] Variable not defined 
#1420, feat: [connector/kafka2ftp] New service kafka2ftp,  fixing  #1401

dojot/history
-------------

dojot/history#66, fixing dojot/dojot#1246 dojot/dojot#1254: Release V0.4.1 
dojot/history#63, fixing dojot/dojot#1252: fix: travis publish doc
dojot/history#61: Unit tests
dojot/history#57: Log interface for History and Persister
dojot/history#60: Corrects persister when cron node configuration is wrong
dojot/history#55, fixing dojot/dojot#1210: Documentation
dojot/history#53, fixing dojot/dojot#1190: chore: improve time travis
dojot/history#51, fixing dojot/dojot#588: fix: Documentation update

dojot/iotagent-mosca
--------------------

dojot/iotagent-mosca#95, fixing dojot/dojot#1449: custom kafka params
dojot/iotagent-mosca#90, fixing dojot/dojot#1201: feat: check crl at start of connection
dojot/iotagent-mosca#87, fixing dojot/dojot#1235: fix: timeout by idle and lifetime
dojot/iotagent-mosca#84, fixing dojot/dojot#1235: feat: timeout by idle and lifetime 
dojot/iotagent-mosca#12, fixing dojot/dojot#483: Update Kafka message documentation
dojot/iotagent-mosca#79, fixing dojot/dojot#1193: fix: add tentant in cname
dojot/iotagent-mosca#78: fix: tls check condition and CRL generation
dojot/iotagent-mosca#75: Unit tests
dojot/iotagent-mosca#10: Fixing doc generation
dojot/iotagent-mosca#73: feat: limitted payload size
dojot/iotagent-mosca#6: Allows users to filter valid messages by topic used
dojot/iotagent-mosca#5: Upgrades iotagent-nodejs version
dojot/iotagent-mosca#69: Adding unit tests
dojot/iotagent-mosca#67, fixing dojot/dojot#1167 dojot/dojot#1167: feat: documentation
dojot/iotagent-mosca#66: fix: even the device does not exist the process continues
dojot/iotagent-mosca#72: Apply fixes from CodeFactor
dojot/iotagent-mosca#70, fixing dojot/dojot#1170: fix: case sensitive for unsecured mode env variable
dojot/iotagent-mosca#65, fixing dojot/dojot#1166: fix: Hardcoded Hostnames for TLS
dojot/iotagent-mosca#3, fixing dojot/dojot#310: Improves handling of non-conformant values for device information fields
dojot/iotagent-mosca#64: IoT agent refactor
dojot/iotagent-mosca#64: IoT agent refactor
dojot/iotagent-mosca#59, fixing dojot/dojot#1173: feat:Log refactoring
dojot/iotagent-mosca#2, fixing dojot/dojot#267: Updates iotagent-nodejs dependency version
dojot/iotagent-mosca#63: feat: add tini
dojot/iotagent-mosca#62, fixing dojot/dojot#1186: Reject promise handler
dojot/iotagent-mosca#1, fixing dojot/dojot#273 dojot/dojot#267 dojot/dojot#272 dojot/dojot#208: Adds missing travis defs
dojot/iotagent-mosca#60, fixing dojot/dojot#1177: Log conf env var
dojot/iotagent-mosca#56: fix promise: even the device does not exist the process continues

dojot/cron
----------

dojot/cron#13: fix: Documentation 

dojot/gui
---------

dojot/gui#597, fixing dojot/dojot#1443: feat: Tabular data report 
dojot/gui#594, fixing dojot/dojot#1102: Fix: Add version information about dojot 
dojot/gui#584, fixing dojot/dojot#1421 dojot/dojot#1299: fix: notification list crashes if the notification node configuration is incorrect
dojot/gui#577, fixing dojot/dojot#1265: fix: typo
dojot/gui#590, fixing dojot/dojot#1441: fix: Error when generating certificates
dojot/gui#583, fixing dojot/dojot#1102: feat: version set (development)
dojot/gui#571, fixing dojot/dojot#1346 dojot/dojot#1346: fix: Fixed component that use web socket real time data
dojot/gui#562, fixing dojot/dojot#1146: [issue#1146] Warning Message Always Visible in Top
dojot/gui#556, fixing dojot/dojot#1179: Template selection menu fix
dojot/gui#561, fixing dojot/dojot#1028 dojot/dojot#1028: 1028rc
dojot/gui#519, fixing dojot/dojot#1153: fix: problems in viewing geo attributes
dojot/gui#551, fixing dojot/dojot#1251 dojot/dojot#1259 dojot/dojot#1259 dojot/dojot#873 dojot/dojot#1251 dojot/dojot#1259: Fix to display messages sent by API Gateway AND Fix to properly remove firmware version
dojot/gui#543: fix img src

dojot/data-broker
-----------------

dojot/data-broker#83, fixing dojot/dojot#1386: Remove kafka topic mapping
dojot/data-broker#82, fixing dojot/dojot#989: Add partition and replication factor env variables
dojot/data-broker#79, fixing dojot/dojot#1237: Feature/removing subscription service
dojot/data-broker#78, fixing dojot/dojot#1238: Feature/correct vulnerabilities
dojot/data-broker#70, fixing dojot/dojot#1205: Feature/documentation
dojot/data-broker#77, fixing dojot/dojot#1206: Feature/add missing tests
dojot/data-broker#74, fixing dojot/dojot#1239: Feature/upgrade node version
dojot/data-broker#75, fixing dojot/dojot#1214: Change log message
dojot/data-broker#68, fixing dojot/dojot#1202 dojot/dojot#1208: Add log messages
dojot/data-broker#67, fixing dojot/dojot#1206 dojot/dojot#1215 dojot/dojot#1218 dojot/dojot#1220 dojot/dojot#1223: Feature/unit tests
dojot/data-broker#69, fixing dojot/dojot#1233: Change Redis images version to a fix one
dojot/data-broker#64, fixing dojot/dojot#1202: Review log messages
dojot/data-broker#65, fixing dojot/dojot#1203: Add SERVICE_PORT variable usage
dojot/data-broker#62, fixing dojot/dojot#1198: Add event to treat unhandledRejection
dojot/data-broker#63, fixing dojot/dojot#1199: Change log level by using environment variable
dojot/data-broker#60, fixing dojot/dojot#1190: chore: improve travis time 

dojot/image-manager
-------------------

dojot/image-manager#33, fixing dojot/dojot#1190: chore: improve time travis
dojot/image-manager#30, fixing dojot/dojot#1188: fix: Documentation update

dojot/device-manager
--------------------

dojot/device-manager#149, fixing dojot/dojot#1415 dojot/dojot#1312: Update docs
dojot/device-manager#142: Unity tests of logger and devices
dojot/device-manager#141: Remove dependencies not used in device-manager
dojot/device-manager#137: Create endpoint and environment variable to configure the log level
dojot/device-manager#136: Automate documentation build in dockerhub
dojot/device-manager#134: DeviceManager documentation update
dojot/device-manager#132, fixing dojot/dojot#1190: chore: improve time travis

dojot/auth
----------

dojot/auth#91, fixing dojot/dojot#1260: Adds exception handler in the kafkaPublisher init
dojot/auth#85, fixing dojot/dojot#1190: chore: improve travis time 
dojot/auth#82: iotagent-mqtt - Add service metrics
dojot/auth#81, fixing dojot/dojot#1087: fix: permission for import should be just POST

dojot/kong
----------

dojot/kong#14, fixing dojot/dojot#1337 dojot/dojot#1338: adding pep kong

dojot/flowbroker
----------------

dojot/flowbroker#224, fixing dojot/dojot#1447: [ContextMngr] Improves log
dojot/flowbroker#220, fixing dojot/dojot#1447: Adds the possibility to configure kafka parameters
dojot/flowbroker#219, fixing dojot/dojot#1447: Replaces the workers' configuration to env variable
dojot/flowbroker#218, fixing dojot/dojot#1447: [ContextMngr] Fixes how the process kill itself
dojot/flowbroker#217, fixing dojot/dojot#1447: [ContextMngr] Fixes reject call without object associated
dojot/flowbroker#216, fixing dojot/dojot#1447: [ContextManager] Improves error checking
dojot/flowbroker#208, fixing dojot/dojot#1401: feat: new node to Publish in FTP topic 
dojot/flowbroker#205: chore: Adds some improvements to lib
dojot/flowbroker#211, fixing dojot/dojot#1324: fix: FTP node, remove get
dojot/flowbroker#214, fixing dojot/dojot#1421 dojot/dojot#1299: fix: notification list crashes if the notification node configuration is incorrect
dojot/flowbroker#191: Externs request timeout to cron-batch node
dojot/flowbroker#204, fixing dojot/dojot#1348: fix: bugfix remote node on kubernetes
dojot/flowbroker#190, fixing dojot/dojot#1261: bugfix remote node k8s
dojot/flowbroker#175: Fix version of third part library inside tests folder

dojot/data-manager
------------------

dojot/data-manager#22: Fix: documentation

dojot/iotagent-leshan
---------------------

dojot/iotagent-leshan#51: chore: add params to create device 
dojot/iotagent-leshan#39: Changes all content request to use TLV

dojot/backstage
---------------

dojot/backstage#18, fixing dojot/dojot#1087: fix: permission for import should be just POST
dojot/backstage#19: iotagent-mqtt - Add service metrics mqqt

dojot/certificate-retriever
---------------------------

dojot/certificate-retriever#7, fixing dojot/dojot#1456: doc: add how to use (development)
dojot/certificate-retriever#4, fixing dojot/dojot#1196 dojot/dojot#1193: fix: add tentant in cname

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.5.0-alpha.1
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.5.0-alpha.1
----

**Comment by betefaber** [comment]
Tested tickets:

[x] #1100 
[x] #1102 
[x] #1148 
[x] #1153 
[x] #1410
