### ISSUE TITLE
[readthedocs] Documentation [v0.4.3/v0.5.0] 

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1473]
- Alguns pontos são sugestões a serem discutidas.
- Podem faltar pontos a serem adicionados, atualizados ou complementados, adicione- os, altere-os ou delete-os.
- Revisar também inclui verificar tradução

###  Tutorials

- Using flow builder,  
   - Dojot nodes 
      - [x] Add nós cron, cron-batch, soma cumulativa e mesclar data **@mprevide**
   - Learn by examples 
      - [x] Adicionar um exemplo com  cumulative sum (contexto), switch and notification node **@mprevide**

###  Outros pontos:
- [x] Explicar como publicar/sub com e sem segurança com o mosca (usando o certificate-retriever https://github.com/dojot/certificate-retriever/tree/development#how-to-use), explicar também variável que habilita publicação no modo inseguro  e  deixar claro o endpoint de atuação **@mprevide**
- [x]  Comentar que videos de instalação k8s e compose usam a 0.4.2, mas a ideia é a mesma pra 0.4.3 **@mprevide**
- [x] dojot/dojot#1444 **@mprevide**

## v0.5.x	

- Architecture
    - [x]  Adicionar kafka-ws.. @jonaphael 
  - [x]  Adicionar kafka2ftp.. @mprevide 
  - [x]  Adicionar mais informação sobre x509-identity-mgmt (Acredito que pode-se ter um novo item na raiz, uma nova página dedicada somente a isso, como em 2. IoT Agent architecture, e aqui fazer apenas um resumo pequeno do x509-identity-mgmt) @thiagodpf 
   - [x]  Revisar @mprevide 
- IoT Agent architecture
  - [x] Revisar/Complementar informações **@luissajunior** @mprevide 
- Concepts
  - [x] Adicionar informações com relação a x509-identity-mgmt @thiagodpf 
  - [x] Revisar @mprevide
- Components and APIs
  - [x] Adicionar documentação das apis de novos serviços /Atualizar Exposed APIs (kafkaws) @jonaphael 
  - [x] Adicionar documentação da api (gui-v2)/Atualizar Exposed APIs  (Se for abrir o código)
  - [x] Adicionar documentação das apis de novos serviços / Atualizar Exposed APIs (x509-identity-mgmt) @thiagodpf 
  - [x] Revisar
- Internal communication
  - [x] Adicionar x509-identity-mgmt a imagem @thiagodpf 
  - [x] Adicionar informações com relação a x509-identity-mgmt @thiagodpf 
  - [x] Revisar @mprevide 
- Installation Guide
  - Compose
    - [x] **SUGESTÃO**:  Comentar que os volumes são habilitados por default (talvez falar q pode usar o down -v )
  - Kubernetes
    - [x] Atualizar (como subir, versao do k8s, HaProxy)
- Frequently Asked Questions
  - [x] Revisar @mprevide 
- Release history
  - [x] Criar release para defendu

### Tutorials

- Using web interface
  - Device management
    - [x] Alterar exemplo para utilizar o VerneMQ **@eduardogmisiuk**
  - [X] Novo item explicando o novo relatório (falar ql algoritmo é usado) @wellitonSouza   (AINDA FALTA SUBIR O VÌDEO)
  - [X] Novo item explicando geração de certificados @wellitonSouza (AINDA FALTA SUBIR O VÌDEO)
  - [x] Novo item explicando dashboard (Se for abrir o código)  (AINDA FALTA SUBIR O VÌDEO)
  - [x] Trocar imagens em atenção para screenshots da gui atual 
  - [x] Falar que só é possivel gerar cert pela gui se estiver no localhost ou com https
  - [x]  Revisar
  
- Using API interface
  - Sending messages
    - [x] Alterar exemplo para utilizar o VerneMQ **@eduardogmisiuk**
  - [x]  Revisar
- Using flow builder,  
  - [x] Add nó kafka-ftp @mprevide
  - [x]  Revisar @mprevide

Outros pontos:

- [x] Criar novo item dedicado ao vernemq + Arquitetura x509, explicando como funciona muito por cima, como publicar com e sem segurança, obter certificado, como desabilitar modo inseguro (linkar com geração de certificados em Using web interface  e dar o passo a passo simples para criar por cli ). Acredito que seria algo qse como https://github.com/dojot/dojot/blob/development/connector/mqtt/vernemq/README.md  @mprevide 
 - [x] Como executar o teste dos 100k (locust) **@eduardogmisiuk**

Obs.: Tudo que for feito deve ser traduzido. 
Obs. 2: Não esquecer de alterar informações de versão como em clones, links, etc.

**Comment by bizetti** [comment]
Released with the dojot versions.
