### ISSUE TITLE
[dojot-module-nodejs] Unhandled promise

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1479]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Report a bug.

* **What is the current behavior?**
The promise in [this line](https://github.com/dojot/dojot-module-nodejs/blob/b4a7c1d3e5a93026dd33aceb8a67e5374da8a1bb/lib/messenger.js#L478) is not being treated, so we don't know whether the message was sent or not. It can also generate an Unhandled Promise error.
This bug was found using iotagent-nodejs library.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: epic
  - iotagent-nodejs version: 2.1.0-beta.8
  - Environment: kubernetes
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
Ticket analysis meeting (June, 5th): It has to be fixed (0.4.3 or 0.4.4)

**Comment by bizetti** [comment]
See code line https://github.com/dojot/dojot-module-nodejs/blob/b4a7c1d3e5a93026dd33aceb8a67e5374da8a1bb/lib/messenger.js#L478
