### ISSUE TITLE
[/history/]Read all historical data, device

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/dojot#148]
Hello,

I have tried to read all historical data related to a device by using '/history/'. But It is not working.
Could you please help me with this example below? 
 
**For example**: curl -X GET http://xy.abc.op.vl:8000**/metric/v2/entities/** -H 'Authorization: Bearer ...' -H 'Fiware-Service:admin' -H 'Fiware-ServicePath:/'

How do I apply '/history/'?
Regards,

**Comment by giovannicuriel** [comment]
Hi!
First, sorry for the huge delay :)

A request for history data would be:

`curl -X GET -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsIn...' -H 'Fiware-Service:admin' -H 'Fiware-ServicePath:/' http://localhost:8000/history/STH/v1/contextEntities/type/device/id/3ba9/attributes/temperature?lastN=10`

This gets the last 10 values for `temperature` attribute from the device `3ba9`. You can check out more operators [here](https://github.com/telefonicaid/fiware-sth-comet/blob/master/doc/manuals/raw-data-retrieval.md).


We will update the documentation to include an example of such request.

**Comment by danielnunesdeoliveira** [comment]
Hello my friend!

It is working very well. I would like to thank you.

Regards.
