### ISSUE TITLE
Security: Handling Keycloak implementation impacts on microservices

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1482]
Currently some dojot libraries uses the Auth tenant`s endpoint to list tenants stored in database.
The target of this task is change these libraries dependency from Auth to Keycloak.

Libraries that demand update:
- dojot/dojot-module-nodejs
- dojot/dojot-module-java
- dojot/dojot-module-python

PR:
(nodejs) https://github.com/dojot/dojot-module-nodejs/pull/51
(java) https://github.com/dojot/dojot-module-java/pull/6
(python) https://github.com/dojot/dojot-module-python/pull/24

**Comment by canattofilipe** [comment]
Currently some dojot libraries uses the Auth tenant`s endpoint to list tenants stored in database.
The target of this task is change these libraries dependency from Auth to Keycloak.

Libraries that demand update:
- dojot/dojot-module-nodejs
- dojot-module-java
- dojot/dojot-module-python
