### ISSUE TITLE
The Things Networking to Dojot Caratê

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/dojot#1489]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**

feature

* **What is the current behavior?**
No apply.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
No apply.

* **What is the expected behavior?**
I should see my data Dojot's platform using LoRa protocol.

* **What is the motivation / use case for changing the behavior?**

No apply.

* **Please tell us about your environment:**
  
  - Version: 0.4.2
  - Environment: docker-compose
  - Operating system: Ubuntu 16.04 LTS 64bits

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

>> **I have this information about gateway:**
![image](https://user-images.githubusercontent.com/29581014/84310836-adc35780-ab38-11ea-9d47-5ba38a6dd94e.png)

>>**But I do not know how fill it and dojot platform too.**

**Comment by mprevide** [comment]
Sorry, I cant really understand what you are doing.
We don't have lora integrated it this version.

Could you explain it better?

Thx

**Comment by danielnunesdeoliveira** [comment]
I just would like to know: How I can use LoRa with Dojot's platform.

**Comment by mprevide** [comment]
You need to create an iotagent for this

**Comment by rascaraficci** [comment]
Closed due to inactivity.
