### ISSUE TITLE
Erro ao rodar simulador MQTT

### ISSUE THREAD

**Issue by mendmax** [dojot/dojot#155]
Olá, instalei o Dojot numa máquina Linux e o simulador MQTT numa máquina windows para fazer testes na plataforma Dojot. o Dojot esta funcionando corretamente mas o simulador MQTT, quando rodo, dá a mensagem abaixo:
+++++++++++++++++++++++++++++++++++++++++++++
$ ./emulator.sh
Device emulator starting...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND http http:8883
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
+++++++++++++++++++++++++++++++++++++++++++++

O Dojot esta instalado no endereço http://10.202.17.73:8000/#/

**Comment by giovannicuriel** [comment]
Olá!

Você tem qual versão do nodejs instalada na máquina?

**Comment by mendmax** [comment]
v8.9.1

**Comment by giovannicuriel** [comment]
Por acaso você consegue acessar o broker MQTT do Windows? A porta que ele fica ouvindo é a 1883.

**Comment by mendmax** [comment]
Eu não sei como fazer. Peguei um script em python na Internet, executei e não conectou. Apresentou a mensagem "error: [Errno 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente". Tentei na porta 1883 e 8883.

**Comment by giovannicuriel** [comment]
Bom, em conversa direta, foi descartada a possibilidade de ser um firewall bloqueando a conexão - o problema era o campo "serverAddress" da configuração do emulador. 

Podemos fechar esta issue?

**Comment by mendmax** [comment]
Ok, funciou com as suas orientações e agora vou seguir a documentação para fazer novas explorações.

http://dojotdocs.readthedocs.io/en/latest/faq/faq.html#how-can-i-send-mqtt-data-to-dojot-so-that-it-appears-on-the-dashboard

http://dojotdocs.readthedocs.io
