### ISSUE TITLE
GUI - Dashboard - Filtering devices and attributes

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1553]
Será implementado o filtro de dispositivos (passo 2) no wizard de criação de widgtes para o dashboard.

A primeira versão da busca será realizada de maneira local, ou seja, ao informar um termo de busca, o filtro será realizado nos dados já renderizados no browser após a api ter sido chamada.

O campo de busca é de texto livre e deve refletir em todo o texto exibido nos itens da lista.

![image.png](https://images.zenhubusercontent.com/5f072def46f861775f369a45/d1b81f4b-f757-4f77-bd41-0a6a2f04d98a)

![image.png](https://images.zenhubusercontent.com/5f072def46f861775f369a45/e1b4d7fa-130e-49d7-a2b4-79e95882157e)

Caso o termo de busca informado não retorne encontre dispositivos, uma mensagem será exibida informando

![image.png](https://images.zenhubusercontent.com/5f072def46f861775f369a45/4ccbe36e-6024-4316-8758-f7b8e82dfca7)

**Comment by ricardoaruiz** [comment]
PR: https://bitbucket.cpqd.com.br/projects/DOJOT/repos/gui/pull-requests/8/overview

**Comment by betefaber** [comment]
**All devices**

![image](https://user-images.githubusercontent.com/37310063/94615123-99d56a00-027d-11eb-9c8f-efe371c1030f.png)

**filtering devices**

- there is data for the filter

![image](https://user-images.githubusercontent.com/37310063/94611359-051c3d80-0278-11eb-9325-b03047446b3e.png)

- there is no data for the filter

![image](https://user-images.githubusercontent.com/37310063/94612732-ea4ac880-0279-11eb-8351-c7db0718f590.png)

**filtering attributes**

- All selected devices and their attributes

![image](https://user-images.githubusercontent.com/37310063/94614356-6cd48780-027c-11eb-8c9d-a7b35a01f79f.png)

- there is data for the filter

![image](https://user-images.githubusercontent.com/37310063/94614659-e66c7580-027c-11eb-80cd-81b4b1a2026d.png)

![image](https://user-images.githubusercontent.com/37310063/94614609-d5236900-027c-11eb-8dde-e48b8def899b.png)

- there is no data for the filter

![image](https://user-images.githubusercontent.com/37310063/94614742-0ac85200-027d-11eb-86c9-663404f71120.png)
