### ISSUE TITLE
GUI - Dashboard - Filtering devices and attributes (selected search and paging)

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1560]

**Comment by ricardoaruiz** [comment]
PR: https://bitbucket.cpqd.com.br/projects/DOJOT/repos/gui/pull-requests/11/overview

**Comment by betefaber** [comment]
- filtering of devices (search and paging): OK

![image](https://user-images.githubusercontent.com/37310063/94722941-63a3f300-032e-11eb-901b-5bc3fcb097f7.png)

![image](https://user-images.githubusercontent.com/37310063/94723110-9cdc6300-032e-11eb-8e74-689dcc443a93.png)


- filtering of attributes (search and paging): OK

![image](https://user-images.githubusercontent.com/37310063/94723229-cd240180-032e-11eb-8d47-361bb97f134a.png)

![image](https://user-images.githubusercontent.com/37310063/94723301-e927a300-032e-11eb-9892-e1c304996fda.png)
