### ISSUE TITLE
[mongodb] tuning logs

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1562]
analyze if there is anything better to be done regarding the logs due to performance, such as log to file.

![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/8e1497e7-8ba7-4756-9958-5ff27a473659)
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/09396bc1-667a-4cb0-92a3-90c4bbe7b663)

**Comment by bizetti** [comment]
Ticket analysis (9th, October 2020): It will be analysed in a general context.
