### ISSUE TITLE
Kubernets - Update deployment model

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#157]

**Comment by ericbaum** [comment]
First commit adding kafka: dojot/kubernetes#7

**Comment by ericbaum** [comment]
Some more changes at: dojot/device-manager#14

**Comment by ericbaum** [comment]
Some more changes at: dojot/device-manager#16

**Comment by ericbaum** [comment]
Iot-Agent changes: dojot/iotagent-json#20
