### ISSUE TITLE
[x509-identity-mgmt] - Issue certificates to HTTPS flow

### ISSUE THREAD

**Issue by canattofilipe** [dojot/dojot#1571]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**
None

* **What is the current behavior?**
The "x509-identity-mgmt component" issue certificates to devices that communicate with dojot through MQTT protocol.

* **What is the expected behavior?**
The "x509-identity-mgmt component" works nice with MQTT + TLS but I would like to use it with HTTP + TLS (HTTPS).
This component create certificates with CN's that follows the pattern `<tenant>:<device id>`, but to work with HTTPS I need CN's like `<mydomain.com.br>`, otherwise the errror `SSL: certificate subject name does not match target host name` raises.
There is a way to work around ?

* **What is the motivation / use case for changing the behavior?**
The dojot access control system needs to implement HTTPS, I was looking for to use "x509-identity-mgmt component"  to issue a self signed certificate.

**Comment by thiagodpf** [comment]
To request a certificate without component validations being applied, you must use the endpoint:
`<component-base-url>/internal/api/v1/throw-away`
However, this endpoint is not available outside the API Gateway, therefore, it is necessary that the request for certificate comes from an internal service of dojot.

Here is an example of an internal component of dojot that requests certificates through this endpoint. In this example, when the component starts, bash scripts are run to generate a CSR and request a certificate for the x509-identity-mgmt component.

To generate the CSR:
`https://github.com/dojot/dojot/blob/development/connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/createCSR.sh`

To request the certificate:
`https://github.com/dojot/dojot/blob/development/connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/signCert.sh`

**Comment by canattofilipe** [comment]
Thanks for reply.
