### ISSUE TITLE
[docker-compose] [v0.4.3] Create Volumes 

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1585]

**Comment by thiagodpf** [comment]
PR:
https://github.com/dojot/docker-compose/pull/163

**Comment by betefaber** [comment]
Tested in v0.4.3-rc.1.

volumes created in services:

- mongodb
- mosca-redis
- data-broker-redis
- device-manager-redis
- minio
- auth-redis
- postgres
- postgres-users
- flowbroker-redis
- flowbroker
- rabbitmq
- zookeeper
- kafka
- ejbca

**Comment by betefaber** [comment]
Tested in v0.5.0-rc.1.

volumes created in services:

-  postgres
-   mongodb
-   minio
-   rabbitmq
-   zookeeper
-   kafka
-   iotagent-mqtt
-   auth-redis
-   flowbroker
-   flowbroker-redis
-   data-broker-redis
-   device-manager-redis
-   kafka-ws-redis
-   mosca-redis
-   x509-identity-mgmt
