### ISSUE TITLE
[ejbca-rest] [v0.4.3] increase deployment-timeout

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1586]
> > Just another simple test.
> > Did you try to kill and up only the ejbca again after this error in ejbca?
> > `sudo docker-compose kill ejbca` and` sudo docker-compose up -d ejbca`
> 
> You are the boss!
> 
> ![dojot-working](https://user-images.githubusercontent.com/46680123/83418014-44856b00-a3f9-11ea-800c-5a361d05cc94.png)
> 
> Thank you very much!! I will try to replicate this with my students tomorrow. Hope it works. Probably it will.
> 
> Regarding the ejbca.ear.failed that Thiago asked for, indeed it is there when I can't pub with mosquitto_pub. I checked the file and it says `JBAS015052: Did not receive a response to the deployment operation within the allowed timeout period [60 seconds]. Check the server configuration file and the server logs to find more about the status of the deployment.`
> 
> When I kill ejbca, and then up -d it, the ".failed" file is not there anymore.

Thanks for the feedback, these problems only appear when the dojot is put to the real test, so we did not anticipate it. sorry.

From what I've investigated here regarding this error message from the Wildfly application server, it appears that this problem is usual in overloaded environments. you can try increasing the **deployment-timeout** in the _standalone.xml_ 
(inside the EJBCA container: /opt/primekey/appserver/standalone/configuration/standalone.xml) 

Probably the EJBCA image that is configured in version 0.4.2 of the dojot must be a different path, something like: /opt/jboss-as-7.1.1.Final/standalone/configuration/standalone.xml. The important thing in this case is to know that we are changing the settings of the application server used by the EJBCA container and not specifically on the dojot platform. Anyway, the next versions of dojot will use a newer EJBCA docker image.

Find This block (subsystem _deployment-scanner_)
```xml
<subsystem xmlns="urn:jboss:domain:deployment-scanner:2.0">
    <deployment-scanner path="deployments" relative-to="jboss.server.base.dir" scan-interval="0" deployment-timeout="600"
        runtime-failure-causes-rollback="${jboss.deployment.scanner.rollback.on.failure:false}" auto-deploy-exploded="true"/>
</subsystem>
```

Then add (or edit) the _attribute_ **deployment-timeout** (in seconds) to a value like 10 minutes (600sec), or some value that best suits your hardware configuration
```xml
<subsystem xmlns="urn:jboss:domain:deployment-scanner:2.0">
    <deployment-scanner path="deployments" relative-to="jboss.server.base.dir" scan-interval="0"
        runtime-failure-causes-rollback="${jboss.deployment.scanner.rollback.on.failure:false}" auto-deploy-exploded="true"
        deployment-timeout="600" />
</subsystem>
```

_Originally posted by @thiagodpf in https://github.com/dojot/dojot/issues/1474#issuecomment-637060188_

**Comment by thiagodpf** [comment]
PR:
https://github.com/dojot/ejbca-rest/pull/48

**Comment by betefaber** [comment]
The parameter **deployment-timeout** (in seconds) was added to the configuration.

Tested in v0.4.3-rc.1
