### ISSUE TITLE
Deployment - Allow choosing VerneMQ or Mosca

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1604]
This behavior has to be supported in the Docker-compose environment as well.

- [ ] Docker-compose
- [ ] K8s

**Comment by mprevide** [comment]
@LeonardoMariano see these environment variables:

```yaml
  # iotagent-mqtt-mosca:
  #   image: dojot/iotagent-mosca:v0.5.0-alpha.3
  #   depends_on:
  #     - mosca-redis
  #     - kafka
  #     - data-broker
  #     - auth
  #     - x509-identity-mgmt
  #   ports:
  #     - 1883:1883
  #     - 8883:8883
  #   restart: always
  #   environment:
  #     DOJOT_MANAGEMENT_USER: 'iotagent-mqtt-mosca'
  #     KAFKA_GROUP_ID: 'iotagent-mqtt-mosca-group'
  #     ALLOW_UNSECURED_MODE: 'true'
  #     LOG_LEVEL: 'info'
  #     MOSCA_TLS_DNS_LIST: 'localhost'
  #     MOSCA_TLS_CRL_UPDATE_TIME: '0 */2 * * *' # Updated CRL Every 2 hours
  #     MOSCA_TLS_CON_MAX_LIFETIME: 7200000 # Maximum lifetime of a connection in ms (If is 0 then is disabled)
  #     MOSCA_TLS_CON_IDLE_TIMEOUT: 1800000 # The idle timeout for a connection in ms (If is 0 then is disabled)
  #     MOSCA_TLS_CNAME: "iotagent-mqtt-mosca"
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 100m
```

**Comment by betefaber** [comment]
Tested in **v0.5.0-alpha.4**.

1. DEFAULT (vernemq)

`ansible-playbook -K -i inventories/example_local deploy.yaml`

- publish by verne: OK

2. LWM2M 

`ansible-playbook -K -i inventories/example_local deploy.yaml --tags "lwm2m"`

- dojot up: **iotagent-lwm2m is added**
- dojot down: **only the iotagent iotagent_lwm2m is created**

- does not publish data (Error: The connection was lost.)
- firmware update: OK

3. VERNE + LWM2M

`ansible-playbook -K -i inventories/example_local deploy.yaml --tags "vernemq,lwm2m"`

- publish by verne:  OK
- firmware update: OK

4. VERNE + MOSCA

` ansible-playbook -K -i inventories/example_local deploy.yaml --tags "mosca,vernemq"`

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Stopping playbook execution! The tags vernemq and mosca cannot be used together"}

5. MOSCA

`ansible-playbook -K -i inventories/example_local deploy.yaml --tags "mosca"`

- publish by mosca: OK

6. MOSCA + LWM2M

`ansible-playbook -K -i inventories/example_local deploy.yaml --tags "mosca,lwm2m"`

- publish by mosca: OK
- firmware update: OK
