### ISSUE TITLE
Backlog for v0.4.3-rc.1

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1611]
API documentation
--------------------------

https://dojot.github.io/auth/apiary_v0.4.3-rc.1.html
https://dojot.github.io/history/apiary_v0.4.3-rc.1.html
https://dojot.github.io/device-manager/apiary_v0.4.3-rc.1.html
https://dojot.github.io/image-manager/apiary_v0.4.3-rc.1.html
https://dojot.github.io/flowbroker/apiary_v0.4.3-rc.1.html
https://dojot.github.io/data-broker/apiary_v0.4.3-rc.1.html
https://dojot.github.io/ejbca-rest/apiary_v0.4.3-rc.1.html
https://dojot.github.io/data-manager/apiary_v0.4.3-rc.1.html
https://dojot.github.io/cron/apiary_v0.4.3-rc.1.html

dojot/history
-------------

dojot/history#72: fix: add index and event create 

dojot/iotagent-mosca
--------------------

dojot/iotagent-mosca#94, fixing dojot/dojot#1449: custom Kafka params

dojot/gui
---------

dojot/gui#628, fixing dojot/dojot#1508: fix: Error showing Tenant
dojot/gui#621, fixing dojot/dojot#1165: Validation for importing firmware 
dojot/gui#623, fixing dojot/dojot#1212: correcting the flow date  
dojot/gui#595, fixing dojot/dojot#1102: Fix: Add version information about dojot
dojot/gui#585, fixing dojot/dojot#1421 dojot/dojot#1299: fix: notification list crashes if the notification node configuration is incorrect 

dojot/flowbroker
----------------

dojot/flowbroker#269, fixing dojot/dojot#1377: Add parameter to del remote node work (
dojot/flowbroker#272, fixing dojot/dojot#1298: Remove mandatory field when GET method
dojot/flowbroker#259, fixing dojot/dojot#1565: feat: Changed  to process messages in parallel
dojot/flowbroker#235, fixing dojot/dojot#1365: Change the parameter to remove node correctly
dojot/flowbroker#240: Fixes label in portuguese
dojot/flowbroker#227, fixing dojot/dojot#1447 dojot/dojot#1449: Adds the possibility to configure kafka parameters
dojot/flowbroker#226: remove ftp get
dojot/flowbroker#213, fixing dojot/dojot#1421 dojot/dojot#1299: fix: notification list crashes if the notification node configuration is incorrect

dojot/ejbca-rest
----------------

dojot/ejbca-rest#48: fixing dojot/dojot#1586: Fix to increase EJBCA's deployment timeout

dojot/iotagent-leshan
---------------------

dojot/iotagent-leshan#50: chore: add params to create device 

dojot/docker-compose
---------------------------

dojot/docker-compose#163: fixing dojot/dojot#1585: volume mapping

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.4.3-rc.1
----
Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.4.3-rc.1
----
Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.4.3-rc.1
----

**Comment by betefaber** [comment]
- Sanity Test in k8s and docker-compose environments

- Tests performed in the admin and test tenants

- [x] devices
- [x] templates
- [x] flows (all nodes + remote node)
     actuate
     aggregation 
    basic 
    CRON-BATCH-BROKER 
    CRON-BATCH-HTTP 
    CRON-EventRequest 
    CRON-HTTPRequest
    cumulative sum + merge data
    cumulative sum 
    device in (deprecated)
    FTP 
    geofence 
    http - GET (#1650)
    http - POST (#1650)
    http-notification (#1650)
    kelvin
    merge data 
    notification 
    remote node
    switch (deprecated)
    template (deprecated)
- [x] notifications
- [x] users
- [x] profiles
- [x] real time
- [x] tracking
- [ ] firmware update

- Validated tickets

![image](https://user-images.githubusercontent.com/37310063/91100054-dbe60d00-e63a-11ea-8d96-23b9849f5907.png)
