### ISSUE TITLE
[X509] the fields parameter with invalid keys

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1613]
When accessing the endpoint `/x509/v1/certificates{?page,limit,fields,keyVal}` filling the _fields_ parameter with invalid keys, the response is the list of all certificates. Expected to return an error, data not found.

Affected baseline: v0.5.0-alpha.3

**Comment by thiagodpf** [comment]
PR with correction:
https://github.com/dojot/dojot/pull/1633
