### ISSUE TITLE
There is no version associate to documentation

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#162]
Actually there is no version associate to [documentation](http://dojotdocs.readthedocs.io/en/latest/). It is a problem due the fact that there is a tag (0.1.0) and some procedures has been changed since it. If we simply update the documentation, an user that try to use an older version will face problems.

**Comment by giovannicuriel** [comment]
I would add all documentation for all components, not only from readthedocs. All APIs in GitHub pages need also to be versioned, so that the user can check the API in the relevant version.

**Comment by mmagr** [comment]
Even though we're lacking the new `0.2.0` version on [public documentation](http://dojotdocs.readthedocs.io), it seems to me that this can be closed - a tag for version `0.1.0` is already there, and "latest" refers to the current status-quo of documentation (that is, mostly what `0.2.0` will look like)

@giovannicuriel what do you think?

**Comment by rascaraficci** [comment]
This issue has been already handled.
