### ISSUE TITLE
[kafka-ws][web socket] Empty message when filtering a parameter from its parent

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1621]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
when filtering a parameter from its parent, Dojot can send a message that is of no worth. 
For example:

Use this filter "fields=attrs/temperature" and send a mqtt publication without this parameter, like '{"humidity": 65}'.

It will return "{"attrs":{}}", via kafka-ws.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Connect vi ws using a url like:
`  ws://<DojotIP>:80/kafka-ws/v1/topics/admin.device-data?ticket=<ticket>&fields=attrs/temperature`
Publish a mqtt message: 
`mosquitto_pub -h <DojotIP> -p 1883 -t admin:<deviceId>/attrs -u admin:<deviceId> -m '{"humidity": 65}'`

* **What is the expected behavior?**
I think it must not send any message

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.5.0 alpha3
  - Environment: [kubernetes]
  - Operating system: [Ubuntu]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
Ticket Analysis: To be analysed.

**Comment by eduardogmisiuk** [comment]
After debating about this issue, we decided to make it clear in the documentation that this behaviour happens. It is not a bug though, since it can make sense to an application.
