### ISSUE TITLE
Error opening more than 2 GEO attributes, white box

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1625]
1° Adding Template with the attributes:
- GEO -> Dynamic
- GEO -> Actuate
- GEO -> Static

A publication was made on all attributes with different coordinates, when detailing the device and opening more than two attributes, the third box with the coordinate is blank.

**Dynamic:**
mosquitto_pub -h 10.50.11.203 -p 1883 -t admin:6e18d0/attrs -m '{ "GEO_Dinamico": "48.858196, 2.294510"}'

**Actuate:**
{
  "topic": "/admin/6e18d0/config",
  "attrs": {
    "GEO_Atuador": "48.850219, 2.294525"
  }
}

**Static**
![Captura de tela de 2020-08-12 17-30-06](https://user-images.githubusercontent.com/52173618/90064695-8c5e2380-dcc1-11ea-83da-af0e9eb98cf0.png)

![Captura de tela de 2020-08-12 16-39-53](https://user-images.githubusercontent.com/52173618/90064711-92540480-dcc1-11ea-9fe5-bb7dc11031b1.png)

Version v0.5.0-alpha.3

**Comment by FrancielePessi** [comment]
Possibility of the same error. 

-  [https://github.com/dojot/dojot/issues/1153](url)
-  [https://github.com/dojot/dojot/issues/994](url)

**Comment by bizetti** [comment]
Ticket Analysis - It won't be fixed.
