### ISSUE TITLE
[kubernetes] In the GUI, there is no indication that the remote node has been removed

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1630]
In the k8s environment, when the remote node is removed,  there is no indication na GUI that the node does not exist.

- docker-compose

![kelvindocker](https://user-images.githubusercontent.com/37310063/90252464-ee2fa200-de15-11ea-92b0-018e90c0f522.png)

- k8s

![kelvinK8s](https://user-images.githubusercontent.com/37310063/90252466-ef60cf00-de15-11ea-87c3-113f0843f889.png)

Note: In the k8s environment, if it is not a remote node there is indication that the node has been removed

![image](https://user-images.githubusercontent.com/37310063/90253365-6a76b500-de17-11ea-9f35-380e7fc0cd4a.png)

**Comment by bizetti** [comment]
It has to be fixed.

**Comment by betefaber** [comment]
The problem was not repeated after the application was restarted.

![image](https://user-images.githubusercontent.com/37310063/90279910-6a3edf80-de40-11ea-979c-1e5904c649a1.png)
