### ISSUE TITLE
[Dashboard] plotting published data at different times

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1677]
Data is plotted correctly when published at the same time.

![dadosaomesmotempo](https://user-images.githubusercontent.com/37310063/91338073-bbd55b80-e7aa-11ea-83d3-505560f23b95.png)

If they are not published at the same time, the first data is out of order.

- publishing the 1st data

![1ºdado](https://user-images.githubusercontent.com/37310063/91338089-c2fc6980-e7aa-11ea-80c9-94889b925213.png)

- publishing the 2nd data

![2ºdado](https://user-images.githubusercontent.com/37310063/91338100-c859b400-e7aa-11ea-8b32-4f6d39b1b10f.png)

**Comment by betefaber** [comment]
- new data published at the same time

![image](https://user-images.githubusercontent.com/37310063/91338687-b0cefb00-e7ab-11ea-9406-d03a9ffeb443.png)

- data published at different times

![Screenshot_13](https://user-images.githubusercontent.com/37310063/91342498-8122f180-e7b1-11ea-9be8-d096c187cc26.png)


In the new publication of this device, as the previously published data was disordered, the graph is inconsistent.

![Screenshot_14](https://user-images.githubusercontent.com/37310063/91340850-0bb62180-e7af-11ea-8e23-92c6e478cef3.png)

**Comment by betefaber** [comment]
- plotting in the area graph

![Screenshot_15](https://user-images.githubusercontent.com/37310063/91346118-bd0c8580-e7b6-11ea-917a-523e8101eb42.png)

**Comment by betefaber** [comment]
- plotting on the bar graph

![Screenshot_19](https://user-images.githubusercontent.com/37310063/91350435-12e42c00-e7bd-11ea-9592-0033f5f43174.png)

![Screenshot_20](https://user-images.githubusercontent.com/37310063/91350448-1972a380-e7bd-11ea-98c5-c5bfab6ba944.png)

![Screenshot_21](https://user-images.githubusercontent.com/37310063/91350462-1ecfee00-e7bd-11ea-9bb9-ae4cedee936e.png)

**Comment by betefaber** [comment]
- table

![image](https://user-images.githubusercontent.com/37310063/91353477-b2a3b900-e7c1-11ea-8e09-a76856a5c158.png)

**Comment by bizetti** [comment]
To be retested.

**Comment by betefaber** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/37310063/91609685-3b4f6000-e94e-11ea-9fb0-b982c3b1bc1d.png)
