### ISSUE TITLE
Device and TLS (MQTT) - Observing the list of revoked certificates

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#168]

**Comment by giovannicuriel** [comment]
Apparently, EJBCA is not recognizing function parameters. If I send the request:

```bash
curl -X GET http://localhost:8000/ca/IOTmidCA/certificate/3101837270795222210/status 
  -H "Authorization: Bearer ${JWT}"
```

I get the answer:

```json
{"status": 400, "message": "soap message: Could not find CA with name null and ID 0"}
```

Even if those parameters don't exist (in the case that I am sending invalid values, which I'm not), the answer should be something like:

```json
{"status": 400, "message": "soap message: Could not find CA with name IOTmidCA and ID 849723..."}
```

I also tried to send the request directly to EJBCA (via SOAP interface), but without success.

**Comment by mprevide** [comment]
Certificate revocation (must drop existing connection)

**Comment by muhamedcpqd** [comment]
Apparently the issuer dn passed to <cacn> field in the request was misunderstood. The correctly issuer dn registered  in the certificates assigned by IOTmidCA is: issuerDN = 'CN=IOTmidCA,O=EJBCA IOT,C=SE'. The field <certcn> must be the certsn (the cert serial number) in hexadecimal. I will create a new pull request changing those fields names correctly and informing the user what must be correctly passed.

**Comment by eduardogmisiuk** [comment]
The documentation continues to mislead about the CA name and format of the certificate's Serial Number.

**Comment by bizetti** [comment]
Ticket analisys (Jan, 24th): There is another EJBCA wrapper. This ticket will be cancelled.
