### ISSUE TITLE
Locust message when creating certificates

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1681]
**1º** Create device using:
- python -m src.scripts.generate_certs dojot create --devices 1

**2º** Create certificates using:
- python -m src.scripts.generate_certs cert --dojot --remove

When creating the certificates, in the log the message is successful, but it was not created.

File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/src/scripts/generate_certs.py", line 583, in register_thing
    thing = Thing(CONFIG['app']['tenant'], thing_id)
  File "/usr/src/app/src/ejbca/thing.py", line 16, in __init__
    self.cert = Certificate(thing_id)
  File "/usr/src/app/src/ejbca/certificate.py", line 25, in __init__
    DojotAPI.create_ejbca_user(self.jwt, self.c_name)
  File "/usr/src/app/src/dojot/api.py", line 247, in create_ejbca_user
    DojotAPI.call_api(requests.post, args, False)
  File "/usr/src/app/src/dojot/api.py", line 361, in call_api
    raise APICallError("exceeded the number of retries to {0}".format(args['url']))
src.dojot.api.APICallError: exceeded the number of retries to http://10.50.11.203/user
generate_cert line 509 | 27-08-2020 16:20:16 [INFO]: Total inserts 17 in 20s using 4 processes
generate_cert line 430 | 27-08-2020 16:20:16 [INFO]: Creating key files...
generate_cert line 442 | 27-08-2020 16:20:16 [INFO]: Successfully created!
generate_cert line 447 | 27-08-2020 16:20:16 [INFO]: Creating certificate files...
_**generate_cert line 459 | 27-08-2020 16:20:16 [INFO]: Successfully created!**_
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/src/scripts/generate_certs.py", line 601, in <module>
    GenerateCerts()
  File "/usr/src/app/src/scripts/generate_certs.py", line 56, in __init__
    self.run()
  File "/usr/src/app/src/scripts/generate_certs.py", line 197, in run
    self.cert_commands()
  File "/usr/src/app/src/scripts/generate_certs.py", line 257, in cert_commands
    self.retrieve_ca_cert()
  File "/usr/src/app/src/scripts/generate_certs.py", line 475, in retrieve_ca_cert
    if res["certificate"] is None:
KeyError: 'certificate'
bash-5.0#

**3º**  When verifying that the certificates were created, nothing was found.

fsilva@freedom:~/Área de Trabalho/DOJOT/LOCUST/dojot/connector/mqtt/locust$ **ls cert**
renew  revoke

version Locust: v0.5.0-alpha2

**Comment by bizetti** [comment]
To be analyzed. Is it fixed?

**Comment by eduardogmisiuk** [comment]
> To be analyzed. Is it fixed?

No, there are some enhancements to be made.

**Comment by betefaber** [comment]
Test OK.

```
generate_cert line 215 | 12-11-2020 18:37:13 [INFO]: Removing certificates...
generate_cert line 224 | 12-11-2020 18:37:13 [INFO]: ... Removed certificates
generate_cert line 226 | 12-11-2020 18:37:13 [INFO]: Creating certificates directories...
generate_cert line 235 | 12-11-2020 18:37:13 [INFO]: ... Created certificates directories
generate_cert line 596 | 12-11-2020 18:37:17 [INFO]: Process 6 finished in 3.558950s
generate_cert line 596 | 12-11-2020 18:37:17 [INFO]: Process 3 finished in 3.571596s
generate_cert line 596 | 12-11-2020 18:37:17 [INFO]: Process 4 finished in 3.963024s
generate_cert line 596 | 12-11-2020 18:37:17 [INFO]: Process 5 finished in 3.960886s
generate_cert line 596 | 12-11-2020 18:37:17 [INFO]: Process 7 finished in 3.956147s
generate_cert line 596 | 12-11-2020 18:37:17 [INFO]: Process 2 finished in 3.973819s
generate_cert line 596 | 12-11-2020 18:37:17 [INFO]: Process 0 finished in 4.113845s
generate_cert line 596 | 12-11-2020 18:37:17 [INFO]: Process 1 finished in 4.144677s
generate_cert line 508 | 12-11-2020 18:37:17 [INFO]: Total inserts 10 in 4s using 8 processes
generate_cert line 432 | 12-11-2020 18:37:17 [INFO]: Creating key files...
generate_cert line 444 | 12-11-2020 18:37:17 [INFO]: Successfully created!
generate_cert line 449 | 12-11-2020 18:37:17 [INFO]: Creating certificate files...
generate_cert line 461 | 12-11-2020 18:37:17 [INFO]: Successfully created!
generate_cert line 406 | 12-11-2020 18:37:17 [INFO]: Beginning database mapping...
generate_cert line 416 | 12-11-2020 18:37:17 [INFO]: Finished database mapping.
```

```
$ ls -la cert/
total 100
drwxr-xr-x 4 root   root   4096 nov 12 15:37 .
drwxrwxr-x 9 efaber efaber 4096 nov 12 15:34 ..
-rw-r--r-- 1 root   root   2487 nov 12 15:37 127716.crt
-rw-r--r-- 1 root   root   1708 nov 12 15:37 127716.key
-rw-r--r-- 1 root   root   2487 nov 12 15:37 1aca45.crt
-rw-r--r-- 1 root   root   1704 nov 12 15:37 1aca45.key
-rw-r--r-- 1 root   root   2487 nov 12 15:37 2aab79.crt
-rw-r--r-- 1 root   root   1704 nov 12 15:37 2aab79.key
-rw-r--r-- 1 root   root   2487 nov 12 15:37 2e1f1e.crt
-rw-r--r-- 1 root   root   1708 nov 12 15:37 2e1f1e.key
-rw-r--r-- 1 root   root   2487 nov 12 15:37 4f3949.crt
-rw-r--r-- 1 root   root   1704 nov 12 15:37 4f3949.key
-rw-r--r-- 1 root   root   2487 nov 12 15:37 9a5f7f.crt
-rw-r--r-- 1 root   root   1708 nov 12 15:37 9a5f7f.key
-rw-r--r-- 1 root   root   2487 nov 12 15:37 a18622.crt
-rw-r--r-- 1 root   root   1708 nov 12 15:37 a18622.key
-rw-r--r-- 1 root   root   2487 nov 12 15:37 ada574.crt
-rw-r--r-- 1 root   root   1704 nov 12 15:37 ada574.key
-rw-r--r-- 1 root   root   2487 nov 12 15:37 c151e2.crt
-rw-r--r-- 1 root   root   1704 nov 12 15:37 c151e2.key
-rw-r--r-- 1 root   root   2109 nov 12 15:37 ca.crt
-rw-r--r-- 1 root   root   2487 nov 12 15:37 df2a30.crt
-rw-r--r-- 1 root   root   1704 nov 12 15:37 df2a30.key
drwxr-xr-x 2 root   root   4096 nov 12 15:37 renew
drwxr-xr-x 2 root   root   4096 nov 12 15:37 revoke
```
