### ISSUE TITLE
[Dashboard] Identification of devices in the charts

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1685]
In the charts there is no information about the devices to which the data belongs.

![image](https://user-images.githubusercontent.com/37310063/91752447-c45bd680-eb9c-11ea-9998-546528591a21.png)

For example, the information could be in a tooltip in the legend.

**Comment by bizetti** [comment]
User can define an specific label during wizard with device name.
Low.

**Comment by bizetti** [comment]
It's possible name the line during the wizard.
