### ISSUE TITLE
Test - Survey of test assets and activity status

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#169]

**Comment by hvjunior** [comment]
This activity has two parts:

- Selenium scripts to test GUI 
By now, Romulo didn´t find the scripts that he used on the GUI tests.

- JMeter scripts to test APIs
The scripts that Romulo used on the tests was storage in Google Drive (  https://drive.google.com/drive/folders/1fMJ-nrHc5DRlZOXW6WNt5vwONf2Q9RGP?usp=sharing )
