### ISSUE TITLE
 Improvement Point: Acceptance of String and Geo in Graph

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1690]
Segment: When adding Geo and String to a chart, there should be an alert box, warning the user that this configuration is not functional.

![Captura de tela de 2020-09-02 11-45-04.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/456d8473-011e-4685-9350-732f10adf0fc)

tested version: v0.5.0-alpha.4

**Comment by FrancielePessi** [comment]
Tip: Only display numeric attributes

**Comment by bizetti** [comment]
It was implemented.
