### ISSUE TITLE
[Dashboard] Separate  configs contexts between tenants

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1694]
Users of different tenants view the same configuration.

----
user `admin`, tenant `admin`
----

![dashboard-admin](https://user-images.githubusercontent.com/37310063/92271738-b79df200-eebe-11ea-83a4-5c812c3f4f97.png)

![user-admin](https://user-images.githubusercontent.com/37310063/92271734-b7055b80-eebe-11ea-8538-6183035cda4b.png)

----
user `teste`, tenant `teste`
----

![user-teste](https://user-images.githubusercontent.com/37310063/92271730-b53b9800-eebe-11ea-97e4-5101513f1fd3.png)

- Although you do not see the data from the other tenant, the graphs created in one tenant are seen by the other.

![dashboard-teste](https://user-images.githubusercontent.com/37310063/92271735-b7055b80-eebe-11ea-9df4-f5473467a558.png)

----
user `usuario`, tenant `admin`
----
![user-usuario](https://user-images.githubusercontent.com/37310063/92272397-d8b31280-eebf-11ea-912c-1a3df0ca8dba.png)
![dashboard-usuario](https://user-images.githubusercontent.com/37310063/92272403-d9e43f80-eebf-11ea-8514-4f20ccab515f.png)

**Detail**: users in different browsers (Google Chrome and Mozilla Firefox)

**Comment by mprevide** [comment]
Maybe It is a cache browser  problem

**Comment by betefaber** [comment]
Test OK. Tested in v0.5.0-rc.1.

- user `admin`, tenant `admin`

![image](https://user-images.githubusercontent.com/37310063/98560856-f8333680-2286-11eb-9ba2-b0831d9912a8.png)

- user `fernanda`, tenant `teste`

![Screenshot_13](https://user-images.githubusercontent.com/37310063/98560692-ce7a0f80-2286-11eb-9d67-1c04419289a3.png)
