### ISSUE TITLE
[100K] [VerneMQ] MQTT connection becomes unstable

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1697]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
MQTT client begins to continuously connecting and disconnecting for a while. This behavior starts after TLS connection maximum life time. 

MQTT publications are accepted during this unstable period.

In attached pcap it is possible to see this period remains around 3 minutes

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
using Locust, connect one client to dojot and wait up to session lifetime (defined in disconnect plugin).
See connect and disconnect statistics

* **What is the expected behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.5.0 alpha4
  - Environment: kubernetes - 100k

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

![locust](https://user-images.githubusercontent.com/53264012/92473703-57a29680-f1b1-11ea-95bc-d5635af8c5a5.PNG)
[VerneLogs.zip](https://github.com/dojot/dojot/files/5188104/VerneLogs.zip)

[pcap_disconnect_v050alpha4.zip](https://github.com/dojot/dojot/files/5188103/pcap_disconnect_v050alpha4.zip)

**Comment by eduardogmisiuk** [comment]
TODO: test with the latest VerneMQ version.

**Comment by bizetti** [comment]
Use local DNS (hosts file) and retest

**Comment by eduardogmisiuk** [comment]
There were two problems:
- The CRL was too big, causing a huge memory usage and consequently killing VerneMQ pods. The solution was to work with a clean CRL.
- The number of ports in HAProxy did not supported the load. We had to modify it via `sysctl` to properly work.

**Comment by rascaraficci** [comment]
This issue will be closed due to inactivity.
It should be reopen if necessary.
