### ISSUE TITLE
Test: Sanity test for dojot 0.4.3

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1712]

**Comment by FrancielePessi** [comment]
Test in the Kubernetes version 0.4.3

[] Automated testing - Codecept
[] Flows
[] Device
[] Template
[] Publication with TLS

**Comment by FrancielePessi** [comment]
Review the FW Simulator in version Docker-compose v0.4.3- Data is not being sent simultaneously to the dojot.
