### ISSUE TITLE
Change context URL - GUI

### ISSUE THREAD

**Issue by luissajunior** [dojot/dojot#1721]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
On project Mobilidade Elétrica we need change the context URL of GUI.
There is an screen who contain all the projects GUI, and that included Dojot. For a user have a good expirience navigation whe need that.

* **Please tell us about your environment:**
  
  - Version: 0.4.2
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 18.04]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
Kong and GUI have to be modified.

**Comment by betefaber** [comment]
Test performed in Mobilidade Elétrica project.
