### ISSUE TITLE
[docker-compose] [release/v0.5.0] some errors when trying up at first time

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1723]
When I trying up the compose for v0.5.0 and  I was using v0.4.3  before and  I don't  delete volumes this error happens.
I think we can document that. 

I'm using:

- Docker version 19.03.8, build afacb8b7f0
- docker-compose version 1.27.3, build 4092ae5d
- ubuntu 20.04

The imgs:
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/4be36030-0e76-497d-89bb-7989b3a22a1d)
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/49c5e037-7263-4b51-93c5-2d3197d87e7d)
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/d189fc76-5518-48fe-bd23-49da1665eefc)
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/1a3ee3ca-a15a-42ae-91c0-780d713fc90f)
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/92d50c61-b9aa-4a10-8dbf-6a475528e8aa)

**Comment by mprevide** [comment]
A day later I restarted my PC and the apigw had down
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/0b7a6691-ed4d-40be-966b-7715f2306df1)
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/8ea07f02-bcfb-4057-aaff-4ffebd3f572a)

**Comment by mprevide** [comment]
I think it is necessary to document an incompatibility of volumes between versions.

**Comment by bizetti** [comment]
It will be treated using dojot#1882
