### ISSUE TITLE
CALL FAILED -DOJOT

### ISSUE THREAD

**Issue by Cleisonucl** [dojot/dojot#1725]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X ] support request

* **Do you want to request a *feature* or report a *bug*?**

I am receiving the **call failed** message

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

N/A

* **What is the expected behavior?**
Normal execution

* **What is the motivation / use case for changing the behavior?**

N/A

* **Please tell us about your environment:**
  
  - ### **Version:0.4.3**
  - Docker version: 2.3.0.5
  - Operating system:Windows 10

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

![14cff7c9-4a66-4fb3-abbc-50f483c3f565](https://user-images.githubusercontent.com/25806538/93786216-6c494a80-fc05-11ea-9880-3a4793632450.jpg)

**Comment by eduardogmisiuk** [comment]
Hello @Cleisonucl , thanks for your report! This is a known bug that does not affect the usability of the platform. It will be corrected in future versions.

**Comment by Cleisonucl** [comment]
@eduardogmisiuk It's completely affecting my usability, since I can't save any of my models because of this message

**Comment by eduardogmisiuk** [comment]
> @eduardogmisiuk It's completely affecting my usability, since I can't save any of my models because of this message

OK. Try to logout and login again.

**Comment by Cleisonucl** [comment]
yes, i solved the problem with that, thanks

**Comment by eduardogmisiuk** [comment]
> yes, i solved the problem with that, thanks

Glad to hear that! In the next version this problem is solved too.
