### ISSUE TITLE
[dojot-modules/auth] Analyse Topics  *.dojot.tenancy

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1726]
Auth uses the topic ``dojot-management.dojot.tenancy`` to produce msgs when tenants are created and deleted.
But the libs dojot-modules create topics like ``admin.dojot.tenancy`` (``$tenant.dojot.tenancy``) 
and nothing seems to publish on this topics.. There is some code that deal with that inside the  libs, but it doesn't  seems to work.

Based on this, I change  a bit the documentation in readthedocs by removing the subject  ``dojot.tenancy``  and
changed to kafka topic ``dojot-management.dojot.tenancy``.

**Comment by betefaber** [comment]
Tested in **v0.6.0-rc.2**
