### ISSUE TITLE
dojot services - Update to include new dojot-module-nodejs version

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1730]
- [x] iotagent-nodejs @jonaphael 
- [x] flowbroker @jonaphael 
- [x] data-broker @canattofilipe 
- [x] cron @canattofilipe 

**Testing**:
- Data Broker:
As data-broker is an internal service, only check if the service is up and running (`docker compose ps`)
- Cron:
Create a broker job and test if it is triggering correctly

Linked to dojot#1479

In this case i think it's necessary to update 0.4.4, 0 .5.0 and dev

**Comment by betefaber** [comment]
Tested in **v0.4.4-rc.1**.

- data-broker
```
docker ps -a | grep data-broker
4c02a2a52dc1        dojot/data-broker:v0.4.4-rc.1         "/sbin/tini -- npm r…"   30 hours ago     Up 30 hours     80/tcp         dojot_data-broker_1
37a729e18e2c        dojot/redis:5.0.5-alpine3.10          "docker-entrypoint.s…"   30 hours ago     Up 30 hours     6379/tcp       dojot_data-broker-redis_1
```
- cron

   - http
```
cron_1                        | <19:18:48 20/10/2020> -- INFO: Succeeded to set up cron job b1a61df6-e52c-4c40-92cf-599b8a44f1c1 with spec {"time":"*/5 * * * *","timezone":"America/Sao_Paulo","name":"Keep alive","description":"This job sends a keep alive notification to a device every 5 minutes","http":{"method":"PUT","headers":{"Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHV293SU55OWZaWXZuRk5FYXpHWTcxeWpQbjhJR3NHaSIsImlhdCI6MTYwMzIyMTUyNywiZXhwIjoxNjAzMjIxOTQ3LCJwcm9maWxlIjoiYWRtaW4iLCJncm91cHMiOlsxXSwidXNlcmlkIjoxLCJqdGkiOiI4MDY5MmY2ODFiNzMyODhlZGZjMTQzNTRiZWJjMmE2MiIsInNlcnZpY2UiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.go_HZ6toxWmdR8SQcLaV-Q9t_g34Dw5cJ-QY3LhW-Dg","Content-Type":"application/json"},"url":"http://device-manager:5000/device/3b43d6/actuate","body":{"attrs":{"message":"keepalive"}}}}.

```
```
persister_1                   | [20/10/20 - 19:20:00] |messenger| INFO: Emitting new event message for subject dojot.device-manager.device@admin
persister_1                   | [20/10/20 - 19:20:00] |persister| INFO: got device event {'event': 'configure', 'data': {'attrs': {'message': 'keepalive'}, 'id': '3b43d6'}, 'meta': {'service': 'admin', 'timestamp': 1603221600060}}
persister_1                   | [20/10/20 - 19:20:00] |persister| INFO: new message is: {'attrs': {'message': 'keepalive'}, 'metadata': {'timestamp': 1603221600060, 'deviceid': '3b43d6', 'tenant': 'admin'}}
persister_1                   | [20/10/20 - 19:20:00] |persister| INFO: Received data: {'attrs': {'message': 'keepalive'}, 'metadata': {'timestamp': 1603221600060, 'deviceid': '3b43d6', 'tenant': 'admin'}}
persister_1                   | [20/10/20 - 19:20:00] |persister| DEBUG: got data event {"attrs": {"message": "keepalive"}, "metadata": {"timestamp": 1603221600060, "deviceid": "3b43d6", "tenant": "admin"}}
persister_1                   | [20/10/20 - 19:25:00] |messenger| INFO: Emitting new event message for subject dojot.device-manager.device@admin
persister_1                   | [20/10/20 - 19:25:00] |persister| INFO: got device event {'event': 'configure', 'data': {'attrs': {'message': 'keepalive'}, 'id': '3b43d6'}, 'meta': {'service': 'admin', 'timestamp': 1603221900026}}
persister_1                   | [20/10/20 - 19:25:00] |persister| INFO: new message is: {'attrs': {'message': 'keepalive'}, 'metadata': {'timestamp': 1603221900026, 'deviceid': '3b43d6', 'tenant': 'admin'}}
persister_1                   | [20/10/20 - 19:25:00] |persister| INFO: Received data: {'attrs': {'message': 'keepalive'}, 'metadata': {'timestamp': 1603221900026, 'deviceid': '3b43d6', 'tenant': 'admin'}}
persister_1                   | [20/10/20 - 19:25:00] |persister| DEBUG: got data event {"attrs": {"message": "keepalive"}, "metadata": {"timestamp": 1603221900026, "deviceid": "3b43d6", "tenant": "admin"}}
```


   - broker
```
cron_1                        | <19:35:35 20/10/2020> -- INFO: Succeeded to set up cron job f3e0a3a2-2580-4968-a86a-7c70e9aa5487 with spec {"time":"*/5 * * * *","timezone":"America/Sao_Paulo","name":"Keep alive","description":"This job sends a keep alive notification to a device every 5 minutes","broker":{"subject":"dojot.device-manager.device","message":{"event":"configure","data":{"attrs":{"message":"keepalive"},"id":"ac096d"},"meta":{"service":"admin","timestamp":1603222242000}}}}.

```
persister_1                   | [20/10/20 - 19:40:01] |messenger| INFO: Emitting new event message for subject dojot.device-manager.device@admin
persister_1                   | [20/10/20 - 19:40:01] |persister| INFO: got device event {'event': 'configure', 'data': {'attrs': {'message': 'keepalive'}, 'id': 'ac096d'}, 'meta': {'service': 'admin', 'timestamp': 1603222242000}}
persister_1                   | [20/10/20 - 19:40:01] |persister| INFO: new message is: {'attrs': {'message': 'keepalive'}, 'metadata': {'timestamp': 1603222242000, 'deviceid': 'ac096d', 'tenant': 'admin'}}
persister_1                   | [20/10/20 - 19:40:01] |persister| INFO: Received data: {'attrs': {'message': 'keepalive'}, 'metadata': {'timestamp': 1603222242000, 'deviceid': 'ac096d', 'tenant': 'admin'}}
persister_1                   | [20/10/20 - 19:40:01] |persister| DEBUG: got data event {"attrs": {"message": "keepalive"}, "metadata": {"timestamp": 1603222242000, "deviceid": "ac096d", "tenant": "admin"}}
persister_1                   | [20/10/20 - 19:45:01] |messenger| INFO: Emitting new event message for subject dojot.device-manager.device@admin
persister_1                   | [20/10/20 - 19:45:01] |persister| INFO: got device event {'event': 'configure', 'data': {'attrs': {'message': 'keepalive'}, 'id': 'ac096d'}, 'meta': {'service': 'admin', 'timestamp': 1603222242000}}
persister_1                   | [20/10/20 - 19:45:01] |persister| INFO: new message is: {'attrs': {'message': 'keepalive'}, 'metadata': {'timestamp': 1603222242000, 'deviceid': 'ac096d', 'tenant': 'admin'}}
persister_1                   | [20/10/20 - 19:45:01] |persister| INFO: Received data: {'attrs': {'message': 'keepalive'}, 'metadata': {'timestamp': 1603222242000, 'deviceid': 'ac096d', 'tenant': 'admin'}}
persister_1                   | [20/10/20 - 19:45:01] |persister| DEBUG: got data event {"attrs": {"message": "keepalive"}, "metadata": {"timestamp": 1603222242000, "deviceid": "ac096d", "tenant": "admin"}}


```

```

**Comment by betefaber** [comment]
Tested in **v0.5.1-rc.2**
