### ISSUE TITLE
[GUI] Missing translation pt-br for "Version" 

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1734]
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/ccc207d2-2607-440f-b9af-a7cb8087716a)

Reported by @cfrancisco

**Comment by betefaber** [comment]
Fixed in **v0.4.4-rc.1**

![image](https://user-images.githubusercontent.com/37310063/96627247-f65cff80-12e6-11eb-81d9-a9156f3d5f8f.png)

**Comment by betefaber** [comment]
Fixed in **v0.5.0-rc.1**

![image](https://user-images.githubusercontent.com/37310063/98157628-5abbb980-1eb8-11eb-9fb2-4724d5e20637.png)
