### ISSUE TITLE
[ansible] Review/standardize ansible variables

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1735]
- maybe remove folders *vars* from all roles
- check if doesn't exist repeated variables between at *roles/**/defaults/main.yaml*  and *inventories/example_local/group_vars/all/dojot.yaml*, if exist changes  at *roles/**/defaults/main.yaml* to something like that `dojot_auth_version: "{{ dojot_version }}"` to avoid confusion.
- some places boolean has `'` and others not, try standardize
- At *roles/auth/defaults/main.yaml#L11* needs `"`?  If  yes change to `"user_passwd"`. And then find others points if can be a problem. 
- At *roles/auth/templates/auth_deployment.yaml.j2#L66*  there is a fixed 'https' this can be a http too, maybe we can create a variable to `https://{{ dojot_domain_name }}/#/setPassword/` in  *roles/auth/defaults/main.yaml*

**Comment by bizetti** [comment]
PR only to development branch.
