### ISSUE TITLE
[ansible-dojot] Alter context from v1beta1 to v1

### ISSUE THREAD

**Issue by luissajunior** [dojot/dojot#1741]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Because the version of kubernetes up then we need change the clients who access his apis. So, the context name need to be chenged.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.2.x
  - Environment: [kubernetes, docker-compose, standalone]
  - Operating system: [Ubuntu 16.04, Fedora 28, Ubuntu on VirtualBox (Windows 10), etc.]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by betefaber** [comment]
![image](https://user-images.githubusercontent.com/37310063/97054297-efd6be00-155a-11eb-9751-9db682445604.png)

**Comment by betefaber** [comment]
Fixed in **v0.5.0-rc.1** by the #1770.
