### ISSUE TITLE
Remove a flow node by dragging it to s specific area

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1749]
@ericbaum commented on [Fri Feb 08 2019](https://github.com/dojot/flowbroker/issues/114)

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

To remove a node it must be selected with the mouse and the delete key has to be pressed on the keyboard

* **What is the expected behavior?**

The expected behavior of this feature is to add an "area" on the flow screen where it is possible to drag the node in order for it to be removed or even remove a "batch" of selected nodes dragged to this area

* **What is the motivation / use case for changing the behavior?**

Avoid having to use the keyboard to remove the node when everything else can be done with the mouse.

---

@raulnegreiros commented on [Wed Feb 27 2019](https://github.com/dojot/flowbroker/issues/114#issuecomment-467847478)

This feature is related to the front-end, it's code resides on dojot/gui. Could be a good idea to open an issue on dojot/dojot or dojot/gui.

**Comment by cfrancisco** [comment]
This enhancement will not be made.
