### ISSUE TITLE
PDP cache (redis) is not updated for group operations

### ISSUE THREAD

**Issue by mmagr** [dojot/dojot#1754]
When a user is assigned to a new group, all cache entries related to this user should be forcibly expired, or else a user calling an endpoint will be subject to the old set of policies for that "hot" endpoint.

Steps to reproduce
-------------------------
- create a user with default "permit" policy for an endpoint
- use the endpoint; User should have access to it
- assign the user to an existing group that denies access to the endpoint
- retrieve a new token for the user (this may be an issue of its own)
- use the endpoint again; User should not have access to it
- **verify that user is still able to access the endpoint**

Steps to circumvent
------------------------
- login to redis-cli
- issue `del PDP;[userid];[http method];[endpoint]`

**Comment by bizetti** [comment]
Ticket analisys (9th, October 2020): It's not be treated.
