### ISSUE TITLE
[microservice-sdk] [config-manager] Object merging is wrongly applied to arrays

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1769]
The merge isn't working as expected in arrays. Example:
Suppose you have a parameter with the default value `['a', 'b', 'c']` and user value `['d', 'e']` . The result with the current implementation gives the result `['d', 'e', 'c']`, which is wrong. The correct result is not a merge of the arrays, but an overwrite: `['d', 'e']`

Affected version: v0.1.5

**Comment by rascaraficci** [comment]
Done!
