### ISSUE TITLE
[flowbroker][ansible] error when trying add remote node

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1770]
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/d3458681-0719-4f8a-b4bb-732fd559701e)

The above error happens when I run: `` curl -H "Authorization: Bearer ${JWT}" http://aya.dojot.com.br/flows/v1/node -H 'content-type: application/json' -d '{"image": "dojot/kelvin-example:v0.5", "id":"kelvin"}'``

When I using docker-compose and run  ``curl -H "Authorization: Bearer ${JWT}" http://localhost:8000/flows/v1/node -H 'content-type: application/json' -d '{"image": "dojot/kelvin-example:v0.5", "id":"kelvin"}'`` everything works fine. 

![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/778ba474-ec4e-4f5f-8772-956e8ab6b9f0)

I tried restarting the pod, but it didn't solve the problem.

Tested in not yet published v0.4.4-rc.1 (https://github.com/dojot/ansible-dojot/commit/9b056e21c5c1340ffc2e86e1470875edaf8574b4)

Commit used to create docker img  https://github.com/dojot/flowbroker/commit/e9f48a2db7c19be5e33927b0bfd92138f0a0789c

Probably this happen at v0.5.x and development.

**Comment by betefaber** [comment]
Fixed in **v0.4.4-rc.1**

Needs to be tested on v0.5.0-rc.1

**Comment by betefaber** [comment]
Fixed in **v0.5.0-rc.1**
