### ISSUE TITLE
[gui-v2] Errors should be shown when it is not possible to login

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1771]
When I try to login with a user or password that does not exist, no error message appears.
As this login page will be changed in the next version (keycloak has its own login page [confirm that we will use its own page]), it could be something simple that only shows the msg returned from the api.

Tested in v0.5.0-alpha.4

**Comment by betefaber** [comment]
An error message is shown.

- pt-br

![Screenshot_28](https://user-images.githubusercontent.com/37310063/100001133-6c023280-2da1-11eb-8ef2-469db51ff5a6.png)

- en-us

![Screenshot_27](https://user-images.githubusercontent.com/37310063/100001135-6d335f80-2da1-11eb-8f20-7b91b5202dd3.png)

But the error message is not timed. Behavior is different from that observed in the GUI login.

Tested in **v0.5.0-rc.2**.

**Comment by bizetti** [comment]
It won't be fixed.
