### ISSUE TITLE
[import] modal dialog illegible

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1777]
![janela modal](https://user-images.githubusercontent.com/37310063/96311742-8f86d000-0fe0-11eb-9cf9-86bf49bea8c7.png)

Affected baseline: **v0.4.4-rc.1**

**Note**: the problem does not happen in Mozilla Firefox

![image](https://user-images.githubusercontent.com/37310063/96595447-0f06ee80-12c2-11eb-9ccf-a8bc2a5b67e2.png)

**Comment by bizetti** [comment]
0.4.4 rc2 and 0.5.0. rc2

**Comment by FrancielePessi** [comment]
Error does not happen in version 0.5.0. rc2 (Google Chrome)

![Captura de tela de 2020-11-25 12-28-46.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/6584dece-8b09-4ff8-b481-dbdcddc44fba)
