### ISSUE TITLE
[dashboard ] The page breaks when a json attribute is selected

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1778]
In a table chart, a json attribute was selected.
The dashboard page breaks and you cannot remove this setting.

![image](https://user-images.githubusercontent.com/37310063/96496651-de6e7880-121f-11eb-99b6-a6ea64436c43.png)

Affected baseline: **v0.5.0-alpha.4**

**Comment by bizetti** [comment]
0.4.4 rc2 and 0.5.0. rc2

**Comment by betefaber** [comment]
Fixed in **v0.5.0-rc.2**.

![image](https://user-images.githubusercontent.com/37310063/100007636-1b8fd280-2dab-11eb-8ac3-e341888d8708.png)
