### ISSUE TITLE
[docker-compose] Flow Broker log file size

### ISSUE THREAD

**Issue by andersonluisribeiro** [dojot/dojot#1780]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Flow Broker log file size has no limit

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Deploy dojot;
Use dojot to create flowbroker logs
See that the log file grows without limits

* **What is the expected behavior?**
The log file must be at most 100MB.

* **What is the motivation / use case for changing the behavior?**
We had a problem in an environment whose log file grew to 52GB

* **Please tell us about your environment:**
  
  - Version: 0.2.x
  - Environment: [kubernetes, docker-compose, standalone]
  - Operating system: [Ubuntu 16.04, Fedora 28, Ubuntu on VirtualBox (Windows 10), etc.]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by betefaber** [comment]
@andersonluisribeiro, may be related to issue #1133?

**Comment by andersonluisribeiro** [comment]
Hi @betefaber, the issue with this ticket is related to the size of the log file, not the content being logged. I believe they are different issues.

**Comment by betefaber** [comment]
Test OK.
