### ISSUE TITLE
[v0.5.0-rc.1] Attempting to inject SQL code resulted in authentication failure.

### ISSUE THREAD

**Issue by thiagodpf** [dojot/dojot#1782]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

Report a security breach

* **What is the current behavior?**

When inserting a piece of SQL code in the Password field, the system experiences an unexpected failure.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

- In the GUI, access the user authentication form;
- In the field for the user name, enter any valid name, it does not have to be a name registered with the database, but only that meets the validation criteria of the field, that is, only letters and numbers;
- In the field for the user's password, insert the following SQL code snippet: `" or ""="`
- Submit the values to the server;
- The error message displayed will be: `Call failed`

* **What is the expected behavior?**

The message `Call failed` appears to be issued when an unexpected error occurs, but if the field was protected against SQL Injection, the correct message should be: `User not found or incorrect password`.

It is necessary to investigate if there is a SQL injection vulnerability in this field;

If the problem occurs before the operation reaches the database, it is necessary to investigate whether any special characters should be escaped.

* **What is the motivation / use case for changing the behavior?**

This appears to be a security breach

* **Please tell us about your environment:**
  
  - Version: v0.5.0-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

![image](https://user-images.githubusercontent.com/28706165/96754964-713a1f00-13a8-11eb-91da-80a64cedf6ca.png)

**Comment by mprevide** [comment]
@thiagodpf 

Try this through the api and see the auth logs.
I think the call failed because the auth threw an error ...

**Comment by FrancielePessi** [comment]
![Seleção_004](https://user-images.githubusercontent.com/52173618/170362714-c69ea62c-d5ab-46f3-a352-5cde1b38dd1c.png)
