### ISSUE TITLE
[gui] Pin aggregator includes all tracking pins

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1798]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When you have some moving devices, activate tracking in one or more, sufficiently zoom out to aggregate them in a single pin and you click in this pin, it will show all the tracking pins.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create some moving devices and activate tracking in one or more of them:
![img1](https://user-images.githubusercontent.com/12804963/96887845-5b396680-145b-11eb-85e5-ff62e51b47ff.png)
Zoom out until the pins are agglutinated in only one:
![img2](https://user-images.githubusercontent.com/12804963/96887943-7906cb80-145b-11eb-8020-ff7760b3ea73.png)
When clicking in the agglutinated pin, all pins are shown, even all the tracking ones:
![img3](https://user-images.githubusercontent.com/12804963/96887948-7a37f880-145b-11eb-841a-7df5935d2b0f.png)

If you are sending data and click in the agglutinated pin, it will close if any of the devices receive a message.
This problem happens in both Map and Satellite views.

* **What is the expected behavior?**
I think it must aggregate all the tracking pins in only one (for each device that the tracking is active).

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: the images are from v0.5.0-rc.1, but it also happens in v0.4.4-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
Ticket analysis (23rd, October): It has to be fixed, but later.

**Comment by cfrancisco** [comment]
The tracking schema was disabled.
