### ISSUE TITLE
[gui] Better error handling in device manipulation when DeviceManager is not accessible

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1808]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?** 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
All of the steps must be done after removing the DeviceManager from the environment (docker-compose down device-manager). To reproduce the problems with the devices, you must be in the Devices page, otherwise you will get a blank page:
![after removing device manager](https://user-images.githubusercontent.com/12804963/97045470-2e18b100-154c-11eb-80f8-449c6dbf5f5f.png)
The displayed message is not informative.

**Creating a device**
Add the name and a template in the device
![img1](https://user-images.githubusercontent.com/12804963/97044758-f3fadf80-154a-11eb-93de-4109eccd92af.png)
When creating the device, the displayed message is not informative.
![img2](https://user-images.githubusercontent.com/12804963/97044763-f4937600-154a-11eb-9af6-1b29dea5de3a.png)

**Removing a device**
Select an already created device:
![img1](https://user-images.githubusercontent.com/12804963/97046486-d7ac7200-154d-11eb-952c-3e3b7e261492.png)
Remove it:
![img2](https://user-images.githubusercontent.com/12804963/97046510-ded38000-154d-11eb-8b61-4b6ba8e777ba.png)
There is no message displayed after the confirmation:
![img3](https://user-images.githubusercontent.com/12804963/97046537-e8f57e80-154d-11eb-8a43-1224b812026d.png)
If you click in any device or try to add another device, the confirmation modal appears again:
![img4](https://user-images.githubusercontent.com/12804963/97046541-ed219c00-154d-11eb-9488-1ff37a3df2aa.png)

**Modifying a device**
Select a device:
![img1](https://user-images.githubusercontent.com/12804963/97047413-4f2ed100-154f-11eb-9064-13d556099926.png)
Change an attribute (e.g. name):
![img2](https://user-images.githubusercontent.com/12804963/97047424-50f89480-154f-11eb-837a-9980b89731e8.png)
No message is displayed after saving:
![img3](https://user-images.githubusercontent.com/12804963/97047429-52c25800-154f-11eb-9999-5fd60a484b02.png)

**Filtering devices**
Search for some device:
![img1](https://user-images.githubusercontent.com/12804963/97168864-eb332500-1767-11eb-8f2c-1e54f438432c.png)
As in the other cases, the messages are not much informative:
![img2](https://user-images.githubusercontent.com/12804963/97168869-ec645200-1767-11eb-9263-927c9b3e9e82.png)
It is also worthy noting that the "Filtrando" message is showing under the "Dispositivos" title, even after closing the filtering bar.

* **What is the expected behavior?**
Show a more informative message and, in some of the cases, show a message. 

* **What is the motivation / use case for changing the behavior?**
If for some reason the DeviceManager is not accessible, the user will not understand what happened, why the device was not modified/created/removed.

* **Please tell us about your environment:**
  
  - Version: v0.5.0-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by FrancielePessi** [comment]
When stopping the device manager, the creation of the template and device are not available and the reproduced message is more informative.

![Captura de tela de 2021-04-15 15-37-02.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/f1769b39-37a1-4c36-b0a1-da8671eb610a)
