### ISSUE TITLE
[gui] Notification date is not correctly shown after refreshing the page

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1810]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create a flow that sends a notification
2. Make the flow send at least one notification
3. Go to the **Notifications** page:
![img1](https://user-images.githubusercontent.com/12804963/97183062-0f006600-177c-11eb-8d0d-44909eefd043.png)
4. Refresh one or more times. You'll get the following:
![img2](https://user-images.githubusercontent.com/12804963/97183067-10319300-177c-11eb-814d-c218605c2464.png)

I tried refreshing by pressing `F5` and `Ctrl+F5` too, to check if it would correct the visualization, but it did not.

* **What is the expected behavior?**
The date should be correctly displayed at all times.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: v0.5.0-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by betefaber** [comment]
**Note**: Problem still occurs in release v0.5.0

**Comment by FrancielePessi** [comment]
Error does not repeat in version v0.6.0-rc.2 (Docker-compose)

![Captura de tela de 2021-03-31 19-11-07.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/162af494-de1c-4ab8-9248-213c3947f87d)
