### ISSUE TITLE
[GUI] Error when changing the device template, from a "firmware update template" to any other template

### ISSUE THREAD

**Issue by thiagodpf** [dojot/dojot#1815]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

report a bug

* **What is the current behavior?**

In the GUI, when I want to change the template of an existing device, this template being characteristic of _Firmware Update_, the update happens, but the GUI fails to render the screen, leaving it all empty.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

- Create a template for the LwM2M Firmware Update;
- Create a device and associate the newly created template with the device;
- After the device is created, try to change the template of the device (remembering that the current template needs to be a template with firmware update metadata);
- The update is successful, but the GUI does not seem to know how to render the screen correctly and everything disappears;
- If I reload the page (F5), everything goes back to normal, with the device having the new template;

![image](https://user-images.githubusercontent.com/28706165/97335132-3d557280-185c-11eb-94f1-95e5c48c9da8.png)

* **What is the expected behavior?**

It is expected that the GUI will be rendered correctly after changing the template on the device.

* **What is the motivation / use case for changing the behavior?**

There is no practical use case for changing the device's firmware update template, but this is an error in the GUI, as everything disappears after confirming the templates change.

* **Please tell us about your environment:**
  
  - Version: 0.5.0-rc1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

---

Template with firmware update metadata, currently associated with the device:
![image](https://user-images.githubusercontent.com/28706165/97335877-1b102480-185d-11eb-869a-dd464d7d4c74.png)

---

![image](https://user-images.githubusercontent.com/28706165/97335987-3f6c0100-185d-11eb-8b0f-598ffc6449f8.png)

---

When trying to change the current template for any template (there is no need for firmware update metadata), an error occurs:
![image](https://user-images.githubusercontent.com/28706165/97336190-7e01bb80-185d-11eb-91f6-67ceb75549b1.png)

---

![image](https://user-images.githubusercontent.com/28706165/97336280-97a30300-185d-11eb-9301-2bfd98ea5ef2.png)

---

The screen is completely empty:
![image](https://user-images.githubusercontent.com/28706165/97336324-a5f11f00-185d-11eb-84e8-ae601819c912.png)

**Comment by FrancielePessi** [comment]
Error does not persist in version 0.6.0-rc2 (Docker-compose)

![Captura de tela de 2021-03-31 19-54-25.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/f65a1f95-30e2-41f5-8463-1a07ff1f293d)

![Captura de tela de 2021-03-31 19-55-12.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/91531009-f387-402a-9df9-d5bb3d4f70a8)

![Captura de tela de 2021-03-31 19-58-17.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/c46d7e54-088e-45b0-b52d-e9b1b54b173d)

![Captura de tela de 2021-03-31 19-57-02.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/ab1ad7a2-a690-4cc1-8767-22165fc2a1eb)
