### ISSUE TITLE
[GUI] Firmware Update - After selecting the image for transfer, the action buttons on the screen are not enabled and no guidance is given to the user

### ISSUE THREAD

**Issue by thiagodpf** [dojot/dojot#1818]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

After selecting the image for transfer, the action buttons on the screen are not enabled and no guidance is given to the user.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

![image](https://user-images.githubusercontent.com/28706165/97466713-2b3e0780-1922-11eb-90f7-f1a1c5f12c1c.png)

* **What is the expected behavior?**

It is expected that the screen action buttons will be enabled when selecting the image to be transferred to the device.

* **What is the motivation / use case for changing the behavior?**

The functionality does not seem to be working properly.

* **Please tell us about your environment:**
  
  - Version: 0.5.0-rc1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by FrancielePessi** [comment]
Error does not persist in version 0.5.0 rc.2  - Docker Compose

![Captura de tela de 2020-11-27 11-53-02.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/7e37e0d8-738d-4424-841b-0a8b8b17ce54)
