### ISSUE TITLE
[gui] Empty static notification message is accepted

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1821]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create the following flow:
![img1](https://user-images.githubusercontent.com/12804963/97741037-e8666600-1ac0-11eb-8ef8-132a6f61f52d.png)
![img2](https://user-images.githubusercontent.com/12804963/97741042-e9979300-1ac0-11eb-9c9d-b4c9d73f8b8f.png)
![img3](https://user-images.githubusercontent.com/12804963/97741047-ea302980-1ac0-11eb-9028-f77989677de7.png) 
![img4](https://user-images.githubusercontent.com/12804963/97741050-ea302980-1ac0-11eb-9a9a-adb0a4637b34.png)

As you can see, the Value for the static notification message is empty. You can freely save it, but this flow will not generate a notification, since it does not have a message. Flowbroker returns this error in the flow execution:
```
|notification -- ERROR: Error while executing notification node: Error: Message must be defined.
```

Note that it happens with the dynamic message too. I left the `payload.message` empty so you can test it, but in this case there is nothing that can be done, since this can be impossible to predict whether the parameter is empty or not in the flow building time.

* **What is the expected behavior?**
Prevent the user from saving the node if it does not provide some value to the static message.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: v0.5.0-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
It will not be implemented.
