### ISSUE TITLE
[gui] JSON object in notification metadata parameter is shown as "undefined"

### ISSUE THREAD

**Issue by eduardogmisiuk** [dojot/dojot#1822]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Configure this flow:
![img1](https://user-images.githubusercontent.com/12804963/97752686-456b1780-1ad3-11eb-926f-700e14f22f60.png)
![img2](https://user-images.githubusercontent.com/12804963/97752690-469c4480-1ad3-11eb-9c69-671d4bc2ff29.png)
![img3](https://user-images.githubusercontent.com/12804963/97752691-469c4480-1ad3-11eb-9344-f32009f8a061.png)
![img4](https://user-images.githubusercontent.com/12804963/97752692-4734db00-1ad3-11eb-9e41-c6db5fb0dc26.png)

Then generate a notification by sending a message to the configured device. The notification will be:
![img5](https://user-images.githubusercontent.com/12804963/97752694-47cd7180-1ad3-11eb-81c6-ddd8a13e60ed.png)

* **What is the expected behavior?**
This is open to analysis. Should the GUI show the JSON? Should it refuse JSON in this case?

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: v0.5.0-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
If the value is an object, use json stringify

**Comment by FrancielePessi** [comment]
Test performed in version v0.6.0-rc.3

![Captura de tela de 2021-04-23 16-30-56.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/89d0be9b-3af4-49f1-bf95-8f9723bb7032)
