### ISSUE TITLE
[Auth] improve error message when creating a new permission using a duplicate name value 

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1829]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

today its returned the error code 500 and the http message: "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or
	there is an error in the application"

* **What is the expected behavior?**
it could be fine improve this message saying what really happens.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.5.0 rc1
  - Environment: [kubernetes]
  - Operating system: [Ubuntu 18.04]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
It will not be fixed. Auth is gonna be changed by keycloak.
