### ISSUE TITLE
Dynamically change the service log level

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1838]
The endpoint to dynamically change a service log level should not be exposed through the API Gateway.

- **history**: the endpoint is exposed
```
curl -X GET ${DOJOT_HOST}/history/log -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json"
{
  "log_level": "DEBUG"
}
```

- **persister**: the endpoint is not exposed
```
curl -X GET ${DOJOT_HOST}/persister/log -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json"   
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.15.7</center>
</body>
</html>
```
- Check if in other services the endpoint is exposed

Baseline affected: **v0.5.0-rc.1**

**Comment by betefaber** [comment]
#1516

**Comment by rascaraficci** [comment]
Analysed: It would be nice to fix to defendu release.

**Comment by bizetti** [comment]
I won't be fixed. History service will be deprecated.
