### ISSUE TITLE
iotagent is changing device model in Orion when sending updates

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#184]
When iotagent sends an update to Orion (in particular), all previous data about the updated device is lost (including other attributes).

How to repeat:
- Create a device based on a template with more than one attribute
- Send an update using iotagent containing only one attribute
- Check in Orion that the device has now only the updated attribute.

Furthermore, it also changes the attribute type. For geo:point attributes this is particular important as it changes to 'Text'.

It is not clear who's should be held responsible for this - maybe Orion?

**Comment by mmagr** [comment]
As dojot's component selection and architecture has already moved past using orion as a context broker, I'm closing this.
