### ISSUE TITLE
[dashboard] The behavior between the fields is different

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1864]
The `Value` and `No. Records` fields do not accept negative values. But the behavior between the fields is different.

- **Value**: the minimum value is zero

- **Nº Records**: the value below zero is "1"

**Step to reproduce the problem**:

1. click on the down arrow in the 2 fields

![Screenshot_32](https://user-images.githubusercontent.com/37310063/100006575-758f9880-2da9-11eb-8dbb-02a10fa40c6a.png)

Affected baseline: v0.5.0-rc.2

**Comment by bizetti** [comment]
Valid values: from 1 to N; not from 0 to N.

**Comment by FrancielePessi** [comment]
![Captura de tela de 2021-08-17 15-55-22.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/85598d20-3e02-46be-9f92-5827cf79ec70)

Version: v0.7.0-rc.3
Environment: [kubernetes, docker-compose]
Operating system: [Ubuntu 18.04]
