### ISSUE TITLE
[GUI] Firmware Update - automatic firmware update states are not updated in the GUI in real time

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1886]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Automatic firmware update states are not updated in the GUI

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
The automatic firmware update information should be updated in real time.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.5.0-rc.2
  - Environment: k8s17
  - Operating system: Ubuntu 20.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rascaraficci** [comment]
Analysed: Waiting for a client's demand to handle this issue.

**Comment by cfrancisco** [comment]
It will no longer be prioritized.
