### ISSUE TITLE
[GUI] Notifications page is not accessible

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1903]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Notifications page is not accessible

![notificacoes1](https://user-images.githubusercontent.com/37310063/102380781-19cebe80-3fa7-11eb-909a-090c1d157ebf.jpg)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
click on the notifications menu item

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.5.1-rc.1
  - Environment: docker-compose (with influxDB and without persister-history)
  - Operating system: Ubuntu 20.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mprevide** [comment]
The notification has not been migrated to influxDB and probably will not.

In the details of the devices, it is not possible to see influxdb data, only the history for now.

**Comment by betefaber** [comment]
The solution is the coexistence of services.
