### ISSUE TITLE
Different behavior between timeseries DB and history

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1907]
The behavior of services is different.

- device does not exist
```
curl -X GET "${DOJOT_HOST}/tss/v1/devices/abcdef/data" -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 
{
  "data": [],
  "paging": {
    "previous": null,
    "current": {
      "number": 1,
      "url": "/tss/v1/devices/abcdef/data?page=1&limit=256&order=desc&dateTo=2020-12-21T12%3A34%3A13.030Z"
    },
    "next": null
  }
}


curl -X GET "${DOJOT_HOST}/history/device/abcdef/history" -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json'
{
  "title": "Device not found",
  "description": "No data for the given device could be found"
}
```

- attribute does not exist

`export DEVICE_ID=e9627c`
```
curl -X GET "${DOJOT_HOST}/tss/v1/devices/${DEVICE_ID}/attrs/int/data" -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 
{
  "data": [],
  "paging": {
    "previous": null,
    "current": {
      "number": 1,
      "url": "/tss/v1/devices/e9627c/attrs/int/data?page=1&limit=256&order=desc&dateTo=2020-12-21T12%3A35%3A10.647Z"
    },
    "next": null
  }
}

curl -X GET "${DOJOT_HOST}/history/device/${DEVICE_ID}/history?attr=int" -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 
{
  "title": "Attr not found",
  "description": "No data for the given attribute could be found"
}
```

  - Version: 0.5.1-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 20.04

**Comment by rascaraficci** [comment]
I think we should differentiate between `resource doesn't exist` and `no data`. To do this in the retriever service, we could check whether the bucket corresponding to the device exists or not.

**Comment by betefaber** [comment]
Test OK
**influxdb-retriever:**

- device does not exist: returns an error code **404**

![retriever-devicenaoexiste](https://user-images.githubusercontent.com/37310063/164317345-87225cd5-5507-49b7-9180-46f1d8c3a28d.png)


- device exists but no data: returns a code **200** with an empty array in the payload.

![retriever-nodata](https://user-images.githubusercontent.com/37310063/164317321-1605e5ef-0a46-4e8f-9133-bbfb4b7e1c58.png)


**history:**

- device does not exist: returns an error code **404**

![history-devicenaoexiste](https://user-images.githubusercontent.com/37310063/164317343-326aa48c-852d-4ebf-8df3-16283b44c0fd.png)

- device exists but no data: returns a code **200** with an empty array in the payload.

![history-nodata](https://user-images.githubusercontent.com/37310063/164317341-1ad75da1-4211-46ed-a0df-988dffe11fe7.png)
