### ISSUE TITLE
[k8s] Change the Kubernetes Container Runtime

### ISSUE THREAD

**Issue by andersonluisribeiro** [dojot/dojot#1918]
Kubernetes is deprecating Docker as a container runtime after v1.20. When Docker runtime support is removed in a future release (currently planned for the 1.22 release in late 2021) of Kubernetes it will no longer be supported and you will need to switch to one of the other compliant container runtimes.

https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker

**Comment by rascaraficci** [comment]
Analysed: It's necessary a discussion as soon as possible.

**Comment by danielapetito** [comment]
studing containerd and migration in K8S/ansible

**Comment by danielapetito** [comment]
Criado PR com alteração.

1. Para migração seguido o site: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd

2. Conforme site oficial Kubernetes obtido pacote containerd do repositório oficial da Docker.
    A última versão do repositório é a 1.4.6-1 (estamos utilizando essa versão)

3. Para migração do docker runtime para o containerd runtime foi necessário alterar a role k8s-cluster do playbook

4. Na execução do playbook label.yaml foi necessário:
 - alterar o hosts.yaml e definir a variável ansible_python_interpreter: /usr/bin/python3 para master_host

**Comment by danielapetito** [comment]
como não temos mais o docker instalado, para verificar imagens, informações do container utilizar o comando **ctr**

obrigatório uso do  namespace (--namespace k8s.io)

exemplos:
 -- sudo ctr --namespace k8s.io images ls
 -- sudo ctr --namespace k8s.io containers ls
