### ISSUE TITLE
Security - Rampup - Keycloak, OpenID Connect, OAuth and others

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1927]

**Comment by thiagodpf** [comment]
Study material:

Course about OAuth2:
https://www.udemy.com/course/oauth-2-simplified/

Course about OpenID Connect:
https://www.udemy.com/course/openid-connect/

OAuth2 book:
https://oauth2simplified.com/

OAuth2 community site:
https://oauth.net/

OktaDev youtube channel:
https://www.youtube.com/channel/UC5AMiWqFVFxF1q9Ya1FuZ_Q


KeyCloak documentation:
https://www.keycloak.org/documentation
