### ISSUE TITLE
Mutual authentication and Safe Channel - Replace Cassandra by something lighter

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#196]

**Comment by mmagr** [comment]
Apparently, cassandra is used for things other than logging:
- In the [service registry](https://github.com/dojot/ma-serviceregistry/blob/master/Java/ServiceRegistry/ServiceRegistry-ejb/src/main/java/br/com/dojot/mutualauthentication/serviceregistry/dao/impl/RegistryDAOBean.java), it is used as the main data store
