### ISSUE TITLE
[FW Update][GUI] Label has not been translated

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1965]
The label has not been translated into Portuguese.

**Steps to reproduce the problem:**

- click `Transfer image to device`

> - pt-br

![Captura de tela de 2021-01-22 14-09-56](https://user-images.githubusercontent.com/37310063/106274598-45360180-6213-11eb-95d4-ae819fc4d4fc.png)

> - en

![Captura de tela de 2021-01-22 14-08-22](https://user-images.githubusercontent.com/37310063/106274637-52eb8700-6213-11eb-87b6-03fcb2e92125.png)

- click `Apply image update`

> - pt-br

![Captura de tela de 2021-01-22 14-10-12](https://user-images.githubusercontent.com/37310063/106274631-5121c380-6213-11eb-9129-b834890666a3.png)

> - en

![Captura de tela de 2021-01-22 14-08-36](https://user-images.githubusercontent.com/37310063/106274649-554de100-6213-11eb-8539-f54838b9aef8.png)

- click `Set device to 'On Hold'`

- pt-br

![Captura de tela de 2021-01-22 14-10-27](https://user-images.githubusercontent.com/37310063/106274642-53841d80-6213-11eb-8748-0db8f745d483.png)

- en

![Captura de tela de 2021-01-22 14-08-52](https://user-images.githubusercontent.com/37310063/106274648-54b54a80-6213-11eb-83ce-344173625d54.png)

- Version: 0.5.2-rc.1
- Environment: k8s17
- Operating system: Ubuntu 20.04

**Comment by rascaraficci** [comment]
Analysed. It should be handled in the future.

**Comment by cfrancisco** [comment]
It will no longer be prioritized.
