### ISSUE TITLE
Integration of keycloak with kong in dojot

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1986]
- [x] Better understanding of what had already been done
- [x] Update kong-plugin-jwt-keycloak plugin to work with various realms 
  - [x] Better documentation of above processes and examples 
- [x] Integrating the keycloak with a backstage and a React APP
  - [x] Example  
  - [x] Documentation  
- [x] Create configuration from old auth in keycloak (wip @mprevide )
- [x] Check services that use the jwt internally, for example, to get tenant or access a service through kong.   (wip @mprevide )
- [x] Library publications removing auth dependency (These changes already exist, just check if they are ok with what we need before publishing) (wip @mprevide )
- [x] Update services that depend on libraries  (wip @mprevide )
- [x] Partial integration with dojot docker-compose without backstages   (wip @mprevide )
- [x] Plugin for the keycloak that creates default settings for new tenants  (wip @thiagodpf )
- [x] Set min and max size and alphanumeric for realms name (maybe in the keycloak plugin)  (wip @thiagodpf )
- [x] ` Valid Redirect URIs`,  on client gui and kong are set to http://localhost:8000/*, they must change according to the deployment. Use env variable in the keycloak plugin? any regex in place of localhost? is this safe? (wip @thiagodpf )
- [x] Facilitate pass the domain and if it is http or https for the keycloak and the backstage (@mprevide/@thiagodpf )
- [x] Facilitate SMTP configuration (perhaps already defined environment variables) and explained (@thiagodpf )
- [x] Password Policies (wip @thiagodpf/@mprevide )
- [x] Plugin keycloak: import: rememberMe, defaultSignatureAlgorithm, rememberMe, bruteForceProtected, resetPasswordAllowed, passwordPolicy.   (wip @thiagodpf )
- [x] Plugin keycloak: Password Policies: Copy blacklist (wip @thiagodpf )
- [x] Integration details such as: default users and passwords, super admin and other domains, etc    (wip @thiagodpf/@mprevide )
- [x] These account management link where  can change name, email, activate 2 factor, it is not explicit anywhere, create link in the gui generated by the backstage http://localhost:8000/auth/realms/admin/account ? @mprevide
- [x] Test with compose parcial domains other than localhost and https (@mprevide)
- [x] Documentation https for docker-compose case
- [x] Test with domains other than localhost and https
- [x] GUI - Multi-realm (choose tenant in home) @luisfelipefurlan  @cfrancisco 
- [x] Tests with nginx in front  (proxy issues with keycloak)  - wip @mprevide
- [x] Final integration with dojot GUI and backstage @luisfelipefurlan  @cfrancisco 
- [ ] Customize screen login keycloak
- [ ] Codecept  (tests)  change the way to get jwt and remove old tests to profile, users.. etc https://github.com/dojot/tests/pull/21
- [ ] Api Tests  - change the way to get jwt and remove old tests to profile, users.. etc https://github.com/dojot/tests/pull/22
- [ ] Tracking-simulator change the way to get jwt
- [x] Final integration with dojot docker-compose   - wip @mprevide
- [ ] Final integration with dojot ansible (Pay attention to the initialization of the keycloak, perhaps adding an init container to check if postgres is ok. Or make sure that the keycloak tries to restart if postgres is not ok.) and check https://github.com/dojot/dojot/tree/feature/iam-keycloak/iam/keycloak#how-to-use-keycloak-with-a-nginx-proxy
- [x] Documentation in readthedocs: explaining how to access and some basic keycloak things, how enable use by cli, headers to use, put in documentation the link to manage the realm itself is also not explicit, it is http://localhost:8000/auth/admin/admin/console, etc  - wip @mprevide
- [ ] Cron service (https://github.com/dojot/cron/pull/43#issuecomment-852143882)
- [ ]  Block access to the realm master's admin panel, release only on localhost
- [x]  Force redirect when accessing via http to https except Well-Known endpoint
- [x]  Document how to use self-generated certificate (like taking and adding in browser) to avoid using http

Activities to be analyzed or for the future:

- [ ] Add vault for passwords
- [ ] Change the kong plugin to add tenant to the header ??
- [ ] Change olds libs to just consume tenants from kafka not consulting in keycloak excluding the need to receive the master's login and password 
- [ ] Improvements on backstage for cookie-hijacking:   Regenerate the Session ID After Login, Perform Secondary Checks (ip),  Change the Cookie Value  ?
- [ ] Backstage:   in the querystring parameter in addition to the error add errorCode ? 
- [ ] Change to  plugin kong acme  (https://docs.konghq.com/hub/kong-inc/acme/) ? 
- [ ] Backstage: put a list of accepted return URLs
- [ ] Accept and license message maybe on the login screen from keycloak ?
- [ ] Migration doc  from auth to keycloak
- [ ] Subdomains as tenant
- [ ]  Dojot training update libs and how get JWT

**Comment by mprevide** [comment]
List about where jwt is used or created (WIP):
 
 - Where obtained a JWT
	- [ ] Locust
	- [ ] iotagent-leshan
	- [ ] tracking-simulator
	- [ ] kafka-ws example with dojot
	- [ ] Cron
	- [ ] Loopback
	- [ ] certreq
	- [ ] ...
 - Where get the tenant by JWT
 	- [ ] Influx-Retriever
 	- [ ] Kakfa-ws
 	- [ ] Cron 
 	- [ ] SDK
 	- [ ] History
 	- [ ] Image Manager
 	- [ ] ...
 - Where created a JWT
 	- [ ] SDK
 	- [ ] flow - cron-batch, orchestrator/auth.js
 	- [ ] data-broker - DeviceCache
 	- [ ] DeviceManager/KafkaNotifier.py
 	- [ ] dojot/dojot-module-nodejs, dojot-module-java, all libs
 	- [ ] ...

- [ ] Tutorials with how to get token (nodes flow, etc)

**Comment by mprevide** [comment]
https://github.com/dojot/dojot/issues/1482

**Comment by mprevide** [comment]
#1531

**Comment by mprevide** [comment]
TODO: dojot/dojot#1982

https://github.com/dojot/backstage/pull/89 create this pr to feature/keycloak

**Comment by mprevide** [comment]
TODO: dojot/dojot#2096



https://github.com/dojot/backstage/pull/95 create this pr to feature/keycloak

**Comment by mprevide** [comment]
#2110

**Comment by mprevide** [comment]
https://docs.google.com/document/d/1hUvMOp3Rp3fOWojmLLBwzVvA_caQoodNIAYAiueapCg/edit#heading=h.senyci6jluhd

**Comment by mprevide** [comment]
https://docs.google.com/document/d/1zMz86KCOydNxHbOMMgrswP8MxUNUQBZY8YcFEwtf12A/edit

**Comment by mprevide** [comment]
https://docs.google.com/document/d/1EzvrzOfPHAAsti1oyOr0-fNxzP_5HdHStpOlkrYYPCI/edit?usp=sharing

**Comment by mprevide** [comment]
Branches where the end codes are:

https://github.com/dojot/dojot/tree/feature/keycloak
https://github.com/dojot/data-broker/tree/feature/keycloak
https://github.com/dojot/iotagent-leshan/tree/feature/keycloak
https://github.com/dojot/image-manager/pull/59
https://github.com/dojot/device-manager/pull/185
https://github.com/dojot/dojot/tree/feature/api-gateway-kong
https://github.com/dojot/flowbroker/tree/feature/keycloak
https://github.com/dojot/iotagent-mosca/tree/feature/keycloak
https://github.com/dojot/backstage/tree/feature/keycloak
https://github.com/dojot/cron/tree/feature/keycloak
https://github.com/dojot/docker-compose/tree/feature/keycloak
https://github.com/dojot/history/tree/feature/keycloak

Documentation:

https://github.com/dojot/docs/tree/feature/keycloak
https://docs.google.com/document/d/1hUvMOp3Rp3fOWojmLLBwzVvA_caQoodNIAYAiueapCg/edit#heading=h.senyci6jluhd

Auto Tests:

- Codecept Test: I just made changes so that flowbasic (npm run test:flowbasic) works with keycloak, the other things didn't test and didn't change. I know that everything that uses JWT will no longer work, since JWT will no longer be in the browser. https://github.com/dojot/tests/tree/feature/codecepct_keycloak_flowbasic (Consider for the test the user admin, with password Dojot@2021 in tenant/realm admin, the password could be in the variable file and passed by environment variables.)
- Python Test: The main idea of this PR is to change how the JWT is obtained and put a README. It may not be merged, just copy the ideas that are interesting.  https://github.com/dojot/tests/tree/feature/keycloak_python

**Comment by mprevide** [comment]
The old libraries have been changed to use keycloak:

- https://github.com/dojot/dojot-module-python - Since v2.0
- https://github.com/dojot/iotagent-java - Since v2.0
-  https://github.com/dojot/dojot-module-java - Since v2.0
- https://github.com/dojot/dojot-module-nodejs  - Since v0.2
- https://github.com/dojot/iotagent-nodejs  - Since v3.0

**Comment by mprevide** [comment]
# Microservices: 

## Branches where the end codes are and has code changes:

- https://github.com/dojot/dojot/tree/feature/keycloak
- https://github.com/dojot/data-broker/tree/feature/keycloak
- https://github.com/dojot/iotagent-leshan/tree/feature/keycloak
- https://github.com/dojot/image-manager/tree/feature/keycloak
- https://github.com/dojot/device-manager/tree/feature/keycloak
- https://github.com/dojot/dojot/tree/feature/api-gateway-kong
- https://github.com/dojot/flowbroker/tree/feature/keycloak
- https://github.com/dojot/iotagent-mosca/tree/feature/keycloak
- https://github.com/dojot/backstage/tree/feature/keycloak
- https://github.com/dojot/cron/tree/feature/keycloak
- https://github.com/dojot/history/tree/feature/keycloak
- **For those services that have not changed, the tag v0.7.0-rc.1 was used to perform the tests.**

## Docker-compose

 - https://github.com/dojot/docker-compose/tree/feature/keycloak (docker-compose  - In the part of creation self signed certificate, the code used to gereate the certs is in https://github.com/dojot/dojot/tree/feature/certgen-self-rsa/tools/certgen)

## Documentation

https://github.com/dojot/docs/tree/feature/keycloak
https://docs.google.com/document/d/1hUvMOp3Rp3fOWojmLLBwzVvA_caQoodNIAYAiueapCg/edit#heading=h.senyci6jluhd

## Automated tests:

- Codecept Test: I just made changes so that flowbasic (npm run test:flowbasic) works with keycloak, the other things didn't test and didn't change. I know that everything that uses JWT will no longer work, since JWT will no longer be in the browser. https://github.com/dojot/tests/tree/feature/codecepct_keycloak_flowbasic (Consider for the test the user admin, with password Dojot@2021 in tenant/realm admin, the password could be in the variable file and passed by environment variables.)
- Python Test: The main idea of this PR is to change how the JWT is obtained and put a README. It may not be merged, just copy the ideas that are interesting.  https://github.com/dojot/tests/tree/feature/keycloak_python

**Comment by mprevide** [comment]
Overview -  Keycloak in dojot: https://docs.google.com/document/d/1Az-whb4MZEJVcbOOXx19ljC5uFTcOxNxoIXq9e1j2Uw/edit#

**Comment by bizetti** [comment]
It's postponed.
