### ISSUE TITLE
Cron service fails to start

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#1988]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
An invalid job can be added to the database which causes the service to crash if restarted.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create a job with an invalid cron time like "0 /5 * * * *"
2. Restart the service

* **What is the expected behavior?**
If the cron job is invalid which shouldn't be added to the database.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.5.2
  - Environment: docker-compose
  - Operating system: Ubuntu

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

<14:55:11 22/02/2021> -- INFO: Read-only channel for tenancy events was created.
<14:55:11 22/02/2021> -- INFO: Created collection jobs into database cron_admin.
<14:55:11 22/02/2021> -- |messenger -- INFO: already have a topic for dojot.tenancy@dojot-management
<14:55:11 22/02/2021> -- INFO: Succeeded to set up cron job 85b744cf-ad33-4593-be61-855a506d3f87 with spec {"time":"*/5 * * * *","timezone":"America/Sao_Paulo","name":"Keep alive","description":"This job sends a keep alive notification to a device every 5 minutes","http":null,"broker":{"subject":"dojot.device-manager.device","message":{"event":"configure","data":{"attrs":{"message":"keepalive"},"id":"71e60a"},"meta":{"service":"admin"}}},"jscode":null}.
<14:55:11 22/02/2021> -- INFO: Succeeded to set up cron job 267e3311-17d5-4107-a128-2e9d11da679a with spec {"time":"* 5 * * * *","timezone":"America/Sao_Paulo","name":"Keep alive","description":"This job sends a keep alive notification to a device every 5 minutes","http":null,"broker":{"subject":"dojot.device-manager.device","message":{"event":"configure","data":{"attrs":{"message":"keepalive"},"id":"2f8e6f"},"meta":{"service":"admin"}}},"jscode":null}.
<14:55:11 22/02/2021> -- ERROR: Failed to set up cron job 198fc2b6-ee0b-4861-bafb-930dc2fc18f3 with spec {"time":"0 /5 * * * *","timezone":"America/Sao_Paulo","name":"Keep alive","description":"This job sends a keep alive notification to a device every 5 minutes","http":null,"broker":{"subject":"dojot.device-manager.device","message":{"event":"configure","data":{"attrs":{"message":"keepalive"},"id":"dfd92d"},"meta":{"service":"admin"}}},"jscode":null} (Error: Field (/5) cannot be parsed).
<14:55:11 22/02/2021> -- INFO: Succeeded to set up cron job 8922073b-c8c3-49e5-a8a1-50d642aab4e2 with spec {"time":"0 */5 * * * *","timezone":"America/Sao_Paulo","name":"Keep alive","description":"This job sends a keep alive notification to a device every 5 minutes","http":null,"broker":{"subject":"dojot.device-manager.device","message":{"event":"configure","data":{"attrs":{"message":"keepalive"},"id":"5345c8"},"meta":{"service":"admin"}}},"jscode":null}.
<14:55:11 22/02/2021> -- ERROR: Failed to set cron jobs for admin (Error: Internal error while setting up cron job.).
<14:55:11 22/02/2021> -- ERROR: Couldn't initialize the cron manager (Error: Internal error while setting cron jobs for tenant admin.).
<14:55:11 22/02/2021> -- ERROR: Cron service initialization failed (Error: Internal error while starting cron manager.). Bailing out!!

**Comment by betefaber** [comment]
- An invalid job: `0 /3 * * * *`

```
curl -X GET http://localhost:8000/cron/v1/jobs -H 'Content-Type:application/json' -H "Authorization: Bearer ${JWT}" 2>/dev/null | jq
[]
```
```
curl -X POST http://localhost:8000/cron/v1/jobs -H 'Content-Type:application/json' -H "Authorization: Bearer ${JWT}" -d ' 
> {
>   "time": "0 /3 * * * *",
>   "timezone": "America/Sao_Paulo",
>   "name": "Keep alive",
>   "description": "This job sends a keep alive notification to a device every 3 minutes",
>   "broker": {
>     "subject": "dojot.device-manager.device",
>     "message": {
>       "event": "configure",
>       "data": {
>         "attrs": {
>           "display": "NOK"
>         },
>         "id": "a4efd7"
>       },
>       "meta": {
>         "service": "admin"
>       }
>     }
>   }
> }' 2>/dev/null | jq
{
  "status": "error",
  "errors": [
    {
      "error": 101,
      "message": "Invalid cron time."
    }
  ]
}
```

```
curl -X GET http://localhost:8000/cron/v1/jobs -H 'Content-Type:application/json' -H "Authorization: Bearer ${JWT}" 2>/dev/null | jq
[]
```

- A valid job: `"0/3 * * * *"`

```
curl -X POST http://localhost:8000/cron/v1/jobs -H 'Content-Type:application/json' -H "Authorization: Bearer ${JWT}" -d ' 
> {
>   "time": "0/3 * * * *",
>   "timezone": "America/Sao_Paulo",
>   "name": "Keep alive",
>   "description": "This job sends a keep alive notification to a device every 3 minutes",
>   "broker": {
>     "subject": "dojot.device-manager.device",
>     "message": {
>       "event": "configure",
>       "data": {
>         "attrs": {
>           "display": "OK"
>         },
>         "id": "a4efd7"
>       },
>       "meta": {
>         "service": "admin"
>       }
>     }
>   }
> }' 2>/dev/null | jq
{
  "status": "success",
  "jobId": "a9bed777-8529-46e4-a497-473b750ece5e"
}
```
```
curl -X GET http://localhost:8000/cron/v1/jobs -H 'Content-Type:application/json' -H "Authorization: Bearer ${JWT}" 2>/dev/null | jq
[
  {
    "jobId": "a9bed777-8529-46e4-a497-473b750ece5e",
    "spec": {
      "time": "0/3 * * * *",
      "timezone": "America/Sao_Paulo",
      "name": "Keep alive",
      "description": "This job sends a keep alive notification to a device every 3 minutes",
      "broker": {
        "subject": "dojot.device-manager.device",
        "message": {
          "event": "configure",
          "data": {
            "attrs": {
              "display": "OK"
            },
            "id": "a4efd7"
          },NOK
          "meta": {
            "service": "admin"
          }
        }
      }
    }
  }
]
```

```
cron_1                        | <12:54:15 21/06/2021> -- INFO: Created collection jobs into database cron_test.
cron_1                        | <12:54:15 21/06/2021> -- INFO: Succeeded to set cron jobs for tenant test.
cron_1                        | <13:05:22 21/06/2021> -- INFO: Succeeded to unset cron job ce40240a-00e5-42a8-b21f-93c390dd348f.
cron_1                        | <13:05:22 21/06/2021> -- INFO: Succeeded to unset cron job af6031ee-3383-448a-89da-2908631f3a10.
cron_1                        | <13:05:22 21/06/2021> -- INFO: Succeeded to unset cron job 5e6ed5ce-e736-45fe-8d1c-ac178dc47146.
cron_1                        | <13:05:22 21/06/2021> -- INFO: Succeeded to unset cron job 55d96a68-9fde-46b9-b233-d6b6bafc1c1c.
cron_1                        | <13:05:22 21/06/2021> -- INFO: Succeeded to unset cron job f9183918-0b27-4e49-8f90-c54b4a3b1fd8.
cron_1                        | <13:28:33 21/06/2021> -- INFO: Succeeded to set up cron job a9bed777-8529-46e4-a497-473b750ece5e with spec {"time":"0/3 * * * *","timezone":"America/Sao_Paulo","name":"Keep alive","description":"This job sends a keep alive notification to a device every 3 minutes","broker":{"subject":"dojot.device-manager.device","message":{"event":"configure","data":{"attrs":{"display":"OK"},"id":"a4efd7"},"meta":{"service":"admin"}}}}.
```

![image](https://user-images.githubusercontent.com/37310063/122771987-542e5680-d27d-11eb-86e8-e584f1f0f7d8.png)

**Comment by betefaber** [comment]
**batch HTTP**

- invalid job:

```
curl -X POST http://localhost:8000/cron/v1/jobs -H 'Content-Type:application/json' -H "Authorization: Bearer ${JWT}" -d '
{
   "time":"* /2 * * * *",
   "timezone": "America/Sao_Paulo",
   "name": "Keep alive",
   "description": "This job sends a keep alive notification to a device every 2 minutes",
   "http": {
  "method": "PUT",
   "headers": {
   "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOi...3tzaTcmhmyAGdICjLN_G1DE8",
   "Content-Type": "application/json"
       },
   "url": "http://device-manager:5000/device/d18ea2/actuate",
   "body": {
    "attrs": {
   "display": "NOK"
  }
    }
 }
}' 2>/dev/null | jq
{
  "status": "error",
  "errors": [
    {
      "error": 101,
      "message": "Invalid cron time."
    }
  ]
}
```
- valid job

```
curl -X POST http://localhost:8000/cron/v1/jobs -H 'Content-Type:application/json' -H "Authorization: Bearer ${JWT}" -d '
{
   "time":"*/2 * * * *",
   "timezone": "America/Sao_Paulo",
   "name": "Keep alive",
   "description": "This job sends a keep alive notification to a device every 2 minutes",
   "http": {
  "method": "PUT",
   "headers": {
   "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIU...e93tzaTcmhmyAGdICjLN_G1DE8",
   "Content-Type": "application/json"
       },
   "url": "http://device-manager:5000/device/d18ea2/actuate",
   "body": {
    "attrs": {
   "display": "OK"
  }
    }
 }
}
```

```
curl -X GET http://localhost:8000/cron/v1/jobs -H 'Content-Type:application/json' -H "Authorization: Bearer ${JWT}" 2>/dev/null | jq
[
  {
    "jobId": "cf9eed0d-65bf-403d-8625-e84d8cddacf6",
    "spec": {
      "time": "*/2 * * * *",
      "timezone": "America/Sao_Paulo",
      "name": "Keep alive",
      "description": "This job sends a keep alive notification to a device every 2 minutes",
      "http": {
        "method": "PUT",
        "headers": {
          "Authorization": "Bearer eyJ0eXAiOiJKV1QiLC...ICjLN_G1DE8",
          "Content-Type": "application/json"
        },
        "url": "http://device-manager:5000/device/d18ea2/actuate",
        "body": {
          "attrs": {
            "display": "OK"
          }
        }
      }
    }
  }
]
```


```
cron_1                        | <16:00:40 21/06/2021> -- INFO: Succeeded to set up cron job cf9eed0d-65bf-403d-8625-e84d8cddacf6 with spec {"time":"*/2 * * * *","timezone":"America/Sao_Paulo","name":"Keep alive","description":"This job sends a keep alive notification to a device every 2 minutes","http":{"method":"PUT","headers":{"Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZzI2S0lwMEcyTmtBS2ptWEVPTGxON3BDU0tkTVd3diIsImlhdCI6MTYyNDI3Nzc2NCwiZXhwIjoxNjI0Mjc4MTg0LCJwcm9maWxlIjoiYWRtaW4iLCJncm91cHMiOlsxXSwidXNlcmlkIjoxLCJqdGkiOiJlZDIxNGQxZGYwZjU0OTM5OTk5NjA2ZDFmNzBiMDZhNSIsInNlcnZpY2UiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.aHaiBcFp3irCkTfXYe93tzaTcmhmyAGdICjLN_G1DE8","Content-Type":"application/json"},"url":"http://device-manager:5000/device/d18ea2/actuate","body":{"attrs":{"display":"OK"}}}}.

```
![Captura de tela de 2021-06-21 13-06-44](https://user-images.githubusercontent.com/37310063/122795156-6a471180-d293-11eb-8cfd-f3ec18e6750f.png)
