### ISSUE TITLE
[GUI-v1][SocketIO] In a short time, the GUI stops consuming realtime data in the device details

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1995]
- When the map is not selected, the line graphs with velocity and pedal data do not seem to stop working
- And when the page is updated getting all the historical data, everything works fine and the data appears

![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/e6d475ec-ac7e-4df8-982c-544d68e3aa4b)

![image (26).png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/9b335dba-b582-48f7-a16c-c445e05eecc9)

![image (27).png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/1970e688-c182-4a1a-a76f-3a5eb3f3ccfc)

![image (28).png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/b7611955-d6ae-47fa-8a3d-3dd3ac0aaa92)

![image (29).png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/b8668f14-3a0c-45e0-96a8-41a86a6e905c)

![image (31).png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/0c4d0ded-f4bc-475b-966b-44aac528dc96)

![image (30).png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/c34ad235-3aa4-4308-8468-8e9adfff6cf1)

How is the data in history:
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/bf9bba04-91b4-47be-97e5-fd57f9e46f53)

![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/4612d1fc-7a03-439f-9a6e-630c19eadfe1)

**Comment by mprevide** [comment]
Version v0.5.2

**Comment by FrancielePessi** [comment]
Several data have been published long enough to display an error, and nothing has been identified. All data were published in real time.

![Captura de tela de 2021-03-31 16-41-56.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/3cc4b861-faa6-4fe2-8869-fabe3d0e00de)
