### ISSUE TITLE
[GUI-v2] Default or be mandatory to define color for line graph

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1997]
If no color is defined for an attribute in the line graph, it turns white and gives the impression that it is not working

![image (25).png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/3850284e-592a-42af-95c5-e1d5df0959e5)

![image (32).png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/1e7ad5bd-212c-4f57-8347-fcf7ee2cf87e)

Version v0.5.2

**Comment by betefaber** [comment]
Version **v0.6.0-rc.1**

Although there is a default color for the selected attribute, the points on the graph are shown in white.

![Captura de tela de 2021-03-05 11-49-48.png](https://images.zenhubusercontent.com/5cd0940469cf6b4ee443403a/fb19d720-1cd6-45cd-b9af-f128e8facac8)

![Captura de tela de 2021-03-05 11-49-58.png](https://images.zenhubusercontent.com/5cd0940469cf6b4ee443403a/8c4f6772-0044-4b76-9ffe-b36f092e3660)

![Captura de tela de 2021-03-05 11-50-07.png](https://images.zenhubusercontent.com/5cd0940469cf6b4ee443403a/5f4399e3-584c-44f5-b045-3eb56fdc3860)

**Comment by mprevide** [comment]
#2015
