### ISSUE TITLE
[gui-v2]  The previous token is saved in the session 

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#2003]
When down the dojot (wiping volumes) and go up again, the previous token is saved in the session if the browser is not closed and remains logged in, however it is not possible to obtain the list of devices to configure a widget.

An error should be returned to the user or force the user to be logged out.

Version 0.5.2

**Comment by FrancielePessi** [comment]
[GUI-v2] When killing and going up a dojot page is logging out.
