### ISSUE TITLE
[flowbroker] [docker-compose] Some problems when trying to re/start the flowbroker

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#2004]
![image (33).png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/d070455e-830c-4195-9636-c9ec453adfcf)

it seems to have something to do with rebooting the virtual machine that was being used.

Version v0.5.2

**Comment by mprevide** [comment]
another case of error, unfortunately I couldn't get a higher quality image.
![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/1507f790-b80e-448c-aef7-fef0c5f2fc5e)

**Comment by mprevide** [comment]
#1773

**Comment by bizetti** [comment]
It has to do an A&D. Use sdk?

**Comment by betefaber** [comment]
`flowbroker] Initialization failed. Error: Could not reach Auth.`

![image](https://user-images.githubusercontent.com/37310063/112167639-5d048300-8bcf-11eb-8354-70ef71f02846.png)

![image](https://user-images.githubusercontent.com/37310063/112167795-81605f80-8bcf-11eb-8ee0-88cfddbdbcb9.png)

**Comment by betefaber** [comment]
http request flow:

![image](https://user-images.githubusercontent.com/37310063/112171211-6511f200-8bd2-11eb-85c7-4067533f5714.png)


```
flowbroker_1                  | <15:16:50 23/03/2021> -- |http -- ERROR: Error was: Error: getaddrinfo EAI_AGAIN kei.dojot.com.br:80
flowbroker_1                  | <15:16:50 23/03/2021> -- WARN: [executor] Node (A49eda1cf521b6:http) execution failed. Error: Error: getaddrinfo EAI_AGAIN kei.dojot.com.br:80
flowbroker_1                  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26). Aborting flow 362b9d3b-3095-4846-9125-564fcddc4928 branch execution.

```

**Comment by mprevide** [comment]
A specific correction was made for the docker-compose with rabbit in this issue. A new issue was opened with the other problems. #2070
