### ISSUE TITLE
[GUI-v1] invalid data on the x-axis of the graph 

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2005]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

invalid data on the x-axis of the graph 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

publish multiple data 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

the behavior of the graph in this version is different from previous versions 

* **Please tell us about your environment:**
  
  - Version: 0.6.0-rc.1
  - Environment: kubernetes, docker-compose
  - Operating system: Ubuntu 20.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

- in **v0.6.0-rc.1**

![Captura de tela de 2021-03-02 15-31-31](https://user-images.githubusercontent.com/37310063/109700275-4fc81b80-7b70-11eb-868d-be05976b0136.png)

- in **v0.5.2**

![Captura de tela de 2021-03-02 15-05-18](https://user-images.githubusercontent.com/37310063/109700343-5fdffb00-7b70-11eb-9d9d-a301a492af94.png)

**Note**: 
- data published at 15:44

![Captura de tela de 2021-03-02 15-44-30](https://user-images.githubusercontent.com/37310063/109700895-1d6aee00-7b71-11eb-9d56-cb9255e684c8.png)

- the same data after a new publish 

![Captura de tela de 2021-03-02 15-44-50](https://user-images.githubusercontent.com/37310063/109700927-2956b000-7b71-11eb-84f6-2f82a1667a3f.png)

**Comment by FrancielePessi** [comment]
K8s
![Captura de tela de 2021-03-24 15-32-16.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/5183cc97-ac34-427a-8940-d8570fcde04b)

Docker-compose
![Captura de tela de 2021-03-24 16-05-05.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/ecbcce19-d83c-46d7-955d-4ed58e31beac)

**Comment by FrancielePessi** [comment]
K8s
![Captura de tela de 2021-03-24 15-32-16.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/5183cc97-ac34-427a-8940-d8570fcde04b)

Docker-compose
![Captura de tela de 2021-03-24 16-05-05.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/ecbcce19-d83c-46d7-955d-4ed58e31beac)
