### ISSUE TITLE
[Gui-v2] Blank screen after setting up map

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#2006]
I configured a map with valid data and the screen for viewing widgets was always blank.
After a long time, I reopened the main screen, the map loaded for a while and then the screen went blank again.

![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/9b250648-c065-4350-8394-a04bd03243ab)

Data in gui-v1:

![image.png](https://images.zenhubusercontent.com/5cd0344669cf6b4ee4433e91/b99ad661-7355-4876-8ad6-787b48bbbf9a)

Publish in MQTT

` mosquitto_pub -h 10.50.4.47 -p 1883 -t admin:4302d4/attrs -u admin:4302d4 -m '{"location": "23.893916, -47.060999" }'`
`mosquitto_pub -h 10.50.4.47 -p 1883 -t admin:4302d4/attrs -u admin:4302d4 -m '{"location": "22.893916, -47.060999" }'`

**Comment by mprevide** [comment]
When there are no data, the page didn't go blank

**Comment by FrancielePessi** [comment]
![Captura de tela de 2021-03-30 16-50-34.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/4341d1f8-4821-4b7a-8e63-3acd4d7e2b18)
