### ISSUE TITLE
[GUI-v2] Default color for attributes values in line, bar, and area charts 

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2015]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

Although there is a default color for the selected attribute, the points on the graph are shown in white.

![Captura de tela de 2021-03-05 11-49-48.png](https://images.zenhubusercontent.com/5cd0940469cf6b4ee443403a/fb19d720-1cd6-45cd-b9af-f128e8facac8)

![Captura de tela de 2021-03-05 11-49-58.png](https://images.zenhubusercontent.com/5cd0940469cf6b4ee443403a/8c4f6772-0044-4b76-9ffe-b36f092e3660)

![Captura de tela de 2021-03-05 11-50-07.png](https://images.zenhubusercontent.com/5cd0940469cf6b4ee443403a/5f4399e3-584c-44f5-b045-3eb56fdc3860)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

use the default color if a new color is not selected 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: **0.6.0-rc.1**
  - Environment: kubernetes, docker-compose
  - Operating system: Ubuntu 20.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

#1997

**Comment by FrancielePessi** [comment]
Docker-compose
![Captura de tela de 2021-03-24 17-04-12](https://user-images.githubusercontent.com/52173618/112376274-00829000-8cc3-11eb-9ce7-241b55b22ee4.png)

K8s
![Captura de tela de 2021-03-24 17-04-54](https://user-images.githubusercontent.com/52173618/112376339-18f2aa80-8cc3-11eb-8141-462f30eac71b.png)
