### ISSUE TITLE
GUI V1 - UX analysis - Immersion

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2018]
- [x] Estudo da documentação.
- [x] Interação com a plataforma.
- [x] Reunião de alinhamento com a equipe (Entendimento do objetivo do negócio e do problema a ser resolvido e alinhamento de especificações técnicas)
- [x] Geração de documentos: Proposta UX, Observações sobre a reunião, Visão do produto, Wishlist para a nova interface.

**Comment by damarisarruda** [comment]
-[ ]Estudo da documentação.
-[ ] Interação com a plataforma.
-[ ] Reunião de alinhamento com a equipe (Entendimento do objetivo do negócio e do problema a ser resolvido e alinhamento de especificações técnicas)
-[ ] Geração de documentos: Proposta UX, Observações sobre a reunião, Visão do produto, Wishlist para a nova interface.
