### ISSUE TITLE
GUI V1 - UX analysis - Validation

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2021]
- [ ] Teste de usabilidade com usuários
- [ ] Tabulação dos dados
- [ ] Design System  
- [ ] Exemplo light mode

**Comment by damarisarruda** [comment]
- [ ] Teste de usabilidade com usuários
- [ ] Tabulação dos dados
- [ ] Design System  
- [ ] Exemplo light mode

**Comment by bizetti** [comment]
Done.
