### ISSUE TITLE
[Kafka-ws] error message during graceful shutdown

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#2023]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

During Graceful shutdown the following logs can be found:

> 2021-03-10T18:55:18.568Z -- microservice-sdk:service-state-manager -- warn: Removing 3 services...
> 2021-03-10T18:55:18.569Z -- microservice-sdk:service-state-manager -- warn: Removed service "kafka"
> 2021-03-10T18:55:18.570Z -- microservice-sdk:service-state-manager -- warn: Removed service "http"
> 2021-03-10T18:55:18.570Z -- microservice-sdk:service-state-manager -- warn: Removed service "redis"
> 2021-03-10T18:55:18.571Z -- microservice-sdk:service-state-manager -- warn: ... successfully removed all services
> 2021-03-10T18:55:18.571Z -- kafka-ws:redis-manager -- warn: Disconnecting from Redis...
> 2021-03-10T18:55:18.572Z -- kafka-ws:websocket-tarball -- debug: Closed connection.
> 2021-03-10T18:55:18.573Z -- kafka-ws:websocket-tarball -- debug: Code: undefined
> Reason: undefined
> 2021-03-10T18:55:18.574Z -- microservice-sdk:consumer -- debug: Disconnecting from kafka...
> 2021-03-10T18:55:18.574Z -- microservice-sdk:consumer -- debug: Unsubscribing from all topics and disconnecting ...
> 2021-03-10T18:55:18.575Z -- microservice-sdk:commit-mngr -- debug: CommitManager finished successfully.. committing processed offsets
> 2021-03-10T18:55:18.576Z -- microservice-sdk:consumer -- debug: Committed processed offsets!
> 2021-03-10T18:55:18.577Z -- microservice-sdk:consumer -- info: Consumer disconnected. { connectionOpened: 1615399504468 }
> 2021-03-10T18:55:18.578Z -- microservice-sdk:consumer -- debug: Successfully disconnected producer from Kafka.
> 2021-03-10T18:55:18.579Z -- kafka-ws:kafka-consumer -- warn: Kafka Consumer finished!
> 2021-03-10T18:55:18.580Z -- microservice-sdk:service-state-manager -- debug: Service "redis" is not registered, will not signalize anything
> 2021-03-10T18:55:19.581Z -- microservice-sdk:service-state-manager -- warn: process did not exit on its own; investigate what is keeping the event loop active
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! kafka-ws@0.2.0 kafka-ws: `node index.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the kafka-ws@0.2.0 kafka-ws script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-03-10T18_55_19_612Z-debug.log

* **What is the expected behavior?**

I expected don't see the error messages

* **Please tell us about your environment:**
  
  - Version: 0.6.0 rc1
  - Environment:  docker-compose
  - Operating system: Ubuntu 18.04 on VirtualBox (Windows 10)

**Comment by betefaber** [comment]
Test OK.


**graceful shutdown**

```
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:45.444Z -- kafka-ws:redis-manager -- debug: Checking if redis is health...
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:45.447Z -- kafka-ws:redis-manager -- debug: redis is health.
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:45.545Z -- kafka-ws:redis-expire-mgmt -- debug: Checking if redis-expire-pub is health...
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:45.548Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-pub is health.
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:45.561Z -- kafka-ws:redis-expire-mgmt -- debug: Checking if redis-expire-sub is health...
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:45.562Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-sub is health.
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:45.585Z -- kafka-ws:kafka-consumer -- debug: Kafka is health
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.593Z -- microservice-sdk:service-state-manager -- warn: Removing 5 services...
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.602Z -- microservice-sdk:service-state-manager -- warn: Removed service "kafka"
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.603Z -- microservice-sdk:service-state-manager -- warn: Removed service "http"
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.603Z -- microservice-sdk:service-state-manager -- warn: Removed service "redis"
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.603Z -- microservice-sdk:service-state-manager -- warn: Removed service "redis-expire-pub"
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.616Z -- microservice-sdk:service-state-manager -- warn: Removed service "redis-expire-sub"
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.616Z -- microservice-sdk:service-state-manager -- warn: ... successfully removed all services
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.617Z -- kafka-ws:redis-manager -- warn: Disconnecting from Redis...
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.632Z -- kafka-ws:redis-manager -- info: Successfully disconnected.
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.656Z -- kafka-ws:redis-manager -- info: end
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.658Z -- kafka-ws:redis-expire-mgmt -- info: RedisExpireMgmt sub client successfully unsubscribe.
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.659Z -- kafka-ws:redis-expire-mgmt -- info: RedisExpireMgmt sub client successfully disconnected.
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.675Z -- kafka-ws:redis-expire-mgmt -- info: RedisExpireMgmt pub client successfully disconnected.
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.676Z -- app -- debug: Stopping the server from accepting new connections...
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.678Z -- app -- debug: The server no longer accepts connections!
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.679Z -- kafka-ws:kafka-consumer -- info: Finishing kafka consumer ....
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.679Z -- microservice-sdk:consumer -- debug: Disconnecting from kafka...
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.697Z -- microservice-sdk:consumer -- debug: Unsubscribing from all topics and disconnecting ...
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.697Z -- microservice-sdk:commit-mngr -- debug: CommitManager finished successfully.. committing processed offsets
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.706Z -- microservice-sdk:consumer -- debug: Committed processed offsets!
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.706Z -- microservice-sdk:service-state-manager -- debug: Service "redis" is not registered, will not signalize anything
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.707Z -- microservice-sdk:service-state-manager -- debug: Service "http" is not registered, will not signalize anything
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.707Z -- kafka-ws:redis-expire-mgmt -- info: pub: onEnd
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.734Z -- kafka-ws:redis-expire-mgmt -- info: sub: onEnd
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.734Z -- microservice-sdk:service-state-manager -- debug: Service "redis-expire-pub" is not registered, will not signalize anything
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:56.734Z -- microservice-sdk:service-state-manager -- debug: Service "redis-expire-sub" is not registered, will not signalize anything
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:57.541Z -- microservice-sdk:consumer -- info: Consumer disconnected. { connectionOpened: 1627912185565 }
kafka-ws-c6797458f-qvmwt kafka-ws 2021-08-02T14:06:57.542Z -- microservice-sdk:consumer -- debug: Successfully disconnected producer from Kafka.
- kafka-ws-c6797458f-qvmwt
```


Tested in **v0.7.0-rc.2**
