### ISSUE TITLE
When the iotagent-mqtt-mosca certificate expires, it is not automatically regenerated.

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2075]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
When the iotagent-mqtt-mosca certificate expires, it is not automatically regenerated

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- The device certificate was generated with a validity of 1 day. After the certificate expires, publishing is not done. Expected behavior.
```
mosquitto_pub -h localhost -p 8883 -t /admin/33323f/attrs -i admin:33323f --cafile ./ca/ca.pem --cert ./cert_33323f/cert.pem --key ./cert_33323f/private.key -m '{"int": 25}' -d
Client admin:33323f sending CONNECT
OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Error: A TLS error occurred.
```
- The device certificate has been regenerated. Publication is not done, even with a valid certificate
```
mosquitto_pub -h localhost -p 8883 -t /admin/33323f/attrs -i admin:33323f --cafile ./ca/ca.pem --cert ./cert_33323f/cert.pem --key ./cert_33323f/private.key -m '{"int": 25}' -d
Client admin:33323f sending CONNECT
OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Error: A TLS error occurred.
```

- Checking the validity of the iotagetn-mqtt-mosca certificate: the certificate has expired
```
openssl s_client -showcerts -connect localhost:8883 </dev/null > output.txt
Can't use SSL_get_servername
depth=1 UID = c-0322ca78f408cf543, CN = X509 Identity CA, OU = Certificate Issuer, O = dojot IoT Platform
verify error:num=19:self signed certificate in certificate chain
verify return:1
depth=1 UID = c-0322ca78f408cf543, CN = X509 Identity CA, OU = Certificate Issuer, O = dojot IoT Platform
verify return:1
depth=0 O = dojot IoT Platform, CN = iotagent-mqtt-mosca
verify error:num=10:certificate has expired
notAfter=Apr  6 15:30:00 2021 GMT
verify return:1
depth=0 O = dojot IoT Platform, CN = iotagent-mqtt-mosca
notAfter=Apr  6 15:30:00 2021 GMT
verify return:1
```

- For the certificate to be regenerated, the container needs to be restarted: stop/start iotagent-mqtt-mosca

- After restarting the container the publication is done
```
$ mosquitto_pub -h localhost -p 8883 -t /admin/33323f/attrs -i admin:33323f --cafile ./ca/ca.pem --cert ./cert_33323f/cert.pem --key ./cert_33323f/private.key -m '{"int": 30}' -d
Client admin:33323f sending CONNECT
Client admin:33323f received CONNACK (0)
Client admin:33323f sending PUBLISH (d0, q0, r0, m1, '/admin/33323f/attrs', ... (11 bytes))
Client admin:33323f sending DISCONNECT
```

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: **0.6.0-rc.2**
  - Environment: docker-compose
  - Operating system: Ubuntu 20.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
Service deprecated.
