### ISSUE TITLE
[GUI-v2] The map does not keep the zoom setting

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2077]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Device positions are updated after polling. However, when zooming in or out, the setting is lost.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Steps to reproduce the problem:
1. Running simulator, publishing geo data
2. In map view, select zoom in or zoom out
3. Check that the configuration is lost

- Initial setting

![Captura de tela de 2021-04-13 12-18-06](https://user-images.githubusercontent.com/37310063/114598221-0804db80-9c68-11eb-8a84-e2a6a8f38ecd.png)

- zoom in

![Captura de tela de 2021-04-13 12-18-31](https://user-images.githubusercontent.com/37310063/114598247-12bf7080-9c68-11eb-9b3d-6ef994a6a131.png)

- after polling

![Captura de tela de 2021-04-13 12-18-38](https://user-images.githubusercontent.com/37310063/114598242-118e4380-9c68-11eb-9de6-89be17ad3065.png)

- zoom out

![Captura de tela de 2021-04-13 12-18-50](https://user-images.githubusercontent.com/37310063/114598278-1b17ab80-9c68-11eb-9edf-5d5fb316c520.png)

- after polling

![Captura de tela de 2021-04-13 12-18-54](https://user-images.githubusercontent.com/37310063/114598273-194de800-9c68-11eb-8278-58f64f1572b6.png)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.6.0-rc.3
  - Environment: kubernetes
  - Operating system: [Ubuntu 16.04, Fedora 28, Ubuntu on VirtualBox (Windows 10), etc.]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by cfrancisco** [comment]
Could apply the GUI-v1's code.

**Comment by bizetti** [comment]
Won't be fixed.
