### ISSUE TITLE
It's not possible do change the name of a device

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#209]
It's not possible to change the name of a device and a non-correlated error message is displayed 'Attributes cannot be updated inline ...'

![image](https://user-images.githubusercontent.com/31006659/35925779-bc24afc6-0c0d-11e8-9a33-3d87e6d7e2de.png)

**Comment by mmagr** [comment]
Apart from the back end fix already published, it is important to make the required changes in API calls - currently GUI will invoke the API with invalid values on `attr`field.

**Comment by rascaraficci** [comment]
It's working!
