### ISSUE TITLE
[Gui V2] Edit table - multiple devices

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#2098]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
 a device  can't be  removed from a dashboard table

![editarTabela](https://user-images.githubusercontent.com/53264012/116449583-b3995880-a830-11eb-99b4-be787c3efcbc.png)
![editarTabela2](https://user-images.githubusercontent.com/53264012/116449592-b7c57600-a830-11eb-8f91-07f3950bae37.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

  - create a table selecting two devices and some attributes
  - Edit the table and on step 2 (devices) deselect one device
  - click next until step 5 (overview)
  - verify the attributes of unchecked device is still shown
  - click on Finish button
  - Verify that no change was done.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.6.0-rc3
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04 on VirtualBox (Windows 10)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by FrancielePessi** [comment]
Test performed [Docker-compose v0.7.0-rc.1], problem persists.

![Captura de tela de 2021-06-22 19-14-16](https://user-images.githubusercontent.com/52173618/123006964-d490ac80-d38e-11eb-80fd-d6999f4b8a26.png)

![Captura de tela de 2021-06-22 19-14-26](https://user-images.githubusercontent.com/52173618/123006998-df4b4180-d38e-11eb-804d-03df572f00eb.png)
