### ISSUE TITLE
[GUI v2] add widget - tooltip

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#2099]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
A tooltip with text "Contemplative reptile" is shown when mouse over any widget.
![tooltip](https://user-images.githubusercontent.com/53264012/116455571-9916ad80-a837-11eb-8120-8ab368681b27.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
remove tooltip or change text

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.6.0-rc3
  - Environment: docker-compose
  - Operating system: [Ubuntu 18.04 on VirtualBox (Windows 10)]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by FrancielePessi** [comment]
Test performed [docker-compose v0.7.0-rc.1]
