### ISSUE TITLE
It's not possible to add a new template to a device

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#210]
It's not possible to change the template associated with a device or add a new one. Also a non-correlated error message is shown. It seems that nothing is editable for a device.

![image](https://user-images.githubusercontent.com/31006659/35926346-13088d5c-0c0f-11e8-8fa3-29898d97b557.png)

**Comment by mmagr** [comment]
This particular error message is generated by device manager when a `POST /device` or `PUT /device/:id` request includes an `attrs` field.

To update the list of used templates, one should update the list on the `templates` field of the payload.

**Comment by mmagr** [comment]
This is affected by dojot/device-manager#25.

**Comment by mmagr** [comment]
This should be fixed in dojot-nightly/docker-compose@0469f79 

@rascaraficci can you please verify?

**Comment by rascaraficci** [comment]
Ok. It's working fine!
