### ISSUE TITLE
Rampup DevOps and dojot

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2113]
====> **DOJOT **
- [x] Ambiente para o Produto DojoT
- [x] Lido: Arquitetura, Conceitos, Guia de instalação
- **Guia para novos colaboradores**
- [x] Leia a documentação da dojot
- [x] Drive da dojot
- [x]  Instalação versão dojot
- **Treinamentos Dojot**
- [x]  Módulo 1 e 2
- [x] Módulo 3
- [ ] Módulo 4
- [ ] Módulo 5

 ====> **Competência-SW: Capacitação**
**Kubernetes/Docker...**
- [x] Docker: Docker: Criando containers sem dor de cabeça (Alura)
- [x] Docker: Docker Swarm: Orquestrador de containers (Alura)
- [x] Docker: Kubernetes: Pods, Services e ConfigMaps (Alura)
- [x] Docker: Kubernetes: Deployments, Volumes e Escalabilidade (Alura)
- [x] Treinamento Docker e Kubernetes e Ansible (EAD CPQD)  **---> PRIORIDADE ALTA**

**Treinamento : Integração continua : Jenkins / Gitlab com pipeline (utilizado na Dojot)** **---> PRIORIDADE BAIXA**
- [ ] Curso-online-desenvolvimento-software-integracao-continua (Alura)
- [ ] Curso-online-entrega-continua (Alura)
- [ ] Confiabilidade-qualidade (Alura)
- [ ] Curso-online-pipeline-ci-jenkins-docker (Alura)
- [ ] Curso-online-jenkins-integracao-continua (Alura)
- [ ] Curso-online-gitlab-docker-integracao-continua (Alura)

**Treinamento : Infraestrutura como codigo**
- [ ] Curso-online-devops-com-vagrant-e-puppet  (Alura) **---> PRIORIDADE MÉDIA**
- [x] Curso-online-infraestrutura-como-codigo-com-ansible (Alura) **---> PRIORIDADE ALTA**

**Treinamento : Monitoramento**
- [ ] Curso-online-grafana-telegraf-monitoramento (Alura) **---> PRIORIDADE MÉDIA**

**DEVOPS ...**
- [x] Conceitos de Devops (Site Internet)
- [x] Conceitos de Modelo de Maturidade Devops (Site Internet)

**Treinamento : Linux** **---> PRIORIDADE MÉDIA**
- [ ] Linux: curso-online-linux-ubuntu (Alura)
- [ ] Linux: curso-online-linux-ubuntu-processos (Alura)
- [ ] Linux: curso-online-shellscripting  (Alura)
- [ ] Linux: curso-online-shellscripting-parte-2 (Alura)
- [ ] Linux: curso-online-linux-essentials-3 (Alura)
- [ ] Linux: curso-online-linux-essentials-4 (Alura)
- [ ] Linux: curso-online-linux-essentials-5 (Alura)
- [ ] Linux: curso-online-linux-essentials-6 (Alura)
- [ ] Linux: curso-online-linux-essentials-7 (Alura)
- [ ] Linux: curso-online-linux-essentials-8 (Alura)
- [ ] Linux: curso-online-linux-essentials-9 (Alura)
- [ ] Linux: curso-online-linux-essentials-10 (Alura)
- [ ] Linux: curso-online-linux-essentials-11 (Alura)
- [ ] Linux: curso-online-linux-essentials-12 (Alura)

**Treinamento : Git**
- [x] Git: curso-online-git-github-controle-de-versao (Alura) **---> PRIORIDADE ALTA**
- [x] Git: curso-online-git-github-branching-conflitos-pull-requests (Alura) **---> PRIORIDADE ALTA**
- [ ] https://www.udemy.com/course/git-e-github/  **---> PRIORIDADE ALTA**

 ====> **INDICAÇÃO EQUIPE DOJOT** **---> PRIORIDADE ALTA**
**Github Actions** https://lab.github.com/githubtraining/devops-with-github-actions
- [x] GitHub Actions: Hello World (GitHub) (obrigatório)
- [x] GitHub Actions: Continuous Integration (GitHub)  (obrigatório)
- [x] GitHub Actions: Publish to GitHub Packages (GitHub) (obrigatório)
- [ ] GitHub Actions: Writing JavaScript Actions (GitHub) (relevante)
- [x] GitHub Actions: Write Docker container actions (GitHub) (obrigatório)
- [x] GitHub Actions: Using GitHub Script (GitHub) (preciso consultar, obrigatório)
- [ ] Migrating from Jenkins to GitHub Actions (GitHub) (opcional)

**AWS**
- [x] Amazon EKS: Gerenciando aplicações conteinerizadas com Kubernetes (Alura)
- [x] Deploy no Amazon EC2: Alta disponibilidade e escalabilidade de uma aplicação (Alura)

**GCP**
- [ ] Google Cloud Serverless: Crie aplicações robustas e escaláveis (Alura)

**Prometheus**
- [ ] https://www.youtube.com/watch?v=7gW5pSM6dlU

**Comment by DanielaPetito** [comment]
**Treinamentos Alura efetuados até 06/05/2021**
         - Docker: Criando containers sem dor de cabeça
         - Docker Swarm: Orquestrador de containers
         - Kubernetes: Pods, Services e ConfigMaps
         - Kubernetes: Deployments, Volumes e Escalabilidade

**Leituras efetuadas:**
         - Conceitos de Modelo de Maturidade Devops
         -  Ambiente para o Produto DojoT
                  - Lido: Arquitetura, Conceitos, Guia de instalação
