### ISSUE TITLE
Rampup DevOps and dojot

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2114]
- [ ] Kubernets ...
- [ ] dojot - guia para novos colaboradores

**Comment by mbrunhara** [comment]
**Conceitos de Devops**
- [ ] [Conceitos DevOps](https://marco-mendes.com/devops/)
- [ ] [Modelos de Maturidade Devops](https://www.dropbox.com/s/qejh6vtnwe75la5/Arkhi-MaturidadeDevOps.pdf?dl=0)

**Treinamento : Linux**
- [ ] [Linux I: Conhecendo e utilizando o terminal](https://www.alura.com.br/curso-online-linux-ubuntu)
- [ ] [Linux II: Programas, processos e pacotes](https://www.alura.com.br/curso-online-linux-ubuntu-processos)
- [ ] [Shell Scripting parte 1: Começando seus scripts de automação de tarefas](https://www.alura.com.br/curso-online-shellscripting)
- [ ] [Shell Scripting parte 2: Fazendo monitoramento, agendando tarefas e backup](https://www.alura.com.br/curso-online-shellscripting-parte-2)
- [ ] [Certificação Linux LPI Essentials parte 3: Command Line Basics](https://www.alura.com.br/curso-online-linux-essentials-3)
- [ ] [Certificação Linux LPI Essentials parte 4: Using the command line to get help](https://www.alura.com.br/curso-online-linux-essentials-4)
- [ ] [Certificação Linux LPI Essentials parte 5: Directories and Listing Files and managing files](https://www.alura.com.br/curso-online-linux-essentials-5)
- [ ] [Certificação Linux LPI Essentials parte 6: Archiving Files on the Command Line](https://www.alura.com.br/curso-online-linux-essentials-6)
- [ ] [Certificação Linux LPI Essentials parte 7: Searching and Extracting Data from Files](https://www.alura.com.br/curso-online-linux-essentials-7)
- [ ] [Certificação Linux LPI Essentials parte 8: Turning Commands into a Script](https://www.alura.com.br/curso-online-linux-essentials-8)
- [ ] [Certificação Linux LPI Essentials parte 9: Understanding Computer Hardware](https://www.alura.com.br/curso-online-linux-essentials-9)
- [ ] [Certificação Linux LPI Essentials parte 10: Where Data is Stored](https://www.alura.com.br/curso-online-linux-essentials-10)
- [ ] [Certificação Linux LPI Essentials parte 11: Your Computer on the Network](https://www.alura.com.br/curso-online-linux-essentials-11)
- [ ] [Certificação Linux LPI Essentials parte 12: Security and File Permissions](https://www.alura.com.br/curso-online-linux-essentials-12)

**Treinamento : Git**
- [ ] [Git e Github: Controle e compartilhe seu código](https://www.alura.com.br/curso-online-git-github-controle-de-versao)
- [ ] [Git e Github: Estratégias de ramificação, Conflitos e Pull Requests](https://www.alura.com.br/curso-online-git-github-branching-conflitos-pull-requests)

**Treinamento : Docker**
- [ ] []
