### ISSUE TITLE
Proc. node management - node-red API

### ISSUE THREAD

**Issue by mmagr** [dojot/dojot#212]
Orchestrator should present a node retrieval API compatible with a node-red front end editor.

**Comment by giovannicuriel** [comment]
To be clear: we need to mimic [these APIs](https://nodered.org/docs/api/admin/methods/), right? (At least all those GETs)

**Comment by mmagr** [comment]
> To be clear: we need to mimic these APIs, right? (At least all those GETs)

Yes, there are at least 3:

`GET /nodes (accept: application/json)`
-  Returns all available node metadata, such as name, module, types, etc

`GET /locales/:moduleid`
- Returns the locale json used to implmement i18n on the UI

`GET /nodes (accept: text/html)
- Returns, in a single call, all available html files, concatenated.

**Comment by giovannicuriel** [comment]
I created a repository for it, nicely named as [node-blue](https://github.com/giovannicuriel/node-blue)
