### ISSUE TITLE
IoT Agent - Generic https implementation 

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2129]

**Comment by mprevide** [comment]
- [ ] Fazer mensagem chegar na dojot publicando com curl e certificado, sem CN ainda

- [ ] Identificação do device/tenant:
 -  [ ]  Com http:
  - colocar no body tenant e deviceid (obrigatório)
 -  [ ]  com https: 
  - **body tenant e deviceid: NÃO é obrigatório**
   - se receber no body, verificar se CN e body batem, se baterem produzir msg
   - se nao receber no body tenant e deviceid, usar CN para tenant e deviceid e produzir msg
- [ ] Sobre setSecureContext
 - utilizar o fs.watch para ver se houve mudança nos arquivos, caso haver chamar o setSecureContext
 - testar revogação, ao revogar o certificado de um device, depois de o fs.watch ser chamado, este device deve ser impedido de publicar. 
 -  [ ] readme:
   - [ ] explicando as variáveis de ambiente e exemplo de requisição http 
   -  [ ] poder habilitar ou desabilitar https
   -  [ ] poder passar as config por variável de ambiente 	
 
- [ ] exemplo
 - um compose, apenas com as dependencias necessarias
