### ISSUE TITLE
Test - Test automation - X.509 management service

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2137]

**Comment by betefaber** [comment]
- [ ] Trusted CA Certificates
   - [ ] Register Trusted CA Certificate
   - [ ] Delete Trusted CA Certificate
   - [ ] Update Trusted CA Certificate
   - [ ] Get Trusted CA Certificate
   - [ ] List Trusted CA Certificates
  
- [ ] x.509 Certificate
   - [ ] Register x.509 Certificate
   - [ ] Create x.509 Certificate from CSR
   - [ ] Delete x.509 certificate
   - [ ] Get x.509 Certificate
   - [ ] List x.509 Certificates
   - [ ] Change the Ownership of a Specified x.509 Certificate
