### ISSUE TITLE
GUI/v2 - Map widget (Selection of devices / attributes and BLUE widget)

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2139]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Report bug

* **What is the current behavior?**
Widget map está ficando azul

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1 ° GUI - v1 Create 2 device geo and publish data.
** mosquitto_pub -h localhost -p 1883 -t admin:d66ba3/attrs -m '{ "test": "-22.742123, -47.365935"}' -q 1 -u admin:d66ba3 **

** mosquitto_pub -h localhost -p 1883 -t admin:4740a3/attrs -m '{ "geov2": "-22.772738, -47.394614" }' -q 1 -u admin:4740a3
**

![Captura de tela de 2021-06-07 10-11-59.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/bb6d703f-798d-4dcb-89c9-349a818f9c00)

2 ° Create a map widget in GUI v2, select one of the created devices.

![Captura de tela de 2021-06-07 10-13-23.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/87d1c9f0-31b7-45f0-a717-d5e2d1f3cfff)

3°  Edit created widget, and select another device.

- Uncheck the previous option ex: GEo and select the new device ex: geo2.

![Captura de tela de 2021-06-07 10-13-36.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/3aa43dcd-df87-4baf-ab15-8d74e0934090)

![Captura de tela de 2021-06-07 10-13-48.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/8fc64a0f-a855-4784-838c-22475b2a3280)

** _ERROR_ ** When showing list, previous attribute is still found ex: GEo.
![Captura de tela de 2021-06-07 10-13-56.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/081260b3-2401-4d9e-9f13-20198726da31)

** Two coordinates are found on the map, but only one should appear.
![Captura de tela de 2021-06-07 10-14-04.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/44a3a649-2a28-40be-a9a0-64eee2bce5eb)

4 ° GUI - V1: Remove device created earlier ex: GEo.
![Captura de tela de 2021-06-07 10-14-33.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/0d9d91cf-bb0e-4c82-876b-524b6a27c07a)

![Captura de tela de 2021-06-07 10-14-36.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/fd00587d-f010-4dd5-9cab-e074201d2ae2)

5º Go back to GUI - v2 and reload page, widget turns blue.
![Captura de tela de 2021-06-07 10-14-44.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/207e922a-e5e5-492a-887b-da3af6afac66)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.6.0
  - Environment: [docker-compose, Kubernetes]
  - Operating system: [Ubuntu 18.04]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by FrancielePessi** [comment]
https://app.zenhub.com/workspaces/dojot-ws-5ca7620c263982676581b05d/issues/dojot/dojot/2154

**Comment by bizetti** [comment]
The map is at coordinates 0,0. It's ok. Won't be fix.
