### ISSUE TITLE
Flow Broker - Making it independent from GUI

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2147]
- [x] Documented A&D phase
- [ ] Implementation
- [ ] Tests

**Comment by cfrancisco** [comment]
Issues already made:

Já feitos:
- 1. Execução do NodeRed standalone;
- 2.1 Módulo para busca dos nós na Dojot (Uso do endpoint GET flows);
- 2.2 Salvar nós na Dojot, utilizando os endpoints POST/PUT/DELETE. 
    - Tudo está no modulo dojotStorageModule, com algumas classes de suporte para fazer essa operação. 
- 3. Adição de um README inicial, aplicação do eslint/prettier e Dockerfile.
- 4.1 Integração do Logger do SDK nos nossos modulos;
    - Os modulos internos do NodeRed ainda não foram feitos.
- 4.2 Integração e uso do ConfigManager ao invés do sistema de settings do Node-RED;
- 5. Remoção da pagina de Palette da UI;
- 6. Feito os 18 nós da Dojot (com texto no i18n de Inglês); 
- 7. Uma grande limpeza dos arquivos e códigos não necessários.
    - Ainda carece de mais, mas um grande tanto já foi realizado. 
- 8. Aplicação do Dark Theme da Dojot;
- 9. Conexão com o Docker-compose; 
- 10. "Back to Dojot" Retorna para a Dojot;
- 11. Integrar os nós Dojot, buscando informações no Flowbroker;
