### ISSUE TITLE
Unhealthy dockers - VerneMQ/V2k-bridge/k2v-bridge

### ISSUE THREAD

**Issue by rezendel** [dojot/dojot#2160]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ x] support request

* **Do you want to request a *feature* or report a *bug*?**
I just started to use the dojot. (v0.6.0) But I cannot publish in a topic using mosquito_pub. It seems that the VerneMQ is not working properly due some issue with the k2v bridge please see screenshot

* **What is the current behavior?**

Some dockers are unhealthy

![Verne-v2k-k2v-unhealth](https://user-images.githubusercontent.com/20887499/122143359-b58e9980-ce27-11eb-964e-2534f95b517a.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.6.0
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 20.04 on virtual box[windows 10]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
Hi @rezendel,

Could you check if the service "x509-identity-mgmt" was healthy? Sometimes it takes 10 minutes for reaching this status.

After "x509-identity-mgmt" is healthy, the other services will became healthy as well.

Regards

**Comment by rezendel** [comment]
Hello @bizetti, 

Thank you for the repply. It was running for more than 10 minutes and no, the service was not healthy, I was not abble to get it running, but meanwhile I just created a new VM this morning, but this time with Ubuntu Server 20.04 ( I was running on the ubuntu desktop before). I don't know if this was the reason.

Now it is working very nice. 

Thank you for the support.

**Comment by rascaraficci** [comment]
Has the problem been solved?
