### ISSUE TITLE
[GUI - v2]  Graph line is off the graph [Using true and false]

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2166]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
The graph line comes out when publishing an integer using False (0) and True (1), GUI - v1 accepts the values as 0 and 1.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1° v1 - Create device with integer attribute. 
2° v1 - Publish: 
![Captura de tela de 2021-06-23 06-36-21.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/ee97d457-c448-4746-8bb3-4419d04d9719)

![Captura de tela de 2021-06-23 06-24-26.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/aa857607-cb61-4d3a-bd03-a2c0cb154871)

3° v2 - Configure a Line chart widget 

v1 - Accepting True and False values
![Captura de tela de 2021-06-23 06-33-47.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/af7b7d26-f4cf-4de8-91b9-d4b194bbf42a)

v2
![Captura de tela de 2021-06-23 06-03-24.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/f9fcacf4-03f6-4312-b770-d39fff2fa013)

v2
![Captura de tela de 2021-06-23 06-03-39.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/00f78666-e998-4abe-8a6f-d16ccbd8b12b)

v2
![Captura de tela de 2021-06-23 06-16-36.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/52261c0f-d0f5-45f6-a64f-99b17d522d72)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.7.0-rc.1
  - Environment: [Docker-compose]
  - Operating system: [Ubuntu 16.08]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
It won't be fixed.
