### ISSUE TITLE
MongoDB - Period (date_from, date_to) filter for notifications

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2167]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] enhancement request
  - [ ] support request

* **What is the current behavior?**

Endpoint for requesting notification is fixed: it returns the last 10 notifications

* **What is the expected behavior?**

Create an additional endpoint with possibility to filter by period (date_from, date_to) and number of notifications.

* **What is the motivation / use case for changing the behavior?**

If the system stays out during a period, the application is not be able to recover old notifications

**Comment by betefaber** [comment]
#2205
