### ISSUE TITLE
Backup/Restore strategy for dojot databases - Analisys, implementation, tests and documentation

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2191]

**Comment by danielapetito** [comment]
Documentado a proposta de backup e passo a passo no documento
https://docs.google.com/document/d/1T9RI7TcXK9fU4PBTLy8j1_9tPaepWSn8Aksl5XFN3w8/edit

**Comment by danielapetito** [comment]
Criado guia de backup e restore do MongoDB com mongodump e mongorestore..

https://docs.google.com/document/d/1Yd3Scz0FzSarafkOpGvotmO9QMhTDGrdiWK9ZyxC5h8/edit?usp=sharing

**Comment by danielapetito** [comment]
Criado a issue #2227 - https://github.com/dojot/dojot/issues/2227
Backup/Restore for MongoDB - Validate copy of data file system
