### ISSUE TITLE
Documentation - Generic document for dojot environment estimates (K8s)

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2195]

**Comment by danielapetito** [comment]
Para o projeto ILPF, criado o documento "ILPF - Definição de Ambiente"
https://docs.google.com/document/d/1XR3xprLcO1d468Msaoh5eut5t4atKssiTDz1DmhW-f8/edit

Para novos clientes/projetos, sugestão ajustar o cenário de dispositivos IoT conforme implantação e baseado nessas informações dimensionar os servidores.
