### ISSUE TITLE
(FE) Device template - prototype - review proposal

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#22]

**Comment by hvjunior** [comment]
The first version of prototype is 
https://docs.google.com/presentation/d/1CQwVQIMhTYvngj3jPWO6S8HTPGGmTdS6LX7Z5syHbZc/edit#slide=id.g2492c2ce3d_0_870

**Comment by rascaraficci** [comment]
The idea is valid, but it could be improved in some aspects:
- model being agnostic of protocol type (MQTT, CoAP, etc)
- capability of instantiate multiple devices from 'device page'
- removing the 'radio button ' and using only the 'drop-down list" with the option of 'new model'  in the device page
