### ISSUE TITLE
GUI - V2 Bar Chart: Selected attributes are not visible.

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2217]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Add bar chart, select more than one attribute. Attributes are not all visible.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* ** If the current behavior is a bug, please provide steps to reproduce and, if possible, a minimal demonstration of the problem **

1°  Add bar chart.

2° Select device

3° Select an attribute.

4° Add attributes.

![Captura de tela de 2021-08-03 13-50-57.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/a5c632e1-3555-447f-8391-8c41cdc3b8a0)

![Captura de tela de 2021-08-03 13-52-21.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/21866625-8d98-4665-a1ce-e13a66c14c9d)

![Captura de tela de 2021-08-03 13-52-32.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/b7faed29-b7fa-48bc-ae56-cc116f9774ea)

![Captura de tela de 2021-08-03 13-52-43.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/2462106f-701e-4366-a2c2-bcc24c7511af)

![Captura de tela de 2021-08-03 13-53-51.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/58225031-6ba9-41b1-96d0-9a4f5cda1331)

* **What is the expected behavior?**
* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.7.0-rc2
  - Environment: [docker-compose, Kubernetes]
  - Operating system: [Ubuntu 16.08]

**Comment by cfrancisco** [comment]
The third attribute is actually shown but has the same value as the x-axis. We could set the X-baseline to 0 or another value.

**Comment by bizetti** [comment]
Won't be fixed.
