### ISSUE TITLE
apigw service in docker-compose is fail when running container 

### ISSUE THREAD

**Issue by BuiVanDuc** [dojot/dojot#2226]
I'm using version of dojot is v0.6.0. I have taken docker-compose up -d to run the project but it occurs an error in apigw service, error logs like below:
`apigw_1                       | stack traceback:
apigw_1                       | 	[C]: in function 'assert'
apigw_1                       | 	/usr/local/share/lua/5.1/kong/init.lua:429: in function 'init'
apigw_1                       | 	init_by_lua:3: in main chunk
apigw_1                       | 2021/08/16 08:48:45 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:429: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: password authentication failed for user "kong"`

* **How do I fix the *bug*?**
Thanks

**Comment by bizetti** [comment]
Hi,

What is the Operational System you are using?

What is the computer configuration (CPU, memory)?

When you restart the system (dojot), does the problem persist?

Regards.
