### ISSUE TITLE
Deployments: Unused instance of the Redis

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#2238]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
The deployments include an instance of the Redis  to be used by the Device Manager, but seems it is no longer used.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
NA

* **What is the expected behavior?**
Remove the Redis instance of the Device Manager if it's not really used.

* **What is the motivation / use case for changing the behavior?**
NA

* **Please tell us about your environment:**
  NA

**Comment by bizetti** [comment]
Duplicated - see dojot/dojot/#2500
