### ISSUE TITLE
MongoDB - Allow changing data expiration time

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2259]
The new data expiration time has to be efective when the persistence service goes up, independent if it's a new deployment or not.

**Comment by betefaber** [comment]
- **initial setting**

![Captura de tela de 2022-04-27 14-50-32](https://user-images.githubusercontent.com/37310063/165991826-7e5a9be0-64a8-4042-906b-6f5e98c7b891.png)

![Captura de tela de 2022-04-27 15-08-31](https://user-images.githubusercontent.com/37310063/165991883-331960b2-d11b-4114-934f-4f43ca73d935.png)

- **publish data**

![Captura de tela de 2022-04-27 15-08-53](https://user-images.githubusercontent.com/37310063/165991922-64878782-5c16-4320-81c9-44d1d9a83ff2.png)

- **change ttl index setting**

![Captura de tela de 2022-04-27 15-11-33](https://user-images.githubusercontent.com/37310063/165991958-5ad3b283-0ccd-4a2c-a5df-390b049fe40c.png)

- **restart the service**

```
docker-compose kill persister
Killing dojot_persister_1 ... done
```
```
docker-compose up -d persister
dojot_mongodb_1 is up-to-date
dojot_auth-redis_1 is up-to-date
dojot_data-broker-redis_1 is up-to-date
dojot_postgres_1 is up-to-date
dojot_zookeeper_1 is up-to-date
Starting dojot_kong-migrations_1 ... 
Starting dojot_kong-migrations_1    ... done
Starting dojot_kong-migrations-up_1 ... done
dojot_apigw_1 is up-to-date
dojot_auth_1 is up-to-date
dojot_data-broker_1 is up-to-date
Recreating dojot_persister_1        ... done
```
- **`expireAfterSeconds` is changed**

![Captura de tela de 2022-04-27 15-32-31](https://user-images.githubusercontent.com/37310063/165992022-397c13b5-b376-46a4-817c-cdbcc0c64995.png)

- **create a new device**

![Captura de tela de 2022-04-27 15-18-03](https://user-images.githubusercontent.com/37310063/165992062-dbe830ac-47f1-4d40-aeff-1794c41e97bd.png)


- **publish data**

![Captura de tela de 2022-04-27 15-29-41](https://user-images.githubusercontent.com/37310063/165992086-257e6ddf-efde-412b-9338-77440f5ec07a.png)


- **check if after expiration time the data is removed**

```
> show collections
admin_35190b
admin_3749f8
admin_c08ba1
admin_notifications
> db.admin_3749f8.find()
> db.admin_35190b.find()
> 
```
