### ISSUE TITLE
[Iot agent http] It is not possible to publish data using a certificate issued by a trusted CA

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#2318]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

It is not possible to publish data using a certificate issued by a trusted CA. Socket is closed during TLS handshake. 

I ran the `openssl s_client -showcerts -connect` command and saw the "Acceptable client certificate CA names" field. The added trusted CA was only listed when I ran against the mqtt port. See the attached file and search for "CN = My CA"

Commands:
```
openssl s_client -showcerts -connect <HOST>:8883
openssl s_client -showcerts -connect <HOST>:8080
```

[https_trustedCA.txt](https://github.com/dojot/dojot/files/7428325/https_trustedCA.txt)

* **Please tell us about your environment:**
  
  - Version: 0.7.1-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gilmaicor** [comment]
Have the CAs been updated?

**Comment by ctossato** [comment]
No. In http agent conteiner it is not updated. But we can see it on x509 api or at "Acceptable client certificate CA names" field of mqtt agent.

**Comment by ctossato** [comment]
I updated the http-agent-cert-sidecar container with the following environment variables:

> CERT_SC_CERTS_FILES_CABUNDLE: cabundle.crt
> CERT_SC_CRON_CABUNDLE: "true"

Now the cabundle.crt is updated, but the client still can't connect. See the attached files.
[http-agent.log](https://github.com/dojot/dojot/files/7608447/http-agent.log)
[cabundle_test.txt](https://github.com/dojot/dojot/files/7608448/cabundle_test.txt)

**Comment by gilmaicor** [comment]
It is not necessary to define the variables ​​CERT_SC_CERTS_FILES_CABUNDLE and CERT_SC_CRON_CABUNDLE

**Comment by betefaber** [comment]
- cabundle.crt has not been updated yet:

```
mosquitto_pub -h localhost -p 8883 -t admin:711ac5/attrs -m '{"temperature": 30}' --cafile caDojot.crt --cert device_cert_ext.crt --key device_cert_ext.key -d
Client mosqpub|24002-mcity75 sending CONNECT
Error: A TLS error occurred.
```
```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "data": {
        "temperature": 26
      }
  }'   --cacert caDojot.crt --cert device_cert_ext.crt --key device_cert_ext.key
curl: (52) Empty reply from server
```

- cabundle.crt is updated: 

>- publicação mqtt: **OK**
```
iotagent-mqtt-cert-sidecar_1  | 2022-01-10T16:00:00.450Z -- cert-sc-iotagent-mqtt:CertificatesMgmt -- debug: retrieveCRL: Old Fingerprint CRL 4E:1E:3B:0A:B8:B7:E8:A1:67:3F:DB:8E:54:76:08:4C:5E:D4:96:3D:2D:F4:F6:98:EF:E8:E3:FC:5B:4E:5B:B3
iotagent-mqtt-cert-sidecar_1  | 2022-01-10T16:00:00.451Z -- cert-sc-iotagent-mqtt:CertificatesMgmt -- debug: retrieveCRL: New Intention Fingerprint CRL 4E:1E:3B:0A:B8:B7:E8:A1:67:3F:DB:8E:54:76:08:4C:5E:D4:96:3D:2D:F4:F6:98:EF:E8:E3:FC:5B:4E:5B:B3
iotagent-mqtt-cert-sidecar_1  | 2022-01-10T16:00:00.451Z -- cert-sc-iotagent-mqtt:CertificatesMgmt -- debug: retrieveCRL: Is this the First Retrieve? false
iotagent-mqtt-cert-sidecar_1  | 2022-01-10T16:00:00.451Z -- cert-sc-iotagent-mqtt:CertificatesMgmt -- debug: retrieveCRL: Are the CRL differents? false
iotagent-mqtt-cert-sidecar_1  | 2022-01-10T16:00:00.451Z -- cert-sc-iotagent-mqtt:CertificatesMgmt -- info: retrieveCRL: CRL doesn't change
iotagent-mqtt-cert-sidecar_1  | 2022-01-10T16:00:00.451Z -- cert-sc-iotagent-mqtt:CertificatesMgmt -- info: retrieveCRL: ...ending retrieve CRL.
iotagent-mqtt-cert-sidecar_1  | 2022-01-10T16:00:00.454Z -- cert-sc-iotagent-mqtt:Utils -- debug: createFile: Creating a file=/vernemq/cert/cabundle.crt
iotagent-mqtt-cert-sidecar_1  | 2022-01-10T16:00:00.455Z -- cert-sc-iotagent-mqtt:Utils -- info: createFile: /vernemq/cert/cabundle.crt is created!
iotagent-mqtt-cert-sidecar_1  | 2022-01-10T16:00:00.455Z -- cert-sc-iotagent-mqtt:CertificatesMgmt -- info: retrieveCaBundle: ... ending retrieve a CA Certificate Bundle...
```
```
mosquitto_pub -h localhost -p 8883 -t admin:711ac5/attrs -m '{"temperature": 30}' --cafile caDojot.crt --cert device_cert_ext.crt --key device_cert_ext.key -d
Client mosqpub|5265-mcity75 sending CONNECT
Client mosqpub|5265-mcity75 received CONNACK
Client mosqpub|5265-mcity75 sending PUBLISH (d0, q0, r0, m1, 'admin:711ac5/attrs', ... (19 bytes))
Client mosqpub|5265-mcity75 sending DISCONNECT
```
>- publicação http: **NOK**
```
http-agent-cert-sidecar_1     | 2022-01-10T16:00:00.345Z -- cert-sc-http-agent:CertificatesMgmt -- debug: retrieveCRL: Old Fingerprint CRL 4E:1E:3B:0A:B8:B7:E8:A1:67:3F:DB:8E:54:76:08:4C:5E:D4:96:3D:2D:F4:F6:98:EF:E8:E3:FC:5B:4E:5B:B3
http-agent-cert-sidecar_1     | 2022-01-10T16:00:00.345Z -- cert-sc-http-agent:CertificatesMgmt -- debug: retrieveCRL: New Intention Fingerprint CRL 4E:1E:3B:0A:B8:B7:E8:A1:67:3F:DB:8E:54:76:08:4C:5E:D4:96:3D:2D:F4:F6:98:EF:E8:E3:FC:5B:4E:5B:B3
http-agent-cert-sidecar_1     | 2022-01-10T16:00:00.345Z -- cert-sc-http-agent:CertificatesMgmt -- debug: retrieveCRL: Is this the First Retrieve? false
http-agent-cert-sidecar_1     | 2022-01-10T16:00:00.345Z -- cert-sc-http-agent:CertificatesMgmt -- debug: retrieveCRL: Are the CRL differents? false
http-agent-cert-sidecar_1     | 2022-01-10T16:00:00.345Z -- cert-sc-http-agent:CertificatesMgmt -- info: retrieveCRL: CRL doesn't change
http-agent-cert-sidecar_1     | 2022-01-10T16:00:00.345Z -- cert-sc-http-agent:CertificatesMgmt -- info: retrieveCRL: ...ending retrieve CRL.
http-agent-cert-sidecar_1     | 2022-01-10T16:00:00.375Z -- cert-sc-http-agent:Utils -- debug: createFile: Creating a file=/certs/cabundle.crt
http-agent-cert-sidecar_1     | 2022-01-10T16:00:00.379Z -- cert-sc-http-agent:Utils -- info: createFile: /certs/cabundle.crt is created!
http-agent-cert-sidecar_1     | 2022-01-10T16:00:00.379Z -- cert-sc-http-agent:CertificatesMgmt -- info: retrieveCaBundle: ... ending retrieve a CA Certificate Bundle...
http-agent-cert-sidecar_1     | 2022-01-10T16:00:50.463Z -- cert-sc-http-agent:x509IdentityMgmt/Client -- debug: getCACert: Getting the CA certificate...
```
```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "data": {
        "temperature": 26
      }
  }'   --cacert caDojot.crt --cert device_cert_ext.crt --key device_cert_ext.key
curl: (52) Empty reply from server
```

**Comment by betefaber** [comment]
**Preconditions**:

- healthy services
- Trusted CA registered
- certificate signed by this trusted CA registered


**certificado assinado pela Dojot: OK**

mosquitto_pub -h localhost -p 8883 -t admin:2a1503/attrs --cafile caDojot.crt --cert admin_2a1503.crt --key admin_2a1503.key -m '{"temperature": 20}' -d
Client mosqpub|22188-mcity75 sending CONNECT
Client mosqpub|22188-mcity75 received CONNACK
Client mosqpub|22188-mcity75 sending PUBLISH (d0, q0, r0, m1, 'admin:2a1503/attrs', ... (19 bytes))
Client mosqpub|22188-mcity75 sending DISCONNECT

curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "data": {
        "temperature": 16
      }
  }'   --cacert caDojot.crt --cert admin_2a1503.crt --key admin_2a1503.key

**certificado externo**

- MQTT: **OK**

mosquitto_pub -h localhost -p 8883 -t admin:711ac5/attrs -m '{"temperature": 51}' --cafile caDojot.crt --cert device_cert_ext.crt --key device_cert_ext.key -d
Client mosqpub|636-mcity75 sending CONNECT
Client mosqpub|636-mcity75 received CONNACK
Client mosqpub|636-mcity75 sending PUBLISH (d0, q0, r0, m1, 'admin:711ac5/attrs', ... (19 bytes))
Client mosqpub|636-mcity75 sending DISCONNECT

- HTTP: **NOK**

curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "data": {
        "temperature": 15
      }
  }'   --cacert caDojot.crt --cert device_cert_ext.crt --key device_cert_ext.key
curl: (52) Empty reply from server


**data is only sent after http agent service is restarted**

mosquitto_pub -h localhost -p 8883 -t admin:711ac5/attrs -m '{"temperature": 41}' --cafile caDojot.crt --cert device_cert_ext.crt --key device_cert_ext.key -d
Client mosqpub|25885-mcity75 sending CONNECT
Client mosqpub|25885-mcity75 received CONNACK
Client mosqpub|25885-mcity75 sending PUBLISH (d0, q0, r0, m1, 'admin:711ac5/attrs', ... (19 bytes))
Client mosqpub|25885-mcity75 sending DISCONNECT


curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "data": {
        "temperature": 14
      }
  }'   --cacert caDojot.crt --cert device_cert_ext.crt --key device_cert_ext.key

![Captura de tela de 2022-01-12 09-27-30](https://user-images.githubusercontent.com/37310063/149144761-c51127ed-2407-403b-9128-a5e3a3d93f81.png)

**Comment by betefaber** [comment]
Fixed by [https://github.com/dojot/dojot/pull/2471](url).

- cabundle.crt has not yet been updated

![image](https://user-images.githubusercontent.com/37310063/152034189-59248a05-a769-4ce7-8dbd-788a9fad53da.png)

----
- cabundle.crt is updated

```
http-agent_1                  | 2022-02-01T18:15:00.196Z -- http-agent:Server -- debug: File changed cabundle.crt (event: change)
http-agent_1                  | 2022-02-01T18:15:00.196Z -- http-agent:Server -- info: Reloading secure context...
http-agent_1                  | 2022-02-01T18:15:00.197Z -- http-agent:Server -- info: Reloading secure context succeeded!
http-agent_1                  | 2022-02-01T18:15:00.197Z -- http-agent:Server -- debug: File changed cabundle.crt (event: change)
http-agent_1                  | 2022-02-01T18:15:00.197Z -- http-agent:Server -- info: Reloading secure context...
http-agent_1                  | 2022-02-01T18:15:00.198Z -- http-agent:Server -- info: Reloading secure context succeeded!
```

```
http-agent-cert-sidecar_1     | 2022-02-01T18:15:00.016Z -- cert-sc-http-agent:CertificatesMgmt -- info: retrieveCaBundle: Retrieving  a CA Certificate Bundle...
http-agent-cert-sidecar_1     | 2022-02-01T18:15:00.016Z -- cert-sc-http-agent:x509IdentityMgmt/Client -- debug: getCABundle: Getting the trusted CA's certificate bundle...
http-agent-cert-sidecar_1     | 2022-02-01T18:15:00.195Z -- cert-sc-http-agent:Utils -- debug: createFile: Creating a file=/certs/cabundle.crt
http-agent-cert-sidecar_1     | 2022-02-01T18:15:00.196Z -- cert-sc-http-agent:Utils -- info: createFile: /certs/cabundle.crt is created!
http-agent-cert-sidecar_1     | 2022-02-01T18:15:00.196Z -- cert-sc-http-agent:CertificatesMgmt -- info: retrieveCaBundle: ... ending retrieve a CA Certificate Bundle...
http-agent-cert-sidecar_1     | 2022-02-01T18:15:08.988Z -- cert-sc-http-agent:x509IdentityMgmt/Client -- debug: getCACert: Getting the CA certificate...
```
```
/certs # ls -lrt
total 20
-rw-r--r--    1 root     root          1678 Feb  1 17:59 http-agent.key
-rw-r--r--    1 root     root          1918 Feb  1 17:59 http-agent.crt
-rw-r--r--    1 root     root          2109 Feb  1 17:59 ca.crt
-rw-r--r--    1 root     root          1079 Feb  1 17:59 ca.crl
-rw-r--r--    1 root     root          3652 Feb  1 18:15 cabundle.crt
/certs #
```
```
iotagent-mqtt-cert-sidecar_1  | 2022-02-01T18:15:00.016Z -- cert-sc-iotagent-mqtt:CertificatesMgmt -- info: retrieveCaBundle: Retrieving  a CA Certificate Bundle...
iotagent-mqtt-cert-sidecar_1  | 2022-02-01T18:15:00.195Z -- cert-sc-iotagent-mqtt:Utils -- info: createFile: /vernemq/cert/cabundle.crt is created!
iotagent-mqtt-cert-sidecar_1  | 2022-02-01T18:15:00.195Z -- cert-sc-iotagent-mqtt:CertificatesMgmt -- info: retrieveCaBundle: ... ending retrieve a CA Certificate Bundle...
```
```
bash-5.1$ cd cert/
bash-5.1$ ls -lrt
total 20
-rw-r--r--    1 root     root          1678 Feb  1 17:59 iotagent-mqtt.key
-rw-r--r--    1 root     root          1926 Feb  1 17:59 iotagent-mqtt.crt
-rw-r--r--    1 root     root          2109 Feb  1 17:59 ca.crt
-rw-r--r--    1 root     root          1079 Feb  1 17:59 ca.crl
-rw-r--r--    1 root     root          3652 Feb  1 18:15 cabundle.crt
bash-5.1$ 
```

![image](https://user-images.githubusercontent.com/37310063/152034710-79e82808-1e3f-483b-8b32-263e68992b1e.png)

![image](https://user-images.githubusercontent.com/37310063/152035138-c246669b-ad15-4794-b13d-ceff16107589.png)

![image](https://user-images.githubusercontent.com/37310063/152040217-b26c9d73-4eae-4d21-aee8-1bd010e16a96.png)

----
- after new cabundle updates data continues to be sent 

![image](https://user-images.githubusercontent.com/37310063/152036716-b82d2e1f-7469-42de-ad07-52edd18420c3.png)

![image](https://user-images.githubusercontent.com/37310063/152036927-1996d285-8124-4711-a8a1-9f69e376a560.png)
