### ISSUE TITLE
[GUI-v1] Report generate: initial period is always AM

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2335]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Initial period is always AM.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
The period for generating the report is in AM/PM format.
The initial period for generating the report is always AM, even if requested in another period.

![Captura de tela de 2021-11-10 16-57-53](https://user-images.githubusercontent.com/37310063/141310951-ae60355a-8d55-497d-bc2b-40de177fa3e6.png)

![Captura de tela de 2021-11-10 16-54-42](https://user-images.githubusercontent.com/37310063/141310982-2a396864-a21e-4f5e-89fc-1ba9f9e892cc.png)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: **0.7.1-rc.1**
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by FrancielePessi** [comment]
google chrome
![Captura de tela de 2022-02-03 11-12-06](https://user-images.githubusercontent.com/52173618/152359327-3cbe68d0-9210-4312-9bc9-c42f490f20e0.png)

![Captura de tela de 2022-02-03 11-12-31](https://user-images.githubusercontent.com/52173618/152359405-15ba02e7-ea4e-4624-9282-5b2e0185b252.png)

Firefox
![Captura de tela de 2022-02-03 11-13-16](https://user-images.githubusercontent.com/52173618/152359532-79451947-5887-4a6a-bb25-3c7a492f03e2.png)

![Captura de tela de 2022-02-03 11-13-51](https://user-images.githubusercontent.com/52173618/152359601-4e4eb8f2-cf9c-4877-be6d-561b5dcd0486.png)

**Comment by FrancielePessi** [comment]
Test Done - Firefox AM - (OK)

![Captura de tela de 2022-02-03 11-20-13](https://user-images.githubusercontent.com/52173618/152360972-8696378f-6084-4666-8427-69396375ec77.png)

Test Done - Firefox PM - (OK)
![Captura de tela de 2022-02-03 12-01-46](https://user-images.githubusercontent.com/52173618/152368739-5f9d5710-fc09-4064-933d-c9c1a595ac60.png)



Google chrome - Test performed - However, neither AM nor PM is displayed, and the date 
format in the English browser is in the Brazilian format.  
![Captura de tela de 2022-02-03 11-31-28](https://user-images.githubusercontent.com/52173618/152362790-ac6c84d5-ebf1-48d0-94d6-782620acf7d4.png)

______________________
![Captura de tela de 2022-02-03 11-25-48](https://user-images.githubusercontent.com/52173618/152361668-df3e614e-167d-47be-9339-d9df9d1a51f6.png)

**Comment by FrancielePessi** [comment]
**_Difference between browsers_** 

**Test performed: Firefox Browser 
Dojot version: 0.8.0 - rc2
Note: AM and PM are displayed on the screen.** 

![Seleção_002](https://user-images.githubusercontent.com/52173618/169894569-47dd423b-02e4-4b31-8d2c-255de871af57.png)


**Test performed: Google Chrome Browser
Dojot version: 0.8.0 - rc2
Note: AM and PM are not displayed on the screen.** 
![Seleção_003](https://user-images.githubusercontent.com/52173618/169896044-41cc702a-699f-4fab-8d34-d5637c42f7cc.png)
