### ISSUE TITLE
[ansible] Distributed volumes

### ISSUE THREAD

**Issue by danielapetito** [dojot/dojot#2338]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Distributed volumes

* **What is the current behavior?**
Local volumes

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Local volume problem with 2 workers

* **Please tell us about your environment:**
  
  - Version: 0.2.x
  - Environment: [kubernetes, docker-compose, standalone]
  - Operating system: [Ubuntu 16.04, Fedora 28, Ubuntu on VirtualBox (Windows 10), etc.]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by danielapetito** [comment]
efetuado estudo do glusterfs + heketi mas identificado que o glusterfs necessita de um device/filesystem dedicado e não aceita um diretório ou filesystem compartilhado para uso.

devido a limitação do glusterfs, optamos por usar o NFS que permite o uso de diretório compartilhado.

configurado as tasks no playbook da dojot para permitir uso de local-storage e NFS.

criado NFS server no servidor 10.50.4.36 (servidor fora do cluster k8s)

estamos trabalhando com PV dinâmico e PV estático:
   – PV estático: Minio, Kafka, InfluxDB, Mongo, Postgres, Zookeeper
   – PV dinâmico: demais serviços

efetuado teste, com sucesso, com local-storage (node_affinity = false e true) e NFS (node_affinity = false e true).

   - teste MQTT = envio msg com mosquito_pub, mosquitto_sub com e sem certificado
   - teste HTTP = envio msg curl 
   - teste criação template e device via curl


PR = https://github.com/dojot/ansible-dojot/pull/166

**Comment by danielapetito** [comment]
Alterado a documentação de instalação da dojot com as informações para volume NFS

Documentação disponível em: https://docs.google.com/document/d/14YLLyA49vFqaczoQ7omABpKcd_B_E5ngb07FYAN8c7Y/edit#

**Comment by danielapetito** [comment]
aberto chamado https://app.zenhub.com/workspaces/dojot-ws-5ca7620c263982676581b05d/issues/dojot/dojot/2498
 para verificar redis dos serviços

**Comment by luissajunior** [comment]
Este ticket será tratado no board de devops
