### ISSUE TITLE
X.509 - Documentation missing information on certificate creation

### ISSUE THREAD

**Issue by luisfelipefurlan** [dojot/dojot#2361]
In the certificate creation documentation it is not listing the need for the "Authorization" property

![image.png](https://images.zenhubusercontent.com/5e4d1c6f8f780f8140f8fdf8/aa09eaf9-fe34-4aa2-b552-c900c1a941b8)

**Comment by heitorlucas2018** [comment]
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.7.0.html#x.509-endpoint-for-certificates-in-general-post
