### ISSUE TITLE
Autorization/Autentication - Keycloak integration - Phase II

### ISSUE THREAD

**Issue by luissajunior** [dojot/dojot#2382]
- [x] Subir ambiente plugin do keycloak criando anteriormete pela mari e thiago  (Heitor)
  - [x] Criar novo realm proxy ao iniciar a dojot  (Heitor)
  - [x] [Proxy] Criar serviço (Rodrigo)
  - [x] [Proxy] Comunicar proxy com keycloak (Rodrigo)
  - [x] [Proxy] Ler secrets ao iniciar (Rodrigo)
  - [x] Verificar possibilidades de integrar kafka com keycloak (Rodrigo)
  - [x] Geração de secrets no cofre (Heitor)
  - [x] Rota de tenants no keycloak-proxy  (Rodrigo)
  - [x] Autenticação no keycloak (Rodrigo)
  - [x] Autenticação generalizada para o sdk (Rodrigo)
  - [x] Validação dos access_tokens no serviços (comunicação entre os serviços) (Rodrigo)
  - [x] Publicação da chave no kafka quando um novo realm for criado no keycloak (Heitor)
  - [x] Ouvir alterações de certificado do realm e disparar no kafka

**Comment by rodrigoaasm** [comment]
About the integration between kafka and keycloak it is necessary to implement a custom extension. There are
custom third-party kafka images that allow integration with keycloak, but I don't recommend.
