### ISSUE TITLE
GUI NX - Search mechanisms - A&D

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2413]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.2.x
  - Environment: [kubernetes, docker-compose, standalone]
  - Operating system: [Ubuntu 16.04, Fedora 28, Ubuntu on VirtualBox (Windows 10), etc.]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by LuanEdCosta** [comment]
**Problem**
The search in all pages only filters by a single field, ex: device name (devices page), template name (templates page), fingerprint (certificates and certification authorities).

**Possibilities**
- Can search by all fields using a text. Example: searching for "1" should return all items that contains "1" in any of its data (name, creation date, number of attrs, etc)
- Complex filter like Gmail to search items with a specific data
- Select field to search and then write in the search input to filter items by a single field
