### ISSUE TITLE
Device Manager - Returns a single page when filtering by device label 

### ISSUE THREAD

**Issue by LuanEdCosta** [dojot/dojot#2419]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
  - Endpoint used: https://dojot.github.io/device-manager/apiary_v0.7.0.html#devices-device-info-get-1
  - When filtering devices by label, the API only returns a single page

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
  - Create 10+ devices with a similar name. Ex: starting with "Device"
  - Make a request to [this endpoint](https://dojot.github.io/device-manager/apiary_v0.7.0.html#devices-device-info-get-1) with this query string: `?page_size=10&page_num=1&label=Device&sortBy=label`
  - The API will only return a single page: `pagination.total === 1`

**Example:**

The API returned 9 devices and shows that there is just a single page, but I have 14 devices with a similar name.

![image](https://user-images.githubusercontent.com/36794274/147689241-ef27703e-1b6d-44d3-ab5a-cde30f791c24.png)

I can get the second page with the other 5 missing devices, but I need to know that there is a next page. In the GUI NX front-end code the pagination buttons get disabled when there is no next page.

![image](https://user-images.githubusercontent.com/36794274/147689579-a9f7248e-1e6a-43d7-9ce0-ae9183263666.png)

* **What is the expected behavior?**
  - The API should return two pages or more, depending of the number of devices with a similar label.

* **What is the motivation / use case for changing the behavior?**
  - This is necessary to the GUI NX works properly

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  - The GUI NX uses the Backstage API that is a wrapper around other Dojot APIs, but I'm sure that there is nothing wrong with that code. You can check the [backstage code here](https://github.com/dojot/backstage/blob/development/src/operations/device/query.getDevices.js)

**Comment by betefaber** [comment]
https://github.com/dojot/dojot/issues/723

**Comment by betefaber** [comment]
**Steps to reproduce the problem**: 

1. import the database: there are 15 `devices` with 2 templates and 15 `dispositivos` with only 1 template
[DojotData_2419.json.txt](https://github.com/dojot/dojot/files/9141576/DojotData_2419.json.txt)   (json attached as txt)

2. filter by **device**

- 6 devices per page: returns only 3 elements

![Captura de tela de 2022-07-19 10-52-23](https://user-images.githubusercontent.com/37310063/179767704-f8ab30b6-3252-40a8-8aed-fb966654bac7.png)


- 12 devices per page: returns only 6 elements

![Captura de tela de 2022-07-19 10-52-29](https://user-images.githubusercontent.com/37310063/179767660-45e8268b-0a22-4def-9df6-c0eebb3b8cc0.png)


- 18 devices per page: returns only 9 elements

![Captura de tela de 2022-07-19 10-52-35](https://user-images.githubusercontent.com/37310063/179767617-1e2c4592-93b7-459b-a475-e540a82d1054.png)


- 36 devices per page: returns all 15 elements

![Captura de tela de 2022-07-19 10-52-41](https://user-images.githubusercontent.com/37310063/179767523-d2402af4-e71e-463c-b40b-d5f6356976db.png)


3. filter by **dispositivo**

- 6 devices per page: returns the 15 elements in 3 pages

![Captura de tela de 2022-07-19 10-53-07](https://user-images.githubusercontent.com/37310063/179767487-9df36de0-7dd5-4638-9581-e8ca464f01c5.png)
