### ISSUE TITLE
[GUI-v1] Date in American format

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2429]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
report bug

* **What is the current behavior?**
Date in American format

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1° Add template with dynamic attributes string value

2° Add to a device 

3° Send data 
mosquitto_pub -h localhost -p 1883 -t admin:a0ea77/attrs -m '{"test": "test"}' -q 1 -u admin:a0ea77 

![Captura de tela de 2022-01-12 09-31-35.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/8eff43a7-1f88-4701-a4f0-bf16cdc25906)

* **Please tell us about your environment:**
  - Version: v0.7.1-rc.2
  - Environment: [kubernetes and docker-compose]
  - Operating system: [Ubuntu 16.04]

**Comment by bizetti** [comment]
Verify using Browser's portuguese confirguration.

**Comment by FrancielePessi** [comment]
Solution: Problem with cache or browser in the specific language (English or Portuguese-Brazil), dates are referring to this configuration, error does not happen.
