### ISSUE TITLE
GUI NX - Show associated certificate on device details page

### ISSUE THREAD

**Issue by LuanEdCosta** [dojot/dojot#2433]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
The associated certificate is not shown in the devices details page

* **What is the expected behavior?**
Show the associated certificate and (if possible) a link to the certificate

* **What is the motivation / use case for changing the behavior?**
The user should see on device details page if the device has an associated certificate

**Comment by FrancielePessi** [comment]
NX GUI Tested Version: Version: DEV-220816 (OK)

![2433.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/771bd684-19f7-4c11-a372-357478bedb62)
