### ISSUE TITLE
GUI-NX [v-guinx-18.01.22] - Generate/Load C.A.-Text is not user-intuitive.

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2452]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request
  - [x] improvement

Informational text for users is not in the best form, **what text should be inserted ?** - not intuitive  
![Captura de tela de 2022-01-21 11-19-25.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/14c4bafe-6220-415b-9902-9639bf0124f7)

* **Please tell us about your environment:**
  
  - Version: v-guinx-18.01.22
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 16.04]

**Comment by bizetti** [comment]
Verificar também na criação de certificado usando csr, e usar meu certificado.
