### ISSUE TITLE
[GUI NX ] v-guinx-18.01.22 - Translation

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2473]
Translation of Device and Template, does not correspond with the source language (Portuguese (Brazil))

Table Widget
![Captura de tela de 2022-01-31 14-09-30.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/8a5faf19-8aad-4213-997c-bdc1b3df6658)

Map Widget 
![Mapa .png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/e7500c61-c2d1-473f-98cc-bb305dca91c1)

* **Please tell us about your environment:**
  
  - Version: v-guinx-18.01.22
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 16.04]

**Comment by LeonamMoura** [comment]
Here it should also be corrected
![image.png](https://images.zenhubusercontent.com/613a14a187b4f6dfe29f2121/c0649c15-0c49-4d93-9458-57231efb85b8)

**Comment by FrancielePessi** [comment]
Test version: v-guinx-03-02-22

Not resolved in the current version. 

![Captura de tela de 2022-03-11 11-25-53.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/f34f9516-6b07-438e-921a-aae839d809be)

**Comment by FrancielePessi** [comment]
test version: v-guinx-03-02-22

Solved in the current version.

![Captura de tela de 2022-03-11 11-28-17.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/d79a1dc0-9c19-4eda-bf66-d9526c4a9e00)
