### ISSUE TITLE
GUI V1 - It's not possible create device

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#2532]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
It's not possible create device

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Try to create device via GUI V1

* **What is the expected behavior?**
Create a device

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.8.0
  - Environment: [kubernetes, docker-compose]
  - Operating system: [Ubuntu 16.04, 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Check object used by GUI V1 (attribute ID). Now, the backend allows entering ID by user.

**Comment by FrancielePessi** [comment]
Tested on version 0.8.0 - rc2 
Resolution: Device was created successfully 

![Seleção_005](https://user-images.githubusercontent.com/52173618/170480464-b8489642-c69f-47cb-9599-6bea97629bc4.png)

![Seleção_006](https://user-images.githubusercontent.com/52173618/170480489-726f48b4-190f-401f-b080-565b893cc143.png)

**Comment by FrancielePessi** [comment]
Version tested: **0.8.0 - rc6**
Ambient version: **k3s**

![2532](https://user-images.githubusercontent.com/52173618/185479464-51484da9-5e82-4106-b271-1ad26eabb4a6.png)
