### ISSUE TITLE
[GUI NX] - Color Selection does not work.

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2550]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

Color Selection does not work.
![image (2).png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/9d5ff908-b6ef-46ff-878f-5c217cce2496)

**Page inspection capture is without information for this problem**

![Captura de tela de 2022-04-11 10-13-13.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/463a3cbb-bba0-44d1-894f-0d6167d5abc5)

* **Please tell us about your environment:**
  
  - Version: GUI-NX
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 16.04]

**Comment by rascaraficci** [comment]
Será tratado (possível solução é a troca do componente de paginação).

**Comment by FrancielePessi** [comment]
Still with the same error - Version released 06 May

![Captura de tela de 2022-05-16 14-44-06.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/b1f222a7-358c-42f1-8b24-3fc72b0e17c8)
