### ISSUE TITLE
[GUI NX] - Inform user that device is a required field. 

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2553]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request
 -  [X] improvement 

Inform user that device is a required field in widget configuration.  

![Captura de tela de 2022-04-11 13-18-09.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/33818323-8632-4726-b29a-3b92b585a1e8)

* **Please tell us about your environment:**
  
  - Version: GUI NX
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 16.04]

**Comment by rascaraficci** [comment]
Será tratado para micro-frontend

**Comment by FrancielePessi** [comment]
Ticket tested in version - Version: DEV-220816 (OK)

![2553.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/a03888f8-c852-4d74-9b3f-30eabf70d35c)
