### ISSUE TITLE
[GUI NX] - Template creation message

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2558]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request
  - [x] improvement

Inform the user that a template has been created with a message and a [new] icon on the same line as the added template. 

![Captura de tela de 2022-04-12 11-48-44.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/0f48b140-d23a-4148-9532-9faedc5a511b)

**Difficult visualization of the new template** 
![Captura de tela de 2022-04-12 11-48-51.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/baaa5cb4-04e1-43ee-9788-0a516d63a4e9)

* **Please tell us about your environment:**
  
  - Version: GUI NX
  - Environment: [kubernetes]
  - Operating system: [Ubuntu 16.04]

**Comment by bizetti** [comment]
Sugestão: ao criar o template, colocá-lo em primeiro na lista.

**Comment by FrancielePessi** [comment]
Ticket tested in version - Version: DEV-220816 (OK)

![2558.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/27a05be2-4585-40ee-8f5d-cbc70b49662c)
