### ISSUE TITLE
GUI - Map Visualization - Why not 'loading' instead of 'dummy'?

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#256]
In the Map Visualization screen, before the map been loaded , it is shown the text 'dummy'. It would be better a message like 'loading'.

![image](https://user-images.githubusercontent.com/31006659/36686977-f35080c6-1b06-11e8-86e6-6886d626d2fe.png)

**Comment by fernandoMessias** [comment]
This PR: https://github.com/dojot/gui/pull/75 solve this problem. When implementing realtime I changed the text "dummy" to the 'loading'.
