### ISSUE TITLE
GUI - Map Visualization - How to identify the mode (map, hibrid, sattelite) in use?

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#257]
Why not to distinguish the current map mode is being used? When you click on the icon to change the mode, nothing allows to identify the current mode.

![image](https://user-images.githubusercontent.com/31006659/36687145-7533f92e-1b07-11e8-8a39-5b213294e647.png)

**Comment by betefaber** [comment]
Added radio button to identify the current map mode.

![screenshot_12](https://user-images.githubusercontent.com/37310063/48082744-837e1b00-e1da-11e8-87bc-02d2380fddc3.png)

![screenshot_13](https://user-images.githubusercontent.com/37310063/48082748-8711a200-e1da-11e8-9b85-193f6ca5eddb.png)
