### ISSUE TITLE
[v0.8.0 - rc2] - Difference between browsers AM/PM ( Report Generator  )

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2578]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

Difference between browsers

Test performed: Firefox Browser
Dojot version: 0.8.0 - rc2
Note: AM and PM are displayed on the screen.

![Seleção_002.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/099ba633-f6c8-40de-b63e-b6f937c7bb69)

Test performed: Google Chrome Browser
Dojot version: 0.8.0 - rc2
Note: AM and PM are not displayed on the screen.

![Seleção_003.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/e9ed4346-0e24-429b-bfd9-7612be6e67a6)

**### Reference:** https://github.com/dojot/dojot/issues/2335 

  - Version: 0.8.0 - rc2
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 16.04]

**Comment by bizetti** [comment]
Won't be fixed.
