### ISSUE TITLE
[GUI NX - v-guinx-19-05-22] - Permanence of notification toasts. 

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2591]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request
  - [x] improvement

Notification toasts are being displayed for (13 seconds), too long to be displayed on screen, hint (5 seconds) and when the user switches screens, the toasts should disappear.

![2022-06-22_10-59.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/222de408-6def-46de-a7c1-9ecf0114037d)

* **Please tell us about your environment:**
  
  - Version: v-guinx-19-05-22
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 20.04]

**Comment by bizetti** [comment]
Won't be fix now.
