### ISSUE TITLE
[Auth] - Error 429

### ISSUE THREAD

**Issue by fernandoMessias** [dojot/dojot#260]
After posting some values to a device, this error started appearing and since then I can't publish anything else.

![selecao_023](https://user-images.githubusercontent.com/14092710/36742796-57ff4c44-1bc7-11e8-90aa-4bdeb5d34031.png)
![selecao_024](https://user-images.githubusercontent.com/14092710/36742797-58357e18-1bc7-11e8-82da-32d2b8b66015.png)

**Comment by mmagr** [comment]
@fernandoMessias were you posting device data or attempting to login?

Both the error and URL presented on your screenshot make me think we're dealing with an authentication error, rather than a device error.

**Comment by mmagr** [comment]
As seen by dojot/gui@610de75 `auth` doesn't need to be called for every websocket operation on the GUI.

Since that was the reason behind the error being rightfully returned by the API gateway, I'm closing this.
