### ISSUE TITLE
GUI - Text 'No configured devices' is not vertically centralized

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#264]
In the device list screen, the text 'No configured devices' appears at the top of the page, in the other screens (templates, flow) the text is vertically centralized.

**Comment by betefaber** [comment]
Text 'No devices to be shown' is not vertically centralized.

**Comment by betefaber** [comment]
Text "No configured devices" is not vertically centralized.

Affected version: **0.3.0-nightly20180604**
