### ISSUE TITLE
Backend - MQTT topic is not uptated

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#267]
Scenario:

1) Create a template with a specific MQTT topic
2) Publish data using the specific topic [OK]
3) Change the MQTT topic into the template
4) Publish data  using the newer topic [NOK]

[iot-agent log]
ID /newer-topic was not found in resolver cache
No device ID was detected. Skipping this message

**Comment by betefaber** [comment]
![image](https://user-images.githubusercontent.com/37310063/40994974-28e6e7fa-68d4-11e8-859d-f38e3bb563e0.png)
