### ISSUE TITLE
Flow Manager - It's not possible to create a flow starting at a device

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#268]
There is no way to choose a device as input.

![image](https://user-images.githubusercontent.com/31006659/37049244-11d4095c-214f-11e8-987f-44d7c8921419.png)

![image](https://user-images.githubusercontent.com/31006659/37049333-5aa5eb50-214f-11e8-87a3-b61bc2ed35a4.png)

**Comment by mmagr** [comment]
This should be fixed in dojot-nightly/docker-compose@4441afe

@rascaraficci can you please verify?

**Comment by rascaraficci** [comment]
It's Ok!

![image](https://user-images.githubusercontent.com/31006659/37204733-d200875a-2370-11e8-85d4-5339addddca5.png)
