### ISSUE TITLE
Flow Manager - Geofence node doesn't show the map

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#269]
It's not possible to define an area for a geofence node. The map is not displayed.

![image](https://user-images.githubusercontent.com/31006659/37049576-05f4e8b2-2150-11e8-8d14-f11041e04fc5.png)

**Comment by mmagr** [comment]
This should be fixed in dojot-nightly/docker-compose@4441afe

@rascaraficci can you please verify?

**Comment by rascaraficci** [comment]
the map is being loaded.
