### ISSUE TITLE
Flow Manager - It's not possible to set a device as output

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#274]
There is no way to choose a device as output (virtual device).

![image](https://user-images.githubusercontent.com/31006659/37051039-39acc5a4-2154-11e8-9827-1915b3eacbdc.png)

**Comment by mmagr** [comment]
This should be fixed in dojot-nightly/docker-compose@4441afe

@rascaraficci can you please verify?

**Comment by rascaraficci** [comment]
It's Ok!

![image](https://user-images.githubusercontent.com/31006659/37204691-9e2f9a38-2370-11e8-97b0-ee067ed873c7.png)
