### ISSUE TITLE
Flow Manager - The name of some nodes change

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#275]
The name of the following nodes:

- 'http request'
- 'template'
- 'change'

change when you drag them to the drawing area.

![image](https://user-images.githubusercontent.com/31006659/37051602-add690e4-2155-11e8-87e0-1e6c916e2b2c.png)

**Comment by mmagr** [comment]
That behavior (the changing of names, that is) is actually expected.
Some nodes define custom labels should the user have not provided a `name` value.

Breaking down:
- **Template**: its behavior was to **always** use the `name` value. This will be updated to use "template" if a `name` is not yet set.
- **Change**: its behavior is to describe what is being changed, if no `name` is provided. This will be kept.
- **http request**: This was actually a bug in the i18n module update. Will be fixed.

**Comment by mmagr** [comment]
This should be fixed in dojot-nightly/docker-compose@4441afe

@rascaraficci can you please verify?

**Comment by rascaraficci** [comment]
It's fine!
