### ISSUE TITLE
Flow Manager - Missing labels next to icons  

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#276]
Many nodes are missing labels next to icons in the edition sidebar.

- 'http request'

![image](https://user-images.githubusercontent.com/31006659/37052035-d36244b0-2156-11e8-975f-3017527e3096.png)

- 'switch'

![image](https://user-images.githubusercontent.com/31006659/37052068-edb87dd4-2156-11e8-9109-1186f44107b4.png)

- 'change'

![image](https://user-images.githubusercontent.com/31006659/37052093-052af834-2157-11e8-8990-9a98342a1243.png)

- 'edge detection'

![image](https://user-images.githubusercontent.com/31006659/37052112-1752fc64-2157-11e8-91be-3be1bb5dce61.png)

- 'email'

![image](https://user-images.githubusercontent.com/31006659/37052130-26b0edce-2157-11e8-92cc-8528341d442b.png)

**Comment by mmagr** [comment]
This should be fixed in dojot-nightly/docker-compose@4441afe

@rascaraficci can you please verify?

**Comment by rascaraficci** [comment]
Bug was fixed!
