### ISSUE TITLE
Flow Manager/GUI - No error message when try to save flow with empty name

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#283]
Scenario:

1) create a flow
2) keep its name empty
3) click on save
    - No message appears. The user doesn't know if it was saved or not!
4) click on dismiss
    - The flow disapears

**Comment by betefaber** [comment]
Test OK.

The message "Flow name is required" is displayed.

![screenshot_58](https://user-images.githubusercontent.com/37310063/46549356-13613a00-c8a8-11e8-82a0-975df7db2840.png)
