### ISSUE TITLE
Flow Manager/GUI: Problem to set geofence node

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#284]
When you start drawing a polygon or a rectangle in the geofence node, there is no way to finish the drawing.  

![image](https://user-images.githubusercontent.com/31006659/37207337-4bdb5d2a-237b-11e8-8d14-e94142945714.png)

![image](https://user-images.githubusercontent.com/31006659/37207316-3aa8e31a-237b-11e8-99ac-7a01fc79aca9.png)

**Comment by rascaraficci** [comment]
Draw a polygon - the action 'Click first point to close the shape' is not working. It stops drawing only when you click on the 'finish'.

**Comment by mmagr** [comment]
This was actually a problem on [leaflet.draw](https://github.com/Leaflet/Leaflet.draw/issues/665). Component has been upgraded.

**Comment by betefaber** [comment]
The problem has been corrected.
![Screenshot_5.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf11fbcd6395428792c07b7692ac7b671bd1478020c594aac170a5c40fcf98a7ef2b638268f0919f1c32f0e2a92624cf5f2d75dad0ba821834584b3be8f44c0ea3c23e68f86482c53.png)

![Screenshot_6.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf21fbcd6395428792c07b7692ac7b671bd1478020c594aac170a5c40fcf98a7ef2b638268f0919f1c32f0e2a92624cf5f2d75dad0ba821834584b3be8f44c0ea3c22e48a8c472c53.png)
