### ISSUE TITLE
GUI - Device status

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#289]

**Comment by betefaber** [comment]
![issue289.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46e187893687d1f1d6abf301b44fff9e2c4533317346f67272d3e02bbc142f51090d4da841585c11a8f98d7da3e32e6c981e5ab38532022d8c6853beb2901eb70bbb25894a82b4bd8344c5e83b27f5c6.png)
