### ISSUE TITLE
GUI - Forgot password

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#292]

**Comment by betefaber** [comment]
Implemented.

![forgot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46ee9b88248d97ebc3abaf51ab57f5973d047d317c5da17d7386e07eeb127d035c5b4eac420d0b44f8af8c7eb4aa2e32db025fb28c341521842f1bbeb98515be04b82888468cb3bb824ac0e82f68.png)

![tela_forgot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46fc919622bd85a69deeb057e611b2843b492d762a10e17132d0ba2ae9417802595b4efa135b5b44fcfadc7fa6b26a75df4e17ff933c0120996048e6edc00db513bb27814e80b4b48945c9ed3522ef898e5d73.png)
