### ISSUE TITLE
Flow Manager - It's not processing data

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#293]
I created a basic flow to process a 'float attribute' with a 'switch node' and write a 'string value' to a virtual device, but nothing happened. No data was sent to the virtual device.

![image](https://user-images.githubusercontent.com/31006659/37345444-bccd1ee6-26ab-11e8-8aee-001b78977d7d.png)

**Comment by rascaraficci** [comment]
Basic flows are working now!

**Comment by danielnunesdeoliveira** [comment]
Hello again.
I am trying to do this example:
![image](https://user-images.githubusercontent.com/29581014/41245098-728ec2f8-6d7d-11e8-8459-a430a338c21e.png)

But it is not working.
1) 
![01](https://user-images.githubusercontent.com/29581014/41245146-9788365c-6d7d-11e8-8a5f-3df3f4f6a67e.PNG)
2)
![02](https://user-images.githubusercontent.com/29581014/41245148-97cf2260-6d7d-11e8-8828-313c8f4f7b99.PNG)
3)
![03](https://user-images.githubusercontent.com/29581014/41245149-97f336d2-6d7d-11e8-8f97-911585975732.PNG)

**Comment by giovannicuriel** [comment]
Hi!
Check if you can connect to the e-mail server (in this case gmail-smtp-in.l.google.com) through port 25. A quick and dirty way of doing that is trying to open a telnet session:

```bash
telnet gmail-smtp-in.l.google.com 25
```

If it simply says that the host is unreachable (or any other similar error), then you should check your network configuration (which will likely involve firewall configuration).

**Comment by danielnunesdeoliveira** [comment]
Hi!!
Now, It is working.
![image](https://user-images.githubusercontent.com/29581014/41352291-7a4c6306-6eef-11e8-8ea9-55063b4914ae.png)
The problem was VM's firewall configuration. 

Thank you.
