### ISSUE TITLE
GUI - Filter in the device list is not working properly 

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#294]
In the filter area when you start typing the name of the device the filter works fine.

![image](https://user-images.githubusercontent.com/31006659/37356505-e6313308-26c4-11e8-9e0d-ff80fa979f7b.png)

But if you minimize the search area, no device is displayed, neither when you maximize the search area again.

![image](https://user-images.githubusercontent.com/31006659/37356666-407b486c-26c5-11e8-9141-e8530b3bf3b5.png)

![image](https://user-images.githubusercontent.com/31006659/37356680-48d30842-26c5-11e8-8b91-8410718fc4b3.png)

**Comment by betefaber** [comment]
_"In the filter area when you start typing the name of the device fine filter works fine"_: This behavior has changed. Now you need to click on the magnifying glass icon to make the search.

However, there are problems in the new behavior.

related issue: [#673](https://github.com/dojot/dojot/issues/673)

**Comment by betefaber** [comment]
Test OK.

![screenshot_54](https://user-images.githubusercontent.com/37310063/47105051-46e18400-d219-11e8-950d-86891d4c1782.png)

![screenshot_55](https://user-images.githubusercontent.com/37310063/47105061-49dc7480-d219-11e8-863d-fe90d8712a72.png)

![screenshot_56](https://user-images.githubusercontent.com/37310063/47105068-4d6ffb80-d219-11e8-82e1-e3062efac929.png)
