### ISSUE TITLE
GUI - Filter in the map visualization is not working properly

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#295]
The filter in the map visualization has some problems:

1) When you click on a device, the marker in the map changes. It doesn't make sense. 

![image](https://user-images.githubusercontent.com/31006659/37357823-2a5a27da-26c8-11e8-9773-7321d792f14b.png)

2) When you click on 'hide all' or 'show all'. It affects the map, but not the devices in the search area.

![image](https://user-images.githubusercontent.com/31006659/37357941-72671786-26c8-11e8-84a0-6f299017f595.png)

3) ...

My suggestion is to implement something similar to the search in the device list.

**Comment by betefaber** [comment]
related issue: [#708](https://github.com/dojot/dojot/issues/708)

**Comment by betefaber** [comment]
Test OK.

![Screenshot_2](https://user-images.githubusercontent.com/37310063/56810133-e9ec0980-680b-11e9-923e-9742cf483817.png)

![Screenshot_4](https://user-images.githubusercontent.com/37310063/56810148-ef495400-680b-11e9-8b8b-38fe9c1e5f00.png)

![Screenshot_5](https://user-images.githubusercontent.com/37310063/56810154-f3757180-680b-11e9-808f-65438ab6acba.png)
