### ISSUE TITLE
GUI - Map visualization is not working with real time data

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#297]
I created 10 devices and simulated them sending data to dojot periodically. It was expected that the devices were be moving by themselves in the map, but it didn't happen.

The following error message appears in the browser console:

![image](https://user-images.githubusercontent.com/31006659/37358444-e179a4b2-26c9-11e8-8f3a-1e6869e50e85.png)

**Comment by betefaber** [comment]
The problem was fixed.
