### ISSUE TITLE
GUI - Problems with long strings in the device edit page

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#301]
The device edit page doesn't handle long strings!

![image](https://user-images.githubusercontent.com/31006659/37363476-d3512e7a-26d6-11e8-95dc-1299033ed0f8.png)

**Comment by betefaber** [comment]
The problem continues if the screen is resized.

![screenshot_50](https://user-images.githubusercontent.com/37310063/42968346-5dc6e8c2-8b79-11e8-9103-5b383c74a0f5.png)

screen resized:

![screenshot_51](https://user-images.githubusercontent.com/37310063/42968369-6b543378-8b79-11e8-82b1-7190e75409a8.png)

**Comment by betefaber** [comment]
Test OK.

![screenshot_57](https://user-images.githubusercontent.com/37310063/46504318-f8d58500-c803-11e8-8a3d-fd23576ed5f8.png)

![image](https://user-images.githubusercontent.com/37310063/46504295-e8250f00-c803-11e8-961a-8ffff44220b3.png)
