### ISSUE TITLE
GUI - Device Detail - Problems with dynamic attribute links

### ISSUE THREAD

**Issue by hvjunior** [dojot/dojot#314]

**Comment by betefaber** [comment]
![Screenshot_9.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cfd1fbcd6395428792c07b7692ac7b671bd1478020c594aac170a5c40fcf98a7ef2b638268f0919f1c32f0e2a92624cf5f2d75dad0ba8228a4584b3be8f44c7e93e23e28e86492c53.png)
