### ISSUE TITLE
GUI - Filter in User Management is not working properly

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#315]
1. filter = admin : show all registered users

![image](https://user-images.githubusercontent.com/37310063/37526946-8c1db894-290f-11e8-909e-eeed232e4144.png)

2. filter = admin + space : show admin user

![image](https://user-images.githubusercontent.com/37310063/37526964-965f2c16-290f-11e8-914d-45c1fdb447ff.png)

3. others filters: **OK**

![image](https://user-images.githubusercontent.com/37310063/37527175-2380da40-2910-11e8-972a-b3a2248d3d2d.png)

**Comment by bizetti** [comment]
Feature doesn't exist anymore.
