### ISSUE TITLE
[GUI] Add User - Username field is filled with numbers only

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#316]
Username field validation:  **_Please use only letters (a-z) and numbers (0-9)_**
![image](https://user-images.githubusercontent.com/37310063/37528818-53c07a86-2914-11e8-9590-bf3b562850fb.png)

If the field is filled with numbers only, the user is not created, but no messages are displayed.
Error appears only on Console.
![image](https://user-images.githubusercontent.com/37310063/37528855-6627a0dc-2914-11e8-85f0-c22a81abef83.png)

**Comment by fernandoMessias** [comment]
It looks like this problem was solved. I created a user only with numbers in username field, the user is not created and an error message is displayed.

![screenshot from 2018-04-12 15-08-24](https://user-images.githubusercontent.com/14092710/38696513-c8433d42-3e65-11e8-8863-65d3e4d3cf39.png)

**Comment by betefaber** [comment]
The bug was fixed.
![invalidUsername.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46e19a8c228e8aadbafaba51aa5cfd916b0a65633b0ba92e7391a172fd172203590c1dff475c5f12aefa8d2ba6b569248a585de8847f4366846c4ff8e7df46f554f832815d84b1b68b49c2ed342de6898d4c3f1f040ac4.png)
