### ISSUE TITLE
[GUI] - Device Detail - Problem with boolean data

### ISSUE THREAD

**Issue by fernandoMessias** [dojot/dojot#318]
When a boolean attribute is selected, no one data is shown.

**Comment by betefaber** [comment]
![Screenshot_26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60bb2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a478fb7b98849c9e03821e68c8e483e0c48.png)
