### ISSUE TITLE
GUI - Is there necessity of two scroll bars in the device list page?

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#323]
Notice there are two scroll bars in the device list page

![image](https://user-images.githubusercontent.com/31006659/37654103-e8b3b406-2c38-11e8-8b27-5c2c94fc1fed.png)

**Comment by mmagr** [comment]
I'm not sure if it's related - but there's also a "dead" footer on this page:

![image](https://user-images.githubusercontent.com/25080094/37654559-5b8bfac8-2c21-11e8-8213-f2bd17b15282.png)

I'm guessing the "inner" scrollbar is scrolling the div before that fixed footer.

**Comment by betefaber** [comment]
The 2nd scroll bar has been removed from the device list page:

![image](https://user-images.githubusercontent.com/37310063/43004294-b2c045f8-8c05-11e8-826e-aee9aac690c8.png)
----
![image](https://user-images.githubusercontent.com/37310063/43004512-69150cf8-8c06-11e8-83a5-ae706195554a.png)
