### ISSUE TITLE
alarm manager connection error

### ISSUE THREAD

**Issue by luisfelipefurlan** [dojot/dojot#325]
auth_1               | Traceback (most recent call last):
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
auth_1               |     response = self.full_dispatch_request()
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
auth_1               |     rv = self.handle_user_exception(e)
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
auth_1               |     reraise(exc_type, exc_value, tb)
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
auth_1               |     raise value
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
auth_1               |     rv = self.dispatch_request()
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
auth_1               |     return self.view_functions[rule.endpoint](**req.view_args)
auth_1               |   File "/usr/src/app/auth/webRoutes.py", line 66, in authenticate
auth_1               |     publish_alarm(err)
auth_1               |   File "/usr/src/app/auth/webRoutes.py", line 56, in publish_alarm
auth_1               |     rabbit_client.send(alarm)
auth_1               |   File "/usr/local/lib/python3.6/site-packages/alarmlibrary/connection.py", line 78, in send
auth_1               |     raise ConnectionClosed("Connection closed")
auth_1               | alarmlibrary.exceptions.ConnectionClosed: Connection closed
auth_1               | 2018-03-20 17:28:25,064 - ERROR - Exception on / [POST]
auth_1               | Traceback (most recent call last):
auth_1               |   File "/usr/src/app/auth/webRoutes.py", line 63, in authenticate
auth_1               |     jwt = auth.authenticate(db.session, auth_data)
auth_1               |   File "/usr/src/app/auth/controller/AuthenticationController.py", line 60, in authenticate
auth_1               |     raise HTTPRequestError(401, 'not authorized')
auth_1               | database.flaskAlchemyInit.HTTPRequestError: (401, 'not authorized')
auth_1               | 
auth_1               | During handling of the above exception, another exception occurred:
auth_1               | 
auth_1               | Traceback (most recent call last):
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
auth_1               |     response = self.full_dispatch_request()
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
auth_1               |     rv = self.handle_user_exception(e)
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
auth_1               |     reraise(exc_type, exc_value, tb)
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
auth_1               |     raise value
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
auth_1               |     rv = self.dispatch_request()
auth_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
auth_1               |     return self.view_functions[rule.endpoint](**req.view_args)
auth_1               |   File "/usr/src/app/auth/webRoutes.py", line 66, in authenticate
auth_1               |     publish_alarm(err)
auth_1               |   File "/usr/src/app/auth/webRoutes.py", line 56, in publish_alarm
auth_1               |     rabbit_client.send(alarm)
auth_1               |   File "/usr/local/lib/python3.6/site-packages/alarmlibrary/connection.py", line 78, in send
auth_1               |     raise ConnectionClosed("Connection closed")
auth_1               | alarmlibrary.exceptions.ConnectionClosed: Connection closed
auth_1               | 172.18.0.21 - - [20/Mar/2018:17:28:25 +0000] "POST / HTTP/1.1" 500 291 "http://localhost:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"

**Comment by giovannicuriel** [comment]
There is still a problem: if RabbitMQ restarts, auth can't connect to it anymore. Even if it is running OK, auth keeps getting 'Connection Closed' exceptions.
