### ISSUE TITLE
geofence node : region is not saved 

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#345]
Steps:

1. Drawn a region rectangular on to a map in the config node.

![image](https://user-images.githubusercontent.com/37310063/37733322-75f9a328-2d26-11e8-801d-d7c4296ba748.png)

2. Save geofence node
3. Open geofence node. Region was not saved.

![image](https://user-images.githubusercontent.com/37310063/37733349-8559fdfe-2d26-11e8-9658-da4066e4df1d.png)

**Comment by rascaraficci** [comment]
Fixed.
