### ISSUE TITLE
[GUI] New Device - Problems in visualization when the field name was filled with more than 23 characters

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#351]
24 characters:
![image](https://user-images.githubusercontent.com/37310063/37795978-c4527fbc-2df4-11e8-9b1a-ae19a8759c23.png)

23 characters:
![image](https://user-images.githubusercontent.com/37310063/37796002-d372ebe4-2df4-11e8-8714-3d0c7971fce0.png)

**Comment by rascaraficci** [comment]
Long device's name breaks the layout of device's detail page. 

![image](https://user-images.githubusercontent.com/31006659/41053447-e539f1aa-6991-11e8-8df9-e549ee798350.png)

**Comment by betefaber** [comment]
Test OK. Name field accepts 40 characters.

- device card

![screenshot_2](https://user-images.githubusercontent.com/37310063/47179348-3a7e2980-d2f4-11e8-844e-1eb9b35006dc.png)

- device details

![screenshot_5](https://user-images.githubusercontent.com/37310063/47179354-410ca100-d2f4-11e8-912f-171b9b7dcf9f.png)

- edit device

![screenshot_6](https://user-images.githubusercontent.com/37310063/47179366-47028200-d2f4-11e8-8222-bb802ef41141.png)
