### ISSUE TITLE
[GUI] Device - name field validation does not work properly

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#353]
Name field validation: 
![image](https://user-images.githubusercontent.com/37310063/37799490-9da4012e-2dfe-11e8-9f84-2232165aa43f.png)

Device name filled with blank space is accepted:
![image](https://user-images.githubusercontent.com/37310063/37799500-a8ebcb48-2dfe-11e8-8884-b608b5360537.png)

**Comment by betefaber** [comment]
Validations that need to be done:

- empty field
- name filled with whites
- character limit
- name already exists

**Comment by mprevide** [comment]
Utilizar a tag na gui  mprevide/gui:updatefirmware

**Comment by betefaber** [comment]
Validations:

- empty field or name filled with blanks

![image](https://user-images.githubusercontent.com/37310063/57327359-29a4d200-70e5-11e9-88f7-73d2fb7f66e8.png)

- invalid characters

![image](https://user-images.githubusercontent.com/37310063/57327285-f06c6200-70e4-11e9-95ac-8b90a2eb66ed.png)

- valid characters

![image](https://user-images.githubusercontent.com/37310063/57327322-0b3ed680-70e5-11e9-8e20-cea397bf2793.png)

- character limit: 40

![image](https://user-images.githubusercontent.com/37310063/57326909-eac24c80-70e3-11e9-9254-d8cb2190ca2d.png)

- name already exists: is allowed the creation of devices with the same name; they are differentiated by the "device id"

![image](https://user-images.githubusercontent.com/37310063/57327601-ba7bad80-70e5-11e9-9bee-e9ab313d55c1.png)
