### ISSUE TITLE
Alarms: Repeated namespaces

### ISSUE THREAD

**Issue by luisfelipefurlan** [dojot/dojot#355]
http://localhost:8000/alarmmanager/api/alarms/namespaces

    "namespaces": [
        {
            "namespace": "dojot.docker"
        },
        {
            "namespace": "dojot.docker"
        },
        {
            "namespace": "dojot.docker"
        },
        {
            "namespace": "dojot.docker"
        },

**Comment by rascaraficci** [comment]
This feature is no longer supported by dojot.
