### ISSUE TITLE
Alarms: Default Fields Not Fulfilled

### ISSUE THREAD

**Issue by luisfelipefurlan** [dojot/dojot#358]
Fields in the default structure are not being populated.
Some fields are being replicated in the primarySubject.

        {
            "namespace": "dojot.auth",
            "domain": "AuthorizationError",
            "description": null,
            "severity": "Minor",
            "primarySubject": {
                "instance_id": "1",
                "module_name": "Authentication Module"
            },
            "additionalData": {
                "reason": "not authorized",
                "username": "Mario"
            },
            "appearance": 1521831423130,
            "reportedAppearance": 1521831313681,
            "lastModified": 1521831423130,
            "reason": null,
            "reportedReason": null,
            "disappearance": null,
            "reportedDisappearance": null,
            "_id": "5ab54dffe4b01131a7c4b7d4"
        }

**Comment by rascaraficci** [comment]
This feature is no longer supported by dojot.
