### ISSUE TITLE
Add new template: internal server error

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#361]
Steps:
1. Add configuration: Select Type = Translator, value = translate
2. Click in Create
3. Edit Attributes
4. Add new configuration: Select Type = Protocol, Select Type = MQTT
5. Click in Save
6. Edit Attributes
7. Add new configuration: Select Type = Topic, value = /teste
8. Click in Save

![image](https://user-images.githubusercontent.com/37310063/37913720-eddd4a7a-30eb-11e8-9f46-6ae99bd4ae40.png)

**Comment by mmagr** [comment]
@betefaber some changes were made to device-manager on the last cycle, and I couldn't reproduce this on the [latest version](https://github.com/dojot-nightly/docker-compose/releases/tag/0.2.0-nightly20180326).

Would you please confirm if this is still reproducible?
