### ISSUE TITLE
GUI - A lot of space is wasted at the bottom of the graphics

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#363]
In the device details page, there is a lot of white space at the bottom of the graphics. This area should be  cropped off.

![image](https://user-images.githubusercontent.com/31006659/37920663-0adb6d48-3117-11e8-8ab6-0f3e94441f20.png)

**Comment by betefaber** [comment]
the problem has been corrected:
![issue363.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46e187893687d0ffdcabf301b44fff9e2c4533317346f67272d3e02bbc142f51090d4da841585c11a8f98d7da3e32e6c981e5ab38532022d8c6853beb2901eb90bbb25894a82b7b48c49c6e83c25f5c6.png)
