### ISSUE TITLE
GUI - Firmware images are being shared by all templates

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#364]
After associating a firmware image with a specific template, all templates become associated with this new image.

![image](https://user-images.githubusercontent.com/31006659/37921199-a4510a86-3118-11e8-8fcf-af7b16a09a1b.png)

![image](https://user-images.githubusercontent.com/31006659/37921213-b0a1c5e6-3118-11e8-80d0-5afac137988d.png)

**Comment by betefaber** [comment]
This issue has been resolved.
![issue364.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46e187893687d0ffdbabf301b44fff9e2c4533317346f67272d3e02bbc142f51090d4da841585c11a8f98d7da3e32e6c981e5ab38532022d8c6853beb2901dbf0bbb25894a82b4b88345c7ef3823f5c6.png)
