### ISSUE TITLE
Attribute of type 'actuator' is not being handled by the GUI 

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#383]
1) It is not possible to set an attribute of type 'actuator' through the GUI

2) GUI does not handle properly an attribute of type 'actuator' when set through the backend

![image](https://user-images.githubusercontent.com/31006659/38147540-312485ba-3429-11e8-8e9e-bc4f40e75a85.png)

**Comment by betefaber** [comment]
Test OK.

- template created via API:

![image](https://user-images.githubusercontent.com/37310063/45762003-c4f34080-bc03-11e8-8342-57515389aa01.png)

- attribute addition via GUI:

![image](https://user-images.githubusercontent.com/37310063/45762119-097edc00-bc04-11e8-81ad-0810eb3da73a.png)
