### ISSUE TITLE
Device creation is not intuitive when there is no template

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#386]
In the device creation page has a message 'Select a template to start', but when there is no template, no message appears in the template selection area. The user don't know if it is a problem or if the template list is empty. It'd better add a message such 'There is no template' or 'Create a template first'.

![image](https://user-images.githubusercontent.com/31006659/38149626-9a23ffd4-3431-11e8-8387-54f5e67dfcda.png)

**Comment by betefaber** [comment]
The message was added: **Create a template first** 

![image](https://user-images.githubusercontent.com/37310063/40363506-263a7f00-5da6-11e8-93f4-d90ddf6ddc18.png)
