### ISSUE TITLE
GUI - long device names are not displayed nicely

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#387]
In the device details page, the name of a device is not displayed in an adequate way for long names.

![image](https://user-images.githubusercontent.com/31006659/38152973-c7cad78c-3440-11e8-91df-62ed4179a632.png)

**Comment by fernandoMessias** [comment]
It looks like this problem has already been solved.

![selecao_047](https://user-images.githubusercontent.com/14092710/38694917-42029196-3e61-11e8-95e6-f7998e87b3a8.png)

**Comment by betefaber** [comment]
Issue has been fixed.

![screenshot_20](https://user-images.githubusercontent.com/37310063/42826074-f402b5b2-89b9-11e8-945b-717253880e33.png)
![screenshot_21](https://user-images.githubusercontent.com/37310063/42826085-f71e74c0-89b9-11e8-8145-8330d6808d6d.png)
![screenshot_22](https://user-images.githubusercontent.com/37310063/42826089-fa8f6fa6-89b9-11e8-900b-9101776fad1d.png)
