### ISSUE TITLE
GUI - The filter in the Auth page doesn't follow the style of the other pages

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#389]
Device List Page

![screen shot 2018-03-31 at 13 28 02](https://user-images.githubusercontent.com/31006659/38165273-5f77046a-34e7-11e8-8d21-a75d38265e04.png)

Auth Page

![screen shot 2018-03-31 at 13 27 23](https://user-images.githubusercontent.com/31006659/38165315-dc730888-34e7-11e8-8c6e-5cf783e26cde.png)

**Comment by betefaber** [comment]
For now the filter has been removed from the user registration page.
The ticket will be retested when the filter is available again.
