### ISSUE TITLE
GUI - The device details page is not handling static attributes properly

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#394]
The device details page tries to load the history (10 last entries) for static attributes, but it doesn't make sense.

![screen shot 2018-03-31 at 21 18 47](https://user-images.githubusercontent.com/31006659/38168661-a8c5efd6-3529-11e8-8f5c-fd2f3746b53d.png)

**Comment by cfrancisco** [comment]
If I've understood correctly, the attribute "device"  is the only one static in this device, correct?

**Comment by rascaraficci** [comment]
That's right!
