### ISSUE TITLE
There is no way to change the user password via GUI

### ISSUE THREAD

**Issue by ericbaum** [dojot/dojot#408]
There is no clear way to change the password of a user via GUI.

This is specially critical for the admin user that is created as default, if it is done on a "publically" accessible environment this user has only the "admin" dummy initial password which is extremely insecure and must be changed as soon as possible.

**Comment by betefaber** [comment]
Added the option to change the password of a user via GUI:

![image](https://user-images.githubusercontent.com/37310063/41107295-77e57824-6a48-11e8-894f-2ef495bdc656.png)
