### ISSUE TITLE
Changes to a user profile are not persisted

### ISSUE THREAD

**Issue by ericbaum** [dojot/dojot#409]
If a user has its initial profile set as "Administrator", when we try to edit this user by changing the profile to "User", this new profile is shown as successfully changed on the GUI.

Then, if we leave the users page and then come back to it, that change is lost and the user profile is back to "Administrator"

**Comment by rascaraficci** [comment]
The auth service is being deprecated and we won't put any further effort on it. Soon, the dojot will be released with Keycloack IAM instead of the auth service.
