### ISSUE TITLE
Alarms: alarms of type "e-mail in use" are not generated

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#411]
1. create user with email from another user

![image](https://user-images.githubusercontent.com/37310063/38272791-af7d8b84-3760-11e8-8f97-35f189c396e7.png)

2. note that alarm is not generated
![image](https://user-images.githubusercontent.com/37310063/38272823-bcebf490-3760-11e8-9c10-b00d085f1561.png)

**Comment by mmagr** [comment]
:thinking: 

My two cents on this:

Even in the effort of "having 'abnormalities' to display" on the alarms page, I think we must have a clear distinction of what is "expected system behavior" - even if that means "system denying user action" - and what is an alarm.

Taking that as context - I think that this (user attempting to configure a new user with an already in use) definitely does not make up for a relevant alarm. This definitely may be something we might want to log, but having that appear along with system-critical information (subsystem failure, resource exhaustion, et cetera) may take the user's (perhaps a systems administrator) attention from what is really important, and by that get in the way of efficient system monitoring.

All that said, my vote goes to have this closed with a "won't fix" label, after we make sure that the service logs such configuration failures appropriately.

**Comment by rascaraficci** [comment]
The alarm feature is no longer supported by dojot.
