### ISSUE TITLE
[GUI] Firmware images are added to virtual models

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#412]
It does not make sense to add firmware images to virtual templates

![image](https://user-images.githubusercontent.com/37310063/38276083-4b7b3a46-376a-11e8-9628-0088f07d49b1.png)

**Comment by mmagr** [comment]
:thinking: 

My two cents on this:
What defines a template as "virtual" is its semantics - its usage policy.
That said, I think that we cannot, beforehand, determine whether it "makes sense" to add a software version/image to any given template.
My position is that us, as system designers, must enforce the "common sense" rule that no given device has ambiguous configuration, that, on current requirements, means that:
> No given device may have two attributes with the same (`label`, `type`) pair.

Translating that for this particular case:
> No given device may be composed of any two given templates that contain software versioning information attached to them

To say that a template is "virtual" or not, at least for me, is up to the user, not the system itself.

All that being said, my vote is that we close this ticket with a "won't fix" label.
