### ISSUE TITLE
Templates should only accept some characters on attributes

### ISSUE THREAD

**Issue by ericbaum** [dojot/dojot#417]
There are a few issues with the creation of flows when the names of attributes on a template contain some special characters like for example "space" or ".".

It is necessary to change both the device-manager backend and the GUI to deny this invalid characters when creating or editing the name of the attributes on a template.

**Comment by mmagr** [comment]
This might still require an update on GUI to notify the user of malformed attribute labels

**Comment by joab-cpqd** [comment]
![Captura de tela de 2019-06-28 16-23-36.png](https://images.zenhubusercontent.com/5cd42b2e6d03ff555513fe23/6fa4d7f0-b770-4283-a3e1-38f6641d06ce)
