### ISSUE TITLE
New version is not showing data published from devices

### ISSUE THREAD

**Issue by valeriasilva** [dojot/dojot#419]
[Question] The previous version (0.1.0) was showing data in the graphics normally. I updated the version (0.2.0) and the platform is not showing data in the graphics anymore. I've sent data from Mosquitto (expecting to see errors from console) and it seems data was sent successfully (I did not get any error). I am still using the default topic structure (/user-id/device-id/attrs) - remembering that the device-id is not being showed as the previous version did, so I had to look at the url to collect the device-id. Also, I am still using the json message structure, e.g. {"light":%light}.That is, it seems I am publishing data but Dojot is not getting/showing in th graphics.
What could it be?

**Comment by mmagr** [comment]
Hello @valeriasilva 

From what you described, it could be either 
1. that one of dojot's services is not running properly (or has errored)
2. that message ingestion is failing for some reason

For (1): Could you please paste the result of the following here?

```shell
# this should be run from the directory where you ran "docker-compose up -d"
# you may need sudo
docker-compose ps
```

For (2): Could you please attach the logs for iotagent-mqtt here? To get those:

```shell
# this should be run from the directory where you ran "docker-compose up -d"
# you may need sudo
docker-compose logs --no-color -t iotagent-mqtt > mqtt.log
```

**Comment by giovannicuriel** [comment]
Hi, everyone!

@valeriasilva, did you have any problems while gathering the logs?

**Comment by rascaraficci** [comment]
This issue has been closed because it has not had recent activity.
