### ISSUE TITLE
Add support for multi-tenancy for a single user

### ISSUE THREAD

**Issue by ericbaum** [dojot/dojot#421]
In the current state of dojot a user might be assigned to a single tenant.

It would be a rather interesting feature allowing an user to be associated with multiple tenants besides being allowed to gather data from only one at a time.

From a GUI perspective, a dropbox could be added by the side of the user avatar with the option to change the tenant, from the ones that are available for that user, that is being exhibited at that moment.

This change would also allow an admin user to have full view and control of what user with lower permissions are doing on their specific tenants as this user could have access to all the tenants that are created.

**Comment by rascaraficci** [comment]
We don't have demand for this feature, so we won't implement it.
