### ISSUE TITLE
[GUI] - Static map in the device detail screen

### ISSUE THREAD

**Issue by fernandoMessias** [dojot/dojot#433]
In the device detail screen, when a static geo attribute is selected, the map is displayed but the message "To see the data select an static or dynamic attribute" is displayed too. The right is, when you select an attribute the message disappears.

![selecao_049](https://user-images.githubusercontent.com/14092710/38699412-4ef5cf5a-3e6e-11e8-8181-cb62b931bdfc.png)

**Comment by betefaber** [comment]
The problem was fixed.
