### ISSUE TITLE
Fix size of the fields in the templates screen

### ISSUE THREAD

**Issue by fernandoMessias** [dojot/dojot#435]
- Fix in the card view;
- Fix in the templates detail;
- Fix in the templates edit.

**Comment by betefaber** [comment]
Different behavior in creating and editing templates:

- when creating a template, the fields accept up to **22 characters**:

![Screenshot_33.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf70eb2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a478fb7b9884ac3e83527e48c874f3f0c48.png)
![Screenshot_34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf709b2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a478fb7b9884ac3e83527e48c8846360c48.png)
![Screenshot_35.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf708b2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a478fb7b9884ac3e83527e48c8847370c48.png)

- in the template edition, up to **25 characters** are accepted:

![Screenshot_37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf70ab2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a488fb7b9884ac3e8352ce08f8d493a0c48.png)
![Screenshot_38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf705b2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a478fb7b9884ac3e8352ce08f8d483f0c48.png)
![Screenshot_39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf704b2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a478fb7b9884ac3e8352ce08f8d493a0c48.png)

**Comment by betefaber** [comment]
Test OK. 

In both the creation and editing of templates, the number of characters accepted in the fields is the same.

- template name: 45 characters

![screenshot_65](https://user-images.githubusercontent.com/37310063/47183170-ab760f00-d2fd-11e8-9e36-b78ef702046f.png)

- attribute name: 25 characters

![screenshot_66](https://user-images.githubusercontent.com/37310063/47183174-ac0ea580-d2fd-11e8-8e5c-8972eb76caf9.png)

- static value: 25 characters

![screenshot_68](https://user-images.githubusercontent.com/37310063/47183173-ac0ea580-d2fd-11e8-979b-a85e103db95d.png)

- meta value: 25 characters

![screenshot_69](https://user-images.githubusercontent.com/37310063/47183172-ac0ea580-d2fd-11e8-978a-48e19569c375.png)
