### ISSUE TITLE
Log out - Aikido

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/dojot#440]
My Aikido Platform log out all the time, but It has happen when I need to change Aikido Tab to another one Tab.

**Comment by giovannicuriel** [comment]
Just to clarify: you are using the web interface and, for no apparent reason, you are logged out - is that the problem?

**Comment by danielnunesdeoliveira** [comment]
Hi @giovannicuriel 

Yes, that is the problem. No apparent reason.

**Comment by giovannicuriel** [comment]
We are working on that. We opened a issue in the GUI repo: dojot/gui#148.

**Comment by danielnunesdeoliveira** [comment]
Now, it is ok.
