### ISSUE TITLE
Dispositivo com Protocolo CoAP

### ISSUE THREAD

**Issue by mendmax** [dojot/dojot#442]
Prezados,
                Tenho um dispositivo que "conversa" utilizando protocolo CoAP. Como posso conectá-lo na DOJOT?

**Comment by matheuscampanhaf** [comment]
Olá @mendmax ! Desculpe a demora.
A versão atual da dojot não tem suporte especificamente para CoAP. Ela suporta o protocolo [LwM2m/CoAP](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf). Neste caso, é preciso inicializar o serviço [iotagent-leshan](https://github.com/dojot/iotagent-leshan) para utilizá-lo.
Caso queira colaborar com a dojot e desenvolver um iotagent-coap podemos lhe dar suporte.

**Comment by rascaraficci** [comment]
This issue has been closed because it has not had recent activity.
