### ISSUE TITLE
Page not found when registering user password

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#446]
Page Not Found by clicking the link sent by email:

![image](https://user-images.githubusercontent.com/37310063/39009908-5a60f066-43e3-11e8-8da0-88c60ca2494e.png)

**Comment by ericbaum** [comment]
This issue apparently has the same root cause as the other issue dojot/gui#139.

The link received on the email only works if the user is already logged out. IF the user is logged in he reaches this page not found screen.

**Comment by betefaber** [comment]
Still happens in baseline **0.3.0-nightly20180607**.

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/48017935-b2cb5400-e116-11e8-9352-2edbde1bce27.png)
