### ISSUE TITLE
GUI error message when successfully creates a user

### ISSUE THREAD

**Issue by manuelgavidia** [dojot/dojot#449]
When creating a user using latest firefox, the user is successfully created but an error message appears in the GUI:
"e.user is undefined"

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/51323177-9325a580-1a4e-11e9-8c3a-acaf34012aae.png)

Tested in Firefox: version  64.0.2 (64-bit)
