### ISSUE TITLE
Problem in template list when create a device

### ISSUE THREAD

**Issue by fernandoMessias** [dojot/dojot#454]
When creating a device, the template list shows only the templates according to the current page of the templates screen. For example:

![bug_template_01](https://user-images.githubusercontent.com/14092710/39198014-65f556e2-47bc-11e8-8585-7a2a8bd38ead.png)
![bug_template_02](https://user-images.githubusercontent.com/14092710/39198015-66174e78-47bc-11e8-928e-0002d5fe8a11.png)
![bug_template_03](https://user-images.githubusercontent.com/14092710/39198017-663c17c6-47bc-11e8-8897-2d1ecd9568ad.png)
![bug_template_04](https://user-images.githubusercontent.com/14092710/39198018-665cb1fc-47bc-11e8-9d74-7ccc62a226f5.png)

The same bug appear in Device filter

![bug_template_03](https://user-images.githubusercontent.com/14092710/39198306-19ecce5a-47bd-11e8-9ba5-e1cf5742165f.png)
![bug_template_05](https://user-images.githubusercontent.com/14092710/39198344-37e723f6-47bd-11e8-8e5e-2fb3d7a87054.png)

**Comment by betefaber** [comment]
fixed version: 0.3.0-nightly20180521

![template_device.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46fc9197338e82bd8ad6bb46b254f3916b0a65633b0ba92e7391a172fd172203590c1dff475c5f12aefa8d2ba6b569248a585de8847f4366846c4ff8e7df46f554f832815d84b1b68b49c2ef3b27e78287483a17040ac4.png)

![filtro_template_device.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46ee9d9637908c969becb253a85ce491164222652007a6693cc7f33ab0487e021b4d44be44510d42afaada2da2b66a2289580bedd2380b74c26b14f9aa9e0dfd50e474d412dcfce9c85ecafa3c2ded8a8a4d3918071989ff5c37a9915985.png)
