### ISSUE TITLE
Template name has incorrect alignment

### ISSUE THREAD

**Issue by fernandoMessias** [dojot/dojot#455]
![template_creation_improvement](https://user-images.githubusercontent.com/14092710/39199469-e5d772d4-47bf-11e8-8842-ffe001b2b948.png)

**Comment by betefaber** [comment]
template name aligned: 

![image](https://user-images.githubusercontent.com/37310063/41107712-4792eb6a-6a49-11e8-8930-92c90f98a364.png)
