### ISSUE TITLE
[GUI] Device details: adjust the size of the device id field

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#458]
![image](https://user-images.githubusercontent.com/37310063/39268442-62ba88c2-48a6-11e8-8a1f-2965e5417f9b.png)

**Comment by fernandoMessias** [comment]
This PR https://github.com/dojot/gui/pull/155 fix this.

**Comment by cfrancisco** [comment]
I couldn't reproduce it. @fernandoMessias, can you check it?

**Comment by fernandoMessias** [comment]
This problem was solved, I will close this issue.
