### ISSUE TITLE
Security failure - email node password field

### ISSUE THREAD

**Issue by DamascenoRafael** [dojot/dojot#461]
When configuring the Data Flows, if you open the editor of the email node you can simple inspect the password field element and change the type from password to text. In that way tou can see the previously registered password.

https://imgur.com/a/z7laeAC

**Comment by mmagr** [comment]
Hello @DamascenoRafael 

Thanks for reporting this.

We're actually in the middle of some major refactoring of how flows work, both to solve some security issues as the one you mentioned, and to make it easier to extend.

That said, we already have a couple of changes that should come into a "0.2.1" version of dojot - and one of them involves changing the way email node works. Should you want to take a peek at what's coming, please have a look at our [nightly snapshot repository](https://github.com/dojot-nightly/docker-compose). Currently, the latest snapshot is the following:
 
https://github.com/dojot-nightly/docker-compose/releases/tag/unfiltered-20180427

**Comment by bizetti** [comment]
There is no longer this funcitonality.
