### ISSUE TITLE
Saving changes in more than one template

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#464]
When more than one template is edited, if one of the templates is saved, changes in all templates are saved.

Initial setting:
![template_config_inicial](https://user-images.githubusercontent.com/37310063/39761583-e0e18e82-52ae-11e8-94ba-f365bab10c00.png)

Edit more than one template:
![template_edit_config](https://user-images.githubusercontent.com/37310063/39761596-e6eec8c6-52ae-11e8-8347-839bdbb930e8.png)

Add configuration in the 3 templates:
![template_add_config](https://user-images.githubusercontent.com/37310063/39761609-ed6883cc-52ae-11e8-8079-4744a0dac3e8.png)

Save one of the templates:
![save_template_umidade](https://user-images.githubusercontent.com/37310063/39761617-f2fdebec-52ae-11e8-8290-e44ff74d8467.png)

Message to save the template:
![mensagem ao salvar um dos templates](https://user-images.githubusercontent.com/37310063/39761624-f80822ba-52ae-11e8-9b30-fb5df5fa6ae0.png)

The changes in the 3 templates are saved:
![templates_salvos](https://user-images.githubusercontent.com/37310063/39761647-06cd24ee-52af-11e8-970f-547a12fe32ff.png)

**Comment by cfrancisco** [comment]
UI changes have made this mechanism no longer applicable.
