### ISSUE TITLE
[GUI] Fix size of the field Firmware Version in the Firmware Management screen

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#471]
Firmware Version with 300 characters:

![screenshot_28](https://user-images.githubusercontent.com/37310063/39942054-c95e1608-5534-11e8-80a6-2829006beae6.png)

**Comment by betefaber** [comment]
Firmware version with 100 characters: overlapping symbols

![screenshot_32](https://user-images.githubusercontent.com/37310063/39946486-b4dea67e-5544-11e8-9117-06f1dea747e8.png)

**Comment by betefaber** [comment]
The size of field was fixed to 128 characters, but still have problems with the data displayed.

![updatefw_128carac](https://user-images.githubusercontent.com/37310063/41489248-b4b06a7e-70c5-11e8-8727-a88f595c3d4b.png)

![updatefw_128carac_1](https://user-images.githubusercontent.com/37310063/41489252-b878b92c-70c5-11e8-9efb-bc3dcf56836c.png)

**Comment by fernandoMessias** [comment]
![Selection_033.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59afdcc3eb662200117e3e29/125516c66e82c728ace21e0d46db9196268197a080e78013f70eb2d86b56357c2301a03f32dfa17de6402d020c0c48a8410e0d47f8f98928f3e23c74dc595effcd7f1d2598694ef1e1c84afd13b0328a488fb7b98845c4ea3a24e18c8d473c0c48.png)

I tried to reproduce and it seems that the problem has been solved, @betefaber could you test this again, please?
