### ISSUE TITLE
Allows the creation of several templates with the same name

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#472]
- templates with name **teste**:

![templates_com_mesmo_nome](https://user-images.githubusercontent.com/37310063/39945442-d93ee168-5540-11e8-8587-3c4d4e109694.png)

-  options in device creation:
![screenshot_29](https://user-images.githubusercontent.com/37310063/39945460-e328608c-5540-11e8-8db6-6fea7c42919a.png)

**Comment by rascaraficci** [comment]
The label is not a key inside dojot; so this behavior is expected.
