### ISSUE TITLE
[Templates] - Different size fields on creation and template editing

### ISSUE THREAD

**Issue by fernandoMessias** [dojot/dojot#475]
In the creation of templates, the fields support 25 characters and in the editing, the fields support only 22 characters. It's better that the fields has the same size.

**Comment by betefaber** [comment]
- in template creation:

![screenshot_6](https://user-images.githubusercontent.com/37310063/41621564-6b7379d4-73e3-11e8-8c41-048f0e0f1a09.png)


- in template edition:

![screenshot_8](https://user-images.githubusercontent.com/37310063/41621569-70f27586-73e3-11e8-9863-0a4f50068067.png)

**Comment by betefaber** [comment]
**The difference is in the static field values.**

In the creation / edition of templates, the labels support 25 characters and does not allowed equals labels.

![labels_iguais](https://user-images.githubusercontent.com/37310063/41623400-043fe8dc-73e9-11e8-8878-6f969a8b43bc.png)

**Comment by betefaber** [comment]
The static field size in creating / editing templates is 25 characters.
