### ISSUE TITLE
Device manager stopped listing devices and templates (docker-compose)

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#476]
The error had already appeared in the environment kubernetes:  https://github.com/dojot/dojot/issues/423

**device-manager log:**

> device-manager_1        | [2018-05-16 12:19:26,409] ERROR in app: Exception on /template [GET]
device-manager_1        | Traceback (most recent call last):
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
device-manager_1        |     context)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
device-manager_1        |     cursor.execute(statement, parameters)
device-manager_1        | psycopg2.ProgrammingError: relation "templates" does not exist
device-manager_1        | LINE 3: FROM templates ORDER BY lower(templates.label)
device-manager_1        |              ^
device-manager_1        |
device-manager_1        |
device-manager_1        | The above exception was the direct cause of the following exception:
device-manager_1        |
device-manager_1        | Traceback (most recent call last):
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
device-manager_1        |     response = self.full_dispatch_request()
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
device-manager_1        |     rv = self.handle_user_exception(e)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
device-manager_1        |     reraise(exc_type, exc_value, tb)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
device-manager_1        |     raise value
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
device-manager_1        |     rv = self.dispatch_request()
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
device-manager_1        |     return self.view_functions[rule.endpoint](**req.view_args)
device-manager_1        |   File "/usr/src/app/DeviceManager/TemplateHandler.py", line 268, in flask_get_templates
device-manager_1        |     result = TemplateHandler.get_templates(request)
device-manager_1        |   File "/usr/src/app/DeviceManager/TemplateHandler.py", line 93, in get_templates
device-manager_1        |     page = db.session.query(DeviceTemplate).order_by(sortBy).paginate(**pagination)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 491, in paginate
device-manager_1        |     items = self.limit(per_page).offset((page - 1) * per_page).all()
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2726, in all
device-manager_1        |     return list(self)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
device-manager_1        |     return self._execute_and_instances(context)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2901, in _execute_and_instances
device-manager_1        |     result = conn.execute(querycontext.statement, self._params)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
device-manager_1        |     return meth(self, multiparams, params)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
device-manager_1        |     return connection._execute_clauseelement(self, multiparams, params)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
device-manager_1        |     compiled_sql, distilled_params
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
device-manager_1        |     context)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
device-manager_1        |     exc_info
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
device-manager_1        |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
device-manager_1        |     raise value.with_traceback(tb)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
device-manager_1        |     context)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
device-manager_1        |     cursor.execute(statement, parameters)
device-manager_1        | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "templates" does not exist
device-manager_1        | LINE 3: FROM templates ORDER BY lower(templates.label)
device-manager_1        |              ^
device-manager_1        |  [SQL: 'SELECT anon_1.templates_id AS anon_1_templates_id, anon_1.templates_label AS anon_1_templates_label, anon_1.templates_created AS anon_1_templates_created, anon_1.templates_updated AS anon_1_templates_updated, anon_1.lower_1 AS anon_1_lower_1, attrs_1.id AS attrs_1_id, attrs_1.label AS attrs_1_label, attrs_1.created AS attrs_1_created, attrs_1.updated AS attrs_1_updated, attrs_1.type AS attrs_1_type, attrs_1.value_type AS attrs_1_value_type, attrs_1.static_value AS attrs_1_static_value, attrs_1.template_id AS attrs_1_template_id, attrs_1.parent_id AS attrs_1_parent_id \nFROM (SELECT templates.id AS templates_id, templates.label AS templates_label, templates.created AS templates_created, templates.updated AS templates_updated, lower(templates.label) AS lower_1 \nFROM templates ORDER BY lower(templates.label) \n LIMIT %(param_1)s OFFSET %(param_2)s) AS anon_1 LEFT OUTER JOIN attrs AS attrs_1 ON anon_1.templates_id = attrs_1.template_id ORDER BY anon_1.lower_1'] [parameters: {'param_1': 20, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)
device-manager_1        | 172.18.0.24 - - [16/May/2018:12:19:26 +0000] "GET /template?limit=1000&sortBy=label HTTP/1.1" 500 30 "http://10.50.11.195:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
device-manager_1        | [2018-05-16 12:19:26,442] ERROR in app: Exception on /device [GET]
device-manager_1        | Traceback (most recent call last):
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
device-manager_1        |     context)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
device-manager_1        |     cursor.execute(statement, parameters)
device-manager_1        | psycopg2.ProgrammingError: relation "devices" does not exist
device-manager_1        | LINE 3: FROM devices ORDER BY lower(devices.label)
device-manager_1        |              ^
device-manager_1        |
device-manager_1        |
device-manager_1        | The above exception was the direct cause of the following exception:
device-manager_1        |
device-manager_1        | Traceback (most recent call last):
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
device-manager_1        |     response = self.full_dispatch_request()
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
device-manager_1        |     rv = self.handle_user_exception(e)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
device-manager_1        |     reraise(exc_type, exc_value, tb)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
device-manager_1        |     raise value
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
device-manager_1        |     rv = self.dispatch_request()
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
device-manager_1        |     return self.view_functions[rule.endpoint](**req.view_args)
device-manager_1        |   File "/usr/src/app/DeviceManager/DeviceHandler.py", line 721, in flask_get_devices
device-manager_1        |     result = DeviceHandler.get_devices(request)
device-manager_1        |   File "/usr/src/app/DeviceManager/DeviceHandler.py", line 235, in get_devices
device-manager_1        |     page = db.session.query(Device).order_by(sortBy).paginate(**pagination)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 491, in paginate
device-manager_1        |     items = self.limit(per_page).offset((page - 1) * per_page).all()
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2726, in all
device-manager_1        |     return list(self)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
device-manager_1        |     return self._execute_and_instances(context)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2901, in _execute_and_instances
device-manager_1        |     result = conn.execute(querycontext.statement, self._params)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
device-manager_1        |     return meth(self, multiparams, params)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
device-manager_1        |     return connection._execute_clauseelement(self, multiparams, params)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
device-manager_1        |     compiled_sql, distilled_params
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
device-manager_1        |     context)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
device-manager_1        |     exc_info
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
device-manager_1        |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
device-manager_1        |     raise value.with_traceback(tb)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
device-manager_1        |     context)
device-manager_1        |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
device-manager_1        |     cursor.execute(statement, parameters)
device-manager_1        | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "devices" does not exist
device-manager_1        | LINE 3: FROM devices ORDER BY lower(devices.label)
device-manager_1        |              ^
device-manager_1        |  [SQL: 'SELECT anon_1.devices_id AS anon_1_devices_id, anon_1.devices_label AS anon_1_devices_label, anon_1.devices_created AS anon_1_devices_created, anon_1.devices_updated AS anon_1_devices_updated, anon_1.devices_persistence AS anon_1_devices_persistence, anon_1.lower_1 AS anon_1_lower_1, attrs_1.id AS attrs_1_id, attrs_1.label AS attrs_1_label, attrs_1.created AS attrs_1_created, attrs_1.updated AS attrs_1_updated, attrs_1.type AS attrs_1_type, attrs_1.value_type AS attrs_1_value_type, attrs_1.static_value AS attrs_1_static_value, attrs_1.template_id AS attrs_1_template_id, attrs_1.parent_id AS attrs_1_parent_id, templates_1.id AS templates_1_id, templates_1.label AS templates_1_label, templates_1.created AS templates_1_created, templates_1.updated AS templates_1_updated, overrides_1.id AS overrides_1_id, overrides_1.did AS overrides_1_did, overrides_1.aid AS overrides_1_aid, overrides_1.static_value AS overrides_1_static_value, pre_shared_keys_1.attr_id AS pre_shared_keys_1_attr_id, pre_shared_keys_1.device_id AS pre_shared_keys_1_device_id, pre_shared_keys_1.psk AS pre_shared_keys_1_psk \nFROM (SELECT devices.id AS devices_id, devices.label AS devices_label, devices.created AS devices_created, devices.updated AS devices_updated, devices.persistence AS devices_persistence, lower(devices.label) AS lower_1 \nFROM devices ORDER BY lower(devices.label) \n LIMIT %(param_1)s OFFSET %(param_2)s) AS anon_1 LEFT OUTER JOIN (device_template AS device_template_1 JOIN templates AS templates_1 ON templates_1.id = device_template_1.template_id) ON anon_1.devices_id = device_template_1.device_id LEFT OUTER JOIN attrs AS attrs_1 ON templates_1.id = attrs_1.template_id LEFT OUTER JOIN overrides AS overrides_1 ON anon_1.devices_id = overrides_1.did LEFT OUTER JOIN pre_shared_keys AS pre_shared_keys_1 ON anon_1.devices_id = pre_shared_keys_1.device_id ORDER BY anon_1.lower_1'] [parameters: {'param_1': 1000, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)
device-manager_1        | 172.18.0.24 - - [16/May/2018:12:19:26 +0000] "GET /device?page_size=1000&sortBy=label HTTP/1.1" 500 30 "http://10.50.11.195:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"

![image](https://user-images.githubusercontent.com/37310063/40117483-80ff18f0-58ed-11e8-892d-5132da3270ba.png)

**Comment by betefaber** [comment]
It was necessary to restart the services.

**Comment by rascaraficci** [comment]
It's been fixed!
