### ISSUE TITLE
In the first publication, the starting date on the chart is in the future.

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#485]
- In the first publication, the starting date on the chart is in the future.

![grafico](https://user-images.githubusercontent.com/37310063/40494265-d3388c74-5f4a-11e8-9e47-4564e10538ff.png)
![grafico1](https://user-images.githubusercontent.com/37310063/40494274-d730c288-5f4a-11e8-970b-bdc0e11f8698.png)

- After a time, the date of the second data is changed.

![grafico3](https://user-images.githubusercontent.com/37310063/40494528-74422ac6-5f4b-11e8-9867-2a37b73ed294.png)

**Comment by betefaber** [comment]
Another example:

![screenshot_11](https://user-images.githubusercontent.com/37310063/40494904-5ec31100-5f4c-11e8-993c-851b3e7dc820.png)

after a few seconds:

![screenshot_12](https://user-images.githubusercontent.com/37310063/40494914-6299c364-5f4c-11e8-94b9-c549235f2740.png)

**Comment by betefaber** [comment]
![screenshot_13](https://user-images.githubusercontent.com/37310063/40510430-15ac5892-5f73-11e8-8425-261eb118c416.png)

![screenshot_15](https://user-images.githubusercontent.com/37310063/40510448-21c1bdb6-5f73-11e8-841e-619a6bb2c017.png)

![screenshot_14](https://user-images.githubusercontent.com/37310063/40510440-1c16f37c-5f73-11e8-8586-fe331d76ff00.png)

- In the eleventh measure, the date / time is stabilized

![screenshot_16](https://user-images.githubusercontent.com/37310063/40510458-28b7414a-5f73-11e8-9a6e-796b3cc9980f.png)

**Comment by fernandoMessias** [comment]
I believe that this PR https://github.com/dojot/gui/pull/184 fixes this problem because now we take the timestamp value from device.

**Comment by betefaber** [comment]
![image](https://user-images.githubusercontent.com/37310063/41482887-61de5c38-70ad-11e8-833b-fcc6cf23f9b5.png)
