### ISSUE TITLE
[GUI] Error filtering templates

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#486]
There are 10 templates with "medidor" in the name.

- 4 in page 1:
![templates1](https://user-images.githubusercontent.com/37310063/40512779-3ab70cc0-5f7a-11e8-91e2-093774087c5e.png)

- 4 in page 2:
![templates2](https://user-images.githubusercontent.com/37310063/40512782-3ecc1a94-5f7a-11e8-8f5f-d2cd125310b6.png)

- 2 in page 3:
![templates3](https://user-images.githubusercontent.com/37310063/40512789-431fc6cc-5f7a-11e8-9e29-f8ab3e7606a9.png)

- Filtering result should be displayed on 2 pages. But the result is in 3 pages.

![filtro_template1](https://user-images.githubusercontent.com/37310063/40512814-556cf53e-5f7a-11e8-92ce-f0e016f8c6e2.png)

**The "medidor 3" template appears alone on page 2:**
![filtro_templarte2](https://user-images.githubusercontent.com/37310063/40512822-59c870cc-5f7a-11e8-8e0a-75731e7cf688.png)

![filtro_template3](https://user-images.githubusercontent.com/37310063/40512829-5d706f40-5f7a-11e8-885b-7f5b2635bde5.png)

**Comment by cfrancisco** [comment]
I couldn't reproduce it, is still occurring? @betefaber

**Comment by betefaber** [comment]
Filtering continues with problems.

templates registered: 

![screenshot_76](https://user-images.githubusercontent.com/37310063/43415044-e875a186-940a-11e8-8435-34ad9b220b66.png)
----

- filtering by "e": 
![screenshot_77](https://user-images.githubusercontent.com/37310063/43415056-f083e36a-940a-11e8-9cca-b5991c1614f3.png)

expected result: teste, TesteTemplate e TesteTemplate2

----

- filtering by "este": 
![screenshot_79](https://user-images.githubusercontent.com/37310063/43415069-f7e827f6-940a-11e8-912b-238a053110ee.png)

expected result: teste, TesteTemplate e TesteTemplate2

----
filter is case sensitive:
- filtering by "teste": 
![screenshot_78](https://user-images.githubusercontent.com/37310063/43415084-fdee5936-940a-11e8-8721-6c9f9bdd52bf.png)

- filtering by "Teste": 
![screenshot_80](https://user-images.githubusercontent.com/37310063/43415097-02e2cf30-940b-11e8-8466-ddcd096efd59.png)

**Comment by betefaber** [comment]
templates registered:

![screenshot_1](https://user-images.githubusercontent.com/37310063/45547642-d4cfe680-b7f7-11e8-933d-3e1a8f58a71b.png)

filtering by "e", 6 templates per page: does not show all filtered templates

![screenshot_3](https://user-images.githubusercontent.com/37310063/45547879-b4545c00-b7f8-11e8-9f96-eab5bc707594.png)

filtering by "e", 12 templates per page: displays all filtered templates

![screenshot_2](https://user-images.githubusercontent.com/37310063/45547887-b9b1a680-b7f8-11e8-89c8-8612ba7d21cd.png)

**Comment by betefaber** [comment]
Two tests were performed:
1. filter by "medidor": 10 templates meet the filter
2. filter by "este": 4 templates meet the filter

The 1st test was successfully executed, but in the 2nd test, with 6 templates per page, the result is incorrect.

**Comment by betefaber** [comment]
**Test 1:** filter by "medidor"

- registered templates: 

![screenshot_5](https://user-images.githubusercontent.com/37310063/46227847-c1b03100-c336-11e8-852b-6986e422366c.png)

- filtered templates, 12 per page: 

![filtro-medidor](https://user-images.githubusercontent.com/37310063/46227923-ff14be80-c336-11e8-8499-edacbbe3c921.png)

- filtered templates, 6 per page: 

![filtro-medidor-6page1](https://user-images.githubusercontent.com/37310063/46227963-15227f00-c337-11e8-9ea7-1167e17a8a3c.png)

![screenshot_10](https://user-images.githubusercontent.com/37310063/46227977-1ce22380-c337-11e8-80a6-cd213fa18a8a.png)

![filtro-medidor-6page2](https://user-images.githubusercontent.com/37310063/46227988-266b8b80-c337-11e8-8f68-a94e7a5fb14c.png)

![screenshot_11](https://user-images.githubusercontent.com/37310063/46228000-2ff4f380-c337-11e8-8402-46b0f850a0a1.png)

**Comment by betefaber** [comment]
**Test 2:** filter by "este"

- registered templates:

![screenshot_5](https://user-images.githubusercontent.com/37310063/46228097-79454300-c337-11e8-9b41-3d1e3653f9fd.png)

- With 6 templates per page, the result shows only 1 template when it should show the 4 templates that meet the filter

![screenshot_6](https://user-images.githubusercontent.com/37310063/46228115-85310500-c337-11e8-8c5d-3ffbdd586fba.png)

![screenshot_7](https://user-images.githubusercontent.com/37310063/46228511-a8a87f80-c338-11e8-8881-c61bfa9d9c95.png)

- But if 12 templates per page are selected, the result is correct.

![screenshot_8](https://user-images.githubusercontent.com/37310063/46228129-92e68a80-c337-11e8-85c5-09200f0ea7c8.png)

![screenshot_9](https://user-images.githubusercontent.com/37310063/46228141-98dc6b80-c337-11e8-9f17-50d2970ac310.png)

**Comment by betefaber** [comment]
Test blocked by issue #982.

**Comment by betefaber** [comment]
Test OK.

![Screenshot_7](https://user-images.githubusercontent.com/37310063/54844902-bf5fdb80-4cb6-11e9-8384-26bb36b95bae.png)

![Screenshot_8](https://user-images.githubusercontent.com/37310063/54844912-c4bd2600-4cb6-11e9-9e5d-fd3edd1dcc3c.png)

**Tested on version 58.2-201903121**
