### ISSUE TITLE
[GUI] Device list is not shown on first login

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#490]
Device list is only shown after the templates are loaded or if the devices screen is refreshed.

- Login for the first time

![no_device_before_template](https://user-images.githubusercontent.com/37310063/40674915-8b0abdb8-634c-11e8-8762-098d6d35b61f.png)

- After the templates are loaded

![devices_apos_template](https://user-images.githubusercontent.com/37310063/40674923-91ef2222-634c-11e8-8ee5-6994e7e16112.png)

- Refresh the devices screen

![devices_apos_refresh](https://user-images.githubusercontent.com/37310063/40674933-98606a6c-634c-11e8-97bf-a947ae46bd96.png)

**Comment by fernandoMessias** [comment]
@betefaber could you test this issue again? I can not reproduce.

**Comment by betefaber** [comment]
Test OK.
