### ISSUE TITLE
[GUI] Template: card to create new template is not displayed if page is changed

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#493]
**Steps:**

1. On page 1, click the _New Template_ button
2. Change page without discarding template creation
3. Return to page 1 and verify that the card for creating the new template has disappeared
4. Click the _New Template_ button and verify that the card for creating the new template is not displayed
5. Click the _New Template_ button several times. The button becomes "white"
![botao_new_template_em_branco](https://user-images.githubusercontent.com/37310063/40682651-c1be0ec6-6362-11e8-87a5-34f8d98fee9c.png)

**Comment by cfrancisco** [comment]
No longer happens.
