### ISSUE TITLE
Attribute of actuator type: inconsistent information in template creation / editing

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#495]
template creation:
![criacao_template](https://user-images.githubusercontent.com/37310063/40686849-10d7fe8e-636f-11e8-816f-990728c08d42.png)

template editing:
![edicao_template](https://user-images.githubusercontent.com/37310063/40686858-19236362-636f-11e8-89d3-2b227334f9c8.png)

device creation:
![criacao_device](https://user-images.githubusercontent.com/37310063/40686891-3ec78878-636f-11e8-8b27-bf746ef38344.png)

**Comment by fernandoMessias** [comment]
This PR https://github.com/dojot/gui/pull/197 fixe this problem

**Comment by betefaber** [comment]
Test OK.

- template:

![Screenshot_212](https://user-images.githubusercontent.com/37310063/59778228-7d7e0b80-928c-11e9-9074-bf2462f5eab3.png)

- device:

![Screenshot_213](https://user-images.githubusercontent.com/37310063/59778235-8078fc00-928c-11e9-8728-5991d65fa30a.png)

- actuator attribute:

![Screenshot_214](https://user-images.githubusercontent.com/37310063/59778242-84a51980-928c-11e9-8539-bce63b0ccb56.png)

- flow:
![image](https://user-images.githubusercontent.com/37310063/59778326-ab635000-928c-11e9-83c4-01599631d3d5.png)

- history:

```
[
    {
        "attr": "atuacao",
        "value": "teste do atuador",
        "device_id": "fdd86a",
        "ts": "2019-06-19T15:15:25.814000Z",
        "metadata": {}
    }
]
```
