### ISSUE TITLE
Function as a service doesn't work at kubernetes setup

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#500]

**Comment by betefaber** [comment]
> curl -X POST https://iotmid10.cpqd.com.br/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" -d '{"image": "mmagr/kelvin:latest","id":"kelvin"}'
> {"message":"ok"}
> 
> curl -X POST https://iotmid10.cpqd.com.br/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" -d '{"image": "raulnegreiros/mysql-insert","id":"mysql-insert"}'
> {"message":"ok"}
> 

![flow_novos_nos_kubernetes](https://user-images.githubusercontent.com/37310063/43222986-fd5dcdd0-9027-11e8-8601-007c418e983e.png)
