### ISSUE TITLE
[GUI] device is removed but remains in device list

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#505]
- device is created:

![device_created](https://user-images.githubusercontent.com/37310063/40729735-7436e7d0-6403-11e8-8160-311835d7d0f4.png)

- device is removed:

![device_removed](https://user-images.githubusercontent.com/37310063/40729752-7ba7dace-6403-11e8-920e-67ac7d723808.png)

- device remains in device list

- but when you select it, device is not found:

![device_test](https://user-images.githubusercontent.com/37310063/40729756-806a305c-6403-11e8-814c-375576bfe041.png)

Affected version: **0.3.0-unfiltered-nightly20180529**

**Note: the last device in the list is not removed**

**Comment by betefaber** [comment]
After refresh of the screen (F5), the list of devices is updated.

**Comment by cfrancisco** [comment]
Is possible to check again this issue?

**Comment by betefaber** [comment]
The error has not been reproduced.
