### ISSUE TITLE
In a multi-tenancy scenario, only "admin" device updates are processed

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#519]
If any user is created associated to a tenant other than "admin", then no other service gets to know its devices - for instance, flowbroker won't receive any messages containing device updates (related to that tenant) generated by an iotagent. Only after restarting flowbroker, data-broker, history and persister services that everything starts working as expected.

How to reproduce:
- Create an user belonging to a tenant different than admin
- Create a device (with a template)
- Send a message to dojot using that device.

Result:
- No device data is processed by neither persister nor history services

Expected:
- All device data properly processed by all relevant services.

Baseline affected: 0.3.0-nightly20180607

**Comment by betefaber** [comment]
Test OK.

- published data:

**log iotagent-mqtt:**

> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- INFO: client up
> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- DEBUG: Authorizing MQTT client teste:afdee2 to publish to /teste/afdee2/attrs
> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- DEBUG: Expected topic is /teste/afdee2/attrs
> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- DEBUG: Device published on topic /teste/afdee2/attrs
> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- DEBUG: Authorized client teste:afdee2 to publish to topic /teste/afdee2/attrs
> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- INFO: client down
> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- DEBUG: ignoring internal message
> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- DEBUG: Published
> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- DEBUG: Trying to publish someting. Current producer topics are { 'device-data':
> iotagent-mqtt_1               |    { admin: 'df6ec9d4-abc4-4b28-9d91-f8e4e5bb10b2',
> iotagent-mqtt_1               |      teste: 'f2c5ec40-eeb6-4358-9c38-1ac18af27ed6' } }
> iotagent-mqtt_1               | <14:02:46 08/10/2018> -- DEBUG: ignoring internal message

- update via socketio:

![screenshot_77](https://user-images.githubusercontent.com/37310063/46615607-fd918600-caee-11e8-8a7f-a1252b1787d2.png)
