### ISSUE TITLE
Device status (online, offline) is not updated

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#531]
Sometimes, device status is not properly updated, even if the device is sending messages to dojot.
Environment is not easily reproducible.
Tested with baseline 0.3.0-20180607.

**Comment by betefaber** [comment]
- test in the docker-compose environment:

**device-manager log:**

> 

device st:admin:435117:0:exp offline
will set admin:435117 online for 5s
device st:admin:567120:0:exp offline
device st:admin:bbcd26:0:exp offline
device st:admin:e6475b:0:exp offline
device st:admin:a3c133:0:exp offline
will set admin:51203a online for 5s
will set admin:fa440a online for 5s
will set admin:ea6f30 online for 5s
will set admin:e6475b online for 5s
will set admin:38317e online for 5s
device st:admin:89e806:0:exp offline
device st:admin:126756:0:exp offline
device st:admin:7ca1df:0:exp offline
device st:admin:cc40f:0:exp offline
device st:admin:6c2b36:0:exp offline
device st:admin:7b456a:0:exp offline
will set admin:7ca1df online for 5s
will set admin:bbcd26 online for 5s
will set admin:567120 online for 5s
will set admin:cc40f online for 5s
will set admin:fa440a online for 5s
will set admin:7b456a online for 5s
will set admin:a3c133 online for 5s
will set admin:51203a online for 5s
will set admin:89e806 online for 5s
will set admin:126756 online for 5s
will set admin:ea6f30 online for 5s
will set admin:38317e online for 5s
will set admin:6c2b36 online for 5s

**Comment by betefaber** [comment]
Device status was updated until 25/Jul/2018

![status](https://user-images.githubusercontent.com/37310063/43399096-5723b6d4-93e0-11e8-833b-b1017ca690f2.png)

After that date, device status is not being updated, even if the device is publishing data.

![dados_publicados](https://user-images.githubusercontent.com/37310063/43399106-5bc6ef12-93e0-11e8-92cd-3ef81c75862c.png)

**Comment by rascaraficci** [comment]
This feature is no longer supporte by dojot.
