### ISSUE TITLE
Subscriptions don't work anymore

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#532]
Sending a subscription request to /subscription doesn't seem to work. Even if the subscription is correctly set, no notification is sent to the receiver (employing code from /ngsi folder in data-broker).

- Actions: send subscription request to /subscription:
```bash
curl -X POST "${DOJOT_HOST}/subscription" \
       -H "Authorization: Bearer ${JWT}" \
       -H 'Content-Type:application/json' \
       -d '
{
  "subject": {
    "entities": {
      "id": "fcae10"
    },
    "condition": {
      "attrs": [
        "a"
      ],
      "expression": {
        "q": "a>10"
      }
    }
},
    "notification": {
      "attrs": [
        "a"
      ],
      "topic": "device-notification"
    }
  }
'
```

- Start the Subscriber script from data-broker:
```bash
node build/ngsi/Subscriber.js -t "device-notification" -k "172.26.0.12:9092" --deviceManager "http://172.26.0.20:5000" -o "http://localhost:8000/devices"
```

Expected result: a notification is sent to localhost:8000/devices
Actual result: nothing happens.

Baseline tested: 0.3.0-nightly20180607

**Comment by giovannicuriel** [comment]
For the record, this is related to #137  and #125. Also, I would like to point out this comment: https://github.com/dojot/dojot/issues/137#issuecomment-367280567

**Comment by rascaraficci** [comment]
This feature is no longer supported, so this issue will be closed.
