### ISSUE TITLE
Timestamp in messages sent by devices

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#533]
iotagent-mosca doesn't allow setting timestamp in received messages - so that devices can send messages in batches.

**Comment by betefaber** [comment]
The first timestamp is converted correctly; the others are truncated and the date is incorrectly converted.

> matheusr@vali:/opt/teste/current/docker-compose$ mosquitto_pub -t /admin/3b0a5d/attrs -i admin:3b0a5d -m '{"timestamp": 1526846710, "mensagem":"teste"}'
> matheusr@vali:/opt/teste/current/docker-compose$ mosquitto_pub -t /admin/3b0a5d/attrs -i admin:3b0a5d -m '{"timestamp": 1526946710, "mensagem":"novo teste"}'
> matheusr@vali:/opt/teste/current/docker-compose$ mosquitto_pub -t /admin/3b0a5d/attrs -i admin:3b0a5d -m '{"timestamp": 1527046710, "mensagem":"outro teste"}'

![screenshot_25](https://user-images.githubusercontent.com/37310063/42839910-8dbba7c4-89db-11e8-9570-3cce804590d4.png)

> matheusr@vali:/opt/teste/current/docker-compose$ mosquitto_pub -t /admin/3b0a5d/attrs -i admin:3b0a5d -m '{"timestamp": 1528819846, "mensagem":"teste1"}'

![screenshot_30](https://user-images.githubusercontent.com/37310063/42839921-99ee46dc-89db-11e8-96a0-47e681b43d1e.png)


> [iota] Cache cleanup done: 0 entries evicted
> will handle authentication request undefined undefined admin:3b0a5d
> ignoring internal message $SYS/80abCY0/new/clients undefined
> will attempt to use client.id as id source
> ignoring internal message $SYS/80abCY0/disconnect/clients undefined
> Published /admin/3b0a5d/attrs { timestamp: 1528819846, mensagem: 'teste1' } admin:3b0a5d undefined undefined
> [iota] Cache cleanup done: 0 entries evicted

**Comment by betefaber** [comment]
![screenshot_34](https://user-images.githubusercontent.com/37310063/42842952-136a06dc-89e5-11e8-8da4-31f21b77e970.png)

- after refresh (F5), the date is corrected.

![screenshot_35](https://user-images.githubusercontent.com/37310063/42842974-23e328cc-89e5-11e8-9fc2-578bdd4d719c.png)

**Comment by betefaber** [comment]
The premise of the test was wrong: timestamp was used in seconds but a **timestamp with millisecond precision** must be used.
