### ISSUE TITLE
Pagination: templates per page

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#536]
Only 6 templates per page are shown.
Could not the user configure the number of elements per page?

**Comment by cfrancisco** [comment]
Right now, there is no way to do it. But we could add a combo-box allowing the user to select it.

**Comment by betefaber** [comment]
The user can set the number of elements per page: 6, 12 or 18.

![image](https://user-images.githubusercontent.com/37310063/42776889-caecf36e-890e-11e8-81c5-803b7e6fb514.png)
