### ISSUE TITLE
Auth and Device-Manager can't be started in older systems

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#549]
Older systems take quite longer time to establish a network connection with Kafka using kafka-python library. During this procedure, the CPU usage is quite high - it remains 100% for many seconds. For older systems, this might be a problem as it takes longer than 30sec to boot up the service (which will trigger a worker thread restart by gunicorn - and this will never end)

**Comment by betefaber** [comment]
- GUNICORN_TIMEOUT default (30):

> matheusr@vali:/opt/teste/current/docker-compose$ sudo docker logs -f a88fc59be429
> Waiting for DB to come up
> Waiting for database to become available...
> Ready to go
> Finished waiting for DB
> gunicorn timeout is 30
> [2018-07-20 17:04:53 +0000] [1] [INFO] Starting gunicorn 19.7.1
> [2018-07-20 17:04:53 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
> [2018-07-20 17:04:53 +0000] [1] [INFO] Using worker: gevent
> [2018-07-20 17:04:53 +0000] [10] [INFO] Booting worker with pid: 10

- GUNICORN_TIMEOUT=2

> matheusr@vali:/opt/teste/current/docker-compose$ sudo docker logs -f ccc1fd140112
> Waiting for DB to come up
> Waiting for database to become available...
> Ready to go
> Finished waiting for DB
> gunicorn timeout is 2
> [2018-07-20 17:09:50 +0000] [1] [INFO] Starting gunicorn 19.7.1
> [2018-07-20 17:09:50 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
> [2018-07-20 17:09:50 +0000] [1] [INFO] Using worker: gevent
> [2018-07-20 17:09:50 +0000] [10] [INFO] Booting worker with pid: 10
> [2018-07-20 17:09:52 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
> [2018-07-20 17:09:53 +0000] [16] [INFO] Booting worker with pid: 16
> [2018-07-20 17:09:55 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:16)
> [2018-07-20 17:09:56 +0000] [22] [INFO] Booting worker with pid: 22
> [2018-07-20 17:09:58 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:22)
> [2018-07-20 17:09:59 +0000] [28] [INFO] Booting worker with pid: 28
> [2018-07-20 17:10:01 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:28)
> [2018-07-20 17:10:02 +0000] [34] [INFO] Booting worker with pid: 34
> [2018-07-20 17:10:04 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:34)
> [2018-07-20 17:10:05 +0000] [40] [INFO] Booting worker with pid: 40
> [2018-07-20 17:10:07 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:40)
> [2018-07-20 17:10:08 +0000] [46] [INFO] Booting worker with pid: 46
> [2018-07-20 17:10:10 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:46)
> [2018-07-20 17:10:11 +0000] [52] [INFO] Booting worker with pid: 52
> [2018-07-20 17:10:13 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:52)
> [2018-07-20 17:10:14 +0000] [58] [INFO] Booting worker with pid: 58
> [2018-07-20 17:10:16 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:58)
> [2018-07-20 17:10:17 +0000] [64] [INFO] Booting worker with pid: 64
> [2018-07-20 17:10:19 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:64)
> [2018-07-20 17:10:20 +0000] [70] [INFO] Booting worker with pid: 70
> [2018-07-20 17:10:22 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:70)
> [2018-07-20 17:10:23 +0000] [76] [INFO] Booting worker with pid: 76
> [2018-07-20 17:10:25 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:76)
> [2018-07-20 17:10:26 +0000] [82] [INFO] Booting worker with pid: 82
> [2018-07-20 17:10:29 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:82)
> [2018-07-20 17:10:30 +0000] [88] [INFO] Booting worker with pid: 88
> [2018-07-20 17:10:32 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:88)
> [2018-07-20 17:10:33 +0000] [94] [INFO] Booting worker with pid: 94

- GUNICORN_TIMEOUT=120

> matheusr@vali:/opt/teste/current/docker-compose$ sudo docker logs -f 2cf9d5a86517
> Waiting for DB to come up
> Waiting for database to become available...
> Ready to go
> Finished waiting for DB
> gunicorn timeout is 120
> [2018-07-20 17:13:39 +0000] [1] [INFO] Starting gunicorn 19.7.1
> [2018-07-20 17:13:39 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
> [2018-07-20 17:13:39 +0000] [1] [INFO] Using worker: gevent
> [2018-07-20 17:13:39 +0000] [10] [INFO] Booting worker with pid: 10

**Note**: GUNICORN_TIMEOUT is declared in the enviroment section of the device-manager

>   device-manager:
>     image: dojot/device-manager:0.3.0-nightly20180712
>     restart: always
>     environment:
>       # TODO: Fill these env variables with suitable values
>       - GUNICORN_TIMEOUT=120
