### ISSUE TITLE
The platform allows to define more than one geo attribute for a device

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#552]
- 2 attributes: 1 static and 1 dynamic
Despite the data published in the dynamic attribute, it assumes the value of the static attribute.

![2atributosgeo](https://user-images.githubusercontent.com/37310063/41792765-52d13020-7630-11e8-9020-676ce8c69438.png)

- 2 dynamic attributes:
Both assume the 1st published data

![2atributosgeo_dinamicos](https://user-images.githubusercontent.com/37310063/41792778-5c48f304-7630-11e8-82fc-5b52c54e5431.png)

- 3 attributes: 2 dynamic and 1 static
All assume the value of the static attribute.

![3atributosgeo_1estatico](https://user-images.githubusercontent.com/37310063/41792786-6143e8be-7630-11e8-9473-e916ef4f1486.png)

**Comment by bizetti** [comment]
Suggestion: not allow more than one geo attribute.

**Comment by giovannicuriel** [comment]
Another suggestion (just for the record): add a metadata to a particular geo attribute that indicates that it is the actual physical location of the device.

**Comment by rascaraficci** [comment]
The idea is not to put restriction to the data model, so won't address this issue.
