### ISSUE TITLE
Flow: no validation in actuate node

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#556]
It is possible to write an actuation on a virtual device or on a device that has no "actuator"  attribute.

![actuate node](https://user-images.githubusercontent.com/37310063/41987091-94a3dcd2-7a0e-11e8-9d07-141f7370a0bd.png)

**Comment by mprevide** [comment]
@luissajunior 
Don't close the issue, just move to merge!

**Comment by betefaber** [comment]
- Filtering is only done on the `actuate` node. It is not done on the `multi actuate` node.

![Screenshot_15](https://user-images.githubusercontent.com/37310063/98578127-af39ad00-229b-11eb-9e9e-49b6ebae914a.png)

- The same device appears in the filtered list several times, depending on the number of actuators it has.

![Screenshot_14](https://user-images.githubusercontent.com/37310063/98578113-aa74f900-229b-11eb-848f-a13a7d6a1682.png)

![image](https://user-images.githubusercontent.com/37310063/98578172-bfea2300-229b-11eb-87fb-fc8ee430dc15.png)

Tested in v0.5.0-rc.1.

**Comment by bizetti** [comment]
It won't be fixed.
