### ISSUE TITLE
[GUI] - Same tooltip to different buttons in Flow screen

### ISSUE THREAD

**Issue by fernandoMessias** [dojot/dojot#558]
Same tooltip is used to different action buttons in Flow screen

![selection_037](https://user-images.githubusercontent.com/14092710/42049937-ea71ff20-7add-11e8-8fbb-e814869802af.png)
![selection_038](https://user-images.githubusercontent.com/14092710/42049940-edbb45ce-7add-11e8-9b1d-96f141a3b9e2.png)
![selection_039](https://user-images.githubusercontent.com/14092710/42049943-f02f058e-7add-11e8-81da-789d6e0eaaaf.png)

**Comment by betefaber** [comment]
![screenshot_13](https://user-images.githubusercontent.com/37310063/42713208-078f6bfe-86c5-11e8-8afb-be0cc0dacf7b.png)
![screenshot_14](https://user-images.githubusercontent.com/37310063/42713214-0afeaa48-86c5-11e8-995d-6c1739aab751.png)
![screenshot_15](https://user-images.githubusercontent.com/37310063/42713217-0da78c92-86c5-11e8-9e1e-b99f9661234b.png)
