### ISSUE TITLE
Docker support in flowbroker got broken

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#560]
After dojot/dojot#500, docker-compose support got broken

**Comment by betefaber** [comment]
- Error adding new functionality:

> {
>     "message": "Failed to add node: ENOENT: no such file or directory, open '/var/run/secrets/kubernetes.io/serviceaccount/token'"
> }

- Environment variable DEPLOY_ENGINE was added in flowbroker:

![screenshot_38](https://user-images.githubusercontent.com/37310063/42882072-d9b74014-8a6e-11e8-9c04-2d7374749074.png)

- With the declared environment variable, 2 new features were added:

![image](https://user-images.githubusercontent.com/37310063/42882474-676a0b9e-8a6f-11e8-996e-41ef59a18058.png)

- Issue  #575 was created to add the environment variable to docker-compose
