### ISSUE TITLE
[GUI]Problems in viewing the integer attribute due to invalid data

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#566]
- The attribute is integer but accepts the values "a" and "B": the chart is broken at invalid values

![screenshot_47](https://user-images.githubusercontent.com/37310063/42292686-aa1bf530-7faa-11e8-91fc-02b6b5107a65.png)
![screenshot_48](https://user-images.githubusercontent.com/37310063/42292689-ad64e620-7faa-11e8-80fd-6896aaf9802c.png)

- Attribute is integer but accepts float values:

![screenshot_49](https://user-images.githubusercontent.com/37310063/42292676-9d67e916-7faa-11e8-8ee5-5648926af6e6.png)
![screenshot_50](https://user-images.githubusercontent.com/37310063/42292682-a3ac1efa-7faa-11e8-8dc6-2b5361e619c4.png)

**Comment by giovannicuriel** [comment]
This has already been fixed, right?

**Comment by cfrancisco** [comment]
This issue will not be prioritized as it does not break the UI.
