### ISSUE TITLE
[device-manager] GET filters not working properly

### ISSUE THREAD

**Issue by luisfelipefurlan** [dojot/dojot#573]
When I make the call using some filter, the results are not being filtered.

/device?label=SOME_LABEL&idsOnly=true
The call returns the id of all devices

**Comment by betefaber** [comment]
Test OK.

- label=SOME_LABEL: **/device?label=SOME_LABEL&idsOnly=true**

![screenshot_127](https://user-images.githubusercontent.com/37310063/52057333-e5d18800-254b-11e9-8584-1e257a2509ce.png)

- no label: **/device?idsOnly=true**

![screenshot_128](https://user-images.githubusercontent.com/37310063/52057294-d4887b80-254b-11e9-9116-18ba1660f3a1.png)

- label=linha: **/device?label=linha&idsOnly=true**

![screenshot_129](https://user-images.githubusercontent.com/37310063/52057313-de11e380-254b-11e9-86fd-3c829790aa5a.png)
