### ISSUE TITLE
Call failed in first login

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#576]
**Prerequisite**: database empty

**Steps**:

1. execute the commands:

- docker-compose down
- docker-compose up -d

2. login with admin user

![callfailed](https://user-images.githubusercontent.com/37310063/42884359-82af6ed0-8a74-11e8-9e5f-0aac10342a75.png)

device-manager log:

[CallFailed.txt](https://github.com/dojot/dojot/files/2205910/CallFailed.txt)

**Affected Version**:  0.3.0-nightly20180712

**Comment by rascaraficci** [comment]
This issues has been fixed in newer versions of dojot.
