### ISSUE TITLE
Documentation update - History API - Options for getting all attributes and lines

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#588]

**Comment by betefaber** [comment]
The options have been implemented but the documentation has not been updated.

- History API - Options for getting one attribute

![Screenshot at 2019-07-05 15-47-46](https://user-images.githubusercontent.com/37310063/60741165-cdbcc500-9f3e-11e9-88a5-995d9bb4e8df.png)

- History API - Options for getting the latest data of all attributes

![Screenshot at 2019-07-05 15-51-19](https://user-images.githubusercontent.com/37310063/60741175-d4e3d300-9f3e-11e9-9642-46e7f40b7995.png)

- History API - Options for getting all attributes

![Screenshot at 2019-07-05 15-51-42](https://user-images.githubusercontent.com/37310063/60741186-de6d3b00-9f3e-11e9-80f3-11de265d4430.png)

Tested in version: **62.3-20190603**

**Comment by betefaber** [comment]
The documentation has been updated.

Added text: `If no query string is set, then all values from all attributes are returned.`

Tested in **v0.5.0-alpha.1**
