### ISSUE TITLE
Add user - username validation

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#603]
Error message is not enlightening.

- **username**: filled with "a"

- **error message**: "Invalid username. Usernames should start with a letter and only lowercase, alphanumeric and underscores are allowed"

Username "a" follows the rule but is not accepted.

![screenshot_56](https://user-images.githubusercontent.com/37310063/43329975-473556be-9198-11e8-8579-b7a3ea17da99.png)
----
![screenshot_61](https://user-images.githubusercontent.com/37310063/43329981-4a7b4c20-9198-11e8-8a0e-97735bea8609.png)

If username with only 1 character can not be accepted, then the error message needs to be changed in this case.

Note: Username "aa" is accepted

![screenshot_57](https://user-images.githubusercontent.com/37310063/43330002-58553e46-9198-11e8-8f1a-2203ea194d96.png)
----
![screenshot_60](https://user-images.githubusercontent.com/37310063/43330009-5b762464-9198-11e8-86fb-4f7a0e90de8e.png)

**Comment by betefaber** [comment]
The problem still occurs.

![Screenshot_194](https://user-images.githubusercontent.com/37310063/56361940-014d4600-61bf-11e9-807e-80ab25d441fd.png)

If the minimum number of characters of the username is 2, the error message should inform.

**Comment by cfrancisco** [comment]
It will no longer be prioritized.
