### ISSUE TITLE
Is it possible to access the current value of any property of a device within a switch node?

### ISSUE THREAD

**Issue by vinimdocarmo** [dojot/dojot#605]
Hi!

I've been playing with dojot for the past 3 days. Today I got stuck to a specific use case on a data flow. 

I have a device called `virtual-device` and this device has two properties named `attr1` and `attr2`, both of type string. Each of these attributes are aggregated from two different devices, let's say `device1` and `device2`.

So, I have this data flow where `virtual-device` is the input device and I want to have a switch node where I can test the current value of `attr1` whenever `attr2` is updated by `device2`. Up to this point, I know that I have access to the payload within the switch node. But, in this case, I only have access to the updated property `attr2` in `msg.payload.attr2`. Is there any way to access the current value of the property `attr1` of `virtual-device`? Maybe something like `msg.current.attr1`.

Here's an image of the data flows to clarify my question:

![flow](https://user-images.githubusercontent.com/4542024/43372675-a093032c-9379-11e8-97f0-3e1230c7e81d.jpg)

**Comment by giovannicuriel** [comment]
Hi!

For now, this is not possible - the message forwarded to the nodes is actually the one sent by a IoT agent (while processing a device message) or flowbroker (as a result of a virtual device update).

**Comment by vinimdocarmo** [comment]
Thanks for the response, @giovannicuriel. Is there any alternative to work around this use case? As I'm new to dojot I might not be following its design guide properly.

**Comment by giovannicuriel** [comment]
Yes, there is! 

You could add [a new node](https://dojotdocs.readthedocs.io/en/latest/faq/faq.html#how-can-i-add-a-new-node-type-to-its-menu) to flow palette to retrieve historical data from dojot (and therefore the attribute's last value using [history API](https://dojotdocs.readthedocs.io/en/latest/using-api-interface.html?highlight=history#checking-historical-data)) - there is a sample node in flowbroker that could be used as a starting point for this. 

This looks rather simple to implement and would be useful in a lot of use cases :smile:

**Comment by vinimdocarmo** [comment]
This looks to be a reasonable solution for my case. Thank you, @giovannicuriel!
