### ISSUE TITLE
[GUI] Add User - email to register the password is not sent

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#625]
The email to register the password is not sent.

**Steps to reproduce the problem:**
create new user

**Actual result:** the email is not sent; password has not been registered

- user created by GUI

> 2018-08-10 14:03:37,869 - INFO - User s1 created by admin
> 2018-08-10 14:03:37,869 - INFO - <User (transient 140349163510864)>
> 2018-08-10 14:03:37,940 - INFO - user s1 added to group admin by admin
> [2018-08-10 14:03:38,899] ERROR in app: Exception on /user [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/src/app/auth/webRoutes.py", line 44, in create_user
>     result = crud.create_user(db.session, user, requester)
>   File "/usr/src/app/auth/controller/CRUDController.py", line 134, in create_user
>     pwdc.create_password_set_request(db_session, new_user)
>   File "/usr/src/app/auth/controller/PasswordController.py", line 259, in create_password_set_request
>     send_mail(user.email, 'Account Activation', html)
>   File "/usr/src/app/auth/utils/emailUtils.py", line 17, in send_mail
>     s = smtplib.SMTP(conf.emailHost, conf.emailPort)
>   File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
>     self.source_address)
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 99, in create_connection
>     raise err # pylint:disable=raising-bad-type
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 86, in create_connection
>     sock.connect(sa)
>   File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
>     raise error(result, strerror(result))
> OSError: [Errno 99] Cannot assign requested address
> 2018-08-10 14:03:38,899 - ERROR - Exception on /user [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/src/app/auth/webRoutes.py", line 44, in create_user
>     result = crud.create_user(db.session, user, requester)
>   File "/usr/src/app/auth/controller/CRUDController.py", line 134, in create_user
>     pwdc.create_password_set_request(db_session, new_user)
>   File "/usr/src/app/auth/controller/PasswordController.py", line 259, in create_password_set_request
>     send_mail(user.email, 'Account Activation', html)
>   File "/usr/src/app/auth/utils/emailUtils.py", line 17, in send_mail
>     s = smtplib.SMTP(conf.emailHost, conf.emailPort)
>   File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
>     self.source_address)
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 99, in create_connection
>     raise err # pylint:disable=raising-bad-type
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 86, in create_connection
>     sock.connect(sa)
>   File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
>     raise error(result, strerror(result))
> OSError: [Errno 99] Cannot assign requested address
> 172.18.0.18 - - [10/Aug/2018:14:03:38 +0000] "POST /user HTTP/1.1" 500 291 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36"

**Expected behavior**: email should be sent
**Affected Version**: v0.3.0-beta1 (0.3.0-nightly_20180807)

- user created by API, with the declared AUTH_EMAIL_HOST, AUTH_EMAIL_USER, AUTH_EMAIL_PASSWD and AUTH_RESET_PWD_VIEW variables

![screenshot_4](https://user-images.githubusercontent.com/37310063/43971488-a4c0d92e-9ca7-11e8-8982-14b960758024.png)

- user created by API, without the declared AUTH_EMAIL_HOST, AUTH_EMAIL_USER, AUTH_EMAIL_PASSWD and AUTH_RESET_PWD_VIEW variables

![image](https://user-images.githubusercontent.com/37310063/43972166-dffbdbb8-9ca9-11e8-848e-91f467588822.png)

**Comment by betefaber** [comment]
- create user via GUI:
[createuser_GUI.txt](https://github.com/dojot/dojot/files/2352903/createuser_GUI.txt)

- create user via API, with the declared variables:
[createuser_API_VariaveisDefinidas.txt](https://github.com/dojot/dojot/files/2352905/createuser_API_VariaveisDefinidas.txt)

- create user via API, without the declared variables:

![createuser_api_variaveisnaodefinidas](https://user-images.githubusercontent.com/37310063/45096025-e9c0c180-b0f5-11e8-87a5-580a70ecfcd1.png)

**Comment by betefaber** [comment]
Email is sent if port 587 is not blocked.

> 2018-09-27 16:56:58,403 - INFO - User bete created by admin
> 2018-09-27 16:56:58,403 - INFO - <User (transient 140158473904872)>
> Consumer already exists
> 2018-09-27 16:56:58,456 - INFO - user bete added to group admin by admin
> 172.23.0.20 - - [27/Sep/2018:16:57:02 +0000] "POST /user HTTP/1.1" 200 373 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
> 172.23.0.20 - - [27/Sep/2018:16:57:02 +0000] "GET /user HTTP/1.1" 200 394 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
>

**Comment by danielnunesdeoliveira** [comment]
Hello.

Could someone please help me ? I am trying a new user create, but It is not working.  I am using GUI to create it.

**Comment by betefaber** [comment]
This was answered in issue #873.
Smtp port must be released and environment variables declared.
