### ISSUE TITLE
Dojot does not show attribute

### ISSUE THREAD

**Issue by EltonARodrigues** [dojot/dojot#628]
Dojot(origin/0.2.x) does not show some attibutebox when selected: 

![erro](https://user-images.githubusercontent.com/8228343/44465649-8b271e00-a5f4-11e8-810c-b6e04e2415ff.png)

![erro](https://user-images.githubusercontent.com/8228343/44541912-ce12ef80-a6e1-11e8-8bae-17b79372882a.gif)

Console error: 
> Error: Minified React error #105; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=105&args[]=o for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

> o(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

**Comment by giovannicuriel** [comment]
Hi, @EltonARodrigues!

We are investigating this issue, but we need a few more info about your deployment. Can you send us the last few values from sensor3? You could get these values by requesting the History service, as [described here](https://dojotdocs.readthedocs.io/en/stable/user_guide.html#checking-historical-data).

We suspect that this might be something related to data types, but we're not quite sure.

**Comment by EltonARodrigues** [comment]
Probably is the data, because with the time and the values come,  the attribute with this error change.

> [
  {
    "device_id": "fce176",
    "ts": "2018-08-27T16:30:23.278000Z",
    "value": 11484.7,
    "attr": "sensor4"
  },
  {
    "device_id": "fce176",
    "ts": "2018-08-27T16:20:22.520000Z",
    "value": 11335.57,
    "attr": "sensor4"
  },
  {
    "device_id": "fce176",
    "ts": "2018-08-27T16:10:21.736000Z",
    "value": 11186.52,
    "attr": "sensor4"
  },
  {
    "device_id": "fce176",
    "ts": "2018-08-27T16:00:20.970000Z",
    "value": 11037.64,
    "attr": "sensor4"
  },
  {
    "device_id": "fce176",
    "ts": "2018-08-27T15:50:20.198000Z",
    "value": 10888.59,
    "attr": "sensor4"
  },
  {
    "device_id": "fce176",
    "ts": "2018-08-27T15:40:19.470000Z",
    "value": 10739.55,
    "attr": "sensor4"
  }
]

**Comment by bizetti** [comment]
Fixed in version 0.3.x.
