### ISSUE TITLE
Instalação via Docker - Containers Restartando.

### ISSUE THREAD

**Issue by jpnmatoso** [dojot/dojot#654]
Segui todos os processos de instalação mencionados nas documentações, porém alguns containers estão em "Restarting".

Além dos procedimentos apresentados no Installation Guide, preciso de mais algum procedimento?

SO Ubuntu 16.04

git clone https://github.com/dojot/docker-compose.git
git checkout 0.2.0
git submodule update --init --recursive
docker-compose up -d

Saída do docker-compose ps:

                Name                               Command                  State                           Ports                     
docker-compose_alarm-manager_1          /bin/sh -c ./entrypoint.sh       Up             8080/tcp                                      
docker-compose_apigw_1                  /docker-entrypoint.sh /bin ...   Restarting                                                   
docker-compose_auth-redis_1             docker-entrypoint.sh redis ...   Up             6379/tcp                                      
docker-compose_auth_1                   ./appRun.sh start                Restarting                                                   
docker-compose_data-broker-redis_1      docker-entrypoint.sh redis ...   Up             6379/tcp                                      
docker-compose_data-broker_1            npm run subscription             Up             80/tcp                                        
docker-compose_device-manager-redis_1   docker-entrypoint.sh redis ...   Up             6379/tcp                                      
docker-compose_device-manager_1         ./docker/entrypoint.sh start     Up             5000/tcp                                      
docker-compose_docker-monitor_1         ./docker/entrypoint.sh start     Up             5000/tcp                                      
docker-compose_flowbroker_1             node index.js -w 1 -s            Up                                                           
docker-compose_gui_1                    nginx -g daemon off;             Up             80/tcp                                        
docker-compose_history_1                ./docker/falcon-docker-ent ...   Up             8000/tcp                                      
docker-compose_image-manager_1          ./docker/entrypoint.sh start     Up             5000/tcp                                      
docker-compose_iotagent-mqtt_1          node /opt/index.js               Up             0.0.0.0:1883->1883/tcp, 0.0.0.0:8883->8883/tcp
docker-compose_kafka_1                  /start.sh                        Up             7203/tcp, 9092/tcp                            
docker-compose_kong-config_1            /opt/kong.config.sh              Restarting                                                   
docker-compose_kong-migration_1         /docker-entrypoint.sh kong ...   Restarting                                                   
docker-compose_minio_1                  /usr/bin/docker-entrypoint ...   Up (healthy)   9000/tcp                                      
docker-compose_mongodb_1                docker-entrypoint.sh mongod      Up             27017/tcp                                     
docker-compose_mosca-redis_1            docker-entrypoint.sh redis ...   Up             6379/tcp                                      
docker-compose_persister_1              python history/subscriber/ ...   Restarting                                                   
docker-compose_postgres_1               docker-entrypoint.sh postgres    Up (healthy)   5432/tcp                                      
docker-compose_rabbitmq_1               docker-entrypoint.sh rabbi ...   Up             25672/tcp, 4369/tcp, 5671/tcp, 5672/tcp       
docker-compose_zookeeper_1              /docker-entrypoint.sh zkSe ...   Up             2181/tcp, 2888/tcp, 3888/tcp  

![image](https://user-images.githubusercontent.com/5174379/45332330-4aad2700-b546-11e8-95cf-29316b9668c2.png)

Agradeço qualquer dica para solução.

**Comment by giovannicuriel** [comment]
Bom dia!

Você poderia, por favor, mandar o log do auth? Você consegue fazer isso com o comando:

```bash
docker-compose logs --tail 200 auth
```

Ele pode dar algumas informações sobre o que pode estar acontecendo - talvez os outros serviços (que são mais silenciosos) estejam caindo pelo mesmo motivo.

**Comment by jpnmatoso** [comment]
Boa tarde Giovanni, tudo bem? Obrigado pelo retorno!

O log do auth está retornando o seguinte:

docker-compose logs --tail 200 auth
Attaching to docker-compose_auth_1
auth_1                  | Database access returned.
auth_1                  | Creating a new instance of this user.
auth_1                  | New instance created.
auth_1                  | failed to configure verification subsystem
auth_1                  | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
auth_1                  |   """)
auth_1                  | MAIL_HOST set to NOEMAIL. This is unsafe and there's no way to reset users forgotten password
auth_1                  | Failed to connect to kong
auth_1                  | dbconf: "dojot_auth"
auth_1                  | postgres ok
auth_1                  | Database already exists
auth_1                  | Creating initial user and permission...
auth_1                  | Creating users
auth_1                  | Querying database for user {'name': 'Admin (superuser)', 'username': 'admin', 'service': 'admin', 'email': 'admin@noemail.com', 'profile': 'admin', 'passwd': 'admin'}

Esta mensagem se repete inúmeras vezes.

O primeiro container a cair é o docker-compose_kong-migration_1 e na sequência derruba o docker-compose_apigw_1

Não sei se ajuda, mas seguem os logs mencionados acima:

docker-compose logs --tail 200 kong-migration
Attaching to docker-compose_kong-migration_1
*** Não possui log....

docker-compose logs --tail 200 apigw
Attaching to docker-compose_apigw_1
apigw_1                 | /bin/sh: line 1:    65 Illegal instruction     (core dumped) luarocks make
apigw_1                 | /bin/sh: line 1:    67 Illegal instruction     (core dumped) luarocks make

docker-compose logs --tail 200 persister
Attaching to docker-compose_persister_1
persister_1             | Failed to bootstrap tenants's consumers:
persister_1             | HTTPConnectionPool(host='data-broker', port=80): Read timed out. (read timeout=3)
persister_1             | Exiting.
persister_1             | will create consumer ['kafka:9092'] history 72c2b41e-6118-495a-9def-cb2b06bdc6f4
persister_1             | Terminating [tenancy-watcher] ...
persister_1             | Failed to bootstrap tenants's consumers:
persister_1             | HTTPConnectionPool(host='auth', port=5000): Max retries exceeded with url: /admin/tenants (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a01db9650>: Failed to establish a new connection: [Errno 111] Connection refused',))
persister_1             | Exiting.

Obrigado mais uma vez!

Abs.

**Comment by giovannicuriel** [comment]
Boa tarde!

É esperado que tanto o kong-config e o kong-migration sejam derrubados. A função de ambos é executar apenas algumas configurações iniciais no kong.

Você poderia, por favor, alterar o serviço do postgres para:

```yaml
  postgres:
    image: "postgres:9.4-alpine"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 100m

  postgres-users:
    image: "postgres:9.4-alpine"
    restart: on-failure
    command: >
      bash -c "createuser kong -d -h postgres -U postgres && createdb kong -U kong -h postgres"
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 100m
```

Esta descrição nova remove a variável POSTGRES_USER e POSTGRES_DB do serviço do postgres e adiciona um pequeno script para a criação do usuário `kong` e de um banco de dados também chamado `kong`. 

Tivemos um problema com sintomas semelhantes ao seu que tinha origem na imagem do postgres utilizada. A imagem mais nova cria apenas o usuário passado na variável POSTGRES_USER - o comportamento anterior era criar este usuário e deixar um usuário padrão `postgres`. Nós usamos ambos os usuários.

Caso funcione, recomendo, se possível, atualizar para uma versão mais nova da dojot, que contém várias correções e melhorias em vários componentes.

**Comment by RobsonEsteves** [comment]
Giovanni,
estou tentando também resolver esse mesmo problema.  Quando vc diz para alterar os serviços do postgres (conforme acima), isso seria criar um novo docker-compose.yml APENAS com esses dois serviços e rodar um docker-compose up ? 

Seria essa a mecanica?

SDS e muito obrigado pela ajuda!
Robson

**Comment by RobsonEsteves** [comment]
Giovanni,
ok muito obrigado! 
Só uma dúvida: com esse procedimento de rodar o docker-compose novamente com essas modificações os dados já existentes no Dojot como Devices, Templates, Flows etc, serão mantidos ou perdidos?
SDS
Robson

**Comment by giovannicuriel** [comment]
Se o `docker-compose down` for executado, os dados serão perdidos, pois os containers dos bancos de dados (postgres e o mongo) serão removidos. Caso seja apenas um `up` ou até mesmo o `restart`, não.

**Comment by rascaraficci** [comment]
This issue has been closed because it has not had recent activity.

**Comment by mautkd** [comment]
Meu código já esta dessa maneira porem estou como o erro abaixo na hora de subir:


dojot@dojot:~/dojot/docker-compose$ sudo docker-compose up -d
dojot_rabbitmq_1_1f057851e96f is up-to-date
dojot_flowbroker-redis_1_11807e6f4dce is up-to-date
dojot_ejbca_1_3318cc3ae438 is up-to-date
dojot_auth-redis_1_efb0e28f2c79 is up-to-date
dojot_device-manager-redis_1_9e0aac4e8006 is up-to-date
dojot_mosca-redis_1_6ee7afce3e5e is up-to-date
dojot_postgres_1_edb358d0d7a4 is up-to-date
dojot_mongodb_1_c403e37393e6 is up-to-date
dojot_gui_1_799018b0b589 is up-to-date
dojot_data-broker-redis_1_4874fb6241e2 is up-to-date
dojot_zookeeper_1_c0e8aeffff7c is up-to-date
dojot_history_1_274028dceb00 is up-to-date
dojot_kafka_1_f057ab94ed0c is up-to-date
dojot_flowbroker-context-manager_1_d28359ef8448 is up-to-date
dojot_data-broker_1_4db632357ccc is up-to-date
dojot_device-manager_1_ce0f299cf349 is up-to-date

ERROR: for apigw  Container "b68be5fd8762" is unhealthy.

ERROR: for auth  Container "b68be5fd8762" is unhealthy.

ERROR: for kong-migration  Container "b68be5fd8762" is unhealthy.

ERROR: for postgres-users  Container "b68be5fd8762" is unhealthy.
ERROR: Encountered errors while bringing up the project.

Alguém saberia ajudar? (ja modifiquei o healt-chek porem sem sucesso).
