### ISSUE TITLE
[GUI] Usability problem in device details screen

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#656]
Device details screen now has scroll.

![screenshot_9](https://user-images.githubusercontent.com/37310063/45361695-49f9ac80-b5a9-11e8-9838-8bfadbcb49ed.png)

The message "Select an attribute to be displayed" is only displayed if the scroll bar is rolled.

**Affected Version**: v0.3.0-beta1 (0.3.0-nightly_20180807)

**Comment by cfrancisco** [comment]
This no longer happens.
