### ISSUE TITLE
Update install docs - configuration bootstrap scripts (Problem running "create.user.sh" on master)

### ISSUE THREAD

**Issue by BrenoFortunato** [dojot/dojot#66]
The script "create.user.sh" won't run on master. After tagging RC2, I was able to run it successfully.

**Comment by mmagr** [comment]
Hello @BrenoFortunato, sorry for the huge delay on replying your issue.

As of now (as tracked by dojot-nightly/docker-compose@ and the current tip of dojot/docker-compose on master, a user is no longer required to run either create.user.sh or kong.config.sh to perform the initial system configuration bootstrapping.

Unfortunately, I also see that documentation is not up to date in that regard.

That said, I'll change this issue to track that documentation update, ok?

**Comment by mmagr** [comment]
Documentation was updated to omit deprecated steps.
