### ISSUE TITLE
iotagent-mosca is not starting right

### ISSUE THREAD

**Issue by rascaraficci** [dojot/dojot#662]
It seems the iotagent-mosca is starting before the auth service being operational. See the logs bellow:

<17:23:41 13/09/2018> -- || -- ERROR: Could not get list of current tenants.
<17:23:41 13/09/2018> -- || -- ERROR: Error is: Error: getaddrinfo ENOTFOUND auth auth:5000

The problem is that it keeps running in a non-operational way, ie, no data is sent to kafka and no errors are logged.

**Comment by betefaber** [comment]
<16:57:52 20/09/2018> -- || -- DEBUG: Trying to publish someting. Current producer topics are {}
<16:57:52 20/09/2018> -- || -- WARN: No producer was created for subject device-data. Maybe it was not registered?
