### ISSUE TITLE
Download maquina virtual

### ISSUE THREAD

**Issue by junqueira200** [dojot/dojot#670]
O download da maquina virtual com o Dojot não esta funcionando. Link : http://www.dojot.com.br/try-me-old/

**Comment by eliasreis54** [comment]
Olá!
Este é um link antigo, e não está mais funcionando.
Você pode testar usando docker, segue o link: [http://www.dojot.com.br/try-me/](url)

**Comment by rascaraficci** [comment]
This issue has been closed because it has not had recent activity.
