### ISSUE TITLE
The map overlay buttons should be configurable

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#678]
The buttons should only be displayed when needed.

![screenshot_39](https://user-images.githubusercontent.com/37310063/45884705-fc402980-bd8a-11e8-91fe-2cacf8767939.png)

in some situations, the map overlay buttons are duplicated:

![screenshot_37](https://user-images.githubusercontent.com/37310063/45884715-02360a80-bd8b-11e8-9b06-1eb383336f9d.png)

**Comment by mprevide** [comment]
This has been removed, this still exists in São Martinho
