### ISSUE TITLE
Flow: email is not sent

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#681]
- **flow configured:**

![image](https://user-images.githubusercontent.com/37310063/45894846-fa379400-bda5-11e8-866e-0dd3cb258c55.png)

- **log flowbroker:**

> [ingestor] got new device event: { metadata: { deviceid: '17c6e', tenant: 'admin', timestamp: 1537548097813 },
>   attrs: { int: 20 } }
> [executor] will handle node change
> debug: Executing change node...
> debug: ... change node was successfully executed.
> [executor] hop (change) result: [{"payload":{"int":20},"saida":{"str":"teste do nÃ³ change"}}]
> [executor] will handle node switch
> debug: Executing switch node...
> debug: ... switch node was successfully executed.
> [executor] hop (switch) result: [{"payload":{"int":20}}]
> [executor] will handle node device out
> debug: Executing device-out node...
> debug: Updating device...
> debug: Message is: { attrs: { str: 'teste do nÃ³ change' },
>   metadata: { deviceid: 'c309b', timestamp: 1537548098827, tenant: 'admin' } }
> will produce to device-data
> debug: ... device was updated.
> debug: ... device-out node was successfully executed.
> [executor] hop (device out) result: undefined
> [executor] will handle node template
> debug: Executing template node...
> debug: ... template node was successfully executed.
> [executor] hop (template) result: [{"payload":{"int":20},"emailBody":"valor: 20 !"}]
> [ingestor] got new device event: { attrs: { str: 'teste do nÃ³ change' },
>   metadata: { deviceid: 'c309b', timestamp: 1537548098827, tenant: 'admin' } }
> [executor] will handle node email
> debug: Executing e-mail node...
> debug: Preparing e-mail options...
> debug: ... e-mail options were successfully build
> debug: E-mail will be sent as:
> debug: { subject: 'teste flow email',
>   to: 'efaber@cpqd.com.br',
>   from: 'dojotcpqd@gmail.com',
>   text: 'valor: 20 !' }
> debug: Preparing SMTP transport handler...
> debug: Using e-mail config: { host: 'gmail-smtp-in.l.google.com', port: '25', secure: false }
> debug: ... e-mail transport was successfully created.
> debug: Sending e-mail...
> debug: ... e-mail node was not successfully executed.
> error: Error while executing e-mail node: Error: connect ECONNREFUSED 64.233.190.26:25
> [executor] Node execution failed. Error: connect ECONNREFUSED 64.233.190.26:25. Aborting flow bbf42b26-31db-4cb4-b9d7-ba31d5fdb474.
>

**Comment by eliasreis54** [comment]
We suspect the error is due to a closed port. we are waiting for the liberation of the port to try again

**Comment by betefaber** [comment]
- in baseline 0.3.0-nightly20190207:

![image](https://user-images.githubusercontent.com/37310063/52638700-aabf4500-2eb9-11e9-8eec-3f61f0a10e55.png)

**Comment by giovannicuriel** [comment]
This flow node was removed due to problems with configuration. It will be back as soon as we have another solution for storing sensitive data in dojot.
