### ISSUE TITLE
[GUI] Add user: missing service in request parameters

### ISSUE THREAD

**Issue by andrewjschuang** [dojot/dojot#689]
In user creation, the http request does not have the parameter 'service' (tenant) in it. Therefore the user creation fails.

HTTP Request Parameters in browser
![Screenshot from 2018-09-25 10-07-54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b55e3171d0aa500116fb266/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3723dd7b668ee12365158424ba853444d04bea6d37ef5f22e7a985902bfd73e0c27c03911faea811bbf01b975df4f81e0b9df5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5bf143e94c56a2103665e3647b.png)

User creation using API with 'service' parameter
![Screenshot from 2018-09-25 10-11-53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b55e3171d0aa500116fb266/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3723dd7b668ee1236505e424baf53444d04bea6d37ef5f22e7a985902bfd73e0c27c03911faea811bbf01b975df4f81e0b9df5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5bf143e94c50a51a376aee647b.png)

User creation using API without 'service' parameter
![Screenshot from 2018-09-25 10-12-34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b55e3171d0aa500116fb266/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3723dd7b668ee1236505d424da853444d04bea6d37ef5f22e7a985902bfd73e0c27c03911faea811bbf01b975df4f81e0b9df5edcfa7f74b9dfd0126754505a9bf54f34a9934acd5bf143e94c56ad153665e5647b.png)

Steps to reproduce the problem:    
    1. Click on "New user"
    2. Fill the form with email from an existing user
    3. Click on "Create"

Expected behaviour:
The user should be created.

Affected version: 0.3.0-nightly_20180912

**Comment by betefaber** [comment]
related issue: [#667](https://github.com/dojot/dojot/issues/667)

**Comment by betefaber** [comment]
The request for user creation has the parameter 'service' (tenant).

- request

![screenshot_4](https://user-images.githubusercontent.com/37310063/47177409-be351780-d2ee-11e8-8310-a042e68b181f.png)

- response

![screenshot_3](https://user-images.githubusercontent.com/37310063/47177676-75319300-d2ef-11e8-8d68-2588b0b46ebe.png)
