### ISSUE TITLE
Initialization failed

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#694]
Flowbroker, postgres and mongo do not start right if the volumes of containers mongodb and postgres are declared.

![postgres](https://user-images.githubusercontent.com/37310063/46148421-6bf85d80-c23e-11e8-9f8a-8c0e6c0308ff.png)

![mongo](https://user-images.githubusercontent.com/37310063/46148422-6bf85d80-c23e-11e8-9a94-b23c3c23b442.png)

![docker ps -a](https://user-images.githubusercontent.com/37310063/46148420-6bf85d80-c23e-11e8-8e98-fd3885e4c499.png)

**log flowbroker:**

> Context Manager Client initialized
> [executor] initializing ...
> (node:1) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
> [amqp] producer ready ...
> info: [executor] Worker ready.
> [amqp] consumer ready ...
> error: [flowbroker] Initialization failed. {"0":"f","1":"a","2":"i","3":"l","4":"e","5":"d","6":" ","7":"t","8":"o","9":" ","10":"c","11":"o","12":"n","13":"n","14":"e","15":"c","16":"t","17":" ","18":"t","19":"o","20":" ","21":"s","22":"e","23":"r","24":"v","25":"e","26":"r","27":" ","28":"[","29":"m","30":"o","31":"n","32":"g","33":"o","34":"d","35":"b","36":":","37":"2","38":"7","39":"0","40":"1","41":"7","42":"]","43":" ","44":"o","45":"n","46":" ","47":"f","48":"i","49":"r","50":"s","51":"t","52":" ","53":"c","54":"o","55":"n","56":"n","57":"e","58":"c","59":"t","60":" ","61":"[","62":"M","63":"o","64":"n","65":"g","66":"o","67":"N","68":"e","69":"t","70":"w","71":"o","72":"r","73":"k","74":"E","75":"r","76":"r","77":"o","78":"r","79":":","80":" ","81":"c","82":"o","83":"n","84":"n","85":"e","86":"c","87":"t","88":"i","89":"o","90":"n","91":" ","92":"0","93":" ","94":"t","95":"o","96":" ","97":"m","98":"o","99":"n","100":"g","101":"o","102":"d","103":"b","104":":","105":"2","106":"7","107":"0","108":"1","109":"7","110":" ","111":"t","112":"i","113":"m","114":"e","115":"d","116":" ","117":"o","118":"u","119":"t","120":"]"}

**log mongo:**

> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=81817fcdde81
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten] db version v3.2.19
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten] git version: a9f574de6a566a58b24d126b44a56718d181e989
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten] allocator: tcmalloc
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten] modules: none
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten] build environment:
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten]     distmod: debian81
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten]     distarch: x86_64
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten]     target_arch: x86_64
> 2018-09-27T12:33:53.789+0000 I CONTROL  [initandlisten] options: {}
> 2018-09-27T12:33:53.793+0000 I STORAGE  [initandlisten] exception in initAndListen: 98 Unable to create/open lock file: /data/db/mongod.lock errno:13 Permission denied Is a mongod instance already running?, terminating
> 2018-09-27T12:33:53.794+0000 I CONTROL  [initandlisten] dbexit:  rc: 100

**log postgres:**

> createuser: creation of new role failed: ERROR:  role "kong" already exists

**Affected Version**: 0.3.0-nightly_20180912

**Comment by giovannicuriel** [comment]
From what I read in your logs, mongo was unable to create a lock using your volume because of file permissions. Maybe using a `:Z` at the end of the volume line might help.

The postgres problem is expected: we are always trying to create the 'kong' user as the default postgres image was change recently.

The error from flowbroker indicates that it can't connect to mongo.

**Comment by betefaber** [comment]
Using a :Z at the end of the volume, Flowbroker and mongo started correctly.

- flowbroker log:

> matheusr@vali:/opt/teste/current/docker-compose$ sudo docker-compose logs -f flowbroker
> Attaching to dojot_flowbroker_1
> flowbroker_1                  | Context Manager Client initialized
> flowbroker_1                  | [executor] initializing ...
> flowbroker_1                  | (node:1) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
> flowbroker_1                  | [api] Service listening on port 80
> flowbroker_1                  | [redis] Succesfully connected to redis
> flowbroker_1                  | [redis] Cache is cleared
> flowbroker_1                  | [amqp] producer ready ...
> flowbroker_1                  | [amqp] producer ready ...
> flowbroker_1                  | info: [executor] Worker ready.
> flowbroker_1                  | [amqp] consumer ready ...
> flowbroker_1                  | [kafka] Created consumer (iotagent-1461)[dojot.tenancy : 89b1fc96-1691-47ab-8f01-1b862b93fc55]
> flowbroker_1                  | Constructor
> flowbroker_1                  | [ingestor] Failed to acquire existing tenancy contexts - consumerDevice is not defined
> flowbroker_1                  | [kafka] Producer ready
> flowbroker_1                  | [kafka] Producer ready
> flowbroker_1                  | [kafka] Producer ready
> flowbroker_1                  | [kafka] Producer ready
> flowbroker_1                  | [kafka] Created consumer (iotagent-1461)[device-data : f75a0c1c-a87f-44c2-acdc-513737a2bbbb]
> flowbroker_1                  | [kafka] Created consumer (iotagent-1461)[dojot.device-manager.device : 03cfc2e3-5c8e-4379-b2dc-57bc3f3d9d4b]
> flowbroker_1                  | Constructor
> flowbroker_1                  | [ingestor] Attempted to re-init device consumer for tenant: admin
> flowbroker_1                  | [ingestor] Tenancy context management initialized
> flowbroker_1                  | [kafka] Producer ready
> flowbroker_1                  | [kafka] Producer ready
> flowbroker_1                  | [kafka] Producer ready
> flowbroker_1                  | [kafka] Producer ready
> flowbroker_1                  | [ingestor] Device consumer ready for tenant: admin
> flowbroker_1                  | [ingestor] Device info consumer ready for tenant admin

-  mongodb log:

> matheusr@vali:/opt/teste/current/docker-compose$ sudo docker-compose logs -f mongodb
> Attaching to dojot_mongodb_1
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=e16e5ef6548f
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten] db version v3.2.19
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten] git version: a9f574de6a566a58b24d126b44a56718d181e989
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten] allocator: tcmalloc
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten] modules: none
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten] build environment:
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten]     distmod: debian81
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten]     distarch: x86_64
> mongodb_1                     | 2018-09-28T12:45:24.612+0000 I CONTROL  [initandlisten]     target_arch: x86_64
> mongodb_1                     | 2018-09-28T12:45:24.613+0000 I CONTROL  [initandlisten] options: {}
> mongodb_1                     | 2018-09-28T12:45:24.617+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
> mongodb_1                     | 2018-09-28T12:45:24.617+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=8G,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
> mongodb_1                     | 2018-09-28T12:45:25.126+0000 I STORAGE  [initandlisten] WiredTiger [1538138725:126620][1:0x7febc654bcc0], txn-recover: Main recovery loop: starting at 4/6144
> mongodb_1                     | 2018-09-28T12:45:25.248+0000 I STORAGE  [initandlisten] WiredTiger [1538138725:248973][1:0x7febc654bcc0], txn-recover: Recovering log 4 through 5
> mongodb_1                     | 2018-09-28T12:45:25.410+0000 I STORAGE  [initandlisten] WiredTiger [1538138725:410823][1:0x7febc654bcc0], txn-recover: Recovering log 5 through 5
> mongodb_1                     | 2018-09-28T12:45:26.877+0000 I CONTROL  [initandlisten]
> mongodb_1                     | 2018-09-28T12:45:26.877+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
> mongodb_1                     | 2018-09-28T12:45:26.877+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
> mongodb_1                     | 2018-09-28T12:45:26.877+0000 I CONTROL  [initandlisten]
> mongodb_1                     | 2018-09-28T12:45:26.879+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
> mongodb_1                     | 2018-09-28T12:45:26.879+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
> mongodb_1                     | 2018-09-28T12:45:26.879+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
> mongodb_1                     | 2018-09-28T12:45:30.070+0000 I NETWORK  [initandlisten] connection accepted from 172.26.0.13:37564 #1 (1 connection now open)
> mongodb_1                     | 2018-09-28T12:45:45.524+0000 I NETWORK  [initandlisten] connection accepted from 172.26.0.23:54180 #2 (2 connections now open)

However, the postgres is still restarting:

![image](https://user-images.githubusercontent.com/37310063/46210558-6581e880-c307-11e8-9037-9dc9df8f0a83.png)

**Comment by betefaber** [comment]
**Note:** 
TLS is enabled. 
The environment variable is declared: **MOSCA_TLS: "true"**

**Comment by betefaber** [comment]
Test OK.

![screenshot_70](https://user-images.githubusercontent.com/37310063/51129362-68024280-1811-11e9-879d-e9bcd5d0ded1.png)

> $ sudo docker-compose logs -f postgres-users
> Attaching to dojot_postgres-users_1
> postgres-users_1              | user kong exists
> postgres-users_1              | database kong exists
> dojot_postgres-users_1 exited with code 0
> $
