### ISSUE TITLE
Setup SMTP.

### ISSUE THREAD

**Issue by suporte-gsm** [dojot/dojot#699]
Where do I configure SMTP options on DOJOT servers so they can forward user creation and flow mail?

**Comment by ericbaum** [comment]
Hello @suporte-gsm ,

To configure the user creation email it is necessary to configure the Auth module that is the one responsible for handling such task. 
What the Auth module does is log into an email that will be the sender of the user creation email to the new user email address.

The Auth module has a few environment variables that must be set in order for this to be accomplished:

- AUTH_EMAIL_HOST -- Address of the SMTP server of the email provider
- AUTH_EMAIL_PORT -- SMTP port that will be used. The default value is port 587.
- AUTH_EMAIL_TLS -- Enable the use of TLS encryption. The default value is True.
- AUTH_EMAIL_USER -- The email address that will be used to log in to the server.
- AUTH_EMAIL_PASSWD -- The email password for the user previously defined.

If you are running the environment using docker-compose as your orchestrator, it is necessary to edit the docker-compose.yaml file and add this environment variables to the list of variables that are already defined. After editigin the docker compsoe file, just execute 'docker-compose up -d' the auth module will be updated and restarted with the new configuration.

If the environment is based on kubernetes then it is necessary to edit de auth module deployment by running from the command line 'kubectl -n dojot edit deployment auth', a text editor will be open with the deployment definition and the listed environment variables have to be added to the list of variables of the auth container.

**Comment by rascaraficci** [comment]
Closed due to inactivity.
