### ISSUE TITLE
[GUI] Find device on map does not work

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#708]
**Steps to reproduce the problem:**

1. In the map view, click "Show search bar"
2. Fill in the Device Name field
3. Click to search for the devices that fit the filter. **No device is shown**.

![screenshot_47](https://user-images.githubusercontent.com/37310063/46492201-3d045d80-c7e3-11e8-9495-7e5a257b6227.png)

![screenshot_48](https://user-images.githubusercontent.com/37310063/46492221-47bef280-c7e3-11e8-8807-cda6794e39f8.png)

4. Clean the filter. All devices must be shown, but **no device is displayed**.

![screenshot_49](https://user-images.githubusercontent.com/37310063/46492225-4beb1000-c7e3-11e8-9ece-e4fe51fa3f85.png)

5. Click to view Devices cards or refresh screen (F5)
6. Click Map view. Devices are displayed.

![image](https://user-images.githubusercontent.com/37310063/46492363-b1d79780-c7e3-11e8-9708-3ccd5a73f5af.png)

**Comment by cfrancisco** [comment]
@betefaber  Could you test again?

**Comment by betefaber** [comment]
Test OK.

- filtering by **bus**:

![Screenshot_151](https://user-images.githubusercontent.com/37310063/55828559-10f3cd00-5ae3-11e9-87c6-c89562b76d72.png)

![Screenshot_150](https://user-images.githubusercontent.com/37310063/55828566-151fea80-5ae3-11e9-9fe4-5bdfdb091b2b.png)

- filtering by **bus-1**:

![Screenshot_148](https://user-images.githubusercontent.com/37310063/55828575-194c0800-5ae3-11e9-8238-530883d45c28.png)

![Screenshot_149](https://user-images.githubusercontent.com/37310063/55828580-1cdf8f00-5ae3-11e9-97d0-ad743b55e16c.png)
