### ISSUE TITLE
[GUI] Increase the display area on the device detail screen

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#709]
Display area on the device detail screen is small; could be better leveraged.

![screenshot_50](https://user-images.githubusercontent.com/37310063/46493253-37f4dd80-c7e6-11e8-865f-b1c74c9305e8.png)

**Comment by mprevide** [comment]
this may be added in the future.

**Comment by cfrancisco** [comment]
Since we will be using the GUI v2 for device details in the future, this issue will not be prioritized.
