### ISSUE TITLE
Attribute data of actuator type is not stored

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#720]
**Steps to reproduce the problem:**

1. Create a flow that generates an action

![screenshot_78](https://user-images.githubusercontent.com/37310063/46624326-bfa05c00-cb06-11e8-9ec6-bd61730fae72.png)

2. Run the flow

- attribute "mensagem" is of type actuator

- log flowbroker:

> flowbroker_1                  | [ingestor] got new device event: { metadata: { deviceid: 'd618c9', tenant: 'admin', timestamp: 1539017054066 },
> flowbroker_1                  |   attrs: { str: 'atue' } }
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] hop (switch) result: [{"payload":{"str":"atue"}}]
> flowbroker_1                  | [executor] will handle node change
> flowbroker_1                  | debug: Executing change node...
> flowbroker_1                  | [executor] hop (change) result: [{"payload":{"str":"atue"},"saida":{"mensagem":"LIGAR"}}]
> flowbroker_1                  | debug: ... change node was successfully executed.
> flowbroker_1                  | [executor] will handle node actuate
> flowbroker_1                  | debug: Executing actuate node...
> flowbroker_1                  | debug: Sending message...
> flowbroker_1                  | debug: Message is: { meta: { deviceid: 'd618c9', service: 'admin' },
> flowbroker_1                  |   metadata: { tenant: 'admin' },
> flowbroker_1                  |   event: 'configure',
> flowbroker_1                  |   data: { attrs: { mensagem: 'LIGAR' }, id: 'd618c9' } }
> flowbroker_1                  | will produce to dojot.device-manager.device
> flowbroker_1                  | debug: ... message was sent.
> flowbroker_1                  | [executor] hop (actuate) result: undefined
> flowbroker_1                  | debug: ... actuate node was successfully executed.
> flowbroker_1                  | [ingestor] got new device event: { metadata:
> flowbroker_1                  |    { deviceid: 'd618c9',
> flowbroker_1                  |      tenant: 'admin',
> flowbroker_1                  |      status: 'online',
> flowbroker_1                  |      reason: 'statusUpdate' } }

3. Verify that the actuator attribute data is not stored

> $ curl -X GET -H 'Content-Type:application/json' -H "Authorization: Bearer ${JWT}" "http://10.4.1.41:8000/history/device/d618c9/history?lastN=10&attr=str&attr=mensagem"
> {
>     "mensagem": [],
>     "str": [
>         {
>             "device_id": "d618c9",
>             "ts": "2018-10-08T16:44:14.066000Z",
>             "value": "atue",
>             "attr": "str"
>         },
>         {
>             "device_id": "d618c9",
>             "ts": "2018-10-08T16:40:44.097000Z",
>             "value": "atue",
>             "attr": "str"
>         }
>     ]
> }

**Affected Version**: 0.3.0-nightly_20180926

**Comment by giovannicuriel** [comment]
Resolved by #780
