### ISSUE TITLE
[GUI] Problem in editing the template node

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#731]
The body text of the template on the "edit template node" screen is hidden.

**Steps to reproduce the problem:**

1. Click "New Flow"
2. Select template node
3. Open the "edit template node" screen

![screenshot_12](https://user-images.githubusercontent.com/37310063/47036978-1c79c300-d154-11e8-9a9e-6b6fdd955ed9.png)

4. Click on the field to edit the template

![screenshot_13](https://user-images.githubusercontent.com/37310063/47036987-213e7700-d154-11e8-895d-cb9bdbee6f25.png)

**Comment by mprevide** [comment]
This seem doesn't  happen anymore. 

I will pass this to test.

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/55582121-11602280-56f5-11e9-8d3f-45a0e7830e09.png)

![image](https://user-images.githubusercontent.com/37310063/55582081-efff3680-56f4-11e9-988e-7461c3f018ed.png)
