### ISSUE TITLE
[GUI] Flowbroker: Text overwrite the flow name

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#734]
**Steps to reproduce the problem:**

1. Select a flow
2. Click to view flow details

![screenshot_16](https://user-images.githubusercontent.com/37310063/47042703-5ce03d80-d162-11e8-8b37-fc569e3131ea.png)

3. Click in the Flow Name field. The "Flow name" text is cut.

![screenshot_17](https://user-images.githubusercontent.com/37310063/47042725-6b2e5980-d162-11e8-9ca7-ac54e420733d.png)

**Comment by betefaber** [comment]
Test NOK.

![image](https://user-images.githubusercontent.com/37310063/48080351-92fa6580-e1d4-11e8-972c-515a69a85050.png)

**Comment by mprevide** [comment]
This seems ok, I will pass to test.

**Comment by betefaber** [comment]
Test NOK.

![Screenshot_72](https://user-images.githubusercontent.com/37310063/55581718-fb059700-56f3-11e9-803a-dff7dd4f77d6.png)


Related [#823](https://github.com/dojot/dojot/issues/823)

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/56768348-7fdc5180-6784-11e9-8212-df308b383009.png)
