### ISSUE TITLE
[Persister] Time to live of device data

### ISSUE THREAD

**Issue by Vitorr32** [dojot/dojot#735]
Currently there is an time to live for the data that Dojot collects that is 1 week, I want to know how to remove the time to live so that data can be stored permanently on the platform

**Comment by davicedraz** [comment]
Hi, I also did some local tests and Dojot is set to default to delete the data after 7 days. 

When I tried to add the environment variable HISTORY_DB_DATA_EXPIRATION: <some value in seconds> in the file docker-compose.yml does not have any effect, neither in the services history, persister or both.

After doing several tests, I realized that it was only possible to change the persistence time by manually setting the time in the following line of code, inside the file 'conf.py':

> db_expiration = os.environ.get('HISTORY_DB_DATA_EXPIRATION', 604800)

Setting the value 0 as a parameter clears them instantly, just as -1 is ignored.

The solution I found, at least to resolve locally in Dojot that runs on our server, is to comment the following line of code in the file 'kafkaSubscriber.py' inside the service 'history':

> self.db[collection_name].create_index('ts', expireAfterSeconds=conf.db_expiration)

Now the time set in the environment variable or in db_expiration is no longer considered. Is there another way to get the same result?

**Comment by giovannicuriel** [comment]
I'll mark this issue as a bug so that we can track it better. 
I think that there should be a way for the user to indicate that the data must be scheduled to be removed or it must stay in the database indefinitely - maybe setting the DATA_EXPIRATION env var should remove data after a while and not setting it would remain in the database?

**Comment by rascaraficci** [comment]
This issue will be closed by inactivity.
