### ISSUE TITLE
Flow-broker - remote node persistence

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#742]

**Comment by betefaber** [comment]
**The node is not persisted:**

![screenshot_35](https://user-images.githubusercontent.com/37310063/50087641-e2767d00-01e7-11e9-8bab-3e5dcaf20569.png)

**Steps executed:**

1. Start dojot
2. Add remote node
3. Create flow with remote node

> {
> "message":"ok",
> "flow":{
> "name":"kelvin flow",
> "enabled":true,
> "id":"e860db31-da3a-40c7-88f0-8075caf1030a",
> "flow":
> [
> {"id":"9d53e6e.1fcd818","type":"tab","label":"Flow 1"},
> {
> "id":"d919caa8.bca788",
> "type":"device in",
> "z":"9d53e6e.1fcd818",
> "name":"termometro",
> "device_source_id":"termometro (d4b9a4)",
> "status":"false",
> "_device_id":"d4b9a4",
> "_device_label":"",
> "_device_type":"",
> "x":234.5,"y":180,
> "wires":[["bce46601.d18af8"]]
> },
> {
> "id":"bce46601.d18af8",
> "type":"kelvin",
> "z":"9d53e6e.1fcd818",
> "name":"",
> "out":"saida.temperatura",
> "outFieldType":"msg",
> "in":"payload.temperatura",
> "inFieldType":"msg",
> "x":464.5,
> "y":186,
> "wires":[["2cd96daa.791942"]]},
> {
> "id":"2cd96daa.791942",
> "type":"device out",
> "z":"9d53e6e.1fcd818",
> "name":"termometro kelvin",
> "device_source":"configured",
> "device_source_msg":"",
> "device_source_id":"termometro kelvin (2e5a3f)",
> "attrs":"saida",
> "_device_id":"2e5a3f",
> "x":718.5,
> "y":188,
> "wires":[]
> }
> ],
> "created":1545045592651,"updated":1545045592651}
> }

4. Execute flow

> flowbroker_1                  | <11:37:04 17/12/2018> -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 64 34 62 39 61 34 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
> flowbroker_1                  |   size: 103,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '3e2e678a-ea72-4db1-899a-3fe46e6e50ec',
> flowbroker_1                  |   offset: 9,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1545046623605 }
> flowbroker_1                  | <11:37:04 17/12/2018> -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <11:37:04 17/12/2018> -- DEBUG: Queued event {"metadata":{"deviceid":"d4b9a4","tenant":"admin","timestamp":1545046623605},"attrs":{"temperatura":1}}
> flowbroker_1                  | <11:37:04 17/12/2018> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"d4b9a4","tenant":"admin","timestamp":1545046623605},"attrs":{"temperatura":1}}
> flowbroker_1                  | <11:37:04 17/12/2018> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: 'd4b9a4', tenant: 'admin', timestamp: 1545046623605 },
> flowbroker_1                  |   attrs: { temperatura: 1 } }
> flowbroker_1                  | [executor] will handle node kelvin
> flowbroker_1                  | [dispatcher] remote [6bbef0072c86] took 2ms
> flowbroker_1                  | [executor] hop (kelvin) result: [{"payload":{"temperatura":1},"saida":{"temperatura":274.15}}]
> flowbroker_1                  | [executor] will handle node device out
> flowbroker_1                  | debug: Executing device-out node...
> flowbroker_1                  | debug: Updating device...
> flowbroker_1                  | debug: Message is: { attrs: { temperatura: 274.15 },
> flowbroker_1                  |   metadata: { deviceid: '2e5a3f', timestamp: 1545046624617, tenant: 'admin' } }
> flowbroker_1                  | object
> flowbroker_1                  | will produce [object Object] to device-data:admin
> flowbroker_1                  | <11:37:04 17/12/2018> -- DEBUG: Trying to publish someting. Current producer topics are { 'dojot.device-manager.device': { admin: 'df3dd0d8-a28d-4a37-8e38-6a41ceba38a5' },
> flowbroker_1                  |   'device-data': { admin: '3e2e678a-ea72-4db1-899a-3fe46e6e50ec' } }
> flowbroker_1                  | debug: ... device was updated.
> flowbroker_1                  | debug: ... device-out node was successfully executed.
> flowbroker_1                  | [executor] hop (device out) result: undefined

![screenshot_29](https://user-images.githubusercontent.com/37310063/50087536-83b10380-01e7-11e9-91ff-61e49332f60b.png)

![screenshot_30](https://user-images.githubusercontent.com/37310063/50087535-83b10380-01e7-11e9-8484-7feef696b95b.png)

5. Restart flowbroker

Restarting dojot_flowbroker_1 ... done

> flowbroker_1                  | Subscribed to topic 295d289f-aa03-42b9-b341-014194b1fe40
> flowbroker_1                  | <11:39:10 17/12/2018> -- DEBUG: Adding a producer topic.
> flowbroker_1                  | [redis] Succesfully connected to redis
> flowbroker_1                  | [amqp] producer ready ...
> flowbroker_1                  | info: [executor] Worker ready.
> flowbroker_1                  | [redis] Cache is cleared
> flowbroker_1                  | [amqp] producer ready ...
> flowbroker_1                  | [amqp] consumer ready ...
> flowbroker_1                  | [amqp] producer ready ...
> flowbroker_1                  | <11:39:10 17/12/2018> -- DEBUG: Connections established with RabbitMQ!
> flowbroker_1                  | [amqp] consumer ready ...
> flowbroker_1                  | debug: ...[remoteNode] container already up with id 6bbef0072c86.

![screenshot_34](https://user-images.githubusercontent.com/37310063/50087579-a6dbb300-01e7-11e9-86b2-073e0f7b4bbe.png)

6. Execute flow


- the flow does not executed:

![screenshot_32](https://user-images.githubusercontent.com/37310063/50087620-d1c60700-01e7-11e9-9c44-af8f28c689ff.png)

![screenshot_33](https://user-images.githubusercontent.com/37310063/50087619-d1c60700-01e7-11e9-9b36-899607f93d37.png)

> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 64 34 62 39 61 34 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
> flowbroker_1                  |   size: 103,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '3e2e678a-ea72-4db1-899a-3fe46e6e50ec',
> flowbroker_1                  |   offset: 15,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1545047005558 }
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: Queued event {"metadata":{"deviceid":"d4b9a4","tenant":"admin","timestamp":1545047005558},"attrs":{"temperatura":5}}
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"d4b9a4","tenant":"admin","timestamp":1545047005558},"attrs":{"temperatura":5}}
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: 'd4b9a4', tenant: 'admin', timestamp: 1545047005558 },
> flowbroker_1                  |   attrs: { temperatura: 5 } }
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 20 7b 22 64 65 76 69 63 65 69 64 22 3a 20 22 64 34 62 39 61 34 22 2c 20 22 74 65 6e 61 6e 74 22 3a 20 22 61 64 6d ... >,
> flowbroker_1                  |   size: 101,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '3e2e678a-ea72-4db1-899a-3fe46e6e50ec',
> flowbroker_1                  |   offset: 16,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1545047006633 }
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: Queued event {"metadata": {"deviceid": "d4b9a4", "tenant": "admin", "status": "online", "reason": "statusUpdate"}}
> flowbroker_1                  | [redis] storing device info on cache . . .
> flowbroker_1                  | [redis] . . . device info stored successfully
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: Pre-processing event {"metadata": {"deviceid": "d4b9a4", "tenant": "admin", "status": "online", "reason": "statusUpdate"}}
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: [ingestor] got new device event: { metadata:
> flowbroker_1                  |    { deviceid: 'd4b9a4',
> flowbroker_1                  |      tenant: 'admin',
> flowbroker_1                  |      status: 'online',
> flowbroker_1                  |      reason: 'statusUpdate' } }
> flowbroker_1                  | [executor] will handle node kelvin
> flowbroker_1                  | [executor] Unknown node kelvin detected. Igoring.
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: [ingestor] ignoring device status update d4b9a4 e860db31-da3a-40c7-88f0-8075caf1030a
> flowbroker_1                  | <11:43:26 17/12/2018> -- DEBUG: [ingestor] ignoring device status update d4b9a4 273524c8-4d75-4de9-b1a4-e8d65c1cb073
> flowbroker_1                  | <11:43:32 17/12/2018> -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 20 7b 22 64 65 76 69 63 65 69 64 22 3a 20 22 64 34 62 39 61 34 22 2c 20 22 74 65 6e 61 6e 74 22 3a 20 22 61 64 6d ... >,
> flowbroker_1                  |   size: 102,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '3e2e678a-ea72-4db1-899a-3fe46e6e50ec',
> flowbroker_1                  |   offset: 17,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1545047012725 }
> flowbroker_1                  | <11:43:32 17/12/2018> -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <11:43:32 17/12/2018> -- DEBUG: Queued event {"metadata": {"deviceid": "d4b9a4", "tenant": "admin", "status": "offline", "reason": "statusUpdate"}}
> flowbroker_1                  | <11:43:32 17/12/2018> -- DEBUG: Pre-processing event {"metadata": {"deviceid": "d4b9a4", "tenant": "admin", "status": "offline", "reason": "statusUpdate"}}
> flowbroker_1                  | <11:43:32 17/12/2018> -- DEBUG: [ingestor] got new device event: { metadata:
> flowbroker_1                  |    { deviceid: 'd4b9a4',
> flowbroker_1                  |      tenant: 'admin',
> flowbroker_1                  |      status: 'offline',
> flowbroker_1                  |      reason: 'statusUpdate' } }

- the node is not persisted

![screenshot_35](https://user-images.githubusercontent.com/37310063/50087641-e2767d00-01e7-11e9-8bab-3e5dcaf20569.png)

**Comment by betefaber** [comment]
After the restart of the flowbroker, the remote node is lost.

- the node is not removed because it does not exist:

curl -X DELETE ${DOJOT_HOST}/flows/v1/node/kelvin -H "Authorization: Bearer ${JWT}" -H "content-type: application/json"
{
    "message": "Failed to remove node."
}

> flowbroker_1                  |   body: { message: 'No such container: 609f927721f8' } }

- the node is not added because it already exists:

curl -X POST ${DOJOT_HOST}/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" -d '{"image": "mmagr/kelvin:latest", "id":"kelvin"}' 
{
    "message": "Failed to add node: ... This image already up. Image: mmagr/kelvin:latest"
}

> flowbroker_1                  | debug: ... This image already up. Image: mmagr/kelvin:latest


> matheusr@vali:/opt/teste/current/docker-compose$ sudo docker ps -a
> CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS                    PORTS                                             NAMES
> c2b97a481f1b        appropriate/curl                                "/opt/kong.config.sh"    27 hours ago        Exited (0) 27 hours ago                                                     dojot_kong-config_1
> 330293b435ee        dojot/iotagent-mosca:0.3.0-nightly20181129      "/opt/entrypoint.sh"     27 hours ago        Up 10 hours               0.0.0.0:1883->1883/tcp, 0.0.0.0:8883->8883/tcp    dojot_iotagent-mqtt_1
> dec6252ae48e        dojot/flowbroker:0.3.0-nightly20181129          "node src/index.js -â¦"   27 hours ago        Up 10 hours                                                                 dojot_flowbroker_1
> 525331d8e16b        giovannicuriel/kong:0.3.0-nightly20180607-old   "/docker-entrypoint.â¦"   27 hours ago        Up 10 hours               8001/tcp, 0.0.0.0:8000->8000/tcp, 8443-8444/tcp   dojot_apigw_1
> 36e450a7d784        postgres:9.4-alpine                             "docker-entrypoint.sâ¦"   27 hours ago        Exited (0) 27 hours ago                                                     dojot_postgres-users_1
> 1c0fb0bbea33        giovannicuriel/kong:0.3.0-nightly20180607-old   "/docker-entrypoint.â¦"   27 hours ago        Exited (0) 27 hours ago                                                     dojot_kong-migration_1
> 3e7392e29731        dojot/auth:0.3.0-nightly20181129                "./appRun.sh start"      27 hours ago        Up 10 hours               5000/tcp                                          dojot_auth_1
> 496f203e2e4b        dojot/device-manager:0.3.0-nightly20181129      "./docker/entrypointâ¦"   27 hours ago        Up 10 hours               5000/tcp                                          dojot_device-manager_1
> bcc2bcbe75de        dojot/persister:0.3.0-nightly20181129           "python history/subsâ¦"   27 hours ago        Up 10 hours                                                                 dojot_persister_1
> 607510a804f2        dojot/data-broker:0.3.0-nightly20181129         "npm run subscription"   27 hours ago        Up 10 hours               80/tcp                                            dojot_data-broker_1
> fbd74052799c        ches/kafka:0.10.1.1                             "/start.sh"              27 hours ago        Up 10 hours               7203/tcp, 9092/tcp                                dojot_kafka_1
> 8e40fe984139        dojot/flowbroker-context-manager:latest         "node src/index.js"      27 hours ago        Up 10 hours                                                                 dojot_flowbroker-context-manager_1
> 5f1caf33e216        dojot/history:0.3.0-nightly20181129             "./docker/falcon-docâ¦"   27 hours ago        Up 10 hours               8000/tcp                                          dojot_history_1
> fd6f3df52a0d        dojot/gui:0.3.0-nightly20181129                 "nginx -g 'daemon ofâ¦"   27 hours ago        Up 10 hours               80/tcp                                            dojot_gui_1
> 4bd6286322b3        dojot/ejbca-rest:0.3.0-nightly20181129          "/root/entrypoint.sh"    27 hours ago        Up 10 hours               5583/tcp, 8080/tcp, 8443/tcp                      dojot_ejbca_1
> 7bafa04008ef        rabbitmq:3.7-alpine                             "docker-entrypoint.sâ¦"   27 hours ago        Up 10 hours               4369/tcp, 5671-5672/tcp, 25672/tcp                dojot_rabbitmq_1
> 8064d2da56bb        mongo:3.2                                       "docker-entrypoint.sâ¦"   27 hours ago        Up 10 hours               27017/tcp                                         dojot_mongodb_1
> fbe5037a247c        postgres:9.4-alpine                             "docker-entrypoint.sâ¦"   27 hours ago        Up 10 hours (healthy)     5432/tcp                                          dojot_postgres_1
> d21b7a565c42        redis:alpine                                    "docker-entrypoint.sâ¦"   27 hours ago        Up 10 hours               6379/tcp                                          dojot_data-broker-redis_1
> 58597dbfccdd        redis:alpine                                    "docker-entrypoint.sâ¦"   27 hours ago        Up 10 hours               6379/tcp                                          dojot_auth-redis_1
> 6a042f4776d7        redis:alpine                                    "docker-entrypoint.sâ¦"   27 hours ago        Up 10 hours               6379/tcp                                          dojot_flowbroker-redis_1
> a4a556197e6f        redis:alpine                                    "docker-entrypoint.sâ¦"   27 hours ago        Up 10 hours               6379/tcp                                          dojot_mosca-redis_1
> 5dab9a9a6b4c        redis:alpine                                    "docker-entrypoint.sâ¦"   27 hours ago        Up 10 hours               6379/tcp                                          dojot_device-manager-redis_1
> 8711911f187c        zookeeper:3.4                                   "/docker-entrypoint.â¦"   27 hours ago        Up 10 hours               2181/tcp, 2888/tcp, 3888/tcp                      dojot_zookeeper_1
> matheusr@vali:/opt/teste/current/docker-compose$

**Comment by betefaber** [comment]
Test OK.

- added remote node: **kelvin**

![screenshot_74](https://user-images.githubusercontent.com/37310063/51273638-602ed380-19b4-11e9-8cc1-2afb400649e3.png)

- flow is created
![image](https://user-images.githubusercontent.com/37310063/51273786-ac7a1380-19b4-11e9-8120-fa12a4d70494.png)

- flow is executed

> $ mosquitto_pub -t /admin/7d8eb4/attrs -m '{"temperatura": 15}' -i admin:7d8eb4

> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 37 64 38 65 62 34 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
> flowbroker_1                  |   size: 104,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '956c3401-b0ec-41d6-9ee9-81c722d14598',
> flowbroker_1                  |   offset: 2,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1547665371360 }
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: Queued event {"metadata":{"deviceid":"7d8eb4","tenant":"admin","timestamp":1547665371360},"attrs":{"temperatura":15}}
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"7d8eb4","tenant":"admin","timestamp":1547665371360},"attrs":{"temperatura":15}}
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: '7d8eb4', tenant: 'admin', timestamp: 1547665371360 },
> flowbroker_1                  |   attrs: { temperatura: 15 } }
> flowbroker_1                  | [executor] will handle node kelvin
> flowbroker_1                  | [dispatcher] remote [e40bafa3e9d3] took 3ms
> flowbroker_1                  | [executor] hop (kelvin) result: [{"payload":{"temperatura":15},"saida":{"temperatura":288.15}}]
> flowbroker_1                  | [executor] will handle node device out
> flowbroker_1                  | object
> flowbroker_1                  | will produce [object Object] to device-data:admin
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: Trying to publish someting. Current producer topics are { 'dojot.device-manager.device':
> flowbroker_1                  |    { admin: '77ae9c31-26a0-499d-84e2-0ef463630c0b',
> flowbroker_1                  |      teste: '4eecd467-dc96-4475-b0c2-3d3bac7e7870' },
> flowbroker_1                  |   'device-data':
> flowbroker_1                  |    { admin: '956c3401-b0ec-41d6-9ee9-81c722d14598',
> flowbroker_1                  |      teste: '931dd2c2-3354-4d4e-8a99-2adb3122eb44' } }
> flowbroker_1                  | [executor] hop (device out) result: undefined
> flowbroker_1                  | debug: Executing device-out node...
> flowbroker_1                  | debug: Updating device...
> flowbroker_1                  | debug: Message is: { attrs: { temperatura: 288.15 },
> flowbroker_1                  |   metadata: { deviceid: 'e88c60', timestamp: 1547665372774, tenant: 'admin' } }
> flowbroker_1                  | debug: ... device was updated.
> flowbroker_1                  | debug: ... device-out node was successfully executed.
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: Received message: { value: <Buffer 7b 22 61 74 74 72 73 22 3a 7b 22 74 65 6d 70 65 72 61 74 75 72 61 22 3a 32 38 38 2e 31 35 7d 2c 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 ... >,
> flowbroker_1                  |   size: 108,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '956c3401-b0ec-41d6-9ee9-81c722d14598',
> flowbroker_1                  |   offset: 3,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1547665372775 }
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: Queued event {"attrs":{"temperatura":288.15},"metadata":{"deviceid":"e88c60","timestamp":1547665372774,"tenant":"admin"}}
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: Pre-processing event {"attrs":{"temperatura":288.15},"metadata":{"deviceid":"e88c60","timestamp":1547665372774,"tenant":"admin"}}
> flowbroker_1                  | <19:02:52 16/01/2019> -- DEBUG: [ingestor] got new device event: { attrs: { temperatura: 288.15 },
> flowbroker_1                  |   metadata: { deviceid: 'e88c60', timestamp: 1547665372774, tenant: 'admin' } }

![screenshot_75](https://user-images.githubusercontent.com/37310063/51273664-72a90d00-19b4-11e9-810b-a08bf1890ad8.png)
![screenshot_76](https://user-images.githubusercontent.com/37310063/51273663-72a90d00-19b4-11e9-9026-25a2ff5de9fb.png)

- flowbroker is restarted

> $ sudo docker-compose restart flowbroker
> Restarting dojot_flowbroker_1 ... done
> $

> flowbroker_1                  | [nodes] image mmagr/kelvin:latest created
> flowbroker_1                  | [nodes] container flowbroker.b31ed07 was created
> flowbroker_1                  | Target: fdbcfcb57b04
> flowbroker_1                  | [nodes] container up: flowbroker.b31ed07:fdbcfcb57b047fb6d51d3d54908ecc0fefa2cdd83668b96bed3da88d818d2f7d
> flowbroker_1                  | [dispatcher] remote [fdbcfcb57b04] took 6ms
> flowbroker_1                  | [dispatcher] remote [fdbcfcb57b04] took 2ms
> flowbroker_1                  | [dispatcher] remote [fdbcfcb57b04] took 5ms
> flowbroker_1                  | debug: ... This image already up. Image: mmagr/kelvin:latest

![screenshot_77](https://user-images.githubusercontent.com/37310063/51273824-c9164b80-19b4-11e9-837d-fdc4649a3c72.png)

- flow is executed

> $ mosquitto_pub -t /admin/7d8eb4/attrs -m '{"temperatura": 12}' -i admin:7d8eb4
>
> flowbroker_1                  | <19:12:08 16/01/2019> -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 37 64 38 65 62 34 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
> flowbroker_1                  |   size: 104,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '956c3401-b0ec-41d6-9ee9-81c722d14598',
> flowbroker_1                  |   offset: 4,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1547665927120 }
> flowbroker_1                  | <19:12:08 16/01/2019> -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <19:12:08 16/01/2019> -- DEBUG: Queued event {"metadata":{"deviceid":"7d8eb4","tenant":"admin","timestamp":1547665927119},"attrs":{"temperatura":12}}
> flowbroker_1                  | <19:12:08 16/01/2019> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"7d8eb4","tenant":"admin","timestamp":1547665927119},"attrs":{"temperatura":12}}
> flowbroker_1                  | <19:12:08 16/01/2019> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: '7d8eb4', tenant: 'admin', timestamp: 1547665927119 },
> flowbroker_1                  |   attrs: { temperatura: 12 } }
> flowbroker_1                  | [redis] storing device info on cache . . .
> flowbroker_1                  | [redis] . . . device info stored successfully
> flowbroker_1                  | [executor] will handle node kelvin
> flowbroker_1                  | [dispatcher] remote [fdbcfcb57b04] took 5ms
> flowbroker_1                  | debug: Executing device-out node...
> flowbroker_1                  | debug: Updating device...
> flowbroker_1                  | debug: Message is: { attrs: { temperatura: 285.15 },
> flowbroker_1                  |   metadata: { deviceid: 'e88c60', timestamp: 1547665928540, tenant: 'admin' } }
> flowbroker_1                  | debug: ... device was updated.
> flowbroker_1                  | debug: ... device-out node was successfully executed.
> flowbroker_1                  | [executor] hop (kelvin) result: [{"payload":{"temperatura":12},"saida":{"temperatura":285.15}}]
> flowbroker_1                  | [executor] will handle node device out
> flowbroker_1                  | object
> flowbroker_1                  | will produce [object Object] to device-data:admin
> flowbroker_1                  | <19:12:08 16/01/2019> -- DEBUG: Trying to publish someting. Current producer topics are { 'dojot.device-manager.device':
> flowbroker_1                  |    { admin: '77ae9c31-26a0-499d-84e2-0ef463630c0b',
> flowbroker_1                  |      teste: '4eecd467-dc96-4475-b0c2-3d3bac7e7870' },
> flowbroker_1                  |   'device-data':
> flowbroker_1                  |    { admin: '956c3401-b0ec-41d6-9ee9-81c722d14598',
> flowbroker_1                  |      teste: '931dd2c2-3354-4d4e-8a99-2adb3122eb44' } }
> flowbroker_1                  | [executor] hop (device out) result: undefined
> flowbroker_1                  | debug: Checking memory.
> flowbroker_1                  | <19:12:09 16/01/2019> -- DEBUG: Received message: { value: <Buffer 7b 22 61 74 74 72 73 22 3a 7b 22 74 65 6d 70 65 72 61 74 75 72 61 22 3a 32 38 35 2e 31 35 7d 2c 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 ... >,
> flowbroker_1                  |   size: 108,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '956c3401-b0ec-41d6-9ee9-81c722d14598',
> flowbroker_1                  |   offset: 5,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1547665928541 }
> flowbroker_1                  | <19:12:09 16/01/2019> -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <19:12:09 16/01/2019> -- DEBUG: Queued event {"attrs":{"temperatura":285.15},"metadata":{"deviceid":"e88c60","timestamp":1547665928540,"tenant":"admin"}}
> flowbroker_1                  | <19:12:09 16/01/2019> -- DEBUG: Pre-processing event {"attrs":{"temperatura":285.15},"metadata":{"deviceid":"e88c60","timestamp":1547665928540,"tenant":"admin"}}
> flowbroker_1                  | <19:12:09 16/01/2019> -- DEBUG: [ingestor] got new device event: { attrs: { temperatura: 285.15 },
> flowbroker_1                  |   metadata: { deviceid: 'e88c60', timestamp: 1547665928540, tenant: 'admin' } }
> flowbroker_1                  | [redis] storing device info on cache . . .
> flowbroker_1                  | [redis] . . . device info stored successfully

![screenshot_78](https://user-images.githubusercontent.com/37310063/51273841-d3d0e080-19b4-11e9-9fc8-0c74de90d0e9.png)
![screenshot_79](https://user-images.githubusercontent.com/37310063/51273840-d3d0e080-19b4-11e9-88c1-09a070381a46.png)
