### ISSUE TITLE
[GUI] New template creation screen disappears when page changes

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#756]
**Prerequisite:**

- At least 7 templates, 6 templates per page

**Steps to reproduce the problem:**

1. On page 1, click "New Template". Template creation screen is displayed.
2. Click page 2
3. Click page 1. Template creation screen disappears. 
4. Click "New Template". Template creation screen does not open.

You need to refresh the page (F5) so that the New Template button reopens the template creation screen.

**Affected Version:** 0.3.0-nightly_20181010

**Comment by MPrevide** [comment]
Maybe this won't be fix, because the page will be refactor.

**Comment by betefaber** [comment]
This ticket will close after refactoring.

**Comment by betefaber** [comment]
Templates screen has been refactored.
