### ISSUE TITLE
Real-time is not working for tenants other than admin

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#764]
On the details screen, the graphs are not updated in real time.

- tenant teste

![screenshot_103](https://user-images.githubusercontent.com/37310063/47525343-64df6200-d873-11e8-9252-e23e424acfde.png)

- simulator publishes data but the map and graphs are not updated

![screenshot_104](https://user-images.githubusercontent.com/37310063/47525356-6c067000-d873-11e8-90a6-a63b9af7e401.png)

- another example

![image](https://user-images.githubusercontent.com/37310063/47526799-3c596700-d877-11e8-97d1-02f29b74b291.png)

**Comment by giovannicuriel** [comment]
There are some evidences that historical data is also affected by this issue.

**Comment by betefaber** [comment]
![real-time-teste](https://user-images.githubusercontent.com/37310063/50841077-0fcbcc00-134b-11e9-847d-172bcf46cf6a.png)

curl -X GET "http://10.4.1.41:8000/history/device/edc04/history?lastN=10&attr=int" -H 'Content-Type: application/json' -H "Authorization: Bearer ${JWT}"
{
    "int": [
        {
            "attr": "int",
            "value": 10,
            "device_id": "edc04",
            "ts": "2019-01-08T15:23:56.216000Z"
        },
        {
            "attr": "int",
            "value": 13,
            "device_id": "edc04",
            "ts": "2019-01-08T15:23:00.630000Z"
        },
        {
            "attr": "int",
            "value": 12,
            "device_id": "edc04",
            "ts": "2019-01-08T15:22:32.935000Z"
        },
        {
            "attr": "int",
            "value": 15,
            "device_id": "edc04",
            "ts": "2019-01-08T15:21:55.382000Z"
        }
    ]
}

baseline: **0.3.0-nightly_20181227**

**Comment by giovannicuriel** [comment]
Is this still happening?

**Comment by betefaber** [comment]
Test OK.

Tested on Version: **62.2-20190524**
