### ISSUE TITLE
[GUI] Device details screen: map is not resized

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#775]
**Steps to reproduce the problem:**

1. In device details screen, select the geo attribute
2. Click the icon to expand the map
3. Verify that the map is not resized

![screenshot_10](https://user-images.githubusercontent.com/37310063/48078200-12396a80-e1d0-11e8-9369-685756d5e86e.png)

**Affected Version**: 0.3.0-nightly_20181030

**Comment by cfrancisco** [comment]
I could not reproduce it. Is possible to check again?

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/56369023-f0a4cc00-61ce-11e9-8fc7-1bb030299910.png)
