### ISSUE TITLE
Template metadata does not have the update function.

### ISSUE THREAD

**Issue by eliasreis54** [dojot/dojot#779]
When you make a PUT request and you want to change the metadata of template, It isn't work. Only the POST method is working.

**Comment by betefaber** [comment]
Test OK.

![screenshot_102](https://user-images.githubusercontent.com/37310063/53047228-be961880-3470-11e9-8dc1-b91ac9bf5931.png)

![screenshot_103](https://user-images.githubusercontent.com/37310063/53047234-c2299f80-3470-11e9-90d6-b07e1a648c6d.png)

> persister_1                   | [19/02/19 - 20:34:32] |messenger| INFO: Emitting new event message for subject dojot.device-manager.device@admin
> persister_1                   | [19/02/19 - 20:34:32] |persister| INFO: got device event {'event': 'template.update', 'data': {'affected': ['52e40b', 'c1dd8e'], 'template': {'created': '2019-02-19T14:22:27.155007+00:00', 'id': 1, 'attrs': [{'value_type': 'string', 'created': '2019-02-19T17:47:37.722035+00:00', 'static_value': '', 'id': 6, 'type': 'actuator', 'template_id': '1', 'label': 'mensagem'}, {'value_type': 'geo:point', 'created': '2019-02-19T17:05:16.252442+00:00', 'static_value': '', 'id': 3, 'type': 'dynamic', 'template_id': '1', 'label': 'gps'}, {'value_type': 'integer', 'created': '2019-02-19T14:22:27.157024+00:00', 'static_value': '', 'id': 1, 'type': 'dynamic', 'template_id': '1', 'metadata': [{'value_type': 'string', 'created': '2019-02-19T17:45:13.154195+00:00', 'static_value': 'pÃ¡ginas', 'id': 11, 'updated': None, 'type': 'meta', 'label': 'unidade'}], 'label': 'int'}, {'value_type': 'string', 'created': '2019-02-19T14:22:27.159371+00:00', 'static_value': 'Sigfox', 'id': 2, 'updated': '2019-02-19T16:55:51.905445+00:00', 'type': 'meta', 'template_id': '1', 'label': 'protocol'}, {'value_type': 'string', 'created': '2019-02-19T17:47:10.987274+00:00', 'static_value': 'indefinido', 'id': 5, 'type': 'static', 'template_id': '1', 'metadata': [{'value_type': 'string', 'created': '2019-02-19T19:00:57.810547+00:00', 'static_value': 'serial number do dispositivo', 'id': 7, 'updated': None, 'type': 'meta', 'label': 'descricao'}], 'label': 'SN'}], 'config_attrs': [{'value_type': 'string', 'created': '2019-02-19T17:47:37.722035+00:00', 'static_value': '', 'id': 6, 'type': 'actuator', 'template_id': '1', 'label': 'mensagem'}, {'value_type': 'string', 'created': '2019-02-19T14:22:27.159371+00:00', 'static_value': 'Sigfox', 'id': 2, 'updated': '2019-02-19T16:55:51.905445+00:00', 'type': 'meta', 'template_id': '1', 'label': 'protocol'}], 'data_attrs': [{'value_type': 'geo:point', 'created': '2019-02-19T17:05:16.252442+00:00', 'static_value': '', 'id': 3, 'type': 'dynamic', 'template_id': '1', 'label': 'gps'}, {'value_type': 'integer', 'created': '2019-02-19T14:22:27.157024+00:00', 'static_value': '', 'id': 1, 'type': 'dynamic', 'template_id': '1', 'metadata': [{'value_type': 'string', 'created': '2019-02-19T17:45:13.154195+00:00', 'static_value': 'pÃ¡ginas', 'id': 11, 'updated': None, 'type': 'meta', 'label': 'unidade'}], 'label': 'int'}, {'value_type': 'string', 'created': '2019-02-19T17:47:10.987274+00:00', 'static_value': 'indefinido', 'id': 5, 'type': 'static', 'template_id': '1', 'metadata': [{'value_type': 'string', 'created': '2019-02-19T19:00:57.810547+00:00', 'static_value': 'serial number do dispositivo', 'id': 7, 'updated': None, 'type': 'meta', 'label': 'descricao'}], 'label': 'SN'}], 'label': 'template'}}, 'meta': {'service': 'admin'}}

----
> device-manager_1              | [19/02/19 - 19:34:04] |TemplateHandler| DEBUG:  Current json payload: 
> {'attrs': [
> {'created': '2019-02-19T17:05:16.252442+00:00', 'label': 'gps', 'static_value': '', 'template_id': '1', 'type': 'dynamic', 'value_type': 'geo:point'}, 
> {'created': '2019-02-19T14:22:27.157024+00:00', 'label': 'int', 'metadata': [{'created': '2019-02-19T17:45:13.154195+00:00', 'label': '@', 'static_value': 'km/h', 'type': '#', 'updated': None, 'value_type': 'integer'}], 'static_value': '', 'template_id': '1', 'type': 'dynamic', 'value_type': 'integer'}, 
> {'created': '2019-02-19T17:47:10.987274+00:00', 'label': 'SN', 'metadata': [{'created': '2019-02-19T19:00:57.810547+00:00', 'label': 'descricao', 'static_value': 'serial number do dispositivo', 'type': 'meta', 'updated': None, 'value_type': 'string'}], 'static_value': 'indefinido', 'template_id': '1', 'type': 'static', 'value_type': 'string'}, 
> {'created': '2019-02-19T17:47:37.722035+00:00', 'label': 'mensagem', 'static_value': '', 'template_id': '1', 'type': 'actuator', 'value_type': 'string'}, 
> {'created': '2019-02-19T14:22:27.159371+00:00', 'label': 'protocol', 'static_value': 'Sigfox', 'template_id': '1', 'type': 'meta', 'updated': '2019-02-19T16:55:51.905445+00:00', 'value_type': 'string'}], 
> 'config_attrs': [{'created': '2019-02-19T14:22:27.159371+00:00', 'id': 2, 'label': 'protocol', 'static_value': 'Sigfox', 'template_id': '1', 'type': 'meta', 'updated': '2019-02-19T16:55:51.905445+00:00', 'value_type': 'string'}], 'created': '2019-02-19T14:22:27.155007+00:00', 
> 'data_attrs': [{'created': '2019-02-19T17:05:16.252442+00:00', 'id': 3, 'label': 'gps', 'static_value': '', 'template_id': '1', 'type': 'dynamic', 'value_type': 'geo:point'}, {'created': '2019-02-19T14:22:27.157024+00:00', 'id': 1, 'label': 'int', 'metadata': [{'created': '2019-02-19T17:45:13.154195+00:00', 'id': 9, 'label': '@', 'static_value': 'km/h', 'type': '#', 'updated': None, 'value_type': 'integer'}], 'static_value': '', 'template_id': '1', 'type': 'dynamic', 'value_type': 'integer'}, {'created': '2019-02-19T17:47:10.987274+00:00', 'id': 5, 'label': 'SN', 'metadata': [{'created': '2019-02-19T19:00:57.810547+00:00', 'id': 7, 'label': 'descricao', 'static_value': 'serial number do dispositivo', 'type': 'meta', 'updated': None, 'value_type': 'string'}], 'static_value': 'indefinido', 'template_id': '1', 'type': 'static', 'value_type': 'string'}, {'created': '2019-02-19T17:47:37.722035+00:00', 'id': 6, 'label': 'mensagem', 'static_value': '', 'template_id': '1', 'type': 'actuator', 'value_type': 'string'}], 'id': 1, 'label': 'template'}
> device-manager_1              | [19/02/19 - 19:34:04] |TemplateHandler| DEBUG:  Checking old template attributes
> device-manager_1              | [19/02/19 - 19:34:04] |TemplateHandler| DEBUG:  Removing attribute
> device-manager_1              | [19/02/19 - 19:34:04] |TemplateHandler| DEBUG:  Commiting new data...
> device-manager_1              | [19/02/19 - 19:34:04] |TemplateHandler| DEBUG: ... data committed.
> device-manager_1              | [19/02/19 - 19:34:04] |TemplateHandler| INFO: Updating template with id: 1
> device-manager_1              | [19/02/19 - 19:34:04] |TemplateHandler| DEBUG:  Querying templates sorted by DeviceTemplate.label
> device-manager_1              | [19/02/19 - 19:34:04] |TemplateHandler| INFO:  Getting template with id 1
> device-manager_1              | [19/02/19 - 20:19:49] |TemplateHandler| DEBUG:  Querying templates sorted by DeviceTemplate.id
> device-manager_1              | [19/02/19 - 20:19:49] |TemplateHandler| INFO:  Getting template with id 1
> device-manager_1              | [19/02/19 - 20:19:49] |DeviceHandler| DEBUG:  Querying devices sorted by device id
> device-manager_1              | [19/02/19 - 20:19:49] |DeviceHandler| INFO:  Getting latest added device(s).
> device-manager_1              | [19/02/19 - 20:19:49] |TemplateHandler| DEBUG:  Querying templates sorted by DeviceTemplate.id
> device-manager_1              | [19/02/19 - 20:19:49] |TemplateHandler| INFO:  Getting template with id 1
> device-manager_1              | [19/02/19 - 20:33:39] |TemplateHandler| DEBUG:  Querying templates sorted by DeviceTemplate.label
> device-manager_1              | [19/02/19 - 20:33:39] |TemplateHandler| INFO:  Getting template with id 1
> device-manager_1              | [19/02/19 - 20:34:32] |TemplateHandler| DEBUG:  Current json payload: {'attrs': [
> {'created': '2019-02-19T17:05:16.252442+00:00', 'label': 'gps', 'static_value': '', 'template_id': '1', 'type': 'dynamic', 'value_type': 'geo:point'}, 
> {'created': '2019-02-19T14:22:27.157024+00:00', 'label': 'int', 'metadata': [{'created': '2019-02-19T17:45:13.154195+00:00', 'label': 'unidade', 'static_value': 'pÃ¡ginas', 'type': 'meta', 'updated': None, 'value_type': 'string'}], 'static_value': '', 'template_id': '1', 'type': 'dynamic', 'value_type': 'integer'}, 
> {'created': '2019-02-19T17:47:10.987274+00:00', 'label': 'SN', 'metadata': [{'created': '2019-02-19T19:00:57.810547+00:00', 'label': 'descricao', 'static_value': 'serial number do dispositivo', 'type': 'meta', 'updated': None, 'value_type': 'string'}], 'static_value': 'indefinido', 'template_id': '1', 'type': 'static', 'value_type': 'string'}, 
> {'created': '2019-02-19T17:47:37.722035+00:00', 'label': 'mensagem', 'static_value': '', 'template_id': '1', 'type': 'actuator', 'value_type': 'string'}, {'created': '2019-02-19T14:22:27.159371+00:00', 'label': 'protocol', 'static_value': 'Sigfox', 'template_id': '1', 'type': 'meta', 'updated': '2019-02-19T16:55:51.905445+00:00', 'value_type': 'string'}], 
> 'config_attrs': [{'created': '2019-02-19T14:22:27.159371+00:00', 'id': 2, 'label': 'protocol', 'static_value': 'Sigfox', 'template_id': '1', 'type': 'meta', 'updated': '2019-02-19T16:55:51.905445+00:00', 'value_type': 'string'}], 'created': '2019-02-19T14:22:27.155007+00:00', 
> 'data_attrs': [{'created': '2019-02-19T17:05:16.252442+00:00', 'id': 3, 'label': 'gps', 'static_value': '', 'template_id': '1', 'type': 'dynamic', 'value_type': 'geo:point'}, {'created': '2019-02-19T14:22:27.157024+00:00', 'id': 1, 'label': 'int', 'metadata': [{'created': '2019-02-19T17:45:13.154195+00:00', 'id': 10, 'label': 'unidade', 'static_value': 'pÃ¡ginas', 'type': 'meta', 'updated': None, 'value_type': 'string'}], 'static_value': '', 'template_id': '1', 'type': 'dynamic', 'value_type': 'integer'}, {'created': '2019-02-19T17:47:10.987274+00:00', 'id': 5, 'label': 'SN', 'metadata': [{'created': '2019-02-19T19:00:57.810547+00:00', 'id': 7, 'label': 'descricao', 'static_value': 'serial number do dispositivo', 'type': 'meta', 'updated': None, 'value_type': 'string'}], 'static_value': 'indefinido', 'template_id': '1', 'type': 'static', 'value_type': 'string'}, {'created': '2019-02-19T17:47:37.722035+00:00', 'id': 6, 'label': 'mensagem', 'static_value': '', 'template_id': '1', 'type': 'actuator', 'value_type': 'string'}], 'id': 1, 'label': 'template'}
> device-manager_1              | [19/02/19 - 20:34:32] |TemplateHandler| DEBUG:  Checking old template attributes
> device-manager_1              | [19/02/19 - 20:34:32] |TemplateHandler| DEBUG:  Removing attribute @
> device-manager_1              | [19/02/19 - 20:34:32] |TemplateHandler| DEBUG:  Commiting new data...
> device-manager_1              | [19/02/19 - 20:34:32] |TemplateHandler| DEBUG: ... data committed.
> device-manager_1              | [19/02/19 - 20:34:32] |TemplateHandler| INFO: Updating template with id: 1
> device-manager_1              | [19/02/19 - 20:34:32] |TemplateHandler| DEBUG:  Querying templates sorted by DeviceTemplate.label
> device-manager_1              | [19/02/19 - 20:34:32] |TemplateHandler| INFO:  Getting template with id 1
