### ISSUE TITLE
503 (Service Temporarily Unavailable) after Dojot Instalation

### ISSUE THREAD

**Issue by RobsonEsteves** [dojot/dojot#783]
Hi,
I installed in the Ubuntu 18.04 the Dojot Platform v0.3.1 following the instructions in this link (using docker-compose): https://dojotdocs.readthedocs.io/en/stable/installation-guide.html#docker-compose.

After that, it seems that everything is fine, except the ALARM MANAGER screen in Dojot's Dashboard, where I'm receiving SERVICE UNAVAILABLE when I select this part in the browser.

Using the Chrome Console I can see the following:
GET http://192.168.1.8:8000/alarmmanager/api/alarms/current/all 503 (Service Temporarily Unavailable)

In terms of Containers I can see that some of them are not running like:

appropriate/curl                          "/opt/kong.config.sh"    9 days ago          Exited (0) 9 days ago                                                       dojot_kong-config_1_f0b38b7ecc6e

 dojot/kong:latest                         "/docker-entrypoint.…"   9 days ago          Exited (0) 9 days ago                                                       dojot_kong-migration_1_bd8184fc187b

 postgres:9.4-alpine                       "docker-entrypoint.s…"   9 days ago          Exited (0) 9 days ago                                                       dojot_postgres-users_1_dfe8b070c270

 I suspect that the problem is the postgres.....

What's the problem? How can I fix it?

Thanks!
Robson

**Comment by giovannicuriel** [comment]
Hi, @RobsonEsteves!
We actually removed the alarm service we had in the past (at that time, the solution was not we were looking for in terms of scalability and performance). As of now, we are investigating other solutions to do that.

And happy new year! :tada:

**Comment by RobsonEsteves** [comment]
Thanks Giovanni. Happy new year too!
BR
Robson
