### ISSUE TITLE
Dojot Upgrade Procedure

### ISSUE THREAD

**Issue by RobsonEsteves** [dojot/dojot#785]
Hi all,
I'd like to know how we can do an upgrade from 0.2.0 to v0.3.1 without impact in the current configurations  (e.g.: flows and nodes), devices, templates etc.

Is there any procedure for that?

Thanks in advance.
,
Robson

**Comment by RobsonEsteves** [comment]
Daniel, thanks! 
I'll try to see / use this procedure.
BR
Robson

**Comment by rascaraficci** [comment]
This issue will be closed due to inactivity.
