### ISSUE TITLE
[GUI] The map is being centralized when the device details / tracking is selected

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#796]
![image](https://user-images.githubusercontent.com/37310063/49541818-04543380-f8bb-11e8-8ef1-75be830de5d6.png)

**Affected Version:** 0.3.0-nightly_20181129

**Comment by cfrancisco** [comment]
No longer happened.

**Comment by betefaber** [comment]
Test OK.

![Screenshot at 2019-05-07 09-15-26](https://user-images.githubusercontent.com/37310063/57298576-ed538080-70a8-11e9-822d-ba1fa113eab3.png)

![Screenshot at 2019-05-07 09-15-48](https://user-images.githubusercontent.com/37310063/57298577-ed538080-70a8-11e9-8e13-0ca3d2364a72.png)
