### ISSUE TITLE
Allow user to easily check liveliness of services through GUI

### ISSUE THREAD

**Issue by mmagr** [dojot/dojot#8]
A user should be able to easily determine the liveliness of all running services of the instance he/she is using.

Such status should be displayed through the "deploy" section of the GUI.

**Comment by hildogjr** [comment]
I "status tab" at the DoJoT GUI will allow users to check the healthy of the service (off, wattling, fully operational). This will also help to troubleshoot installation problems (as I had with the docker version).

**Comment by rascaraficci** [comment]
The current GUI doesn't have the goal of being an administration interface. So, we won't implement this feature.
