### ISSUE TITLE
[GUI] Change user password - no message is displayed when required fields are not filled

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#801]
**Steps to reproduce the problem:**

1. Log in with any user
2. Click "Login details"
3. Click "Change Password"
4. Click "Save"

**Affected Version:** 0.3.0-nightly20181129

**Comment by betefaber** [comment]
Test NOK.

![image](https://user-images.githubusercontent.com/37310063/51276057-cb7ba400-19ba-11e9-935b-4eda32f13392.png)

**Comment by mprevide** [comment]
This must be done.

**Comment by betefaber** [comment]
Test OK.

![image.png](https://images.zenhubusercontent.com/5cd0940469cf6b4ee443403a/f5bbaa90-db5b-49c8-a0c8-962889c6a3a4)
