### ISSUE TITLE
[Auth] System permission

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#802]
- Create a type of Permission "System" and associate with them de inicial permissions

- The user cant remove permissions with type System

- Change api to filter by System type

**Comment by MPrevide** [comment]
- [x] Colocar permissões do tipo sistema a serem fixas e não excluíveis, num arquivo de configuração.
- [  ] Alterar limite de requisições no Kong para endpoints especificos
- [  ] Colocar dependência de niveis (Ex.: para criar device é preciso ver templates)
- [  ] Não permitir excluir o grupo Admin

**Comment by betefaber** [comment]
Test OK.

* Created a type of Permission "System"
![image](https://user-images.githubusercontent.com/37310063/53104625-79c0bf00-350e-11e9-932e-255f2b4981ee.png)

* The user can't remove permissions with type "System"
![image](https://user-images.githubusercontent.com/37310063/53104597-67468580-350e-11e9-8587-9bab5b73e4e8.png)

* filter by "System" type
![image](https://user-images.githubusercontent.com/37310063/53104683-98bf5100-350e-11e9-9841-fa09b39c1eb2.png)
