### ISSUE TITLE
Error 501 on Apache JMeter

### ISSUE THREAD

**Issue by RobsonEsteves** [dojot/dojot#812]
Hi, 
I just installed the Dojot v0.3.1 and it seems that everything is running well. 
When I tried to use the my Apache JMeter i the same way that I already used with Aikido version with success, I can connect successfully the platform but when I try to publish to the device I'm receiving error 501 (not implemented).

From Aikido to the version v0.3.1 is there any change in the tempate and or devices configurations that could justify this behavior?

It seems that the devices are not being recognized, but in the Dojot screen its everything correct?

Do you have some suggestions where I can investigate?

Thanks all!
Robson

**Comment by giovannicuriel** [comment]
This is weird as there are no big changes in API since Aikido. Are you trying to send a command via /device/{deviceid}/actuate? Could you provide which request are you sending?

**Comment by rascaraficci** [comment]
Closed due to inactivity.
