### ISSUE TITLE
Error in first login

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#816]
**Prerequisite**: database empty

**Steps to reproduce the problem:**

1. Execute the commands:

- docker-compose down
- docker-compose up -d

2. Login with admin user

![screenshot_2](https://user-images.githubusercontent.com/37310063/50491906-e2eaf100-09fb-11e9-9389-af0078e29942.png)

**Affected Version**: 0.3.0-nightly20181227

**Comment by rascaraficci** [comment]
It's been fixed.
