### ISSUE TITLE
Edit group: API rate limit exceeded

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#817]
**Steps to reproduce the problem:**

1. Select the group "user"
2. Deselect permissions

![screenshot_7](https://user-images.githubusercontent.com/37310063/50492884-53484100-0a01-11e9-9e91-9cd32d2b88c7.png)

3. Click save

![screenshot_8](https://user-images.githubusercontent.com/37310063/50492903-7246d300-0a01-11e9-8e9b-99c5756f5a06.png)

![screenshot_9](https://user-images.githubusercontent.com/37310063/50492907-7a067780-0a01-11e9-975a-7e9efa761f69.png)

After the error, the groups are not displayed

![screenshot_6](https://user-images.githubusercontent.com/37310063/50492609-c0f36d80-09ff-11e9-9ca9-4689c2655653.png)

Affected Version: 0.3.0-nightly20181227

**Comment by betefaber** [comment]
The problem is resolved if the configuration below is changed in the kong.config.sh file.

Ex:
> config.minute = 200
> config.hour = 400

**Comment by betefaber** [comment]
Test OK.

![Screenshot_73](https://user-images.githubusercontent.com/37310063/55581291-d957e000-56f2-11e9-92be-c527e68f3e49.png)

**Comment by danielnunesdeoliveira** [comment]
Hello @betefaber 

> The problem is resolved if the configuration below is changed in the kong.config.sh file.
> 
> Ex:
> 
> > config.minute = 200
> > config.hour = 400
> 
> The service needs to be restarted:
> 
> > $ docker-compose restart kong-config

Sorry, but what mean **200** on config.**minute** and **400** on config.**hour** ?
