### ISSUE TITLE
Group details: API rate limit exceeded

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#818]
**Steps to reproduce the problem:**

1. Create group "a" with "Modify Template" permission
2. Select group to view group details

![screenshot_11](https://user-images.githubusercontent.com/37310063/50493406-71fc0700-0a04-11e9-8f09-4a035e8eb11e.png)

**Affected Version:** 0.3.0-nightly20181227

**Comment by betefaber** [comment]
The problem is resolved if the configuration below is changed in the kong.config.sh file.

Ex:
> config.minute = 200
> config.hour = 400

The service needs to be restarted:

> $ docker-compose restart kong-config

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/55832588-4224cb00-5aec-11e9-8fe1-ec8fc1c84e85.png)

**Comment by danielnunesdeoliveira** [comment]
> 
> 
> The problem is resolved if the configuration below is changed in the kong.config.sh file.
> 
> Ex:
> 
> > config.minute = 200
> > config.hour = 400
> 
> The service needs to be restarted:
> 
> > $ docker-compose restart kong-config

Please, what mean "config.hour = 400" ? and "config.minute = 200" ?

I am asking, because I am getting problem of limit acess API TOKEN. For now, I have 02 different applications. The one a asking API TOKEN in 5 to 5 minutes other API TOKEN request in 1 to 1 minutes.

Regards,

**Comment by giovannicuriel** [comment]
Hi! 
If I remember correctly, these values mean "200 requests per minute" and "400 requests per hour". In other words, these two values would allow small bursts of requests (a bunch of requests in a minute), but in general it would be expected a quite low number of requests (in an hour, it could be at most 400 of them).

**Comment by giovannicuriel** [comment]
Maaaaybe - and this is a rough guess - these values are being shared for all requests, not only for client authentication. I'd increase both values and check whether this problem goes away.

But I think @rascaraficci is able give a more appropriate advice here 😄

**Comment by danielnunesdeoliveira** [comment]
@giovannicuriel 
Regards my friends, It is working very well now!
