### ISSUE TITLE
[GUI] Interface does not display the list of registered profiles in the User crud

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#819]
The profiles are fixed in the GUI: **Administrator** and **User**.

![screenshot_12](https://user-images.githubusercontent.com/37310063/50517495-b2589500-0a97-11e9-8edd-f6a231a34dbc.png)

**Note**: Profile "User" has been removed.

![screenshot_13](https://user-images.githubusercontent.com/37310063/50517539-efbd2280-0a97-11e9-9275-4ca530c603c6.png)

**Comment by MPrevide** [comment]
In this:
 - Block delete of admin user

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/52733290-83e03c00-2fa9-11e9-82a7-c9143dde09a8.png)
