### ISSUE TITLE
[Auth] It's possible  modify/create groups and permissions without permission for that

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#820]

**Comment by MPrevide** [comment]
Even without permission for modify the Groups I can do that.

**Comment by MPrevide** [comment]
https://github.com/dojot/auth/blob/master/auth/initialConf.py
In lines 119 e 120,  I think It should   /auth/ at begin 
i dont know if this the cause of the error, but....

**Comment by MPrevide** [comment]
The lines 119 e 120  look right, because of the way Kong is configured

**Comment by MPrevide** [comment]
The same: https://github.com/dojot/dojot/issues/844
