### ISSUE TITLE
[GUI] Flowbroker: Label overlaps flow's name

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#823]
When the user opens a flow created previously the window's label overlaps the flow's name as the following image illustrates:

![image](https://user-images.githubusercontent.com/21104864/50636098-efab9f80-0f3b-11e9-889f-1e3741bcaa60.png)

Note: once selected the field it fixes itself.

version: 0.3.0-nightly20181227

**Comment by mprevide** [comment]
This does not happen anymore.
I'll pass the test.

**Comment by betefaber** [comment]
It happens after some refreshs (F5).

![Screenshot_72](https://user-images.githubusercontent.com/37310063/55578887-57b18380-56ed-11e9-84f6-595341573122.png)

Tested on Version: 58.2-20190321

**Comment by cfrancisco** [comment]
Solved in dojot/dojot#734

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/56768456-cdf15500-6784-11e9-8403-6fab60ca851c.png)
