### ISSUE TITLE
[Auth] Do not permit to delete/edit Admin user, Admin group and permissions type system

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#825]

**Comment by MPrevide** [comment]
And add export and import in list of inicial  system permission create.

**Comment by MPrevide** [comment]
- Check the case, for example "/ devices / (*)" and not the permission for "/ devices / history / (*)"

**Comment by MPrevide** [comment]
Remove: historyws,  alarms and mashup in the inicial list

**Comment by MPrevide** [comment]
Break devices into two permissions: / devices and / devices / history

The email and admin user name can be edited.

**Comment by MPrevide** [comment]
Add to system permissions 
 
"/graphql/permissions/(.*)", and  checkconflicts

**Comment by betefaber** [comment]
Test OK.

- Can't possible remove and edit admin group
![screenshot_104](https://user-images.githubusercontent.com/37310063/53102286-20569100-350a-11e9-8097-fd2f1ab818e0.png)

- Can't possible remove admin user
![screenshot_106](https://user-images.githubusercontent.com/37310063/53102303-264c7200-350a-11e9-9671-a3d7d8d2f78a.png)

- Admin user: email and name can be change
![screenshot_105](https://user-images.githubusercontent.com/37310063/53102318-2c425300-350a-11e9-9335-21970955a333.png)

- Can't delete a system permission
![screenshot_107](https://user-images.githubusercontent.com/37310063/53102739-11bca980-350b-11e9-9b8f-df69dac9f131.png)

![screenshot_108](https://user-images.githubusercontent.com/37310063/53102749-15503080-350b-11e9-8743-c1fcbd63631c.png)
