### ISSUE TITLE
Container do Flowbroker Restartando

### ISSUE THREAD

**Issue by RobsonEsteves** [dojot/dojot#826]
Prezados,
estou com o container do Flowbroker restartando continuamente e com isso não consigo mais criar fluxos e interações.  A versão do Dojot é a AIKIDO, rodando em Ubuntu 16.04.

Abaixo, coloco parte do comando docker-compose logs --tail 200 flowbroker. Os logs de erro me parecem que se repetem. 

Alguma dica para tentar solucionar esse problema?

Muito obrigado!
Robson

flowbroker_1            | SyntaxError: Unexpected token <
flowbroker_1            |     at createScript (vm.js:80:10)
flowbroker_1            |     at Object.runInThisContext (vm.js:139:10)
flowbroker_1            |     at Module._compile (module.js:616:28)
flowbroker_1            |     at Object.Module._extensions..js (module.js:663:10)
flowbroker_1            |     at Module.load (module.js:565:32)
flowbroker_1            |     at tryModuleLoad (module.js:505:12)
flowbroker_1            |     at Function.Module._load (module.js:497:3)
flowbroker_1            |     at Module.require (module.js:596:17)
flowbroker_1            |     at require (internal/module.js:11:18)
flowbroker_1            |     at Object.<anonymous> (/opt/flowbroker/orchestrator/nodeManager.js:20:19)
flowbroker_1            |     at Module._compile (module.js:652:30)
flowbroker_1            |     at Object.Module._extensions..js (module.js:663:10)
flowbroker_1            |     at Module.load (module.js:565:32)
flowbroker_1            |     at tryModuleLoad (module.js:505:12)
flowbroker_1            |     at Function.Module._load (module.js:497:3)
flowbroker_1            |     at Module.require (module.js:596:17)
flowbroker_1            | /opt/flowbroker/orchestrator/nodes/get-context/get-context.js:7
flowbroker_1            | <!DOCTYPE html>
flowbroker_1            | ^
flowbroker_1            |
flowbroker_1            | SyntaxError: Unexpected token <
flowbroker_1            |     at createScript (vm.js:80:10)
flowbroker_1            |     at Object.runInThisContext (vm.js:139:10)
flowbroker_1            |     at Module._compile (module.js:616:28)
flowbroker_1            |     at Object.Module._extensions..js (module.js:663:10)
flowbroker_1            |     at Module.load (module.js:565:32)
flowbroker_1            |     at tryModuleLoad (module.js:505:12)
flowbroker_1            |     at Function.Module._load (module.js:497:3)
flowbroker_1            |     at Module.require (module.js:596:17)
flowbroker_1            |     at require (internal/module.js:11:18)
flowbroker_1            |     at Object.<anonymous> (/opt/flowbroker/orchestrator/nodeManager.js:20:19)
flowbroker_1            |     at Module._compile (module.js:652:30)
flowbroker_1            |     at Object.Module._extensions..js (module.js:663:10)
flowbroker_1            |     at Module.load (module.js:565:32)
flowbroker_1            |     at tryModuleLoad (module.js:505:12)
flowbroker_1            |     at Function.Module._load (module.js:497:3)
flowbroker_1            |     at Module.require (module.js:596:17)
flowbroker_1            | /opt/flowbroker/orchestrator/nodes/get-context/get-context.js:7
flowbroker_1            | <!DOCTYPE html>
flowbroker_1            | ^
flowbroker_1            |
flowbroker_1            | SyntaxError: Unexpected token <
flowbroker_1            |     at createScript (vm.js:80:10)
flowbroker_1            |     at Object.runInThisContext (vm.js:139:10)
flowbroker_1            |     at Module._compile (module.js:616:28)
flowbroker_1            |     at Object.Module._extensions..js (module.js:663:10)
flowbroker_1            |     at Module.load (module.js:565:32)
flowbroker_1            |     at tryModuleLoad (module.js:505:12)
flowbroker_1            |     at Function.Module._load (module.js:497:3)
flowbroker_1            |     at Module.require (module.js:596:17)
flowbroker_1            |     at require (internal/module.js:11:18)
flowbroker_1            |     at Object.<anonymous> (/opt/flowbroker/orchestrator/nodeManager.js:20:19)
flowbroker_1            |     at Module._compile (module.js:652:30)
flowbroker_1            |     at Object.Module._extensions..js (module.js:663:10)
flowbroker_1            |     at Module.load (module.js:565:32)
flowbroker_1            |     at tryModuleLoad (module.js:505:12)
flowbroker_1            |     at Function.Module._load (module.js:497:3)
flowbroker_1            |     at Module.require (module.js:596:17)
flowbroker_1            | /opt/flowbroker/orchestrator/nodes/get-context/get-context.js:7
flowbroker_1            | <!DOCTYPE html>

**Comment by raulnegreiros** [comment]
Olá @RobsonEsteves, você poderia mostrar a parte do docker-compose referente ao flowbroker?

**Comment by rascaraficci** [comment]
Essa issue será fechada por inatividade a mais de dois meses.
