### ISSUE TITLE
Tenant is not removed when the last user of the tenant is deleted

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#831]
- adding the first user of the tenant; the tenant is created

> auth_1                        | 2019-01-04 13:27:08,728 - INFO - User bete created by admin
> auth_1                        | Consumer already exists
> auth_1                        | 2019-01-04 13:27:08,818 - INFO - user bete added to group admin by admin
> auth_1                        | 2019-01-04 13:27:12,557 - INFO - Will emit tenant lifecycle event teste - CREATE
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:27:12 +0000] "POST /user HTTP/1.1" 200 378 "-" "PostmanRuntime/7.1.1"
> auth_1                        | Consumer already exists
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:27:31 +0000] "POST /password/resetlink?link=052ca5f81a66676ee5442d8bc3bf46d1 HTTP/1.1" 200 32 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
> auth_1                        | 2019-01-04 13:27:40,123 - INFO - user bete loged in
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:27:40 +0000] "POST / HTTP/1.1" 200 352 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:27:53 +0000] "GET /user HTTP/1.1" 200 399 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:27:53 +0000] "GET /user HTTP/1.1" 200 399 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:27:54 +0000] "GET /pap/permission?type=system HTTP/1.1" 200 3775 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:27:54 +0000] "GET /pap/group HTTP/1.1" 200 318 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

- another user of the same tenant

> auth_1                        | 2019-01-04 13:36:57,466 - INFO - User faber created by admin
> auth_1                        | 2019-01-04 13:36:57,548 - INFO - user faber added to group admin by admin
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:37:01 +0000] "POST /user HTTP/1.1" 200 376 "-" "PostmanRuntime/7.1.1"
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:37:36 +0000] "GET /user HTTP/1.1" 200 587 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:37:36 +0000] "GET /user HTTP/1.1" 200 587 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
> auth_1                        | Consumer already exists
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:38:55 +0000] "POST /password/resetlink?link=c0fc907ef9c74335108a9d2eaa5e238b HTTP/1.1" 200 32 "http://10.4.1.41:8000/" "Mozilla/5.0 (Linux; Android 6.0; MotoG3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36"
> auth_1                        | 2019-01-04 13:39:19,582 - INFO - user faber loged in
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:39:19 +0000] "POST / HTTP/1.1" 200 354 "http://10.4.1.41:8000/" "Mozilla/5.0 (Linux; Android 6.0; MotoG3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36"
> 

- removing a user

auth_1                        | 2019-01-04 13:39:58,315 - INFO - user faber deleted by admin
auth_1                        | 2019-01-04 13:39:58,315 - INFO - {'id': '4', 'name': 'Bete', 'username': 'faber', 'service': 'teste', 'email': 'faber.bete@gmail.com', 'profile': 'admin', 'created_date': '2019-01-04 13:36:57.535693', 'created_by': '1'}
auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:39:58 +0000] "DELETE /user/4 HTTP/1.1" 200 42 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:39:58 +0000] "GET /user HTTP/1.1" 200 399 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

- removing the last user from the tenant

> auth_1                        | 2019-01-04 13:41:00,856 - INFO - user bete deleted by admin
> auth_1                        | 2019-01-04 13:41:00,856 - INFO - {'id': '3', 'name': 'Elisabete', 'username': 'bete', 'service': 'teste', 'email': 'efaber@cpqd.com.br', 'profile': 'admin', 'created_date': '2019-01-04 13:27:08.793973', 'created_by': '1'}
> auth_1                        | 2019-01-04 13:41:01,170 - INFO - will emit tenant lifecycle event teste - DELETE
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:41:01 +0000] "DELETE /user/3 HTTP/1.1" 200 42 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
> auth_1                        | 172.28.0.22 - - [04/Jan/2019:13:41:01 +0000] "GET /user HTTP/1.1" 200 209 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
> 
> persister_1                   | [04/01/19 - 13:41:01] |messenger| INFO: Emitting new event message for subject dojot.tenancy@internal
> persister_1                   | [04/01/19 - 13:41:01] |messenger| INFO: Received message in tenanct subject.
> persister_1                   | [04/01/19 - 13:41:01] |messenger| DEBUG: Tenant is: internal
> persister_1                   | [04/01/19 - 13:41:01] |messenger| DEBUG: Message is: b'{"type": "DELETE", "tenant": "teste"}'
> persister_1                   | [04/01/19 - 13:41:01] |messenger| INFO: This tenant was already registered. Bailing out.

Although the message indicating that the tenant would be removed, this does not happen. If a new user of this tenant is created, he will have access to the tenant's data.

**Affected Version**: 0.3.0-nightly_20181227

**Comment by giovannicuriel** [comment]
After the last user is removed from a particular tenant, there might be resources (devices, templates or flows) still associated to it. Thus, it should not be removed.

Tenant CRUD operations should be performed by a user with administrative access in a dojot deployment and it might not be related to user CRUD operations.

Shall we close this issue?
