### ISSUE TITLE
[GUI] Groups: add vertical scroll bar

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#842]
![screenshot_51](https://user-images.githubusercontent.com/37310063/50915248-85a16780-141f-11e9-87d6-101026e973e1.png)

![screenshot_52](https://user-images.githubusercontent.com/37310063/50915048-1b88c280-141f-11e9-8717-e672a835f17e.png)

**Comment by mprevide** [comment]
The auth says that it can handle alphanumeric, but actually auth can not.
When I create groupname "1212121212", the auth response with admin group permissions, because the group admin has id 1.

**Comment by betefaber** [comment]
Test OK.

![grupos](https://user-images.githubusercontent.com/37310063/53016021-3d686280-342b-11e9-8814-d692cd287214.png)
![screenshot_83](https://user-images.githubusercontent.com/37310063/53016085-786a9600-342b-11e9-86e0-b1068e142122.png)
