### ISSUE TITLE
[GUI] Groups: cards are hidden

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#843]
When the window is resized, the cards are hidden.

![screenshot_51](https://user-images.githubusercontent.com/37310063/50915575-3dcf1000-1420-11e9-8ad6-c0ff04a73a9c.png)

![screenshot_54](https://user-images.githubusercontent.com/37310063/50915576-3e67a680-1420-11e9-832e-5fda4da32e0f.png)

**Comment by mprevide** [comment]
This happens in all pages

**Comment by betefaber** [comment]
The same behavior applies to all pages.
