### ISSUE TITLE
[GUI] Templates: remove configuration parameters that are not being used

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#849]
![screenshot_5](https://user-images.githubusercontent.com/37310063/50978962-a380d200-14dc-11e9-989f-ec538f0c5afd.png)

**Comment by mprevide** [comment]
This must be done

**Comment by betefaber** [comment]
- In the GUI the option to create a configuration attribute has been removed.

![Screenshot_179](https://user-images.githubusercontent.com/37310063/59705064-f8372000-91d3-11e9-84ff-54952433f05b.png)

- **But by API you can create it.**

![Screenshot_184](https://user-images.githubusercontent.com/37310063/59705077-02f1b500-91d4-11e9-9d25-edd078ba4339.png)

![Screenshot_183](https://user-images.githubusercontent.com/37310063/59705079-02f1b500-91d4-11e9-8aff-34d3d3ef6a0f.png)

- However, if the configuration attribute is created by the API, only the protocol option is available.

![Screenshot_178](https://user-images.githubusercontent.com/37310063/59705191-451af680-91d4-11e9-9451-55556bbb7b32.png)

Tested on Version: **62.3-20190603**

**Comment by betefaber** [comment]
This issue has been closed because in the GUI the option to create a configuration attribute has been removed.
