### ISSUE TITLE
GUI - FW Update - New CRUD for image repository

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#853]

**Comment by betefaber** [comment]
Done.

![Screenshot_212](https://user-images.githubusercontent.com/37310063/56502285-2ce66e00-64e8-11e9-8999-7df8a818ea16.png)

![Screenshot_214](https://user-images.githubusercontent.com/37310063/56502293-3079f500-64e8-11e9-84fa-08e836b836a8.png)

![Screenshot_215](https://user-images.githubusercontent.com/37310063/56502296-3374e580-64e8-11e9-8c98-dd6318cdfea1.png)
