### ISSUE TITLE
[AUTH] Permissions - Define end-points for GUI use

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#854]

**Comment by MPrevide** [comment]
Remove: historyws, alarms and mashup in the inicial list

**Comment by MPrevide** [comment]
Break devices into two permissions: / devices and / devices / history

**Comment by MPrevide** [comment]
Add to system permissions 
 
"/graphql/permissions/(.*)", and  checkconflicts

**Comment by betefaber** [comment]
Test OK.

![screenshot_109](https://user-images.githubusercontent.com/37310063/53103814-05d1e700-350d-11e9-952c-1ea67d35361d.png)

![screenshot_110](https://user-images.githubusercontent.com/37310063/53103826-09fe0480-350d-11e9-81eb-58540feca8f2.png)
