### ISSUE TITLE
[GUI] Template: Change metadata - does not validate fields populated with invalid values

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#859]
![screenshot_14](https://user-images.githubusercontent.com/37310063/50990900-7cd19400-14fa-11e9-9c7b-0102b8ce12c1.png)

**Note:** validation is done by adding the metadata

**Affected Version:** 0.3.0-nightly_20181227

**Comment by betefaber** [comment]
Test NOK.

The fields validation is done, but the metadata is saved with **invalid values**.

**Steps:**

1. Select an attribute with metadata
2. Edit the metadata with invalid values
3. Click SAVE

![screenshot_98](https://user-images.githubusercontent.com/37310063/53043818-2005b980-3468-11e9-91d5-d74f2aa33d11.png)

4. Click DISCARD

![screenshot_99](https://user-images.githubusercontent.com/37310063/53043941-63602800-3468-11e9-9729-0b30e4b18719.png)

5. Click SAVE
6. Click SAVE 

![screenshot_100](https://user-images.githubusercontent.com/37310063/53043840-2e53d580-3468-11e9-96d8-724b1fba7908.png)

![screenshot_101](https://user-images.githubusercontent.com/37310063/53043847-31e75c80-3468-11e9-9ecc-6ca21d18a95b.png)

**Comment by betefaber** [comment]
Test NOK.

The validation is done in the GUI:

1. attribute name

![Screenshot_105](https://user-images.githubusercontent.com/37310063/55650578-7e8abb00-57bc-11e9-8d26-e34f8837c76a.png)

2. attribute type

![Screenshot_108](https://user-images.githubusercontent.com/37310063/55650591-864a5f80-57bc-11e9-9e16-2fe764f96836.png)

3. value

![Screenshot_103](https://user-images.githubusercontent.com/37310063/55650609-96623f00-57bc-11e9-9b72-94860bc84358.png)


But the metadata is saved with invalid values.

![Screenshot_109](https://user-images.githubusercontent.com/37310063/55650635-b265e080-57bc-11e9-9fd6-0aa917c2215d.png)

![Screenshot_104](https://user-images.githubusercontent.com/37310063/55650640-b8f45800-57bc-11e9-9db0-16bf19a3a42c.png)

Only the validation of attribute name of metadata is done, in the update of the template.

![Screenshot_111](https://user-images.githubusercontent.com/37310063/55650918-67989880-57bd-11e9-81c7-e06ca7475c3b.png)

**Comment by betefaber** [comment]
related #1029

**Comment by mprevide** [comment]
Utilizar a tag na gui  mprevide/gui:updatefirmware

**Comment by betefaber** [comment]
Test OK.

Validations of the attribute and metadata fields are done.

----
**Attribute**
----

- attribute name:

![attributename](https://user-images.githubusercontent.com/37310063/59217257-e9c58480-8b93-11e9-9806-e606f0663d0a.png)

- attribute type;

![attributetype](https://user-images.githubusercontent.com/37310063/59217268-f053fc00-8b93-11e9-8107-3533c779ff3a.png)

- attribute value type;

![attributevaluetype](https://user-images.githubusercontent.com/37310063/59217277-f518b000-8b93-11e9-9f4c-b62349d6957d.png)

- attribute value:

![attributevalue](https://user-images.githubusercontent.com/37310063/59217284-fb0e9100-8b93-11e9-856f-2221b64d77a7.png)

----
 **Metadata**
----
- Meta attribute name:

![meta_atttributename](https://user-images.githubusercontent.com/37310063/59216722-9d2d7980-8b92-11e9-8beb-e4464c985e13.png)

- Meta attribute type:

![MetaAttributeType](https://user-images.githubusercontent.com/37310063/59216737-a74f7800-8b92-11e9-8247-9a5ab922b5e6.png)

- Meta value type:

![MetaType](https://user-images.githubusercontent.com/37310063/59216802-cf3edb80-8b92-11e9-8d2d-88437ad30686.png)

- Meta value:

![MetaValue](https://user-images.githubusercontent.com/37310063/59216813-d960da00-8b92-11e9-8250-ef5131d8232b.png)

Tested on Version: **62.3-20190603**
