### ISSUE TITLE
create.user.sh e criando um novo device

### ISSUE THREAD

**Issue by kiul55** [dojot/dojot#86]
Olá,

Estou tentando usar a plataforma, porém estou encontrando alguns problemas.
Não consegui rodar o script "create.user.sh", mas consegui acessar a plataforma mesmo assim.

Acessando a plataforma, não consigo criar novos devices. Realizo toda a configuração (nome, atributos, etc) e na hora de clicar em "Save" nada acontece. Alguém pode me ajudar ?

Obrigado!

================================================================
Hello,

I'm trying to use the platform, but I'm encountering some problems.
I was unable to run the "create.user.sh" script, but I was able to access the platform.

Accessing the platform, I can not create new devices. I make all the configuration (name, attributes, etc) and at the time of clicking "Save" nothing happens. Can someone help me ?

Thank you!

**Comment by mmagr** [comment]
Olá, @kiul55 

Pelo que você descreveu, estou assumindo que está usando o branch master do repositório docker/docker-compose como base para o seu ambiente.

Este branch aponta para as versões ainda em desenvolvimento dos componentes, e pode apresentar instabilidades, conforme os serviços individuais são atualizados.

Dito isso você poderia usar a última versão estável da plataforma? Caso o problema persista podemos verificar o problema a partir deste ponto.

Para montar um ambiente usando a última versão estável, por favor siga os passos abaixo.

```shell
git clone https://github.com/dojot/docker-compose.git
# Cloning into 'docker-compose'...
# remote: Counting objects: 379, done.
# remote: Compressing objects: 100% (16/16), done.
# remote: Total 379 (delta 10), reused 15 (delta 6), pack-reused 356
# Receiving objects: 100% (379/379), 146.75 KiB | 0 bytes/s, done.
# Resolving deltas: 100% (201/201), done.
# Checking connectivity... done.
cd docker-compose/

# o próximo comando seleciona a tag da última release estável.
git checkout 0.1.0-dojot
# Note: checking out '0.1.0-dojot'.
# 
# You are in 'detached HEAD' state. You can look around, make experimental
# changes and commit them, and you can discard any commits you make in this
# state without impacting any branches by performing another checkout.
# 
# If you want to create a new branch to retain commits you create, you may
# do so (now or later) by using -b with the checkout command again. Example:
# 
#   git checkout -b <new-branch-name>
# 
# HEAD is now at a9061e4... Fast-forwards components to 0.1.0-dojot-RC2

sudo docker-compose up -d 
# Creating network "dockercompose_default" with the default driver
# Creating dockercompose_gui_1
# Creating dockercompose_mongodb_1
# Creating dockercompose_mashup_1
# Creating dockercompose_postgres_1
# Creating dockercompose_perseo-core_1
# Creating dockercompose_mqtt_1
# Creating dockercompose_coap_1
# Creating dockercompose_device-manager_1
# Creating dockercompose_sth_1
# Creating dockercompose_perseo-fe_1
# Creating dockercompose_orion_1
# Creating dockercompose_apigw_1
# Creating dockercompose_iotagent_1
# Creating dockercompose_auth_1

# após algum tempo .... (aguarde alguns minutos para ter certeza que os serviços estão 
# rodando.
sudo ./kong.config.sh 
sudo ./create.user.sh 
# {
#     "message": "user created",
#     "user": {
#         "id": "f1b66d20-75a8-471e-b499-c84dec3e66a4",
#         "service": "admin",
#         "username": "admin"
#     }
# }
```

---

Hello, @kiul55 

Judging by what's been described by you, I'm tempted to believe you're using the tip of dojot/docker-compose master branch as a base for your environment.

While there's nothing wrong with that, this branch does point to the latest development version of each service that comprises dojot, and thus may present instability (components that are not properly integrated with one another) as individual services are developed/upgraded.

Having said that, could you please try it again using our latest stable version? Should the problem persist, we'd be happy to help you from there.

To setup an environment on this latest version, be sure to use the following.

```shell
git clone https://github.com/dojot/docker-compose.git
# Cloning into 'docker-compose'...
# remote: Counting objects: 379, done.
# remote: Compressing objects: 100% (16/16), done.
# remote: Total 379 (delta 10), reused 15 (delta 6), pack-reused 356
# Receiving objects: 100% (379/379), 146.75 KiB | 0 bytes/s, done.
# Resolving deltas: 100% (201/201), done.
# Checking connectivity... done.
cd docker-compose/

# this switches the local copy to the stable release I mentioned.
git checkout 0.1.0-dojot
# Note: checking out '0.1.0-dojot'.
# 
# You are in 'detached HEAD' state. You can look around, make experimental
# changes and commit them, and you can discard any commits you make in this
# state without impacting any branches by performing another checkout.
# 
# If you want to create a new branch to retain commits you create, you may
# do so (now or later) by using -b with the checkout command again. Example:
# 
#   git checkout -b <new-branch-name>
# 
# HEAD is now at a9061e4... Fast-forwards components to 0.1.0-dojot-RC2

sudo docker-compose up -d 
# Creating network "dockercompose_default" with the default driver
# Creating dockercompose_gui_1
# Creating dockercompose_mongodb_1
# Creating dockercompose_mashup_1
# Creating dockercompose_postgres_1
# Creating dockercompose_perseo-core_1
# Creating dockercompose_mqtt_1
# Creating dockercompose_coap_1
# Creating dockercompose_device-manager_1
# Creating dockercompose_sth_1
# Creating dockercompose_perseo-fe_1
# Creating dockercompose_orion_1
# Creating dockercompose_apigw_1
# Creating dockercompose_iotagent_1
# Creating dockercompose_auth_1

# now, as you might have already noticed, give the services some time to boot
# otherwise you'll get those nasty "connection refused" errors
# to be on the safe side, something around 5min should suffice
sudo ./kong.config.sh 
sudo ./create.user.sh 
# {
#     "message": "user created",
#     "user": {
#         "id": "f1b66d20-75a8-471e-b499-c84dec3e66a4",
#         "service": "admin",
#         "username": "admin"
#     }
# }
```

**Comment by kiul55** [comment]
Olá, @mmagr!

Segui suas instruções, e consegui rodar "create.user.sh". Entretanto ainda não consigo adicionar nenhum device, clico no botão "Save" e nada acontece. Tem ideia do que fazer ?

=================================================================================

Hello, @mmagr!

I followed your instructions, and I was able to run "create.user.sh". However I still can't add any device, I click on the "Save" button and nothing happens. Any idea what to do?

**Comment by mmagr** [comment]
Montei um ambiente replicando o seu ambiente, notei que a criação do primeiro dispositivo demorou um tanto (algo em torno de 12s) para funcionar. Após este primeiro device, os demais são criados normalmente (algo em torno de 100ms). Note que os tempos podem variar de máquina para máquina.

Caso após algum tempo o device ainda não tenha sido criado, você poderia, por favor coletar o log do serviço usado?

Para coletar o log necessário, do diretório raiz do docker-compose:

```shell
# voce pode precisar de sudo
docker-compose exec device-manager cat /var/log/uwsgi/app/app.log
```
---
I have setup an environment mirroring your scenario, and have noticed that the first device creation usually takes a bit longer than usual (something around 12s on my environment). With that first device created, the following are properly created with their usual processing latency (around 100ms). Do notice that running/latencies might vary from machine to machine.

Should the device fail to be created after some time, could you please get the log from the device management service?

To retrieve the logs please run, from docker-compose's root directory:

```shell
# you may need sudo for this
docker-compose exec device-manager cat /var/log/uwsgi/app/app.log
```

**Comment by kiul55** [comment]
Aguardei em torno de 1 minuto e nada aconteceu.

Coletei o log e a seguinte mensagem apareceu:

> cat: /var/log/uwsgi/app/app.log: No such file or directory

Estou usando uma máquina virtual com o ubuntu, isso faz com que o desempenho da máquina reduza bastante, mas deveria funcionar normalmente, correto ? (adicionar dispositivos e testá-los).

Obrigado pela agilidade das respostas.

**Comment by mmagr** [comment]
Oi @kiul55,

Estranho não haver o arquivo.
Você pode, por favor colar aqui o resultado desse comando?
```shell
docker-compose images
```

**Comment by kiul55** [comment]
@mmagr,

>       Container                Repository          Tag       Image Id      Size 
--------------------------------------------------------------------------------
dockercompose_apigw_1    dojot/kong               latest   f87d09b2c069   375 MB
dockercompose_auth_1     dojot/auth               latest   764fff5cf3b2   698 MB
dockercompose_coap_1     telefonicaiot            latest   13ea7755b509   627 MB
                         /lightweightm2m-                                       
                         iotagent                                               
dockercompose_device-    dojot/device-manager     latest   04ba691b1e28   680 MB
manager_1                                                                       
dockercompose_gui_1      dojot/gui                latest   b7f273d67ae0   114 MB
dockercompose_iotagent   dojot/iotagent-json      latest   369fb264e811   671 MB
_1                                                                              
dockercompose_mashup_1   dojot/mashup             latest   cb88fb2b8efd   800 MB
dockercompose_mongodb_   mongo                    3.2      16dc6ae8085e   287 MB
1                                                                               
dockercompose_mqtt_1     ansi/mosquitto           latest   671980dfb6e5   434 MB
dockercompose_orion_1    dojot/fiware-orion       latest   31d5bce6dcd8   940 MB
dockercompose_perseo-    telefonicaiot/perseo-    latest   c152e0adedd4   364 MB
core_1                   core                                                   
dockercompose_perseo-    dojot/perseo-fe          latest   76815759607b   744 MB
fe_1                                                                            
dockercompose_postgres   postgres                 9.4      13fff887b6fb   251 MB
_1                                                                              
dockercompose_sth_1      telefonicaiot/fiware-    latest   e47cc64ffd03   280 MB
                         sth-comet  

>

**Comment by mmagr** [comment]
Me parece que você ainda está com a versão mais nova (instável) dos serviços.

Você pode, por favor executar os comandos abaixo?

```shell
docker-compose down
git checkout 0.1.0-dojot
git log -1 --oneline
# o resultado deve ser: a9061e4 Fast-forwards components to 0.1.0-dojot-RC2
docker-compose pull
docker-compose up -d
# ... aguarde algum tempo ...
./kong.config.sh
./create.user.sh
docker-compose images
```

O resultado do último comando deve ser:
```
          Container                           Repository                       Tag           Image Id      Size  
----------------------------------------------------------------------------------------------------------------
dockercompose_apigw_1            kong                                    0.10              058e95893dd6   308 MB 
dockercompose_auth_1             dojot/auth                              0.1.0-dojot-RC2   1d82a27dd15a   476 MB 
dockercompose_coap_1             telefonicaiot/lightweightm2m-iotagent   latest            13ea7755b509   627 MB 
dockercompose_device-manager_1   dojot/device-manager                    0.1.0-dojot-RC2   b9ec2ddef0fe   476 MB 
dockercompose_gui_1              dojot/gui                               0.1.0-dojot-RC2   09a9bf3dc403   113 MB 
dockercompose_iotagent_1         dojot/iotagent-json                     0.1.0-dojot-RC2   d19964c697ff   671 MB 
dockercompose_mashup_1           dojot/mashup                            0.1.0-dojot-RC2   b949bb90ce85   809 MB 
dockercompose_mongodb_1          mongo                                   3.2               16dc6ae8085e   287 MB 
dockercompose_mqtt_1             ansi/mosquitto                          latest            671980dfb6e5   434 MB 
dockercompose_orion_1            dojot/fiware-orion                      0.1.0-dojot-RC2   7fb4076e8143   937 MB 
dockercompose_perseo-core_1      telefonicaiot/perseo-core               latest            c152e0adedd4   364 MB 
dockercompose_perseo-fe_1        dojot/perseo-fe                         0.1.0-dojot-RC2   7812ed1bc46f   647 MB 
dockercompose_postgres_1         postgres                                9.4               13fff887b6fb   251 MB 
dockercompose_sth_1              telefonicaiot/fiware-sth-comet          latest            e47cc64ffd03   280 MB 
```

A parte importante é a coluna `tags` que aponta para a versão `0.1.0-dojot-RC2`.
Feito isso, a criação deve ocorrer normalmente (com a nota sobre talvez demorar um pouquinho da primeira vez).

**Comment by kiul55** [comment]
@mmagr,

Consegui, o resultado do comando foi igual ao seu e foi possível adicionar um device.
Mais uma vez obrigado!
