### ISSUE TITLE
[GUI][Auth] Update User  -  Doesn't change profile

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#863]
When a use the api http://localhost:8000/auth/user/4, for example, the profile dont change

**Comment by MPrevide** [comment]
Use another endpoint the pap/permissions

**Comment by mprevide** [comment]
Fix get user in auth to return in profile the correct group

**Comment by mprevide** [comment]
postponed because this feature needs so many changes in auth.

**Comment by betefaber** [comment]
For now, the user profile will not change.
