### ISSUE TITLE
[GUI] Device: actuator attribute

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#867]
When creating an actuator attribute, you can assign a value to the parameter.

![screenshot_71](https://user-images.githubusercontent.com/37310063/51248322-e5939300-1976-11e9-8fc1-946bb2f7b821.png)

But in the attribute history, only the value of the effective actuation is stored.

![screenshot_72](https://user-images.githubusercontent.com/37310063/51248334-ed533780-1976-11e9-9211-8f30e3f44ce6.png)

> flowbroker_1                  | <19:54:50 15/01/2019> -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69
>  64 22 3a 22 33 61 36 34 35 64 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
> flowbroker_1                  |   size: 99,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '9b2d7e1d-28f1-4ca3-9b62-7ae72512ca54',
> flowbroker_1                  |   offset: 0,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1547582088593 }
> flowbroker_1                  | <19:54:50 15/01/2019> -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <19:54:50 15/01/2019> -- DEBUG: Queued event {"metadata":{"deviceid":"3a645d","tenant":"admin","timestamp":1547582088593},"attrs"
> :{"bool":true}}
> flowbroker_1                  | <19:54:50 15/01/2019> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"3a645d","tenant":"admin","timestamp":1547582088593}
> ,"attrs":{"bool":true}}
> flowbroker_1                  | <19:54:50 15/01/2019> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: '3a645d', tenant: 'admin', timestamp: 15
> 47582088593 },
> flowbroker_1                  |   attrs: { bool: true } }
> flowbroker_1                  | [redis] storing device info on cache . . .
> flowbroker_1                  | [redis] . . . device info stored successfully
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | [executor] hop (switch) result: [{"payload":{"bool":true,"serialNumber":"undefined"}}]
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] will handle node change
> flowbroker_1                  | debug: Executing change node...
> flowbroker_1                  | debug: ... change node was successfully executed.
> flowbroker_1                  | [executor] hop (change) result: [{"payload":{"bool":true,"serialNumber":"undefined"},"saida":{"mensagem":"ATUE"}}]
> flowbroker_1                  | [executor] will handle node actuate
> flowbroker_1                  | debug: **Executing actuate node...**
> flowbroker_1                  | debug: Sending message...
> flowbroker_1                  | debug: Message is: { meta: { deviceid: '3a645d', service: 'admin' },
> flowbroker_1                  |   metadata: { tenant: 'admin' },
> flowbroker_1                  |   event: 'configure',
> flowbroker_1                  |   data: **{ attrs: { mensagem: 'ATUE' }, id: '3a645d' } }**
> flowbroker_1                  | object
> flowbroker_1                  | will produce [object Object] to dojot.device-manager.device:admin
> flowbroker_1                  | <19:54:50 15/01/2019> -- DEBUG: Trying to publish someting. Current producer topics are { 'dojot.device-manager.device':
> flowbroker_1                  |    { admin: 'd88f83e5-0493-4b68-ade1-6553b536e45e',
> flowbroker_1                  |      teste: '2ad9ae2f-aee3-45a2-9d75-649de301b8c0' },
> flowbroker_1                  |   'device-data':
> flowbroker_1                  |    { admin: '9b2d7e1d-28f1-4ca3-9b62-7ae72512ca54',
> flowbroker_1                  |      teste: '86facf58-d4cd-4f4a-a300-34154b1a71ba' } }
> flowbroker_1                  | debug: ... message was sent.
> flowbroker_1                  | debug: ... **actuate node was successfully executed.**
> flowbroker_1                  | [executor] hop (actuate) result: undefined
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | [executor] hop (switch) result: [null]
> flowbroker_1                  | debug: Checking memory.
> flowbroker_1                  | <19:54:52 15/01/2019> -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22
>  33 61 36 34 35 64 22 2c 22 73 65 72 76 69 63 65 22 3a 22 61 64 6d 69 6e 22 7d 2c 22 6d ... >,
> flowbroker_1                  |   size: 149,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: 'd88f83e5-0493-4b68-ade1-6553b536e45e',
> flowbroker_1                  |   offset: 20,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1547582090496 }
> flowbroker_1                  | <19:54:52 15/01/2019> -- DEBUG: Emitting new event message for subject dojot.device-manager.device@admin

![screenshot_73](https://user-images.githubusercontent.com/37310063/51248341-f17f5500-1976-11e9-8e05-fb75b1ab4798.png)

Is the field required in the GUI?

**Affected Version**: 0.3.0-nightly_20181227

**Comment by mprevide** [comment]
The actuator must have the same behavior as dynamic, it does not need a static value.

Is that correct, @raulnegreiros?

**Comment by mprevide** [comment]
#966

**Comment by betefaber** [comment]
Test OK.

The field for actuator data entry has been removed.

![Screenshot_101](https://user-images.githubusercontent.com/37310063/59382995-6e9bd400-8d35-11e9-9407-30e949b3e6c9.png)

**Note**: This field may be required when the GUI allows action on a device.

Tested on Version: **62.3-20190603**
