### ISSUE TITLE
Não recebo e-mail para configurar senha ao criar usuários

### ISSUE THREAD

**Issue by cbsseip** [dojot/dojot#873]
Na criação de usuários pela interface WEB da dojot, não recebo o e-mail para configurar uma senha no e-mail cadastrado, também ao informar o usuário e clicar no "esqueci a senha" também não recebo nada para configura-la.

**Comment by betefaber** [comment]
As seguintes variáveis de ambiente precisam ser adicionadas à seção **auth** do docker-compose.yml:
```
AUTH_EMAIL_HOST: "<servidor smtp>" ex: "smtp.gmail.com"
AUTH_EMAIL_USER:
AUTH_EMAIL_PASSWD:
AUTH_RESET_PWD_VIEW: "http://<servidor dojot>:8000/#/setPassword/"
```
OBS: a porta smtp deve estar liberada

**Comment by danielnunesdeoliveira** [comment]
Eu segui o procedimento descrito, mas não obtive sucesso. Não recebo a orientação por e-mail para fazer o _login_ no novo usuário. Estou utilizando o docker-compose v0.4.0.

**Usuário cadastrado**:
![image](https://user-images.githubusercontent.com/29581014/65989290-c59df400-e45f-11e9-82cb-cfd7f272beab.png)

**auth**:
![image](https://user-images.githubusercontent.com/29581014/65988960-3264be80-e45f-11e9-9573-a9cca5199458.png)

**Porta smtp liberada**:
![image](https://user-images.githubusercontent.com/29581014/65989122-7657c380-e45f-11e9-9bd9-5892ad974b74.png)

**Página de recuperação**:
![image](https://user-images.githubusercontent.com/29581014/65989338-da7a8780-e45f-11e9-96d6-520e0262cb3b.png)

**Comment by danielnunesdeoliveira** [comment]
Estou com uma dificuldade para a recuperação da senha. Recebo a seguinte orientação:
![image](https://user-images.githubusercontent.com/29581014/65993194-20871980-e467-11e9-9288-58b6db78ce59.png)
Mas quando acesso o link, ele me leva a página: http://7f0f3be642dfee2a7269b6a25eff7384/
Como faço para efetivamente fazer o _login_ no novo usuário cadastrado?

**Comment by betefaber** [comment]
Bom dia, Daniel

Para a recuperação da senha, faltou configurar uma variável de ambiente:

AUTH_RESET_PWD_VIEW: "http://<ip do servidor>:8000/#/setPassword/"

**Comment by danielnunesdeoliveira** [comment]
Bom dia.

Adicionei a configuração faltante, mas ele não responde quando clico sobre o botão _submit_:
![image](https://user-images.githubusercontent.com/29581014/66046996-5080fc00-e4fd-11e9-8824-d1dd67de54ab.png)

**Comment by betefaber** [comment]
O link recebido no email funciona, e a senha é recuperada, se nenhum usuário estiver conectado no mesmo navegador.

**Comment by danielnunesdeoliveira** [comment]
> O link recebido no email funciona, e a senha é recuperada, se nenhum usuário estiver conectado no mesmo navegador.

Por favor, não está aceitando. Eu estou utilizando o navegador Chrome e não estou conectado em nenhum usuário. Eu digito a nova senha e a confirmo, mas parece que ela não é salva, não tenho um retorno do tipo : "Senha cadastrada".

**Comment by betefaber** [comment]
Oi Daniel,

Verificarei por que as mensagens de erro não estão sendo exibidas nessa versão.

De qualquer forma, realizei alguns testes e obtive as seguintes respostas:

- senha está na blacklist

![blacklist](https://user-images.githubusercontent.com/37310063/66211762-0a5da100-e693-11e9-8728-bd422e729ae8.png)

- cadastrando a mesma senha

![mesma_senha](https://user-images.githubusercontent.com/37310063/66211736-ff0a7580-e692-11e9-9080-7f48a0f5a748.png)

- cadastrando uma senha fácil

![password_easy](https://user-images.githubusercontent.com/37310063/66211750-0598ed00-e693-11e9-8860-44b40cbe0a7a.png)

- várias requisições

![varias_requisições](https://user-images.githubusercontent.com/37310063/66211770-0f225500-e693-11e9-9ba9-f7fbd97819e5.png)

- a página expirou

![pagina_expirou](https://user-images.githubusercontent.com/37310063/66211775-13e70900-e693-11e9-8c1d-c8ffc9e8ac37.png)

- se a senha foi cadastrada com sucesso, a página de login é exibida

![senha_correta](https://user-images.githubusercontent.com/37310063/66211793-1a758080-e693-11e9-84a4-7abdc4dfecd9.png)

Espero ter ajudado.
Se o erro que estiver aparecendo for diferente desses, por favor, reporte-o.

Att,
Bete

**Comment by betefaber** [comment]
Test OK.

related issue: #1259

**Comment by mauriciocontrole** [comment]
Olá @mprevide,

Eu sou desenvolvedor junior e estou aprendendo a mexer na plataforma.

Criei um usuário utilizando a interface gráfica web, porém agora preciso da senha.

Não recebi um e-mail de senha nem ao criar nem ao entrar em Forgot Password.

Segui os passos informados nos comentários acima:

![userdojot](https://user-images.githubusercontent.com/54628595/84788849-fd38d600-afc5-11ea-8fa6-a56a0cf04af3.PNG)

Mesmo depois de incluir essas linhas,  não recebo o e-mail.

Teria mais alguma coisa que preciso fazer ?

**Comment by betefaber** [comment]
Olá Mauricio,

Você poderia verificar se as portas do seu servidor de e-mail estão liberadas?

**Comment by danielnunesdeoliveira** [comment]
Olá pessoal @betefaber 

Estou com uma versão da Dojot e voltei a ter o mesmo problema citado pelo @mauriciocontrole. 

Esse é o meu servidor:
![image](https://user-images.githubusercontent.com/29581014/139592452-a5797a64-dcbc-48b1-b0c5-6b775b06b020.png)

Essa é a permissão:
1) No terminal do Linux:
![image](https://user-images.githubusercontent.com/29581014/139592472-8b713d6b-4718-4548-86ce-ed8548a7996a.png)
2) No console do provedor:

![image](https://user-images.githubusercontent.com/29581014/139592515-f9ffe76f-9b93-4d96-9c12-accdc75c9c1a.png)


E assim que foi configurado do auth >> docker-compose.yml:

![image](https://user-images.githubusercontent.com/29581014/139592606-c3da8bf9-12da-43da-b912-8abaa1ec540d.png)

Por favor, não consigo resolver.

Obrigado,
