### ISSUE TITLE
[GUI] Permissions - sidebar tilt

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#889]

**Comment by betefaber** [comment]
Test OK.

![screenshot_84](https://user-images.githubusercontent.com/37310063/53016456-78b76100-342c-11e9-84fc-aa4cae7515b6.png)
![screenshot_85](https://user-images.githubusercontent.com/37310063/53016461-7d7c1500-342c-11e9-9c90-bb6b8c584d12.png)
