### ISSUE TITLE
[GUI] Device: Changing a parameter's metadata

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#891]
In the metadata change screen, clicking the SAVE button does not return to the previous screen. You must click DISCARD.
Even so, the value is changed.

**Steps to reproduce the problem:**

1. Click New Device
2. Set a name
3. Add template with metadata into dynamic attributes
4. Click Dynamic Attributes
5. Expand Meta attributes
6. Change static value of metadata
7. Click SAVE 

![screenshot_130](https://user-images.githubusercontent.com/37310063/52068838-9d729400-2564-11e9-8cbd-9f4467a6487d.png)

Does not return to the previous screen. You must click DISCARD.

8. Click DISCARD to return to the device creation screen
9. Click SAVE to create the device

Although "discarding" the metadata change, the value is saved.

> device-manager_1              | [31/01/19 - 13:57:05] |DeviceHandler| DEBUG:  Generated a new device id 56704d
> device-manager_1              | [31/01/19 - 13:57:05] |DeviceHandler| DEBUG:  Adding new template list for device <Device(label='termometro fahrenheit')>
> device-manager_1              | [31/01/19 - 13:57:05] |DeviceHandler| DEBUG:  Finding template from template list
> device-manager_1              | [31/01/19 - 13:57:05] |DeviceHandler| DEBUG:  Updated metadata 2
> device-manager_1              | [31/01/19 - 13:57:05] |DeviceHandler| DEBUG:  Added overrided form <DeviceOverride (transient 140461674236896)>
> device-manager_1              | [31/01/19 - 13:57:05] |BackendHandler| INFO:  Publishing create event to Kafka
> device-manager_1              | [31/01/19 - 13:57:05] |KafkaNotifier| DEBUG:  topic for dojot.device-manager.device is 857c0b0b-cecd-444b-abf7-a76858e39605
> device-manager_1              | [31/01/19 - 13:57:05] |DeviceHandler| INFO:  Creating a new device with id 56704d.

> persister_1                   | [31/01/19 - 13:57:05] |messenger| INFO: Emitting new event message for subject dojot.device-manager.device@admin
> persister_1                   | [31/01/19 - 13:57:05] |persister| INFO: got device event {'event': 'create', 'data': {'created': '2019-01-31T13:57:05.414480+00:00', 'templates': [1], 'label': 'termometro fahrenheit', 'id': '56704d', 'attrs': {'1': [{'created': '2019-01-14T17:56:02.141803+00:00', 'value_type': 'float', 'label': 'temperatura', 'type': 'dynamic', 'template_id': '1', 'metadata': [{'created': '2019-01-14T17:56:02.144222+00:00', 'value_type': 'string', 'label': 'unidade', 'type': 'meta', 'updated': None, 'id': 2, 'static_value': 'Â°F'}], 'id': 1}]}}, 'meta': {'service': 'admin'}}

**NOTE**: If the metadata value is changed and discarded **without saving**, it is modified.

**Affected Version:** 0.3.0-nightly20181227

**Comment by mprevide** [comment]
This error still occurs when using °.

**Comment by betefaber** [comment]
Test OK.

Saving the change to a metadata on the Manage Attributes screen returns to the previous screen.

Tested on Version: **62.3-20190603**
