### ISSUE TITLE
Device data are not published

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#896]
![screenshot_1](https://user-images.githubusercontent.com/37310063/52417036-1aa48880-2ad2-11e9-884d-b0bafcc44531.png)

> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- |messenger -- DEBUG: Emitting new event new-tenant for subject dojot.tenancy@dojot-management
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- |messenger -- DEBUG: No one is listening to subject dojot.tenancy new-tenant events.
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- |messenger -- DEBUG: Got topic for subject device-data and tenant teste: e6a03258-8e01-4074-adbd-97c590028850
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- |messenger -- DEBUG: Adding a producer topic.
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- |messenger -- DEBUG: Got topic for subject dojot.device-manager.device and tenant teste: 0b3a5dfd-5e86-4f38-be96-ae9c56
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- DEBUG: Scheduling a subscription operation...
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- DEBUG: Adding new topic 0b3a5dfd-5e86-4f38-be96-ae9c56a72e23
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- DEBUG: Subscribed to topic 0b3a5dfd-5e86-4f38-be96-ae9c56a72e23.
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- |messenger -- DEBUG: Got topic for subject iotagent.device and tenant teste: 3d83a451-5c66-44ba-8e2e-60200ef37a8a
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- DEBUG: Scheduling a subscription operation...
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- DEBUG: Adding new topic 3d83a451-5c66-44ba-8e2e-60200ef37a8a
> iotagent-mqtt_1               | <13:51:58 07/02/2019> -- DEBUG: Subscribed to topic 3d83a451-5c66-44ba-8e2e-60200ef37a8a.
> iotagent-mqtt_1               | <13:52:01 07/02/2019> -- DEBUG: Unsubscribing from topics b340a015-8100-4bb2-b129-934e5aea4bf6,e0791291-f674-4eee-b8b0-f149b0a436e5,0b3a5dfd-5e8a8a
> iotagent-mqtt_1               | <13:52:01 07/02/2019> -- DEBUG: Subscribing to topics b340a015-8100-4bb2-b129-934e5aea4bf6,e0791291-f674-4eee-b8b0-f149b0a436e5,0b3a5dfd-5e86-4f
> iotagent-mqtt_1               | <13:52:03 07/02/2019> -- DEBUG: Cheking memory.
> iotagent-mqtt_1               | <13:52:13 07/02/2019> -- DEBUG: Cheking memory.
> iotagent-mqtt_1               | <13:52:23 07/02/2019> -- DEBUG: Cheking memory.
> iotagent-mqtt_1               | <13:52:33 07/02/2019> -- DEBUG: Cheking memory.
> iotagent-mqtt_1               | <13:52:43 07/02/2019> -- DEBUG: Cheking memory.
> iotagent-mqtt_1               | <13:52:53 07/02/2019> -- DEBUG: Cheking memory.
> iotagent-mqtt_1               | <13:53:03 07/02/2019> -- DEBUG: Cheking memory.
> iotagent-mqtt_1               | <13:53:03 07/02/2019> -- **|producer -- DEBUG: Error while creating producer: Error: all broker connections are down**
> iotagent-mqtt_1               | <13:53:13 07/02/2019> -- DEBUG: Cheking memory.
> iotagent-mqtt_1               | <13:53:23 07/02/2019> -- DEBUG: Cheking memory.
> iotagent-mqtt_1               | <13:53:33 07/02/2019> -- DEBUG: Cheking memory.

![screenshot_2](https://user-images.githubusercontent.com/37310063/52417205-77a03e80-2ad2-11e9-81b2-92887c950c1a.png)

**Affected Version**: 0.3.0-nightly20190207

**Comment by giovannicuriel** [comment]
Maybe the ALLOW_UNSECURED_MODE is set to false in docker-compose?

**Comment by betefaber** [comment]
To publish data in an insecure mode, you must configure the environment variable in iotagent-mqtt:
      **ALLOW_UNSECURED_MODE: 'true'**
