### ISSUE TITLE
Real-time is not working for admin tenant

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#897]
Real-time is not working for admin tenant, but work for tenant other than admin.

- tenant "admin":

![screenshot_6](https://user-images.githubusercontent.com/37310063/52436007-53f0ee80-2afa-11e9-8f92-61fc8101ac3d.png)

![screenshot_7](https://user-images.githubusercontent.com/37310063/52436005-53f0ee80-2afa-11e9-94db-c613168b6a34.png)

![screenshot_8](https://user-images.githubusercontent.com/37310063/52436004-53585800-2afa-11e9-8b5b-4820a4cd1c7e.png)

- On the details screen, the map also are not updated in real time.

![screenshot_12](https://user-images.githubusercontent.com/37310063/52436334-2ce6ec80-2afb-11e9-8af1-61f7ad1aabca.png)

![screenshot_13](https://user-images.githubusercontent.com/37310063/52436333-2ce6ec80-2afb-11e9-8b6a-686441b11277.png)

----
- tenant "teste": real-time is working for tenant other than admin

![screenshot_9](https://user-images.githubusercontent.com/37310063/52436081-75ea7100-2afa-11e9-88c4-0d0a19a0d5eb.png)

![screenshot_10](https://user-images.githubusercontent.com/37310063/52436080-75ea7100-2afa-11e9-838b-d66148e6f4e7.png)

![screenshot_11](https://user-images.githubusercontent.com/37310063/52436079-7551da80-2afa-11e9-9940-15f80ee78401.png)

**Comment by betefaber** [comment]
- tenant "admin": no parameters are updated in real-time

![screenshot_15](https://user-images.githubusercontent.com/37310063/52438200-e5af2a80-2aff-11e9-8d9b-5fd65e5c011a.png)

- in the tenant "teste", all parameters are updated in real-time (there are messages indicating that the data has changed)

![screenshot_16](https://user-images.githubusercontent.com/37310063/52438290-142d0580-2b00-11e9-8480-c305d49c599d.png)

**Comment by andersonluisribeiro** [comment]
Tests were performed now and the problem did not happen again. May be related to instabilities in the data-broker.

**Comment by betefaber** [comment]
Test OK.

![Screenshot_195](https://user-images.githubusercontent.com/37310063/56366564-d2889d00-61c9-11e9-92d9-572aaab5118a.png)

![Screenshot_196](https://user-images.githubusercontent.com/37310063/56366584-d74d5100-61c9-11e9-9c60-38d850c65928.png)
