### ISSUE TITLE
No node is shown in the addition of a flow

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#899]
![screenshot_18](https://user-images.githubusercontent.com/37310063/52478085-61a28480-2b8b-11e9-8069-c14a38beaa05.png)

![screenshot_19](https://user-images.githubusercontent.com/37310063/52478083-6109ee00-2b8b-11e9-9448-febc230e0cc4.png)

**Affected Version**: 0.3.0-nightly_20190207

**Comment by betefaber** [comment]
- the flow is created via API but is not displayed in the GUI

![screenshot_23](https://user-images.githubusercontent.com/37310063/52484142-c1edf200-2b9c-11e9-8607-b5e4196b3de6.png)

![screenshot_24](https://user-images.githubusercontent.com/37310063/52484153-c7e3d300-2b9c-11e9-870a-9dd2ffab391e.png)

**Comment by giovannicuriel** [comment]
Is this somehow connected to dojot/docker-compose#102?

**Comment by betefaber** [comment]
Error was not reproduced in version **62.3-20190603**.
