### ISSUE TITLE
[Flowbroker] Geofence node needs two outputs

### ISSUE THREAD

**Issue by ericbaum** [dojot/dojot#901]
It is useful to have two possible outputs for the geofence node, where the first corresponds to a matched area and the second correspond to an unmatched area.

This would give to the user the possibility to have two different flow branches with behavior for each of the cases without having to draw and match the same map area twice.

**Comment by rascaraficci** [comment]
It's an interesting feature, but we don't have plans to implement it, so this issue will be closed.
