### ISSUE TITLE
Even though the device has TLS certificates, it can publish data without using them

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#906]
- **device has TLS certificates:**

> matheusr@vali:/opt/teste/current/docker-compose/certs$ ls -la
> total 24
> drwxrwxrwx 2 root root 4096 Fev 11 10:05 .
> drwxr-xr-x 8 root root 4096 Fev 11 10:05 ..
> -rw-r--r-- 1 root root 1493 Fev 11 10:05 7231d5.crt
> -rw-r--r-- 1 root root  944 Fev 11 10:05 7231d5.csr
> -rw-r--r-- 1 root root 1704 Fev 11 10:05 7231d5.key
> -rw-r--r-- 1 root root 1899 Fev 11 10:05 IOTmidCA.crt
> matheusr@vali:/opt/teste/current/docker-compose/certs$

- **publishing data using the certificates**

_mosquitto_pub -t /admin/7231d5/attrs -i admin:7231d5 -m '{"int":10}' -p 8883 --cert 7231d5.crt --key 7231d5.key --cafile IOTmidCA.crt_

> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- DEBUG: Authenticating MQTT client
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- |iotagent -- INFO: Getting device from http://device-manager:5000/device/7231d5
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- INFO: Parameters are: url: http://device-manager:5000/device/7231d5, headers: { authorization: 'Bearer and0IHNjaGVtYQ==.eyJzZXJ2aWNlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImlvdGFnZW50LW1xdHQifQ==.ZHVtbXkgc2lnbmF0dXJl' }, method: get, TAG
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- DEBUG: Connection authorized for
> iotagent-mqtt_1               | {"pid":9,"hostname":"faac19273a6c","name":"MoscaServer","level":30,"time":1549887277426,"msg":"client connected","client":"admin:7231d5","v":1}
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- INFO: client up
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- DEBUG: Authorizing MQTT client admin:7231d5 to publish to /admin/7231d5/attrs
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- DEBUG: Expected topic is /admin/7231d5/attrs
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- DEBUG: Device published on topic /admin/7231d5/attrs
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- DEBUG: Authorized client admin:7231d5 to publish to topic /admin/7231d5/attrs
> iotagent-mqtt_1               | {"pid":9,"hostname":"faac19273a6c","name":"MoscaServer","level":30,"time":1549887277433,"msg":"closed","client":"admin:7231d5","v":1}
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- INFO: client down
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- DEBUG: ignoring internal message
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- DEBUG: Published data: {"int":10}, client: admin:7231d5, topic: /admin/7231d5/attrs
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'device-data':
> iotagent-mqtt_1               |    { admin: '9b7a19f8-2d3e-4411-9e99-f29281311741',
> iotagent-mqtt_1               |      teste: '7992c6d0-9c15-44eb-871a-b3af4a4eb6bd' } }
> iotagent-mqtt_1               | <12:14:37 11/02/2019> -- DEBUG: ignoring internal message

- **publishing data without using the certificates**

_mosquitto_pub -t /admin/7231d5/attrs -i admin:7231d5 -m '{"int":20}'_

> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- DEBUG: Authenticating MQTT client
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- |iotagent -- INFO: Getting device from http://device-manager:5000/device/7231d5
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- INFO: Parameters are: url: http://device-manager:5000/device/7231d5, headers: { authorization: 'Bearer and0IHNjaGVtYQ==.eyJzZXJ2aWNlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImlvdGFnZW50LW1xdHQifQ==.ZHVtbXkgc2lnbmF0dXJl' }, method: get, TAG
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- DEBUG: Connection authorized for
> iotagent-mqtt_1               | {"pid":9,"hostname":"faac19273a6c","name":"MoscaServer","level":30,"time":1549887400108,"msg":"client connected","client":"admin:7231d5","v":1}
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- INFO: client up
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- DEBUG: Authorizing MQTT client admin:7231d5 to publish to /admin/7231d5/attrs
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- DEBUG: Expected topic is /admin/7231d5/attrs
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- DEBUG: Device published on topic /admin/7231d5/attrs
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- DEBUG: Authorized client admin:7231d5 to publish to topic /admin/7231d5/attrs
> iotagent-mqtt_1               | {"pid":9,"hostname":"faac19273a6c","name":"MoscaServer","level":30,"time":1549887400109,"msg":"closed","client":"admin:7231d5","v":1}
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- INFO: client down
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- DEBUG: ignoring internal message
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- DEBUG: Published data: {"int":20}, client: admin:7231d5, topic: /admin/7231d5/attrs
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'device-data':
> iotagent-mqtt_1               |    { admin: '9b7a19f8-2d3e-4411-9e99-f29281311741',
> iotagent-mqtt_1               |      teste: '7992c6d0-9c15-44eb-871a-b3af4a4eb6bd' } }
> iotagent-mqtt_1               | <12:16:40 11/02/2019> -- DEBUG: ignoring internal message

![image](https://user-images.githubusercontent.com/37310063/52564952-95301980-2dec-11e9-8244-885d6379c116.png)

**Affected Version**: 0.3.0-nightly_20190207

**Comment by giovannicuriel** [comment]
Indeed this is problematic and there's nothing in any IoT agent that prevents this from happening. But this will not be easily implemented, as there might be many necessary patches in EJBCA-REST, DeviceManager (maybe) and IoT agents.

A few quick (not necessarily correct :smile:) thoughts about this:
- The IoT agent must know the list of devices that should use encrypted connections
- This list could be build by: device attributes set in DeviceManager, by collecting devices that were used to sign certificates.

**Comment by betefaber** [comment]
Tested in version **61.1-20190423**.

- device has TLS certificates:

```
matheusr@vali:/opt/teste/certificate-retriever/certs$ ls -la
total 24
drwxrwxrwx 2 root     root     4096 Mai  8 15:55 .
drwxr-xr-x 5 root     root     4096 Mai  8 14:28 ..
-rw-r--r-- 1 root     root     1493 Mai  8 15:55 919351.crt
-rw-r--r-- 1 root     root      944 Mai  8 15:55 919351.csr
-rw-r--r-- 1 root     root     1704 Mai  8 15:55 919351.key
-rw-rw-r-- 1 matheusr matheusr 1899 Mai  8 13:53 IOTmidCA.crt
```

- publishing data using the certificates

`mosquitto_pub -t /admin/919351/attrs -i admin:919351 -m '{"int":15}' -p 8883 --cert 919351.crt --key 919351.key --cafile IOTmidCA.crt`
```

iotagent-mqtt_1               | <19:02:29 08/05/2019> -- DEBUG: Authenticating MQTT client
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- |iotagent -- INFO: Getting device from http://device-manager:5000/device/919351
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- INFO: Parameters are: url: http://device-manager:5000/device/919351, headers: { authorization: 'Bearer and0IHNjaGVtYQ==.eyJzZXJ2aWNlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImlvdGFnZW50LW1xdHQifQ==.ZHVtbXkgc2lnbmF0dXJl' }, method: get, TAG
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- DEBUG: Connection authorized for
iotagent-mqtt_1               | {"pid":9,"hostname":"fb15f3ee524a","name":"MoscaServer","level":30,"time":1557342149460,"msg":"client connected","client":"admin:919351","v":1}
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- INFO: client up
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- DEBUG: Authorizing MQTT client admin:919351 to publish to /admin/919351/attrs
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- DEBUG: Expected topic is /admin/919351/attrs
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- DEBUG: Device published on topic /admin/919351/attrs
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- DEBUG: Authorized client admin:919351 to publish to topic /admin/919351/attrs
iotagent-mqtt_1               | {"pid":9,"hostname":"fb15f3ee524a","name":"MoscaServer","level":30,"time":1557342149477,"msg":"closed","client":"admin:919351","v":1}
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- INFO: client down
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- DEBUG: ignoring internal message
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- DEBUG: Published data: {"int":15}, client: admin:919351, topic: /admin/919351/attrs
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'device-data': 
iotagent-mqtt_1               |    { admin: '055c9e52-88ef-40f3-9a25-65ddd2f8a657',
iotagent-mqtt_1               |      teste: 'b5c18ec1-6338-4b9a-80be-c7a79005e664' } }
iotagent-mqtt_1               | <19:02:29 08/05/2019> -- DEBUG: ignoring internal message

```

```
persister_1                   | [08/05/19 - 19:02:30] |messenger| INFO: Emitting new event message for subject device-data@admin
persister_1                   | [08/05/19 - 19:02:30] |persister| INFO: Received data: {'metadata': {'deviceid': '919351', 'tenant': 'admin', 'timestamp': 1557342149486}, 'attrs': {'int': 15}}
persister_1                   | [08/05/19 - 19:02:30] |persister| DEBUG: got data event b'{"metadata":{"deviceid":"919351","tenant":"admin","timestamp":1557342149486},"attrs":{"int":15}}'

```

- publishing data without using the certificates

```

matheusr@vali:/opt/teste/certificate-retriever/certs$ mosquitto_pub -t /admin/919351/attrs -i admin:919351 -m '{"int":20}'
Error: The connection was lost.
```
