### ISSUE TITLE
[Device-manager] the same metadata multiple times

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#915]
The device manager allows the same metadata multiple times in the same attribute.

The following request exemplify the situation:
```sh
curl -X POST http://127.0.0.1:8000/template \
-H "Authorization: Bearer ${JWT}" \
-H 'Content-Type:application/json' \
-d '{ "label": "sample",
  "attrs": [
    { "label": "simpleAttr",
      "type": "dynamic",
      "value_type": "string",
      "metadata": [
       { "type": "mapping",
         "label": "type2",
         "static_value": "dummy",
         "value_type": "string"
       },
       { "type": "mapping",
         "label": "type2",
         "static_value": "dummy",
         "value_type": "string"
       }
      ]
    }
   ]
}'
```

**Comment by betefaber** [comment]
Test OK.

Can not create the same metadata in the same attribute.

- **creating template via API**:
curl -X POST http://127.0.0.1:8000/template \
-H "Authorization: Bearer ${JWT}" \
-H 'Content-Type:application/json' \
-d '{ "label": "sample",
  "attrs": [
    { "label": "simpleAttr",
      "type": "dynamic",
      "value_type": "string",
      "metadata": [
       { "type": "mapping",
         "label": "type2",
         "static_value": "dummy",
         "value_type": "string"
       },
       { "type": "mapping",
         "label": "type2",
         "static_value": "dummy",
         "value_type": "string"
       }
      ]
    }
   ]
}'

{
    "errors": {
        "metadata": [
            "a template cant not have repeated attributes"
        ]
    },
    "message": "failed to parse attr"
}

- **creating template via GUI**:

![image](https://user-images.githubusercontent.com/37310063/54756099-45e8c000-4bc6-11e9-95bf-fca22196d7a5.png)
