### ISSUE TITLE
[AUTH] Operations with groups and permissions are not logged

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#918]
In previous versions the actions were logged.

Ex:

> auth_1                        | 2019-01-09 11:26:22,814 - INFO - group grupoA created by admin
> 
> auth_1                        | 2019-01-09 12:17:31,352 - INFO - group grupoC updated by admin
> 
> auth_1                        | 2019-01-09 16:59:52,404 - INFO - permission all_template added to group GrupoB by admin
> 
> auth_1                        | 2019-01-09 17:14:01,631 - INFO - group GrupoB deleted by admin

**Affected Version**: 0.3.0-nightly_20190207

**Comment by giovannicuriel** [comment]
The problem is that parts of Auth uses a log from flask and other parts use logger from dojot.module. They should use only one logger.

**Comment by betefaber** [comment]
Test OK.

The operations are logged:

- Create Profile

```
auth_1                        | [18/06/19 - 19:21:06] |CRUDController| INFO: group grupoA created by admin
auth_1                        | [18/06/19 - 19:21:06] |CRUDController| INFO: {'id': None, 'name': 'grupoA', 'description': 'grupo A', 'created_date': None, 'created_by': 1}
auth_1                        | [18/06/19 - 19:21:06] |RelationshipController| INFO: permission ro_device added to group grupoA by admin
auth_1                        | [18/06/19 - 19:21:07] |RelationshipController| INFO: permission ro_flows added to group grupoA by admin
```

- Update profile

```
auth_1                        | [18/06/19 - 19:23:02] |CRUDController| INFO: group grupoA updated by admin
auth_1                        | [18/06/19 - 19:23:02] |RelationshipController| INFO: permission all_template added to group grupoA by admin
```
- Remove profile

`auth_1                        | [18/06/19 - 19:23:45] |CRUDController| INFO: group grupoA deleted by admin
`

Tested on Version: **62.3-20190603**
