### ISSUE TITLE
[Import/Export] Error in empty database export

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#920]
![erroexportacaosemdados](https://user-images.githubusercontent.com/37310063/52857456-58c32d00-310e-11e9-84bc-4880869ca642.png)

> data-manager_1                | <19:42:24 14/02/2019> -- DEBUG: Will export data
> data-manager_1                | <19:42:24 14/02/2019> -- DEBUG: Will call http://device-manager:5000/device
> data-manager_1                | <19:42:24 14/02/2019> -- DEBUG: Will call http://device-manager:5000/template
> data-manager_1                | <19:42:24 14/02/2019> -- DEBUG: Will call http://flowbroker:80/v1/flow
> data-manager_1                | <19:42:24 14/02/2019> -- DEBUG: Received error Error: connect ECONNREFUSED 192.168.0.23:80. Rejecting the request

- in the previous version, the empty base was exported

> data-manager_1                | <13:28:14 16/01/2019> -- DEBUG: Will export data
> data-manager_1                | <13:28:14 16/01/2019> -- DEBUG: Will call http://device-manager:5000/device
> data-manager_1                | <13:28:14 16/01/2019> -- DEBUG: Will call http://device-manager:5000/template
> data-manager_1                | <13:28:14 16/01/2019> -- DEBUG: Will call http://flowbroker:80/v1/flow
> data-manager_1                | <13:28:14 16/01/2019> -- DEBUG: Data received.

>    file generated:
>    {"devices":[],"templates":[],"flows":[]}

**Comment by betefaber** [comment]
**Note**: problem occurs only in the admin tenant

**Comment by andersonluisribeiro** [comment]
The import/export issues were solved on pull request: https://github.com/dojot/device-manager/pull/112

**Comment by betefaber** [comment]
Test OK.

```
data-manager_1                | <16:36:04 01/04/2019> -- DEBUG: Will export data
data-manager_1                | <16:36:04 01/04/2019> -- DEBUG: Will call http://device-manager:5000/device
data-manager_1                | <16:36:04 01/04/2019> -- DEBUG: Will call http://device-manager:5000/template
data-manager_1                | <16:36:04 01/04/2019> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager_1                | <16:36:04 01/04/2019> -- DEBUG: Data received.
```

DojotData.json

> {"devices":[],"templates":[],"flows":[]}
