### ISSUE TITLE
[Data Flows] Page was broken after data import

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#921]
**Steps to reproduce the problem:**

1. Start dojot
2. Click "Data Flows"

![antesimport](https://user-images.githubusercontent.com/37310063/52868800-6aff9400-312b-11e9-86c2-bed319948e64.png)

3. Create templates, devices and flows
4. Export the data
5. Restart the dojot
6. Import the data that was exported. Despite the success message, the data is not imported.
7. Reload page (F5)
8. Click "Data Flows"

![screenshot_71](https://user-images.githubusercontent.com/37310063/52868836-7bb00a00-312b-11e9-830d-89dbcfddec21.png)
![screenshot_74](https://user-images.githubusercontent.com/37310063/52868834-7bb00a00-312b-11e9-8ccd-2aad9ac89158.png)
![screenshot_75](https://user-images.githubusercontent.com/37310063/52868833-7bb00a00-312b-11e9-96e4-b595b2a6d22c.png)

**Affected Version:** 0.3.0-nightly20190207

**Comment by joab-cpqd** [comment]
This bug is related with authorization token. After User exports a file and restarts Dojot, a new token isn't given back. This is the reason of user can't import a file. I will open a new ticket to fix this token bug.
During the tests I note that cancel button isn't closing the import modal, which is another issue.

**Comment by betefaber** [comment]
Test OK.

```
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Will import data.
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Will call delete http://flowbroker:80/v1/flow
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Flows deleted.
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Will call delete http://flowbroker:80/v1/node
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Nodes deleted.
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Nodes imported.
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Flows imported.
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Will call http://device-manager:5000/import
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Devices and templates imported.
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Will call delete http://cron:5000/cron/v1/jobs
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Cron jobs deleted
data-manager_1                | <17:38:59 31/05/2019> -- DEBUG: Cron jobs imported
```

![image](https://user-images.githubusercontent.com/37310063/58724058-06063c00-83b2-11e9-97f5-80faf726170a.png)

Tested on Version: **62.2-20190524**
