### ISSUE TITLE
[GUI] Import/Export: the text has not been defined

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#928]
The text has not been defined in English:

![image](https://user-images.githubusercontent.com/37310063/53111827-a7146980-351c-11e9-88a9-f4e43f6a9c04.png)

![image](https://user-images.githubusercontent.com/37310063/53111855-b5fb1c00-351c-11e9-8be7-95b8885ec710.png)

**Affected Version**: 0.3.0-nightly20190207

**Comment by mprevide** [comment]
This is ok now
