### ISSUE TITLE
[Flowbroker] Initialization failed

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#929]
> $ sudo docker-compose -p dojot down

> $ sudo docker-compose -p dojot up -d

> $ sudo docker-compose logs -f flowbroker
> Attaching to dojot_flowbroker_1
> flowbroker_1                  | debug: Node manager is using the docker engine
> flowbroker_1                  | Context Manager Client initialized
> flowbroker_1                  | [executor] initializing ...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- INFO: Building new producer: { kafka:
> flowbroker_1                  |    { producer:
> flowbroker_1                  |       { 'metadata.broker.list': 'kafka:9092',
> flowbroker_1                  |         'compression.codec': 'gzip',
> flowbroker_1                  |         'retry.backoff.ms': 200,
> flowbroker_1                  |         'message.send.max.retries': 10,
> flowbroker_1                  |         'socket.keepalive.enable': true,
> flowbroker_1                  |         'queue.buffering.max.messages': 100000,
> flowbroker_1                  |         'queue.buffering.max.ms': 1000,
> flowbroker_1                  |         'batch.num.messages': 1000000,
> flowbroker_1                  |         dr_cb: true,
> flowbroker_1                  |         'client.id': 'flowbroker-ad2d6141-59e5-4eb0-b342-16cddda04687' },
> flowbroker_1                  |      consumer:
> flowbroker_1                  |       { 'group.id': 'flowbroker-group',
> flowbroker_1                  |         'metadata.broker.list': 'kafka:9092' },
> flowbroker_1                  |      dojot:
> flowbroker_1                  |       { subscriptionHoldoff: 2500,
> flowbroker_1                  |         timeoutSleep: 5,
> flowbroker_1                  |         connectionRetries: 5 } } }
> flowbroker_1                  | <19:57:53 20/02/2019> -- |producer -- DEBUG: Creating a new Kafka producer...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- DEBUG: Creating a new Kafka consumer...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- DEBUG: Configuration is: { 'metadata.broker.list': 'kafka:9092',
> flowbroker_1                  |   'group.id': 'dojot-module-e9983f2b-12d5-4a83-b57c-39c8ecf38c02' }
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- DEBUG: Creating a new Kafka consumer...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- DEBUG: Configuration is: { 'group.id': 'flowbroker-group',
> flowbroker_1                  |   'metadata.broker.list': 'kafka:9092' }
> flowbroker_1                  | debug: Initializing kafka messenger ...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: Connecting Kafka producer...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |producer -- DEBUG: Producer is ready.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- INFO: Kafka client connected
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: ... Kafka producer successfully connected.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: Connecting Kafka consumer for tenancy data...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- INFO: Connecting the consumer...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- INFO: Requesting consumer connection...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- INFO: ... consumer connection requested.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- INFO: Consumer is connected
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- INFO: Kafka client connected
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: ... Kafka consumer for tenancy data successfully connected.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: Connecting Kafka consumer for common messages...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- INFO: Connecting the consumer...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- INFO: Requesting consumer connection...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- INFO: ... consumer connection requested.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |consumer -- INFO: Consumer is connected
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- INFO: Kafka client connected
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: ... Kafka consumer for common messages successfully connected.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: Initializing tenancy consumer...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: Requesting topic for dojot.tenancy@dojot-management to http://data-broker...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: Got topic for subject dojot.tenancy and tenant dojot-management: 76a7ea6a-6ba1-4e5e-a48c-af505ba99ee7
> flowbroker_1                  | <19:57:53 20/02/2019> -- DEBUG: Scheduling a subscription operation...
> flowbroker_1                  | <19:57:53 20/02/2019> -- DEBUG: Adding new topic 76a7ea6a-6ba1-4e5e-a48c-af505ba99ee7
> flowbroker_1                  | <19:57:53 20/02/2019> -- DEBUG: Subscribed to topic 76a7ea6a-6ba1-4e5e-a48c-af505ba99ee7.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: ... topic for dojot.tenancy@dojot-management was requested.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: Registering callback for tenancy consumer...
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: Registering new callback for subject dojot.tenancy and event message
> flowbroker_1                  | <19:57:53 20/02/2019> -- |messenger -- DEBUG: ... callback registered for tenancy consumer.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.28.0.22:5000.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <19:57:53 20/02/2019> -- |auth -- DEBUG: Remaining 4 time(s).
> flowbroker_1                  | [amqp] producer ready ...
> flowbroker_1                  | info: [executor] Worker ready.
> flowbroker_1                  | [amqp] consumer ready ...
> flowbroker_1                  | <19:57:56 20/02/2019> -- DEBUG: Unsubscribing from topics 76a7ea6a-6ba1-4e5e-a48c-af505ba99ee7
> flowbroker_1                  | <19:57:56 20/02/2019> -- DEBUG: Subscribing to topics 76a7ea6a-6ba1-4e5e-a48c-af505ba99ee7
> flowbroker_1                  | <19:57:58 20/02/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.28.0.22:5000.
> flowbroker_1                  | <19:57:58 20/02/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <19:57:58 20/02/2019> -- |auth -- DEBUG: Remaining 3 time(s).
> flowbroker_1                  | debug: Checking memory.
> flowbroker_1                  | <19:58:07 20/02/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.28.0.23:5000.
> flowbroker_1                  | <19:58:07 20/02/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <19:58:07 20/02/2019> -- |auth -- DEBUG: Remaining 2 time(s).
> flowbroker_1                  | <19:58:13 20/02/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.28.0.21:5000.
> flowbroker_1                  | <19:58:13 20/02/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <19:58:13 20/02/2019> -- |auth -- DEBUG: Remaining 1 time(s).
> flowbroker_1                  | debug: Checking memory.
> flowbroker_1                  | <19:58:18 20/02/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.28.0.21:5000.
> flowbroker_1                  | <19:58:18 20/02/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <19:58:18 20/02/2019> -- |auth -- DEBUG: Remaining 0 time(s).
> flowbroker_1                  | error: [flowbroker] **Initialization failed.**

> $ sudo docker ps -a
> CONTAINER ID        IMAGE                                                    COMMAND                  CREATED             STATUS                     PORTS                                             NAMES
> 1298b42970b5        dojot/data-manager:0.3.0-nightly20190207                 "npm start"              4 minutes ago       Up 4 minutes                                                                 dojot_data-manager_1
> 23e39321c4f8        appropriate/curl                                         "/opt/kong.config.sh"    4 minutes ago       Exited (0) 4 minutes ago                                                     dojot_kong-config_1
> ec6eb8f1ae11        dojot/iotagent-mosca:0.3.0-nightly20190207               "/opt/iot-agent/entrâ¦"   4 minutes ago       Up 4 minutes               0.0.0.0:1883->1883/tcp, 0.0.0.0:8883->8883/tcp    dojot_iotagent-mqtt_1
> 5c5bab47ae64        dojot/flowbroker:0.3.0-nightly20190207                   "node src/index.js -â¦"   4 minutes ago       Up 4 minutes                                                                 dojot_flowbroker_1
> 7e64ff91456f        giovannicuriel/kong:0.3.0-nightly20180607-old            "/docker-entrypoint.â¦"   4 minutes ago       Up 4 minutes               8001/tcp, 0.0.0.0:8000->8000/tcp, 8443-8444/tcp   dojot_apigw_1
> 1b6f33e0b64a        dojot/auth:0.3.0-nightly20190207                         "sh ./appRun.sh start"   4 minutes ago       Up 4 minutes               5000/tcp                                          dojot_auth_1
> 015a0a462f3a        postgres:9.4-alpine                                      "docker-entrypoint.sâ¦"   4 minutes ago       Exited (0) 4 minutes ago                                                     dojot_postgres-users_1
> a4a46236a2e7        giovannicuriel/kong:0.3.0-nightly20180607-old            "/docker-entrypoint.â¦"   4 minutes ago       Exited (0) 4 minutes ago                                                     dojot_kong-migration_1
> c127dc6096ab        dojot/persister:0.3.0-nightly20190207                    "python history/subsâ¦"   4 minutes ago       Up 4 minutes                                                                 dojot_persister_1
> 061c88373ebc        dojot/device-manager:0.3.0-nightly20190207               "sh ./docker/entrypoâ¦"   4 minutes ago       Up 4 minutes               5000/tcp                                          dojot_device-manager_1
> 84bd0de7eff5        dojot/data-broker:0.3.0-nightly20190207                  "npm run subscription"   4 minutes ago       Up 4 minutes               80/tcp                                            dojot_data-broker_1
> d838d80faa38        dojot/flowbroker-context-manager:0.3.0-nightly20190207   "node src/index.js"      4 minutes ago       Up 4 minutes                                                                 dojot_flowbroker-context-manager_1
> cdcc969dfa1b        ches/kafka:0.10.1.1                                      "/start.sh"              4 minutes ago       Up 4 minutes               7203/tcp, 9092/tcp                                dojot_kafka_1
> 2a6156a7dafe        dojot/history:0.3.0-nightly20190207                      "sh ./docker/falcon-â¦"   4 minutes ago       Up 4 minutes               8000/tcp                                          dojot_history_1
> 8c6bfea418df        dojot/backstage                                          "npm start"              5 minutes ago       Up 4 minutes                                                                 dojot_backstage_1
> 36b5d7134730        rabbitmq:3.7-alpine                                      "docker-entrypoint.sâ¦"   5 minutes ago       Up 5 minutes               4369/tcp, 5671-5672/tcp, 25672/tcp                dojot_rabbitmq_1
> deeb04f95700        redis:alpine                                             "docker-entrypoint.sâ¦"   5 minutes ago       Up 4 minutes               6379/tcp                                          dojot_auth-redis_1
> a89aa7242958        redis:alpine                                             "docker-entrypoint.sâ¦"   5 minutes ago       Up 4 minutes               6379/tcp                                          dojot_device-manager-redis_1
> 0346bb3700b2        redis:alpine                                             "docker-entrypoint.sâ¦"   5 minutes ago       Up 4 minutes               6379/tcp                                          dojot_mosca-redis_1
> 3fae9dcc4bf1        redis:alpine                                             "docker-entrypoint.sâ¦"   5 minutes ago       Up 5 minutes               6379/tcp                                          dojot_data-broker-redis_1
> 3f4f451cd726        redis:alpine                                             "docker-entrypoint.sâ¦"   5 minutes ago       Up 5 minutes               6379/tcp                                          dojot_flowbroker-redis_1
> 31584d2e3d6e        mongo:3.2                                                "docker-entrypoint.sâ¦"   5 minutes ago       Up 4 minutes               27017/tcp                                         dojot_mongodb_1
> 805d7e4148f4        zookeeper:3.4                                            "/docker-entrypoint.â¦"   5 minutes ago       Up 4 minutes               2181/tcp, 2888/tcp, 3888/tcp                      dojot_zookeeper_1
> 0489393f59c2        dojot/gui:0.3.0-nightly20190207                          "nginx -g 'daemon ofâ¦"   5 minutes ago       Up 5 minutes               80/tcp                                            dojot_gui_1
> 787a5c9249d0        dojot/ejbca-rest:0.3.0-nightly20190207                   "/root/entrypoint.sh"    5 minutes ago       Up 5 minutes               5583/tcp, 8080/tcp, 8443/tcp                      dojot_ejbca_1
> 1575e594f067        postgres:9.4-alpine                                      "docker-entrypoint.sâ¦"   5 minutes ago       Up 5 minutes (healthy)     5432/tcp                                          dojot_postgres_1

**Comment by betefaber** [comment]
Test OK.

> .
> .
> .
> flowbroker_1                  | <16:56:14 19/03/2019> -- |consumer -- INFO: Connecting the consumer...
> flowbroker_1                  | <16:56:14 19/03/2019> -- |consumer -- INFO: Requesting consumer connection...
> flowbroker_1                  | <16:56:14 19/03/2019> -- |consumer -- INFO: ... consumer connection requested.
> flowbroker_1                  | <16:56:14 19/03/2019> -- |consumer -- INFO: Consumer is connected
> flowbroker_1                  | <16:56:14 19/03/2019> -- |messenger -- INFO: Kafka client connected
> flowbroker_1                  | <16:56:14 19/03/2019> -- |messenger -- DEBUG: ... Kafka consumer for common messages successfully connected.
> flowbroker_1                  | <16:56:14 19/03/2019> -- |messenger -- DEBUG: Initializing tenancy consumer...
> flowbroker_1                  | <16:56:14 19/03/2019> -- |messenger -- DEBUG: Requesting topic for dojot.tenancy@dojot-management to http://data-broker...
> flowbroker_1                  | [amqp] producer ready ...
> flowbroker_1                  | info: [executor] Worker ready.
> flowbroker_1                  | [amqp] consumer ready ...
> flowbroker_1                  | <16:56:14 19/03/2019> -- |messenger -- DEBUG: Got topic for subject dojot.tenancy and tenant dojot-management: 2e8bab6c-d0e6-4068-8610-9853dd018f50
> flowbroker_1                  | <16:56:14 19/03/2019> -- DEBUG: Scheduling a subscription operation...
> flowbroker_1                  | <16:56:14 19/03/2019> -- DEBUG: Adding new topic 2e8bab6c-d0e6-4068-8610-9853dd018f50
> flowbroker_1                  | <16:56:14 19/03/2019> -- DEBUG: Subscribed to topic 2e8bab6c-d0e6-4068-8610-9853dd018f50.
> flowbroker_1                  | <16:56:14 19/03/2019> -- |messenger -- DEBUG: ... topic for dojot.tenancy@dojot-management was requested.
> flowbroker_1                  | <16:56:14 19/03/2019> -- |messenger -- DEBUG: Registering callback for tenancy consumer...
> flowbroker_1                  | <16:56:14 19/03/2019> -- |messenger -- DEBUG: Registering new callback for subject dojot.tenancy and event message
> flowbroker_1                  | <16:56:14 19/03/2019> -- |messenger -- DEBUG: ... callback registered for tenancy consumer.
> flowbroker_1                  | <16:56:14 19/03/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.23.0.23:5000.
> flowbroker_1                  | <16:56:14 19/03/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <16:56:14 19/03/2019> -- |auth -- DEBUG: Remaining 4 time(s).
> flowbroker_1                  | <16:56:17 19/03/2019> -- DEBUG: Unsubscribing from topics 2e8bab6c-d0e6-4068-8610-9853dd018f50
> flowbroker_1                  | <16:56:17 19/03/2019> -- DEBUG: Subscribing to topics 2e8bab6c-d0e6-4068-8610-9853dd018f50
> flowbroker_1                  | <16:56:19 19/03/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.23.0.23:5000.
> flowbroker_1                  | <16:56:19 19/03/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <16:56:19 19/03/2019> -- |auth -- DEBUG: Remaining 3 time(s).
> flowbroker_1                  | debug: Checking memory.
> flowbroker_1                  | <16:56:24 19/03/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.23.0.23:5000.
> flowbroker_1                  | <16:56:24 19/03/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <16:56:24 19/03/2019> -- |auth -- DEBUG: Remaining 2 time(s).
> flowbroker_1                  | <16:56:29 19/03/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.23.0.23:5000.
> flowbroker_1                  | <16:56:29 19/03/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <16:56:29 19/03/2019> -- |auth -- DEBUG: Remaining 1 time(s).
> flowbroker_1                  | debug: Checking memory.
> flowbroker_1                  | <16:56:37 19/03/2019> -- |auth -- ERROR: Could not initialize tenancy consumer: Error: connect ECONNREFUSED 172.23.0.23:5000.
> flowbroker_1                  | <16:56:37 19/03/2019> -- |auth -- DEBUG: Trying again in a few moments.
> flowbroker_1                  | <16:56:37 19/03/2019> -- |auth -- DEBUG: Remaining 0 time(s).
> flowbroker_1                  | error: [flowbroker] Initialization failed.
> flowbroker_1                  | debug: Node manager is using the docker engine
> flowbroker_1                  | Context Manager Client initialized
> flowbroker_1                  | [executor] initializing ...
> .
> .
> .

**Comment by ErnandesAJr** [comment]
This happened again with Dojot v0.4.x. The same container initialization error. I had to restart the services to get back up and running.

**Comment by bizetti** [comment]
Hi Ernands. We couldn't reproduce the situation. Do you still have the log to send us?
