### ISSUE TITLE
[GUI] Support to object exhibition like type of attr

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#931]
Actually, the GUI does not offer support to exhibit object as data, I would like to request this support.

Use case:
a device has an attribute that is an object and the user wants to visualize it on dojot's GUI similarly he can do with strings.

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/60728534-f204ab80-9f16-11e9-83f8-83890f20c4e3.png)

Tested in version: **62.3-20190603**
