### ISSUE TITLE
[GUI] Sidebar missbehaviours

### ISSUE THREAD

**Issue by cfrancisco** [dojot/dojot#937]
Sometimes the sidebars have some unexpected behaviors, as lose the scroll bar, hide elements, etc.

A unexpected behaviour is shown below:
![Screenshot from 2019-02-22 11-12-21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c13020f1fa5c0011f3d876/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f3793dd7b168ee1336505d424cad53444d04bea6d37ef5f22e7a985902bfd73e0c27c03911faea811bbf01b975df4f81e0b9df5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5df643e54952a11a326be0647b.png)

**Comment by betefaber** [comment]
- Based on the text, the error was not reproduced.

- Attached picture was not uploaded.

Tested in version: **63.1-20190705**
