### ISSUE TITLE
Undefined error when 2 images are removed

### ISSUE THREAD

**Issue by cfrancisco** [dojot/dojot#941]

**Comment by bizetti** [comment]
Ticket analysis (Jan, 3rd 2020): Retest.

**Comment by betefaber** [comment]
Test OK.

1. **remove images**

![remover-imagem1 1](https://user-images.githubusercontent.com/37310063/71845135-6840c100-30a6-11ea-8f23-6047d17bfc40.png)

- image 1.1 removed

![imagem1 1-removida](https://user-images.githubusercontent.com/37310063/71845156-742c8300-30a6-11ea-9b6e-3abb352e6c79.png)

- image 1.2 removed

![imagem1 2-removida](https://user-images.githubusercontent.com/37310063/71845152-7393ec80-30a6-11ea-8ef0-a54346ea49fb.png)
----
2. **remove versions**

![removerversao](https://user-images.githubusercontent.com/37310063/71845193-8c040700-30a6-11ea-8e9a-95a3a31ad7e9.png)

- version 1.1 removed

![version1 1-removida](https://user-images.githubusercontent.com/37310063/71845196-8c9c9d80-30a6-11ea-9b8e-6977c91d4a7b.png)

- version 1.2 removed

![version1 2-removida](https://user-images.githubusercontent.com/37310063/71845195-8c040700-30a6-11ea-8bab-44c6ac514e8e.png)

- template updated

![updatetemplateimagem](https://user-images.githubusercontent.com/37310063/71845194-8c040700-30a6-11ea-8ebc-e652f43ca9f2.png)
----
3. **remove versions with associated images**

- version 1.1 removed

![versao1comimagem-removida](https://user-images.githubusercontent.com/37310063/71845221-9920f600-30a6-11ea-9894-d30caf8fd323.png)

- version 1.2 removed

![versa01 2comimagem-removida](https://user-images.githubusercontent.com/37310063/71845220-9920f600-30a6-11ea-99ac-7d59ce8bf94b.png)

- template updated

![updatetemplateversion](https://user-images.githubusercontent.com/37310063/71845219-9920f600-30a6-11ea-9856-f50873453b0e.png)

Tested in version **v0.4.1_rc2**
