### ISSUE TITLE
[FW] - Apply i18n in all messages

### ISSUE THREAD

**Issue by cfrancisco** [dojot/dojot#946]
Currently, all messages are in English.

**Comment by betefaber** [comment]
Some messages have not yet been translated:

- image without label

![Screenshot_206](https://user-images.githubusercontent.com/37310063/56501535-8dc07700-64e5-11e9-9e01-1c48b18bbcba.png)

- template firmware update

![Screenshot_207](https://user-images.githubusercontent.com/37310063/56501578-b3e61700-64e5-11e9-8c93-6a21e1460326.png)

![Screenshot_208](https://user-images.githubusercontent.com/37310063/56501586-b8123480-64e5-11e9-9408-86c8bbdcdcc4.png)

- binary already exists

![Screenshot_211](https://user-images.githubusercontent.com/37310063/56501603-bfd1d900-64e5-11e9-9d11-032b4897db8b.png)
