### ISSUE TITLE
[FW] Add specific permissions to access FW

### ISSUE THREAD

**Issue by cfrancisco** [dojot/dojot#947]
If the user has access to templates, he also has access to firmware management (similar in device edition). We should create different permissions for firmware management.

**Comment by mprevide** [comment]
https://github.com/dojot/dojot/issues/993#issuecomment-476581931

**Comment by mprevide** [comment]
The Endpoints have been configured in these PRs.

https://github.com/dojot/auth/pull/72
https://github.com/dojot/backstage/pull/3

**Comment by cfrancisco** [comment]
Implementation made following the @rascaraficci's suggestions. 

In the future, we should split these operations in a better way thinking about the user personas.

**Comment by betefaber** [comment]
Permissions for firmware update have been created.

Rules:
- Viewer: just for GET
- Modifier: GET, POST, PUT and DELETE

If the user has access to templates, he do not necessarily has access to firmware management. 
But if the user has access to firmware management, he must also has access to templates. An issue will open.
