### ISSUE TITLE
[FW] - Missing dynamic visualization for image states

### ISSUE THREAD

**Issue by cfrancisco** [dojot/dojot#963]
Actually isn't showing the current data for image states. Is recommended using socket.io to get this information.

**Comment by betefaber** [comment]
Test OK

- **on hold**

![image](https://user-images.githubusercontent.com/37310063/61298648-fbaece80-a7b4-11e9-88c5-a3509c9366f1.png)

- **downloading**

![image](https://user-images.githubusercontent.com/37310063/61298702-13865280-a7b5-11e9-8a37-e0ee35d14fec.png)

- **downloaded**

![image](https://user-images.githubusercontent.com/37310063/61298737-21d46e80-a7b5-11e9-8536-dc7871687699.png)

- **updating**

![image](https://user-images.githubusercontent.com/37310063/61298779-37499880-a7b5-11e9-9573-97e4d97f7678.png)

- **on hold (applied image)**

![image](https://user-images.githubusercontent.com/37310063/61298831-4b8d9580-a7b5-11e9-9e0c-f6852d85bc92.png)

- **on hold (state reset)**

![image](https://user-images.githubusercontent.com/37310063/61298921-7a0b7080-a7b5-11e9-87b1-4e2e825d209b.png)

Tested in version **63.1-20190705**
