### ISSUE TITLE
[GUI] GUI allows the user to set a value to actuator attribute

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#966]
During the template creation, the GUI allows the user to set a value to actuator attribute.

The following image illustrates the situation:

![image](https://user-images.githubusercontent.com/21104864/53952920-df857d00-40b0-11e9-9927-5b3abc2e910a.png)

**Comment by betefaber** [comment]
similar to that reported in [https://github.com/dojot/dojot/issues/867](url)

**Comment by mprevide** [comment]
#1066

**Comment by betefaber** [comment]
Test OK.

![image](https://user-images.githubusercontent.com/37310063/61297757-492a3c00-a7b3-11e9-990a-daa3386caea3.png)

Tested in version: **63.1-20190705**
