### ISSUE TITLE
[GUI] Device is created with empty metadata configuration

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#968]
No validation for unfilled metadata configuration.

**Steps to reproduce the problem:**

1. Click New Device
2. Set a name
3. Add template with metadata into dynamic attributes
4. Click Dynamic Attributes
5. Expand Meta attributes
6. Delete static value of metadata
7. Click SAVE

![metavazio](https://user-images.githubusercontent.com/37310063/54044383-92d39c00-41ad-11e9-9211-16b196ccd190.png)

**Comment by cfrancisco** [comment]
It will no longer be prioritized.
