### ISSUE TITLE
Allows creation of a device from templates with repeated parameters

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#971]
**Steps to reproduce the problem:**

1. Click New Device
2. Set a name
3. Add templates with repeated parameters (same label but different types)
4. Click SAVE

![Screenshot_126](https://user-images.githubusercontent.com/37310063/54054846-169b8180-41ca-11e9-86e3-1a6828ca5404.png)

**Note**: If the parameters are of the same type, the device is not created

![Screenshot_124](https://user-images.githubusercontent.com/37310063/54054850-1bf8cc00-41ca-11e9-8b76-c38fb523f3fd.png)

**Affected Version:** 0.3.0-nightly20190207

**Comment by betefaber** [comment]
Test OK.

Add templates with repeated parameters:

**same label but different types**
- create

![Screenshot_136](https://user-images.githubusercontent.com/37310063/55825126-bb67f200-5adb-11e9-9c5d-2ae2ec32cdaa.png)

- update

![Screenshot_146](https://user-images.githubusercontent.com/37310063/55826317-23b7d300-5ade-11e9-80a8-66bda601b46e.png)

**same label and type**

- create

![Screenshot_147](https://user-images.githubusercontent.com/37310063/55827115-d9cfec80-5adf-11e9-97d7-7d5b2c2e7151.png)

- update

![Screenshot_141](https://user-images.githubusercontent.com/37310063/55825973-5ad9b480-5add-11e9-9dcb-6fe02567ab84.png)

**Comment by betefaber** [comment]
Test **NOK**.

**The error has returned.**

- templates with repeated parameters (same label but different types): **device is created**

![Screenshot_131](https://user-images.githubusercontent.com/37310063/59445993-01407f80-8dd7-11e9-992b-93662334bb5f.png)

![Screenshot_132](https://user-images.githubusercontent.com/37310063/59445992-01407f80-8dd7-11e9-821e-5a3354584938.png)

![Screenshot_130](https://user-images.githubusercontent.com/37310063/59445994-01407f80-8dd7-11e9-9f9a-6b2ca81388d0.png)

![Screenshot_133](https://user-images.githubusercontent.com/37310063/59446021-0d2c4180-8dd7-11e9-87c7-ec69d41b8da8.png)

![Screenshot_134](https://user-images.githubusercontent.com/37310063/59446020-0d2c4180-8dd7-11e9-9cb8-179e8d174668.png)

![Screenshot_136](https://user-images.githubusercontent.com/37310063/59446019-0d2c4180-8dd7-11e9-89f2-501bbe27e082.png)

- templates with repeated parameters (same label and type): **device is not created**

![Screenshot_120](https://user-images.githubusercontent.com/37310063/59446460-ea4e5d00-8dd7-11e9-9d73-6b2dbe6ddd99.png)

![Screenshot_121](https://user-images.githubusercontent.com/37310063/59446470-efaba780-8dd7-11e9-9d2b-eb3ebe6114ca.png)

![Screenshot_122](https://user-images.githubusercontent.com/37310063/59446477-f5a18880-8dd7-11e9-8c8d-2eebb052009e.png)

![Screenshot_123](https://user-images.githubusercontent.com/37310063/59446486-fafed300-8dd7-11e9-8527-371c70937371.png)

![Screenshot_126](https://user-images.githubusercontent.com/37310063/59446498-00f4b400-8dd8-11e9-8779-824f25c65e0c.png)


**Note**: This issue has been fixed in version **58.2-20190321**

**Comment by eduardogmisiuk** [comment]
Tested the procedure described in https://github.com/dojot/dojot/issues/971#issuecomment-501757051 in version v0.5.0-rc.1 and still occurs.

**Comment by bizetti** [comment]
I won't be fixed.
