### ISSUE TITLE
[GUI] Image mgmt always enabled

### ISSUE THREAD

**Issue by cfrancisco** [dojot/dojot#973]
Even when you disable the image management for a template, it still contains some image attributes.

**Comment by betefaber** [comment]
Test OK.

- **Firmware disabled**

![Screenshot at 2019-07-16 10-49-35](https://user-images.githubusercontent.com/37310063/61300389-3fef9e00-a7b8-11e9-97e5-1657ac3a92d7.png)

- **Firmware enabled**

![Screenshot at 2019-07-16 10-49-55](https://user-images.githubusercontent.com/37310063/61300405-467e1580-a7b8-11e9-9a93-e9fec5ed3b01.png)

- **Firmware disabled**

![Screenshot at 2019-07-16 10-50-13](https://user-images.githubusercontent.com/37310063/61300424-4f6ee700-a7b8-11e9-8af3-3229c33efeac.png)

Tested in version: **63.1-20190705**
