### ISSUE TITLE
[FW] Image manager doesn't show binary info

### ISSUE THREAD

**Issue by cfrancisco** [dojot/dojot#983]

**Comment by betefaber** [comment]
Test OK.

![Screenshot at 2019-07-16 11-19-18](https://user-images.githubusercontent.com/37310063/61303269-9c08f100-a7bd-11e9-9aac-d6fe4eadf3e0.png)

![image](https://user-images.githubusercontent.com/37310063/61303181-7976d800-a7bd-11e9-8966-645c289ece1e.png)

Tested in version **63.1-20190705**
