### ISSUE TITLE
[DataBroker] Real-time is not working for any tenant

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#985]
Real-time is not working for any tenant.

- admin tenant:

![Screenshot_6](https://user-images.githubusercontent.com/37310063/54452421-e3aa3e00-4733-11e9-988c-ea2e055643fc.png)

![image](https://user-images.githubusercontent.com/37310063/54452520-2409bc00-4734-11e9-99a8-a71e1af3b445.png)

- other tenant:

![Screenshot_5](https://user-images.githubusercontent.com/37310063/54452428-e9a01f00-4733-11e9-8608-3008626a6f13.png)

![image](https://user-images.githubusercontent.com/37310063/54452596-47346b80-4734-11e9-9708-d37aa9a3eeaa.png)

**Affected Version**: 58.1-20190313

**Comment by mprevide** [comment]
This problem is related with data-broker

**Comment by giovannicuriel** [comment]
I was not able to reproduce this problem.
