### ISSUE TITLE
Default Kafka topics configuration cannot be changed

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#989]
There is no way to change default configuration for Kafka topics. If in one deployment the "device-data" subject for "admin" tenant must have more than one partition, there is no way to configure dojot in order to get that.

There must be two ways of doing such thing:

- [ ] Adding a configuration file to data-broker (so that the administrator can configure it before hand)
- [ ] Add topic profile edition endpoints (which may lead to Kafka partition rebalancing). This might not be desireable at this point, but it could be useful nonetheless.

**Comment by bizetti** [comment]
Ticket analysis (Jan, 3rd 2020): New analysis is necessary.

**Comment by raulnegreiros** [comment]
There is a way to change the default partition number, the side effect is that it changes the __default__ configuration for ALL the topics. You just need to configure the `KAFKA_NUM_PARTITIONS` environment variable on the Kafka's docker configuration.
But I believe that Giovanni's first approach is more adequate.

**Comment by eduardogmisiuk** [comment]
Already solved in the way that Raul explained before.

**Comment by bizetti** [comment]
Done.
