### ISSUE TITLE
[GUI] MAP view: when hiding / showing a device, the other devices are centralized

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#990]
In real-time, when hiding / showing a device, the other devices are centralized. The same behavior is not observed in static devices.

**Steps to reproduce the problem:**

- **devices in real-time**

1. Select map view
2. Open the side bar
3. Select bus-23
![bus23](https://user-images.githubusercontent.com/37310063/54637402-53d3ff00-4a67-11e9-8bdd-ac7e817b53bd.png)

4. Click Hide Device. _The devices are "centralized"._
![hide-bus23](https://user-images.githubusercontent.com/37310063/54637415-5b93a380-4a67-11e9-82c9-d80f6e68bb20.png)

5. bus-23 hided
![bus23-hided](https://user-images.githubusercontent.com/37310063/54637427-61898480-4a67-11e9-8aaa-e3a27b684c07.png)

6. Click Show Device. _The devices are "centralized"._
![show-bus23](https://user-images.githubusercontent.com/37310063/54637436-66e6cf00-4a67-11e9-9431-6b71a1562218.png)

- **static devices**

1. Select map view
2. Open the side bar
3. Select bus-15
![bus15](https://user-images.githubusercontent.com/37310063/54637448-6e0ddd00-4a67-11e9-901c-64dfd6baecf7.png)

4. Click Hide Device
![hide-bus15](https://user-images.githubusercontent.com/37310063/54637456-72d29100-4a67-11e9-8204-01aeda22615e.png)

5. Click Show Device
![show-bus15](https://user-images.githubusercontent.com/37310063/54637468-782fdb80-4a67-11e9-9db1-51c34f2729e0.png)

**Affected Version:** 58.1-20190313

**Comment by cfrancisco** [comment]
I verified how google maps behaves and, when you're filtering, there are no changes on the viewport. Maybe could we follow this pattern (for filtering and tracking? )

**Comment by cfrancisco** [comment]
These behaviors were changed because the UI was fully factored in.
