### ISSUE TITLE
[GUI] Template - update firmware - Constraint error

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#991]
When I active the firmware option. more than once, the msg  'Duplicate key value violates unique constraint "attrs_template_id_type_label_key"'  is displayed.
Maybe we need to treat this msg.

**Comment by cfrancisco** [comment]
@mprevide   Could you check it again in the new baseline?

**Comment by mprevide** [comment]
@cfrancisco 
Now the error msg is "failed to parse attr" for the same situation

**Comment by cfrancisco** [comment]
The error was treated in dojot/dojot#1069, closing as duplicate.
