### ISSUE TITLE
[Gui] Add Permissions in Firmware

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#993]
For add Permissions in firmware update (doesn't show button, for example)

Roles:
- viewer just for GET
- modifier GET, POST, PUT and DELETE

Imports:

import ability from 'Components/permissions/ability';
import Can from '../../components/permissions/Can';

How use:

const cannotEdit = !ability.can('modifier', 'fw-image');
const cannotEdit = !ability.can('viewer', 'fw-image');
or
`<Can do="modifier" on="fw-image">
</Can>`
` <Can do="viewer" on="fw-image">
</Can>`

**Comment by cfrancisco** [comment]
Waiting for discussion about firmware permission (dojot/dojot#947).

**Comment by mprevide** [comment]
This permission is associated with the endpoint. Since the user does not have permission to access such an endpoint, he will not be able to work with firmware even if he can manage the template.
The GUI would only display the firmware button or not.

**Comment by mprevide** [comment]
Everything has been set up for a while, you just need to use 'fw-image'.

**Comment by betefaber** [comment]
Specific permissions to access FW were added:

![image](https://user-images.githubusercontent.com/37310063/61081212-0f48e680-a3fd-11e9-8f6c-d4c1b936e068.png)

![fw](https://user-images.githubusercontent.com/37310063/61081107-d446b300-a3fc-11e9-9834-333b234b8788.png)
